Bibtex
hlissner/doom-emacs pull request #2888
Opened 2020-04-11 23:06 UTC by brianmcgillion

2020-04-15 11:33 UTC, bdarcus commented
While you wait on a review, two things:

1. @patrl asked on #2861 what happens if one just have either the `ivy` or `helm` feature selected. I suggested we include in the README that the module depends on one.
2. depending on time, we should add the new [org-roam-bibtex](https://github.com/Zaeph/org-roam-bibtex) extension, which tightly integrates org-roam and ivy/helm-bibtex and org-ref; would be dependent on the `+roam` feature

2020-04-15 13:30 UTC, bdarcus commented
Also, just saw [this](https://github.com/melpa/melpa/pull/6840); bibtex-completion is being split from ivy/helm-bibtex. Does it impact us?

Guessing not, but just thought I'd ask.

2020-04-15 14:51 UTC, brianmcgillion commented
> Also, just saw [this](https://github.com/melpa/melpa/pull/6840); bibtex-completion is being split from ivy/helm-bibtex. Does it impact us?
> 
> Guessing not, but just thought I'd ask.es it did as doom/upgrade has been failing for the last hours. I am converted to being a :pin advocate

2020-04-15 14:52 UTC, brianmcgillion commented
it did as doom/upgrade has been failing for the last hours. I am converted to being a :pin advocate

2020-04-15 14:52 UTC, brianmcgillion commented
> While you wait on a review, two things:
> 
> 1. @patrl asked on #2861 what happens if one has neither the `ivy` or `helm` feature selected. I suggested we include in the README that the module depends on one.
> 2. Depending on your time (though it should be easy; doesn't appear to require much or any config), we should add the new [org-roam-bibtex](https://github.com/Zaeph/org-roam-bibtex) extension, which tightly integrates org-roam and ivy/helm-bibtex and org-ref, and has been submitted to MELPA. This would need to be dependent on the org `+roam` feature.

Yes I will do this, once the package in in melpa

2020-04-16 15:02 UTC, bdarcus commented on modules/tools/biblio/config.el
> +    (setq bibtex-completion-bibliography (list (concat org-directory "library.bib"))
By default, are these variables here set to nil, so that we need to set something reasonable?

2020-04-16 16:55 UTC, brianmcgillion commented on modules/tools/biblio/config.el
> +    (setq bibtex-completion-bibliography (list (concat org-directory "library.bib"))
yes, 

https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el#L262
- not sure why keywords is not a default.

https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el#L309

2020-04-16 16:58 UTC, brianmcgillion commented on modules/tools/biblio/packages.el
> +;;(package! bibtex-completion)
Pulled in in this commit set (https://github.com/hlissner/doom-emacs/pull/2907)

2020-04-19 17:21 UTC, bdarcus commented
This looks good. It adds documentation, and significant new functionality, to the new biblio package.

I've tested it, and it works as I expect.

2020-04-20 17:15 UTC, Wetlize commented on modules/tools/biblio/config.el
> +  :when (featurep! :lang org)
Is it necessary to future gate `org-ref`? Despite the name it also provides features outside of the org-mode.

2020-04-20 17:17 UTC, Wetlize commented on modules/tools/biblio/packages.el
> +(when (featurep! :lang org)
Same thing, this feature gate is probably redundant.

2020-04-20 17:21 UTC, Wetlize commented on modules/tools/biblio/config.el
> +    (setq org-ref-notes-(function )
Should be `org-ref-notes-function`.

2020-04-20 17:24 UTC, Wetlize commented on modules/tools/biblio/config.el
> +               (list (car (org-ref-get-bibtex-key-and-file thekey)))))))))
This is the same as `org-ref-notes-function-many-files` function, any reason to extract lambda?
Furthermore, we can do the next thing:
```lisp
(setq 
  ...
  org-ref-notes-function (if (directory-name-p org-ref-notes-directory)
                              #'org-ref-notes-function-many-files
                            #'org-ref-notes-function-one-file))

2020-04-20 17:28 UTC, Wetlize commented on modules/tools/biblio/config.el
>    (add-to-list 'ivy-re-builders-alist '(ivy-bibtex . ivy--regex-plus)))
We can refactor this into:
```lisp
(when (featurep! :completion ivy)
    (add-to-list 'ivy-re-builders-alist '(ivy-bibtex . ivy--regex-plus)))
```
under the `:config` section of `bibtex-completion` package.

2020-04-20 17:49 UTC, Wetlize commented
I've noticed that a a lot of bibliographical packages want to specify the same patterns as user options:
- pdf directory path
- path to default bibliographical files
- path to bibliographical notes

So I propose to expose the next user options on top of config.el:
```lisp
(defvar +biblio-pdf-library-dir "~/Documents/Library/"
  "Directory where pdf files are stored. Must end with a slash.")

(defvar +biblio-default-bibliography-files '("~/Documents/Biblio/biblio.bib")
  "A list of default bibtex files to use.")

(defvar +biblio-notes-path "~/Documents/Notes/"
  "The place where you will store your notes for bibliography files.

This can be either a single file or directory of files.
In case of directory the path must end with a slash.")
```
They can affect next variables:
- `+biblio-default-bibliography-files`:
  - `bibtex-completion-library-path`
  - `org-ref-pdf-directory`
- `+biblio-default-bibliography-files`:
  - `reftex-default-bibliography`
  - `bibtex-completion-bibliography`
  - `org-ref-default-bibliography`
- `+biblio-notes-path`:
  - `bibtex-completion-notes-path`
  - `org-ref-bibliography-notes`
  - `org-ref-notes-directory`

This would simplify and unify the whole interface better.

2020-04-20 17:55 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  :when (featurep! :lang org)
I think we were originally assuming one wouldn't use org-ref without having the org feature selected, but you raise a good point. No objections from me to removing it.

2020-04-20 18:01 UTC, bdarcus commented
> I've noticed that a a lot of bibliographical packages want to specify the same patterns as user options:

Yes, I've noticed (and grumbled about) that too.

...

> So I propose to expose the next user options on top of config.el:
...
> This would simplify and unify the whole interface better for the end user.

+1

2020-04-20 18:21 UTC, Wetlize commented
I also remember that back in time I had difficulties understand how all those packages suppose to work together. We can briefly describe them in the documentation or just link to (or include as a quote block) [this](https://old.reddit.com/r/emacs/comments/cxu0qg/emacs_org_and_bibtex_as_alternative_to_zotero_and/eyqe4vq/) reddit thread.

2020-04-20 18:36 UTC, brianmcgillion commented on modules/tools/biblio/config.el
> +  :when (featurep! :lang org)
Many of the modules under org-ref (require 'org) or org-ref-core which requires org so it will pull in org. hence you should have it, although I agree that it is not org olny.

2020-04-20 18:44 UTC, brianmcgillion commented on modules/tools/biblio/config.el
> +    (setq org-ref-notes-(function )
TAB, seems to have a nasty habit of turning (keywords) into code, so TAB at the beginning of the line to align or else ...

2020-04-20 18:49 UTC, brianmcgillion commented on modules/tools/biblio/config.el
> +               (list (car (org-ref-get-bibtex-key-and-file thekey)))))))))
https://github.com/jkitchin/org-ref/blob/master/org-ref.org#setting-up-notes-to-work-with-multiple-notesorg-files

2020-04-20 18:49 UTC, brianmcgillion commented on modules/tools/biblio/packages.el
> +(when (featurep! :lang org)
same comment as above

2020-04-20 18:59 UTC, brianmcgillion commented
> This would simplify and unify the whole interface better for the end user.

I totally agree. I had thought of something similar when doing it, but then discounted the idea because many folks are coming from own configs, so having different variants helm-bibtex, bibtex complete, org-ref .... So I was figuring that the permutation checking might be a mess. But having said that they can always use the standard (after! ...) if they wish and ignore the +biblio variables and just the packages directly.

I will send an update in a few.

2020-04-20 19:00 UTC, brianmcgillion commented
> I also remember that back in time I had difficulties to understand how all those packages suppose to work together. We can very briefly describe their roles in the documentation.
> 
> As a reference, there's a [reddit thread](https://reddit.com/r/emacs/comments/cxu0qg/emacs_org_and_bibtex_as_alternative_to_zotero_and/eyqe4vq/) that already does so, but not briefly.

Thanks for the link. That will surely help!

2020-04-20 19:02 UTC, Wetlize commented on modules/tools/biblio/config.el
> +               (list (car (org-ref-get-bibtex-key-and-file thekey)))))))))
The case of outdated documentation :(
https://github.com/jkitchin/org-ref/commit/dc3d259a876e53b939bb885d915ff013e122acc0

2020-04-20 19:33 UTC, Wetlize commented on modules/tools/biblio/config.el
> +(use-package! org-ref
We should also preset `org-ref-completion-library` under `:init` section:
```lisp
;; This need to be set before the package is loaded, because org-ref will
;; automatically `require' an associated package during its loading.
(setq org-ref-completion-library (cond ((featurep! :completion ivy)  #'org-ref-ivy-cite)
                                       ((featurep! :completion helm) #'org-ref-helm-bibtex)
                                       (t                            #'org-ref-reftex)))
```

2020-04-20 19:55 UTC, brianmcgillion commented
@Wetlize, you raise another issue that @bdarcus and I debated a bit. Should org-noter be under the biblio module or as +noter under org/contrib? Technically you do not need the biblo packages to take notes, however, who takes notes that does not in some way use the biblio packages?

2020-04-20 20:06 UTC, Wetlize commented
@brianmcgillion I think we should keep them separated. One can think about annotations and bibliography as 2 different things. The bibliography module can just reference `:lang org +noter` somehow in the documentation, as a potential object of interest.

2020-04-20 20:11 UTC, brianmcgillion commented
would crossreferencing the setting of the notes path be too much confusion? so from noter, 

```
(if (fboundp +biblio-notes-path)
    (setq org-noter-notes-search-path  +biblio-notes-path))
```
or something to that effect?

2020-04-20 21:29 UTC, brianmcgillion commented on modules/tools/biblio/config.el
> +               (list (car (org-ref-get-bibtex-key-and-file thekey)))))))))
thanks again.

2020-04-21 11:46 UTC, Wetlize commented
> would cross-referencing the setting of the notes path be too much confusion?

I think we should avoid doing so and keep it dumb as for now (i.e. just default `org-noter-notes-search-path` to `org-directory`). In future, if users will find this confusing and not intuitive we can change how org-noter (and maybe other org related bibliography packages) will integrate with the rest of Doom.

2020-04-21 12:29 UTC, Wetlize commented on modules/tools/biblio/config.el
> +  :after (org bibtex-completion)
Can we just `:defet t` this? I cannot wrap my head why would we need to wait for all these packages to apply configuration for this package.

2020-04-22 09:49 UTC, brianmcgillion commented
rebase and bump the biblio packages

2020-04-26 16:51 UTC, Wetlize commented on modules/tools/biblio/config.el
> +  :init
```suggestion
  :preface
```
Whoops, when `:after` is present `:init` runs after these all packages are loaded. This needs to be set earlier, otherwise it will fail to load a proper for user completion library, defaulting him to helm.

2020-04-26 17:34 UTC, Wetlize commented on modules/tools/biblio/config.el
> +  :init
```suggestion
  :preface
```
We need to `:preface` this for a better robustness. Something can load `org-ref` before this block will be evaluated. If this will happen, `org-ref-completion-library` will be set only after the package is loaded, failing `require` a needed for user completion engine and defaulting him to helm.

This just actually happened in my config with this module and took me some time to figure out.

2020-04-26 17:56 UTC, brianmcgillion commented on modules/tools/biblio/config.el
> +  :init
thank you. Change pushed

2020-04-26 18:00 UTC, brianmcgillion commented
rebased, and updated the time stamp

2020-04-26 21:11 UTC, bdarcus commented
Any chance we can get this merged soon @hlissner? Anything we're missing?

2020-04-30 07:10 UTC, brianmcgillion commented
Rebased and bump the pins

2020-04-30 23:28 UTC, hlissner commented
Sorry for the delay. As I'm very new to bibtex, org-roam and org-ref, reviewing this is taking me a while; digging through these packages. There are few pain points I'm looking for alternatives around:

1. The three `defcustom`s. I'd _like_ not to introduce new variables, and am investigating a way around these; especially because we do not use `defcustom` anywhere else. I want to avoid them.

2. We have a lot of `(unless X (setq X DEFAULTS))`, and I'm going through each of their upstream defaults to see if these checks are warranted (or if we could simply define them _in_ their respective `defvar`s.

3. I don't fully understand the relationship between org-ref and bibtex-completion, and wonder why `:after (org bibtex-completion)` is necessary. This complicates the customization path for the user, because neither `(after! org ...)` nor `(after! bibtex-completion ...)` will be enough to configure the package (and due to `use-package`'s [weird :after semantics](https://github.com/jwiegley/use-package/issues/829), any config in `(after! org-ref ...)` will be overruled by what's in this module's `:config` block for it.

I'll keep you posted as I truck along.

2020-05-01 11:29 UTC, bdarcus commented
Thanks for the update @hlissner. 

Given how common it is to integrate these tools (and related, how commonly people get confused how they're supposed to fit together), perhaps your investigations can lead to suggestions upstream.

2020-05-03 12:22 UTC, bdarcus commented
@brianmcgillion - you might bump `org-roam-bibtex` again, as they just issued a new release, with new features.

2020-05-03 15:41 UTC, brianmcgillion commented
Thank you @hlissner for the thorough review.

> * The three `defcustom`s. If possible, I'd _like_ to avoid introducing new variables, and am investigating a way around these; especially because we do not use `defcustom` anywhere else.
> * We have a lot of `(unless X (setq X DEFAULTS))`, and I'm going through each of their upstream defaults to see if these checks are warranted (or if we could simply define them _in_ their respective `defvar`s).

The first drafts used the (unless ... set...) form as seen in other modules. It was suggested by @Wetlize https://github.com/hlissner/doom-emacs/pull/2888#issuecomment-616712460 that it would greatly cleanup the interface if we reduce the multiple packages "file path" variables down to just 3 which would then set them in the respective packages.

The problem stems from the packages providing some level of functionality for bibliographic management but there is not one overarching package tying them together, e.g. reftex-default-bibliography, org-ref-default-bibliography,  bibtex-completion-bibliography all point to the same place and all have to be set, (to the confusion of most users). In the documentation, we indicate how the user can set the variables directly if they so wish rather than using the defcustom.

2020-05-03 15:44 UTC, brianmcgillion commented
> 3\. I don't fully understand the relationship between org-ref and bibtex-completion, and wonder why `:after (org bibtex-completion)` is necessary. This complicates the customization path for the user, because neither `(after! org ...)` nor `(after! bibtex-completion ...)` will be enough to configure the package (and due to `use-package`'s [:after semantics](https://github.com/jwiegley/use-package/issues/829), any config in a user's `(after! org-ref ...)` will be overruled).

Will be fixed in the next push. I believe that `after! org` will be sufficient, as the bibtex-completion will be loaded before this.

2020-05-04 11:03 UTC, das-s commented
If I might chime in here as someone who is already using this merge request:
IMHO the module is not documented enough for people who are new to reference managment or consider switching from more mainstream programs like zotero or citavi. For example, the linked reddit post in the current readme only considers papers but books or online sources are not touched upon. Especially org-ref and its corresponding packages are neither documented very well nor easily discoverable for the new user. Maybe implementing a dedicated keybinding layer would be sufficient to make discoverability easier. This might not be up to the task for the current PR but should be considered. 

I'd help with documenting if my skills suffice. 
Some ideas about approaching this documentation:
* What to do if drag-n-drop fails? 
* What if there is no DOI?
* How to add entries manually

2020-05-04 11:17 UTC, bdarcus commented
> If I might chime in here as someone who is already using this merge request:
> IMHO the module is not documented enough for people who are new to reference managment or consider switching from more mainstream programs like zotero or citavi. For example, the linked reddit post in the current readme only considers papers but books or online sources are not touched upon. Especially org-ref and its corresponding packages are neither documented very well nor easily discoverable for the new user. 

I agree with all of the above.

It's related to the problem @brianmcgillion noted just above that the functionality is spread across multiple packages, which we are trying to integrate as nicely as we can.

This is pretty common in the emacs world, and while it has its annoyances, there is value to it as well.

The practical question for this module documentation is what we should be responsible for documenting, and what should we defer to the packages we're using?

It's not really our fault if upstream package documentation is lacking. OTOH, we should certainly a) report gaps upstream, and b) look for places where we can provide a bridge.

> Maybe implementing a dedicated keybinding layer would be sufficient to make discoverability easier. 

You mean "dedicated" to Doom and this module, that supersede those in the packages we're using?

Can you give an example where this is currently a problem that we don't do this?

> This might not be up to the task for the current PR but should be considered for the future.
> 
> I'd help with documenting if my skills suffice.
> Some ideas about approaching this documentation:
> 
> * What to do if drag-n-drop fails?
> * What if there is no DOI?
> * How to add entries manually
> * Whats a general workflow?
> * How to add notes to file?
> * How can org-noter be incorporated?
> * How to create an org-roam entry with cite links?

All are good and reasonable issues.

But per my points above, which of those are realistically our responsibility to document, and which should be reported upstream?

2020-05-04 15:01 UTC, das-s commented
> You mean "dedicated" to Doom and this module, that supersede those in the packages we're using?

Sorry, I worded this incorrectly. I meant a dedicated default keybinding prefix when using `biblio`, for example `SPC-r`(could also only be active on selected mode-maps like `org` or `bibtex`). This would then pack some useful commands behind it for getting started. In case someone knows their way around it can be overwritten by custom bindings. Admittedly, this approach might be beyond the philosophy of doom-emacs.

> Can you give an example where this is currently a problem that we don't do this?

Does this get answered with my previous paragraph? If not, could you please rephrase this? Do you mean doom-emacs in general or specific changes in the current PR? 

> But per my points above, which of those are realistically our responsibility to document, and which should be reported upstream?

I admit that this a weak point and those questions might be more fitting on a blog or in `doom-emacs/docs/` documentation. Most of it should be documented upstream. Still, doom provides a features section for some [modules](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lookup/README.org). Maybe one could think of adding some helpful tips there, but this is most likely outside the range of this PR.

2020-05-04 21:16 UTC, bdarcus commented
> I meant a dedicated default keybinding prefix when using `biblio`, for example `SPC-r`(could also only be active on selected mode-maps like `org` or `bibtex`). This would then pack some useful commands behind it for getting started. In case someone knows their way around it can be overwritten by custom bindings. Admittedly, this approach might be beyond the philosophy of doom-emacs.

It probably would, but @hlissner would be arbiter of that question.

You can always create your own keybindings to do this too.

> Maybe one could think of adding some helpful tips there, but this is most likely outside the range of this PR.

Sure. Hopefully we can get this PR merged, and maybe that can be a latter step.

Feel free to collect of that info for possible inclusion.

2020-05-08 11:10 UTC, brianmcgillion commented
rebased and bumped the pins

2020-05-08 15:19 UTC, LauraBMo commented
Hey, thanks a lot for extending the module tools: biblio. As LaTeX user it will be really handy.
Nevertheless, I really think that `org-ref` should be offered as an option with a flag.
It is a great package, but I think it does not integrate well with Doom philosophy.
- It slowdowns the init time a lot.

2020-05-08 15:23 UTC, bdarcus commented
The assumption currently is that if someone is using org, then we can
assume you want org-ref.

So you're saying that's not the case with you?

FWIW, I have no objection to adding that flag; just clarifying.

2020-05-08 15:28 UTC, LauraBMo commented
Yes, I am using `ox-bibtex` [https://github.com/yyr/org-mode/blob/master/contrib/lisp/ox-bibtex.el](url)

2020-05-08 18:49 UTC, brianmcgillion commented
it is deferred so do not load on init, only when referenced. Also it uses ivy-bibtex if you have ivy enabled and not helm (https://github.com/hlissner/doom-emacs/pull/2888/commits/5f0edbca435e71dfbb3484ed7f49a1717c36b74a#diff-9535f000ae2e09e5c9700b6136569cc6R79), the overall package used to be  called helm-bibtex, but that has now been split into 3 packages (https://github.com/tmalsburg/helm-bibtex/commit/473761dffe956b5aa7d60d399d037ec7d80c69b8). ivy-bibtex, helm-bibtex and bibtex-completion. bibtex-completion is used by helm/ivy as the backend, but used to be included by requiring helm-bibtex. I can check if the reference has been changed in orf-ref.

AFAIK the "ox-" series of packages are used for exporting form org to some other format (https://orgmode.org/worg/exporters/ox-overview.html).

As regards to speed, I see no additional delays with init. I have these packages enabled and still get between 0.5 and 0.6 second times on init.

For pure latex enabled use cases reftex is included in the latex module under the +ref flag.

As for the doom philosophy, I can not really comment there. But what I can see is that it seems to about giving a reasonable set of defaults for the average user of a package, with the flexibility to modify those to your needs. So if org-ref is not the common citation mechanism used by org users I have no issue to flag it out. If, however, it is one or 2 folks, I would probably suggest to add the following to the documentation `(package! org-ref :disable)` for people to opt-out.

2020-05-08 20:11 UTC, LauraBMo commented
`(package! org-ref :disable)` seems a good option.
Just for clarifying, it is `org-ref` who loads `helm`.
The line  `(setq org-ref-completion-library #'org-ref-ivy-cite)` does not solve the problem.
I am referring to [for now it is stuck in helm](https://github.com/jkitchin/org-ref/issues/552#issuecomment-537116098) (actually, that is the main reason I do not use `org-ref`).

2020-05-15 09:33 UTC, bdarcus commented
Org-roam just added tagging support, which can be used to type bibliographic notes, including (optionally) by placing them in a subdir.

https://org-roam.github.io/org-roam/manual/Tags.html#Tags

2020-05-17 11:16 UTC, bdarcus commented
> Sorry for the delay. As I'm very new to bibtex, org-roam and org-ref, reviewing this is taking me a while; digging through these packages. There are few pain points I'm trying to deal with:
> 
> 1. The three `defcustom`s. If possible, I'd _like_ to avoid introducing new variables, and am investigating a way around these; especially because we do not use `defcustom` anywhere else.
> 2. We have a lot of `(unless X (setq X DEFAULTS))`, and I'm going through each of their upstream defaults to see if these checks are warranted (or if we could simply define them _in_ their respective `defvar`s).
> 3. I don't fully understand the relationship between org-ref and bibtex-completion, and wonder why `:after (org bibtex-completion)` is necessary. This complicates the customization path for the user, because neither `(after! org ...)` nor `(after! bibtex-completion ...)` will be enough to configure the package (and due to `use-package`'s [:after semantics](https://github.com/jwiegley/use-package/issues/829), any config in a user's `(after! org-ref ...)` will be overruled).
> 
> I'll keep you posted as I truck along.

Can we assess where we're at?

My understanding is that @brianmcgillion addressed 3 in a subsequent commit, and provided context for 1 and 2 in [this comment](https://github.com/hlissner/doom-emacs/pull/2888#issuecomment-623129214). 

So the question of those variables is the key thing we're stuck on ATM?

2020-05-19 17:46 UTC, jlmaccal commented
I ran into a problem with this module and `(format +onsave)`.

Specifically, when `(format +onsave)` is set, dragging a pdf file onto an open bib file does not work correctly. Org-ref correctly looks up the reference information based on the doi and inserts it into the bib file. The file is then saved and autoformatted. This leaves the point in the wrong place for the remainder of org-ref's drag and drop handling, which leads to strange filenames, like `nil.pdf` and other weird problems. This is fixed by disabling `(format +onsave)`.

I would suggest that either autoformating of bib files should be disabled if both the biblio module is loaded and `+onsave` is set, or that appropriate advice is added around org-ref functions to temporarily disable autosave.

2020-05-29 19:46 UTC, bdarcus commented
Just a gentle bump, @hlissner, while I'm thinking about :-)

https://github.com/hlissner/doom-emacs/pull/2888#issuecomment-629780792

2020-06-01 00:09 UTC, JonathanReeve commented
I've been testing this branch, and I'm no expert, so take this as you will, but I find that enabling this module causes everything org-related in Doom not to work, on my setup, at least. It complains: `(wrong-type-argument stringp nil)`. I did `toggle-debug-on-error` and I got this traceback (truncated, but called from require(org) and so on. 

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  directory-name-p(nil)
  (if (directory-name-p org-ref-notes-directory) (function org-ref-notes-function-many-files) (function org-ref-notes-function-one-file))
  (setq org-ref-notes-function (if (directory-name-p org-ref-notes-directory) (function org-ref-notes-function-many-files) (function org-ref-notes-function-one-file)))
  (if nil nil (setq org-ref-notes-function (if (directory-name-p org-ref-notes-directory) (function org-ref-notes-function-many-files) (function org-ref-notes-function-one-file))))
  (progn (require (quote org-ref) nil nil) (setq org-ref-open-pdf-function (quote org-ref-get-pdf-filename-helm-bibtex)) (if nil nil (setq org-ref-notes-function (if (directory-name-p org-ref-notes-directory) (function org-ref-notes-function-many-files) (function org-ref-notes-function-one-file)))) t)
  (closure (t) nil (progn (require (quote org-ref) nil nil) (setq org-ref-open-pdf-function (quote org-ref-get-pdf-filename-helm-bibtex)) (if nil nil (setq org-ref-notes-function (if (directory-name-p org-ref-notes-directory) (function org-ref-notes-function-many-files) (function org-ref-notes-function-one-file)))) t))()
  eval-after-load-helper("/home/jon/.emacs.doom.d/.local/straight/build/org-mode/org.elc")
  run-hook-with-args(eval-after-load-helper "/home/jon/.emacs.doom.d/.local/straight/build/org-mode/org.elc")
  do-after-load-evaluation("/home/jon/.emacs.doom.d/.local/straight/build/org-mode/org.elc")
```

What I'm guessing is happening is that [this line](https://github.com/brianmcgillion/doom-emacs/blob/bibtex/modules/tools/biblio/config.el#L91) calls `(if (directory-name-p org-ref-notes-directory))`, which on my system is `nil`, since I don't have one of these directories—I just use a single org-ref notes file. 

My setup is pretty much just like the one in [your config.el](https://github.com/brianmcgillion/doomd/blob/master/config.org), with these lines: 

```
(setq! +biblio-pdf-library-dir "~/Dropbox/Papers/"
       +biblio-default-bibliography-files '("~/Dropbox/Papers/library.bib")
       +biblio-notes-path "~/Dropbox/Org/Projects/books.org")
```

So I don't know what's going wrong. 

But I do know that I can work around this by adding the line: 

```
(setq! org-ref-notes-directory "")
```

right above my config lines from earlier. If my elisp-fu were better, I'd try to fix this, but alas, that's all I got. Hope this helps.

2020-06-06 18:51 UTC, theianjones commented
I just tested this out and was able to get everything working. I did end up with `Warning (:warning): Bibtex-completion couldn't find entry with key "EvilreadthedocsioenlatestPdf".` but I think this may be a user warning?

2020-06-13 15:46 UTC, Emiller88 commented on modules/tools/biblio/config.el
> +           (setq bibtex-completion-notes-path value)))))
This is really clever, but it might be more readable and easy to understand if you followed how the org and capture declares the variables 

https://github.com/hlissner/doom-emacs/blob/0f3bd571011f0f13a77b2f22e2c25dd5bfe03c2a/modules/lang/org/config.el#L24-L61

https://github.com/hlissner/doom-emacs/blob/0f3bd571011f0f13a77b2f22e2c25dd5bfe03c2a/modules/lang/org/autoload/org-capture.el#L73-#160

And just set them like the modules readme covers, making it easier for users to hack on rather than follow the logic of the function. For example
```lisp
(after! bibtex-completion
  (setq! bibtex-completion-bibliography +biblio-default-bibliography-files
        bibtex-completion-library-path +biblio-pdf-library-dir
        bibtex-completion-notes-path +biblio-notes-path))
```

2020-06-13 15:54 UTC, Emiller88 commented on modules/tools/biblio/config.el
> +           (setq bibtex-completion-notes-path value)))))
I think this module should also consider setting some "opinionated" defaults of where files should be like other doom modules, see the org-mode stuff again.

Maybe 
```lisp
(setq! +biblio-pdf-library-dir (concat org-directory "pdfs")
       +biblio-default-bibliography-files '((concat org-directory "bib"))
       +biblio-notes-path (concat org-directory "notes"))
```
My example makes it a hard dependency on org, but there could be a `+bib-directory` variable created. This would make fewer changes for the end user if anything changes in the future.

2020-06-15 14:46 UTC, bdarcus commented on modules/tools/biblio/config.el
> +           (setq bibtex-completion-notes-path value)))))
Unfortunately, this PR seems stalled ATM.

It seems that @brianmcgillion must be busy with other things.

And while I updated [my own branch](https://github.com/bdarcus/doom-emacs/tree/bd-biblio) with some of the suggestions above, I'm an elisp novice, so not always super clear how to proceed on some of the details.

Finally, we've not had any feedback from @hlissner since end-of-April, so I'm not sure what, if anything, remains to be done. 

I do know at least some of his concerns have been addressed by @brianmcgillion, and by the suggestions of @myshevchuk and upstream changes in `org-roam`.

2020-06-21 11:18 UTC, brianmcgillion commented on modules/tools/biblio/config.el
> +    (setq org-roam-bibtex-templates
Sorry for the delay, missed the updated thread here. Changes pushed.

2020-06-21 11:19 UTC, brianmcgillion commented on modules/tools/biblio/config.el
> +           (setq bibtex-completion-notes-path value)))))
Thanks @Emiller88, I will take a look

2020-06-21 11:28 UTC, brianmcgillion commented
> But I do know that I can work around this by adding the line:
> 
> ```
> (setq! org-ref-notes-directory "")
> ```
> 
> right above my config lines from earlier. If my elisp-fu were better, I'd try to fix this, but alas, that's all I got. Hope this helps.

Thanks @JonathanReeve, I think your deduction is spot on. `directory-name-p` does not seem to behave logically, i.e. nil in my understanding is not a directory name so should take the alternative path just like " " or "file", however, it is instead treated as an invalid parameter. I will look to fix that.

2020-06-26 11:30 UTC, bdarcus commented on modules/tools/biblio/README.org
> +#+DATE:    April 11, 2020
```suggestion
#+DATE:    June 26, 2020
```

2020-07-10 13:42 UTC, bdarcus commented on modules/tools/biblio/README.org
> +#+DATE:    April 11, 2020
So how do we get this unstuck @hlissner?

2020-07-20 14:28 UTC, tecosaur commented
@brianmcgillion how's it going? Have you had any further time to look into this? I'm just a casual observes but it looks like this is 95% of the way there

2020-07-21 02:09 UTC, hlissner commented on modules/tools/biblio/README.org
> +#+DATE:    April 11, 2020
May as well move it up. The date should represent when it was added to Doom.

2020-08-03 04:13 UTC, AnikaSU commented
> An user of `org-roam` may use a one long file note using `org-ref`, so it would be a good idea that the module provides an independent flag (e.g. +roam-bibtex) for `org-roam-bibtex`.

I agree with that

2020-08-03 10:56 UTC, bdarcus commented on modules/tools/biblio/README.org
> +#+DATE:    April 11, 2020
"It" being the module; so when it was first merged?

Or "it" meaning this README, so when it is merged?

2020-08-06 04:37 UTC, hlissner commented on modules/tools/biblio/README.org
> +#+DATE:    April 11, 2020
It being the module.

2020-09-07 21:13 UTC, helpotters commented
Any updates about the org-ref and org-roam-bibtex integrations?

2020-09-08 13:40 UTC, Emiller88 commented
@helpotters I can't speak for the plan on a timeline for integration of it into doom, but it's working very well for me by just dropping the changes here into my private config. I think if more people can test the stability of the module in their work we can find any nagging issues.

2020-09-09 16:01 UTC, Emiller88 commented
I'm having an issue that I believe is related to the configuration. Occasionally I get an error when creating a new notes file.

`if: Symbol’s function definition is void: pushnew`

2020-09-09 16:13 UTC, Emiller88 requested changes

2020-09-09 16:13 UTC, Emiller88 commented on modules/tools/biblio/config.el
> +- tags ::
```suggestion
             :head "#+title: ${=key=}: ${title}\n#+roam_key: ${ref}\n#+roam_tags:
             
```
`org-roam` recommends using lowercase keywords now, and they also have added `roam_tags` which can replace the tags section for better functionality.

2020-09-09 20:36 UTC, helpotters commented
If it's solid enough to run for general testing, I'd be enthusiastic to
participate. Thank you for the suggestion and encouragement!

2020-09-09 20:42 UTC, bdarcus commented
It's definitely solid enough for testing (and even merging probably).

>

2020-10-14 06:04 UTC, brianmcgillion commented on modules/tools/biblio/config.el
> +- tags ::
Thanks, sorry for the late reply. I changed to lower case, however, I have not tested without the tags :: yet. But I will do that soon and delete as needed

2020-10-14 13:40 UTC, brianmcgillion commented
> I've been testing this branch, and I'm no expert, so take this as you will, but I find that enabling this module causes everything org-related in Doom not to work, on my setup, at least. It complains: `(wrong-type-argument stringp nil)`. I did `toggle-debug-on-error` and I got this traceback (truncated, but called from require(org) and so on.

@JonathanReeve could you test, with some guidance from @Lejon the single file option should work. I tested a single org file without Roam enabled and it created the notes. If not please let me know!

2020-10-14 13:44 UTC, brianmcgillion commented
> If it's solid enough to run for general testing, I'd be enthusiastic to participate. Thank you for the suggestion and encouragement!

I use it on a daily basis. I just rebase ontop of doom/develop occasionally and it is working fine. Of course, I have my workflow and these tools allow many ways to achieve similar things, so I have not exhausted all config possibilities.

2020-10-14 14:30 UTC, bdarcus reviewed
> @JonathanReeve could you test, with some guidance from @lejon the single file option should work. I tested a single org file without Roam enabled and it created the notes. If not please let me know!

After we get confirmation on this piece, LGTM!

2020-10-14 18:43 UTC, JonathanReeve commented
I've been using this successfully for some time now. Even started using org-roam, and org-roam-bibtex, as well. I haven't tested it with minimal or little config, but it works with my setup. :shipit:

2020-10-30 23:24 UTC, A6GibKm commented
Looking forward for this :+1:

2020-12-02 22:28 UTC, lzmartinico commented on modules/tools/biblio/config.el
> +  (setq org-ref-open-pdf-function 'org-ref-get-pdf-filename-helm-bibtex)
Hi, I just started testing your PR and it mostly works great! One questions I had though is why is this set to override org-ref-open-pdf-at-point? This change breaks opening a PDF file from a cite link (through pressing Enter for the org-ref modal, and Open PDF)

2020-12-18 10:05 UTC, junwei-wang commented
I am looking forward to merging this pull request.

2020-12-25 19:14 UTC, aaaawwWWWwwwwWWW commented on modules/tools/biblio/README.org
> ++ ~+biblio-default-bibliography-files~
```suggestion
+ ~+biblio-pdf-library-dir~
```

2020-12-25 20:18 UTC, aaaawwWWWwwwwWWW commented
since hugo and ox-hugo are already integrated into doom, would be nice the addition of https://github.com/andras-simonyi/citeproc-org into biblio

2021-01-03 15:49 UTC, bdarcus commented
> since hugo and ox-hugo are already integrated into doom, and now with this org-ref, would be nice the addition of https://github.com/andras-simonyi/citeproc-org into biblio

That would be a good next step, but we first have to get this merged. It's now been more than eight months.

2021-01-04 16:53 UTC, aaaawwWWWwwwwWWW commented
> That would be a good next step, but we first have to get this merged. It's now been more than eight months.

Sure thing! I've been using this PR for almost 11 days now and works great!

2021-01-21 17:08 UTC, lzmartinico commented on modules/tools/biblio/config.el
> +- tags ::
What's the point of having this when you also have roam_tags? As far as I can tell, this and the keywords below aren't easily searchable. In fact, it would be really nice if the entries in keywords automatically linked to a note!

2021-01-21 17:14 UTC, bdarcus commented on modules/tools/biblio/config.el
> +- tags ::
What's "this"? The tags?

If yes, those aren't functionally the same as roam_tags. It's like the difference between keywords/tags and categories.

2021-01-21 17:35 UTC, lzmartinico commented on modules/tools/biblio/config.el
> +- tags ::
Yes sorry, I meant the tags. I was looking at the org-roam forum and it seems like they are half-deprecated, or at least there is no built-in way to search through them, so it's not clear to me how you would use them - insert a backlink to a "category" note?

2021-01-21 17:37 UTC, junwei-wang commented on modules/tools/biblio/config.el
> +- tags ::
`SPC n r f` -> `org-roam-find-find`

2021-01-21 17:52 UTC, lzmartinico commented on modules/tools/biblio/config.el
> +- tags ::
As far as I can tell, org-roam-find-file (I assume find-find was a typo?) only filters through the roam_tags, and not the tags:: ? Or am I missing some custom search filter?

2021-01-21 19:29 UTC, lzmartinico commented on modules/tools/biblio/config.el
> +- tags ::
I went back and looked at Jethro's [How to take smart notes](https://blog.jethro.dev/posts/how_to_take_smart_notes_org/), which was helpful to understand how they used tags at the time; as I was guessing, it's for backlinks. I think then it makes sense to keep that in the template. On the other hand, it would be nice if a backlink was automatically added for backlinks!

2021-01-29 19:00 UTC, bdarcus commented
Is anyone else seeing this?

Using `ivy-bibtex`, when I select a candidate, and do `M-o` to get the action menu, I just get a generic ivy menu; not the `ivy-bibtex` actions I'm expecting.

2021-02-06 17:42 UTC, natejlong commented
@bdarcus I'm also seeing that generic ivy menu

2021-02-07 18:38 UTC, bdarcus commented
Thanks @natejlong.

I don't ever recall seeing that before. Is that something new in ivy?

2021-02-07 18:42 UTC, bdarcus commented
As we're still waiting to get this merged, I just thought I'd update on the discussions I've been involved in on this PR.

https://github.com/tmalsburg/helm-bibtex/pull/355

What's interesting about this is it proposes to adapt to bibtex-completion to make ivy/helm-bibtex-like functionality available in default Emacs completion, and hence also selectrum.

I think it would be straightforward to adapt here, for when there is a selectrum module merged.

2021-02-08 04:13 UTC, natejlong commented
Honestly it's the first time I've noticed it too! I was using helm-bibtex previously, not a big expert on helm or ivy to be honest. 

I should've also mentioned I'm not using this PR exactly, so it might be a config/package version difference, but if there's anything I can do to help you out let me know

On Sun, Feb 7, 2021, at 13:43, bdarcus wrote:
> 

> As we're still waiting to get this merged, I just thought I'd update on the discussions I've been involved in on this PR.

> tmalsburg/helm-bibtex#355 <https://github.com/tmalsburg/helm-bibtex/pull/355>

> What's interesting about this is it proposes to adapt to bibtex-completion to make ivy/helm-bibtex-like functionality available in default Emacs completion, and hence also selectrum.

> I think it would be straightforward to adapt here, for when there is a selectrum module merged.


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/hlissner/doom-emacs/pull/2888#issuecomment-774730219>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAYT37GSGB3XCPAQGAAEQM3S53NLTANCNFSM4MGFYSBA>.

2021-02-20 14:18 UTC, bdarcus commented
> Honestly it's the first time I've noticed it too! I was using helm-bibtex previously, not a big expert on helm or ivy to be honest.

I think we want that keybinding to bypass that interim menu and go straight to the actions, but I'm not an expert either, so not sure.

2021-02-20 14:32 UTC, bdarcus commented
As we wait on input from henrik, a bit of an update on the discussion I linked to above on adding support for completing-read/selectrum to bibtex-completion, as it has bearing on an initial decision on a module keybinding.

Both `ivy-bibtex` and `helm-bibtex` have their respective entry points, which brings up a search interface for a bibliography collection, and then one choose actions for the selected candidate(s).

But @minad made the, I think very good, suggestion to instead expose those actions as full interactive commands, so that the user can more directly do, for example `M-x ivy-bibtex-insert-key`.

Which brings me to this:

``` elisp
:desc "Bibliographic entries"        "b"
        (cond ((featurep! :completion ivy)   #'ivy-bibtex)
              ((featurep! :completion helm)  #'helm-bibtex)))
```
              
It strikes me that those commands really means "search bibliographic entries" (which is basically the docstring for these functions), and so I think ideally the binding should be "SPC n b s", and that perhaps later we can add additional commands to "SPC n b."

2021-02-21 13:39 UTC, bdarcus commented
As for @hlissner, here's what he said on discord awhile back in response to a query from @bmg:

> I have a couple design issues with the PR that I can't solve without more insight into how to use org-ref and org-roam-bibtex.

If this is the holdup ATM, it might give someone (@myshevchuk?) an idea of where to look, if they have the time and inclination.

2021-02-21 14:41 UTC, lejon commented
Please take me off this thread since I’m not the right Leif Jonsson.

BR
-Leif Jonsson

> On 21 Feb 2021, at 14:39, bdarcus <notifications@github.com> wrote:
> 
> 
> As for @hlissner <https://github.com/hlissner>, here's what he said on discord awhile back in response to a query from @BMG <https://github.com/BMG>:
> 
> I have a couple design issues with the PR that I can't solve without more insight into how to use org-ref and org-roam-bibtex.
> 
> If this is the holdup ATM, it might give someone (@myshevchuk <https://github.com/myshevchuk>?) an idea of where to look, if they have the time and inclination.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/hlissner/doom-emacs/pull/2888#issuecomment-782859797>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA664MYCSRYBS3IYPLEWFOTTAEEKVANCNFSM4MGFYSBA>.
>

2021-02-21 14:51 UTC, bdarcus commented
Can we do that?

You might just click the unsubscribe link at the bottom of the
notification email?

2021-02-21 14:53 UTC, lejon commented
You’re right! I thought that was GitHub in general, but it was this specific thread!
Thanks!

Cheers!
-Leif

> On 21 Feb 2021, at 15:51, bdarcus <notifications@github.com> wrote:
> 
> 
> Can we do that?
> 
> You might just click the unsubscribe link at the bottom of the
> notification email?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/hlissner/doom-emacs/pull/2888#issuecomment-782870131>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA664M4LJMODVELDFRIK6SLTAEMXXANCNFSM4MGFYSBA>.
>

2021-02-25 01:06 UTC, bdarcus commented
> Is anyone else seeing this?
> 
> Using `ivy-bibtex`, when I select a candidate, and do `M-o` to get the action menu, I just get a generic ivy menu; not the `ivy-bibtex` actions I'm expecting.

Seems a bug:

https://github.com/abo-abo/swiper/issues/2397

2021-02-26 10:36 UTC, myshevchuk commented
@bdarcus Hi, is there anything specific I could help with? I looked at the configuration code and most of it is now outdated. Also, ORB is still unstable and a few possibly breaking changes are expected.

2021-02-26 11:56 UTC, bdarcus commented
> @bdarcus Hi, is there anything specific I could help with? I looked at the configuration code and most of it is now outdated. Also, ORB is still unstable and a few possibly breaking changes are expected.

No, I was just wondering if you saw anything off that you thought might have caused the concern that @hlissner noted, but didn't really explain.

But what you say itself might itself suggest removing this for now.

Should we just do that and merge the other stuff, @brianmcgillion?

2021-02-26 12:22 UTC, Jonghyun-Yun commented
The module causes errors with vanilla `config.el`, which is something people don't expect to see. How about revising 
https://github.com/brianmcgillion/doom-emacs/blob/6d61f98ef11c4fcdfd30135564a9290d7337ca27/modules/tools/biblio/config.el#L88-L93 as follows?

``` emacs-lisp
    (setq org-ref-notes-function #'org-ref-notes-function-one-file)
    (unless (null org-ref-notes-directory)
      (setq org-ref-notes-function (if (directory-name-p org-ref-notes-directory)
                                       #'org-ref-notes-function-many-files
                                     #'org-ref-notes-function-one-file)))
```

2021-03-01 21:56 UTC, bdarcus commented
In case anyone is testing the new [WIP selectrum PR](https://github.com/hlissner/doom-emacs/pull/4664), I've put together a PR for bibtex-completion that makes it compatible.

So if you want to test the two together, I now finally got it all working correctly ....

https://github.com/tmalsburg/helm-bibtex/pull/361

![Screenshot from 2021-03-01 16-20-49](https://user-images.githubusercontent.com/1134/109560655-22b13580-7aaa-11eb-953b-052a765d8996.png)

The screenshot demonstates my point above about it possibly making sense to change the keybindings for the bibliography module; that `ivy-bibtex` and `helm-bibtex` should probably be bound to `n b s` for "search".

2021-03-14 17:16 UTC, bdarcus commented
> In case anyone is testing the new [WIP selectrum PR](https://github.com/hlissner/doom-emacs/pull/4664), I've put together a PR for bibtex-completion that makes it compatible.

Update; now a separate package.

https://github.com/bdarcus/bibtex-actions

2021-03-16 17:05 UTC, helpotters commented
I'm a bit lost. Is there a new package just for ivy-bibtex/helm-bibtex compatability? kkkkkkkk

2021-03-16 17:10 UTC, bdarcus commented
> I'm a bit lost. Is there a new package just for ivy-bibtex/helm-bibtex compatability?

What are you referring to?

If the package I posted just above, the easiest way to think of it is it's like `selectrum-bibtex` (though will work with other completing-read-based completion systems).

If this PR, no; the module already has that; this is expanding the features.

2021-03-17 20:06 UTC, helpotters commented
The org-file for biblio is not very clear in how to setup or utilize the package. 

For example, something as simple as inserting a citation from the default bibtex file.

2021-03-17 21:18 UTC, bdarcus commented
> The org-file for biblio is not very clear in how to setup or utilize the package.
> 
> For example, something as simple as inserting a citation from the default bibtex file.

It's been awhile (this PR was submitted almost a year ago at this point), but I think that's because these packages, and this module, provide a range of ways that could work.

Are you authoring in latex-mode, markdown-mode, or org-mode, for example?

Using primarily ivy-bibtex or helm-bibtex to insert the citations, or something else?

Aside: if the former, you open those commands, and insert the citation from there. But that's extensively documented at [that project](https://github.com/tmalsburg/helm-bibtex).

Do others have any views on this question; about the depth of what should be documented here?

2021-03-21 07:49 UTC, tecosaur commented on init.example.el
> +       ;;biblio            ; A collection of bibliographic reference tools
Can this be sassier? :grin:

2021-03-21 14:17 UTC, bdarcus commented on init.example.el
> +       ;;biblio            ; A collection of bibliographic reference tools
Best comment ever!

Any suggestions?

2021-03-21 15:08 UTC, tecosaur commented on init.example.el
> +       ;;biblio            ; A collection of bibliographic reference tools
Courtesy of the Doom discord:
> Writes a PhD for you[citation needed]

2021-04-20 02:54 UTC, brianmcgillion commented
> I believe these should be, and are, set with the +biblio variables @brianmcgillion, so you can remove this part?

At the top of the section it states "It is of course possible to set the variables directly through their respective packages as shown below, in which case you can ignore the ~+biblio...~ versions.". So the instructions are there more for completeness if someone chooses that option.

2021-05-01 13:37 UTC, payasrelekar commented on init.example.el
> +       ;;biblio            ; A collection of bibliographic reference tools
One question, is this going to be a separate module, as seen in above line, org should it be a flag for org module, like +roam, +deft etc.
Considering this is heavily dependent on org-mode and org-roam, shouldn't be a flag?

2021-05-01 13:45 UTC, bdarcus commented on init.example.el
> +       ;;biblio            ; A collection of bibliographic reference tools
> One question, is this going to be a separate module, as seen in above line, org should it be a flag for org module, like +roam, +deft etc.
> Considering this is heavily dependent on org-mode and org-roam, shouldn't be a flag?

I'm confused. It's already a separate module.

And a user of this module may heavily use latex, for example, but not org at all.

It won't load those org-related packages unless you use the `org` module.

2021-05-01 19:05 UTC, bdarcus commented
For those of you interested in this, but not on the org list, after many years of stops and starts, `org-cite` (native org citation support) is set to be merged soon, and Bastien put out a call for testing today.

https://lists.gnu.org/archive/html/emacs-orgmode/2021-05/msg00003.html

So if you contribute to that, it will get it merged sooner rather than later.

If all goes smoothly, this should be merged for org 9.5.

2021-05-03 15:26 UTC, natejlong commented
> For those of you interested in this, but not on the org list, after many years of stops and starts, org-cite (native org citation support) is set to be merged soon, and Bastien put out a call for testing today.

Thank you so much for linking this, I had no idea this was in the works. More importantly thank you @bdarcus for your work on the feature itself! I read through the thread there and the citation syntax looks like _exactly_ what I've wanted in org. So excited to try this out

2021-05-06 11:06 UTC, bdarcus commented
Does `org-cite` have any implications for the details of this package?

I'm wondering in particular about `org-ref`.

I do know it's author (John Kitchen) is hoping to rewrite that package to support it, but also that he doesn't have much time to do this, and has estimated it might take a year.

So not sure; maybe we should put that package behind a flag?

2021-05-07 12:55 UTC, bdarcus commented
> > In case anyone is testing the new [WIP selectrum PR](https://github.com/hlissner/doom-emacs/pull/4664), I've put together a PR for bibtex-completion that makes it compatible.
> 
> Update; now a separate package.
> 
> https://github.com/bdarcus/bibtex-actions

Another update:

Now on MELPA, and now incorporated into the above monster selectrum PR.

So if you have `selectrum` and `biblio` selected in your init.el, you will get `bibtex-actions`.

2021-05-27 15:43 UTC, tecosaur commented
I'm definitely of the mind that adding citeproc would be a good idea :+1: 
Also, I'd estimate the merge timeline to be of the order of weeks based on current progress.

2021-05-27 15:47 UTC, bdarcus commented
> I'm definitely of the mind that adding citeproc would be a good idea.

That, plus putting `org-ref` behind a flag, would seem the best way forward, giving users the most flexibility.

I don't, for example, use `org-ref`, and likely won't with `org-cite`. But I suspect others will use both.

2021-06-09 04:04 UTC, brianmcgillion commented
based on a discussion with @bdarcus I have added +ref for inclusion of org-ref. Please add (org +ref) to your .doom.d/init.el

2021-06-09 12:42 UTC, bdarcus commented
> based on a discussion with @bdarcus I have added +ref for inclusion of org-ref. Please add (org +ref) to your .doom.d/init.el

Thanks @brianmcgillion!

FYI, I've learned a bit more about `org-cite` "follow" processors in the last 48 hours, after earlier not paying much attention to them.

The `org-cite` author describes them succinctly as "Follow is what happens when you use C-o on a citation." 

In other words, it allows you to bind a function to `org-open-at-point`, to be able to run actions on either org citations or citation-references.

My plans for `bibtex-actions`, which will allow a kind of lightweight embarkified micro-org-ref:

https://github.com/bdarcus/bibtex-actions/issues/141

If and when John rewrites `org-ref`, I'd expect it to be just such a "follow" processor.

2021-06-23 01:01 UTC, chuxubank submitted a review, later dismissed

2021-06-29 14:18 UTC, iyefrat commented
@brianmcgillion Hey! I have a few remarks on the PR:

- I think the `+ref` flag makes more sense on the `biblio` module, since all the code that deals with it is in the `biblio` module, maybe as a `+org-ref` flag.
- You might want to state more clearly in the readme that  `org-ref` installs **both** `ivy` and `helm` as dependencies, as users might wonder where the helm installation came from.
- I think you forgot to update the existence of the `+ref` flag in the readme.
-  You might also want to introduce a doctor check that warns users if they have `:tools biblio +org-ref` on but not `:lang org` on, and maybe one that warns them against using `org-ref` if they are using a completion system that isn't `ivy` or `helm` since it seems that'll cause issues.

2021-06-29 14:29 UTC, bdarcus commented on modules/tools/biblio/config.el
> +    (setq org-ref-notes-function (if (and org-ref-notes-directory (directory-name-p org-ref-notes-directory))
This will need to be changed to incorporate the org-ref flag?

Default behavior with org should be to use org-cite (when it's merged, though that will be before this module is merged here).

2021-06-29 16:24 UTC, bdarcus commented
I just added the draft PR to add org-cite support https://github.com/hlissner/doom-emacs/pull/5212, to hopefully make it easier to align this and (maybe) #4664.

2021-06-30 22:05 UTC, bdarcus commented
>     * You might want to state more clearly in the readme that  `org-ref` installs **both** `ivy` and `helm` as dependencies, as users might wonder where the helm installation came from.

A related issue: `org-roam-bibtex` currently requires `org-ref`, so has the same issue, though they intend to move to `org-cite`.

BTW, both `org-roam` and `org-roam-bibtex` are set for a major breaking change in a few days, to correspond with the release of `org-roam v2`.

2021-07-09 09:44 UTC, bdarcus commented
Just by way of update, org-cite is now in org-mode master.

2021-07-14 12:27 UTC, bdarcus commented
> Just by way of update, org-cite is now in org-mode master.

I think this is ready for review.

https://github.com/hlissner/doom-emacs/pull/5212

@hlissner will ultimately have to decide the path forward.

I think it's no-brainer that org-cite becomes default when the org + biblio modules.

Less clear is what to do about this PR.

I have added a section to #5212 that addresses that, but to summarize here I see two options:

1. close this PR in favor of #5212, but add some of this there
2. close #5212 in favor of this, but merge that code here

Or I guess a third option is #5212 could add org-cite on top of this. This just might need to be adjusted to ensure that's easy to do.

1 is a cleaner path going forward, particularly with the new vertico module (org-ref, as discussed above, will install both ivy and helm even if you use vertico), while 2 provides more options.

2021-07-18 17:44 UTC, bdarcus commented
Screencast demo of WIP org-cite version of org-ref.

https://www.youtube.com/watch?v=4ta4J20kpmM

I was already leaning towards removing org-ref from here, but this makes the case stronger.

2021-07-28 23:50 UTC, bdarcus commented
Update, after talking to @brianmcgillion today.

We're going to drop `org-ref` from here, but I plan to (already have actually) add it's successor, `org-ref-cite`, to #5290.

The goal will be to merge that first, for Brian to rebase on that, and then this PR will just be about adding ORB.

2021-09-27 01:31 UTC, chuxubank commented on modules/tools/biblio/config.el
> +  (setq org-ref-open-pdf-function 'org-ref-get-pdf-filename-helm-bibtex)
```suggestion
  (setq org-ref-get-pdf-filename-function #'org-ref-get-pdf-filename-helm-bibtex)
```

2021-11-22 21:49 UTC, iyefrat commented
@brianmcgillion so since #5290 got merged this can be reworked on top on that (and be merged finally :grimacing:)

2022-02-03 05:17 UTC, brianmcgillion commented
will close this merge request. Will add org-roam-bibtex in https://github.com/hlissner/doom-emacs/pull/6077 and org-ref can be discussed for inclusion separately.

2022-02-03 05:17 UTC, closed without merging