Add +powershell to lang/sh module
hlissner/doom-emacs pull request #3810
Opened 2020-08-23 11:17 UTC by samwdp

Added ability to get syntax highlighting on powershell scripts. Also added check for LSP to enable completion

2020-10-06 01:56 UTC, hlissner requested changes
Hi! Sorry for the late response. It seems like a lot of noise has crept into this PR. Would you mind rebasing it onto `develop` and making the marked changes?

2020-10-06 01:58 UTC, hlissner requested changes
Oh, and could you add a `+powershell` flag to `:lang sh` in docs/modules.org?

2020-10-06 07:43 UTC, samwdp commented
I have made the changes in my fork but the changes are not reflected in the PR

2020-10-06 21:18 UTC, hlissner requested changes

2020-10-06 21:18 UTC, hlissner commented on modules/lang/sh/config.el
> +		(add-hook 'powershell-mode-local-vars-hook #'lsp!)))
Please correct the indentation here. It should be 2 spaces (and 4 for the `add-hook` line).

2020-10-06 21:18 UTC, hlissner commented on modules/lang/sh/config.el
> +	      :when (featurep! +powershell)
Please add `:defer t` here, otherwise the package is eagerly loaded.

2020-10-08 17:56 UTC, hlissner approved these changes

2020-10-08 17:56 UTC, merged

2020-10-08 17:57 UTC, hlissner commented
Looks good to me. Thanks for your help!