doc/adding editorconfig and hl-column-fill documentation
hlissner/doom-emacs pull request #3815
Opened 2020-08-23 22:30 UTC by jeetelongname

Added docs for editorconfig and hl-column-fill

----

#

2020-09-26 15:20 UTC, rushsteve1 commented
This is related to #1166

2020-11-06 07:40 UTC, hlissner requested changes

2020-11-06 07:40 UTC, hlissner commented on modules/ui/fill-column/README.org
> +those types buffers open
Add period at end of sentence.

2020-11-06 07:40 UTC, hlissner commented on modules/ui/fill-column/README.org
> +of customisation's
`s/customisation's/customizations`

2020-11-06 07:40 UTC, hlissner commented on modules/ui/fill-column/README.org
> +of customisation's
And add period afterwards.

2020-11-06 07:40 UTC, hlissner commented on modules/ui/fill-column/README.org
> +If you want to change the face use
Add colon to end of the sentence

2020-11-06 07:40 UTC, hlissner commented on modules/ui/fill-column/README.org
> +                      :inverse-video t))
Do not recommend `set-face-attribute` (or any `set-face-*` function) to users. Recommend `custom-set-faces!` instead, which is much less error prone (doesn't require the user to be mind load order of the `hl-fill-column` package and the theme. e.g.

```elisp
(custom-set-faces!
  '(hl-fill-column-face :background "red"
                        :foreground "blue"
                        :inverse-video t))
```

2020-11-06 07:40 UTC, hlissner commented on modules/ui/fill-column/README.org
> +You can look at the documentation for ~set-face-attribute~ for the full list
Mention <kbd>SPC</kbd><kbd>h</kbd><kbd>f</kbd> `custom-set-faces\!` for looking up documentation and demos of this macro's usage.

2020-11-06 07:40 UTC, hlissner commented on modules/ui/fill-column/README.org
> +For it to take affect you need to do..
Replace incomplete ellipses (`..`) at the end of the sentence with colon `:`)

2020-11-06 07:40 UTC, hlissner commented on modules/ui/fill-column/README.org
> +* Configuration
Please add a blank line before first-level headings.

2020-11-12 02:14 UTC, hlissner requested changes

2020-11-12 02:14 UTC, hlissner commented on modules/ui/fill-column/README.org
> +and or convenience. For more info read this [[https://www.emacswiki.org/emacs/EightyColumnRule][emacs wiki page]]
Correct grammar:

> This module highlights the characters at the 80th column in the current buffer. This serves to remind users to keep lines short for accessibility and/or convenience. [[https://www.emacswiki.org/emacs/EightyColumnRule][Read more about this on the Emacs Wiki page]].

2020-11-12 02:14 UTC, hlissner commented on modules/ui/fill-column/README.org
> +desired column you would do this using
Add colon `:` to end of the sentence.

2020-11-12 02:14 UTC, hlissner commented on modules/ui/fill-column/README.org
> +For this to take effect in the current session cycle
Was something cut off here? Perhaps it should be 

> For this to take effect in the current session restart `hl-fill-column-mode`.

2020-11-12 02:14 UTC, hlissner commented on modules/ui/fill-column/README.org
> +Setting on a mode by mode basis is quite simple
Add colon `:` to end of the sentence.

2020-11-12 02:14 UTC, hlissner commented on modules/ui/fill-column/README.org
> +of customizations. This can be accessed using =SPC h f=
Add period to end of the sentence.

2021-03-06 03:34 UTC, hlissner approved these changes

2021-03-06 03:35 UTC, merged