Add ccls-specific configuration
hlissner/doom-emacs pull request #3879
Opened 2020-09-01 18:34 UTC by gagbo

Most of these changes come from MaskRay's private configuration found
here :
https://github.com/MaskRay/Config/blob/c078dfad340041673f2e056729a44c3df05a6248/home/.config/doom/modules/private/my-cc/config.el

- Limit ccls threads to be maximum half the available core count
- Add wrappers to call ccls LSP extensions
- Enable ccls-code-lens-mode
- Set initial state to emacs when navigating ccls-tree
- Use 'font-lock for semantic highlighting, making the speed choice
  according to variable's docstring

2020-09-01 18:40 UTC, gagbo commented
Documentation on the initialisation options :
 https://github.com/MaskRay/ccls/wiki/Customization#indexthreads
https://github.com/MaskRay/ccls/wiki/Customization#indextrackdependency

2020-09-01 18:54 UTC, gagbo commented
looks like parametersInDeclaration is actually still a valid value, but unsure about what it does https://github.com/MaskRay/ccls/blob/3e04997061bd1313676dafb9897f4a9590f90eeb/src/config.hh#L285

@MaskRay (sorry for the ping) do you put `parametersInDeclaration` to false to get faster indexing ? Does it prevent getting the parameters in the declaration when we ask the server process later ? I could not find doc on the wiki, and I can't understand what it does from looking at the code

2020-10-06 01:12 UTC, hlissner requested changes

2020-10-06 01:12 UTC, hlissner commented on modules/lang/cc/config.el
> +    (evil-set-initial-state 'ccls-tree-mode 'emacs))
Use `set-evil-initial-state!`, then you don't need a `(when (featurep! ...) ...)` check.

2020-10-06 01:12 UTC, hlissner commented on modules/lang/cc/config.el
> +                  :threads ,(max 1 (/ (string-to-number (shell-command-to-string "nproc")) 2)))))
This doesn't seem like a platform independent option. Can this be generalized? Or perhaps wrapped in a `(and IS-MAC IS-LINUX)` check?

2020-10-06 01:12 UTC, hlissner commented on modules/lang/cc/config.el
> +                  :threads ,(max 1 (/ (string-to-number (shell-command-to-string "nproc")) 2)))))
Also, please use `(cdr (doom-call-process "nproc"))` instead, as it doesn't pull the shell into the mix.

2020-10-06 01:12 UTC, hlissner commented on modules/lang/cc/config.el
> +      :n "w" #'+ccls/references-write))))
To be consistent everywhere where :desc is used, please inline the keys and their descriptions.

2020-10-06 01:24 UTC, gagbo commented on modules/lang/cc/config.el
> +                  :threads ,(max 1 (/ (string-to-number (shell-command-to-string "nproc")) 2)))))
I thought it was universal. It is very much not.

2020-10-06 04:48 UTC, hlissner requested changes
Both this and the later usage of `doom-call-process` is incorrect. It takes a list of arguments, not a single command. e.g.

```lisp
(doom-call-process "sysctl" "-n" "hw.ncpu")
;; and
(doom-call-process "clang" "-print-resource-dir")
```

Please correct these. `apply` may help:

```elisp
(apply #'doom-call-process '("sysctl" "-n" "hw.ncpu"))
```

2020-10-08 17:58 UTC, hlissner requested changes

2020-10-08 17:58 UTC, hlissner commented on modules/lang/cc/config.el
> +                                  :resourceDir (cdr (doom-call-process "clang -print-resource-dir"))))))))
This `doom-call-process` still needs to be fixed to: `(doom-call-process "clang" "-print-resource-dir")`

2020-10-11 03:18 UTC, hlissner approved these changes

2020-10-11 03:18 UTC, merged

2020-10-11 03:18 UTC, hlissner commented
Looks good to me. Thanks for your help!

2020-10-11 16:06 UTC, laduke commented
hi, just updated doom and saw this in my *Messages*: 

`File local-variables error: (doom-hook-error lsp! (file-missing Searching for program No such file or directory sysctl -n hw.ncpu))`

2020-10-11 16:10 UTC, gagbo commented
Yup sorry. fixed in #4075 . You can apply the change manually in your repo and it will work after a restart