Bump :lang dart
hlissner/doom-emacs pull request #3884
Opened 2020-09-02 16:41 UTC by ericdallo

emacs-lsp/lsp-dart@437c548 -> emacs-lsp/lsp-dart@9036e4b
- Bump to latest lsp-dart with support to hot-restart/reload after save

ericdallo/hover@6f9ed1a -> ericdallo/hover@079efb1
- Bump to latest hover.el with support to clear buffer and clear-buffer-on-hot-restart

2020-09-02 19:47 UTC, hlissner requested changes
Hey, thanks for the bump PR. Sorry to be pedantic, but could you remove the blank line between the commit lines? i.e.

```diff
 Bump :lang dart

 emacs-lsp/lsp-dart@437c548 -> emacs-lsp/lsp-dart@9036e4b
-
 ericdallo/hover.el@6f9ed1a -> ericdallo/hover.el@079efb1
```

I must be particular about this so that bump commits remain machine readable for future CI, which uses the first blank line in a commit's body to delimit the bump preamble from the commentary.

2020-09-02 20:15 UTC, ericdallo commented
No problem @hlissner, done.
Is there any doom script/command where I can easily input the commits and have this formatted message?

2020-09-02 20:54 UTC, hlissner approved these changes

2020-09-05 05:52 UTC, merged

2020-09-05 05:53 UTC, hlissner commented
@ericdallo Yes, but it's not publicly available yet, unfortunately (it depends on a larger rewrite of Doom's CLI that I am still working on). In any case, thanks for the PR!