Bumps lsp-mode
hlissner/doom-emacs pull request #3928
Opened 2020-09-11 17:19 UTC by acristoffers

A fix upstream gets rid of a (random) bug that forces users to restart emacs.
Specifically https://github.com/emacs-lsp/lsp-mode/issues/2141.

2020-09-17 09:03 UTC, brotzeit commented
Can you please also bump lsp-ui ? There have been merged lots of fixes the last weeks.

2020-09-17 11:21 UTC, acristoffers commented
Done, both bumped to the latest commits.

2020-10-02 23:28 UTC, acristoffers commented
Bumped versions again.

2020-10-05 04:00 UTC, hlissner requested changes
Hi! Thanks for the PR. Could you rebump this (and squash your commits). A few packages have moved forward while I was on break:

```elisp
;; -*- no-byte-compile: t; -*-
;;; tools/lsp/packages.el

(if (featurep! +eglot)
    (progn
      (package! eglot :pin "61b71ea769fa14887465517f70832861f7052816")
      (package! project :pin "da0333a697b18f0a863c1b1523d2fc7991b31174"))
  (package! lsp-mode :pin "9a79593e8a4efd1b07e6503fc646df726eeb66b6")
  (package! lsp-ui :pin "25552041f5af110c282fe8a2c714dec0f7a2320e")
  (when (featurep! :completion ivy)
    (package! lsp-ivy :pin "20cac6296e5038b7131ee6f34a96635f1d30fe3c"))
  (when (featurep! :completion helm)
    (package! helm-lsp :pin "fc09aa0903ee6abe4955e9a6062dcea667ebff5a")))
```

Could you also reword your commit message to:

```
Bump :tools lsp

emacs-lsp/helm-lsp@4263c96 -> emacs-lsp/helm-lsp@fc09aa0
emacs-lsp/lsp-ivy@4cdb739 -> emacs-lsp/lsp-ivy@20cac62
emacs-lsp/lsp-mode@4145a70 -> emacs-lsp/lsp-mode@9a79593
emacs-lsp/lsp-ui@c39ae37 -> emacs-lsp/lsp-ui@2555204
joaotavora/eglot@5f873d2 -> joaotavora/eglot@61b71ea

A fix upstream gets rid of a (random) bug that forces users to restart
emacs. Specifically emacs-lsp/lsp-mode#2141.
```

Bump commits must follow a particular format, so that they remain machine-readable for future CI.

2020-10-05 12:36 UTC, acristoffers commented
Done.

2020-10-05 21:26 UTC, merged

2020-10-05 21:26 UTC, hlissner commented
Thanks for your help!