Bump dart
hlissner/doom-emacs pull request #3954
Opened 2020-09-17 02:09 UTC by ericdallo

After some months coding with dart I ended with these mapping which I find it's very useful.

* Improve mappings for dart
* Bump hover and lsp-dart(add test tree feature) to latest version

2020-09-18 11:57 UTC, thiagokokada approved these changes

2020-10-02 00:14 UTC, ericdallo commented
Ping @hlissner

2020-10-05 03:35 UTC, hlissner requested changes

2020-10-05 03:35 UTC, hlissner commented on modules/lang/dart/config.el
> +         "r" #'flutter-run-or-hot-reload))
Did you mean to remove `:localleader` here? `r` as a floating keybind doesn't seem right.

Also, please correct the indentation here (it's one space off).

2020-10-05 03:35 UTC, hlissner commented on modules/lang/dart/packages.el
> +  (package! lsp-dart :pin "cdb41f73fecec367547b5a2a27a2d96b5ad55183"))
Would you mind re-bumping `lsp-dart` (and updating the commit message). Seems it's moved forward a bit while I was on break.

2020-10-05 23:02 UTC, ericdallo commented
Done @hlissner

2020-10-06 01:01 UTC, hlissner approved these changes

2020-10-06 01:02 UTC, merged

2020-10-06 01:02 UTC, hlissner commented
Good work. Thanks again!