M4e4 Module Revamp
hlissner/doom-emacs pull request #3971
Opened 2020-09-22 18:03 UTC by tecosaur

# Mu4e4u

This is a bit of a stub PR, but it's going to become more fleshed out, and this way it should be more visable and hence improve the chance of getting help/comments.

## Todo

- [ ] Better handling of Gmail
- [ ] Configure `org-msg`
- [ ] Configure `mu4e-alert`
- [ ] Detail faster syncing solution (goimapnotify)
- [ ] ?maybe add cooperative locking from https://tecosaur.github.io/emacs-config/config.html#process-control
- [ ] More stuff which will come up

2020-09-22 18:29 UTC, mjlbach commented on modules/email/mu4e/config.el
> +Otherwise, the user is prompted for the accound they wish to use."
accound -> account

2020-09-23 05:01 UTC, tecosaur commented on modules/email/mu4e/config.el
> +Otherwise, the user is prompted for the accound they wish to use."
fixd

2020-09-23 14:22 UTC, agraul commented on modules/email/mu4e/autoload/email.el
> +Otherwise, the user is prompted for the account they wish to use."
I think "account" is a bit misleading here. As far as I understand, `mu4e-set-account` only sets the "From" address. It does not switch the mu4e context. This can be confusing because  `set-email-account!` is used to create mu4e contexts.

Speaking of contexts, it would be really great if this function would filter the `:personal-addresses` given the current context. We'd need to have a mapping, but since mu4e contexts can store arbitrary `vars`, we could do that. Right now I can press `c c` to compose, pick a context and then pick a mailing address that belongs to a different context.

2020-09-23 14:24 UTC, tecosaur commented on modules/email/mu4e/autoload/email.el
> +Otherwise, the user is prompted for the account they wish to use."
I only use one context, so I can't really test this - but if you'd like to add this that would be great :smiley:

2020-09-23 20:17 UTC, ymarco commented on modules/email/mu4e/config.el
> +  (use-package! org-msg
Can use `(uses-package! :when (feturep! :lang org) ...)` instead of adding another nesting level

2020-09-24 21:21 UTC, agraul commented on modules/email/mu4e/autoload/email.el
> +Otherwise, the user is prompted for the account they wish to use."
I started working on it, but now I am thinking that if we let someone declare a list of email addresses associated with a given context, we could just use that and skip the `plist-get`. Of course only if such a list exists for the active context.

2020-09-30 18:09 UTC, tecosaur commented on modules/email/mu4e/config.el
> +  (use-package! org-msg
donezo

2020-10-01 17:17 UTC, A6GibKm commented
Could you please consider putting org-msg behind a module flag?

2020-10-06 13:48 UTC, loafofpiecrust commented
Instead of trying to detect whether an account is `gmail`, it seems to me like it'd make more sense to do it by context, especially since you can have a gsuite account that is not `@gmail.com` and we shouldn't rely on `gmail` being in the name. I use a context-dependent variable instead:
```el
  (defvar +mu4e-context-gmail nil
    "Whether the current mu4e context is associated with a GMail-like server.")

  (set-email-account! "university"
                      `(;; all the other variables...
                        (+mu4e-context-gmail . ,nil))

  (set-email-account! "personal"
                      `(;; all the other variables...
                        (+mu4e-context-gmail . ,t))
```

2020-10-09 18:53 UTC, tecosaur commented
@loafofpiecrust the thing is, I want it to be possible to have mixed gmail/non-gmail addresses in a given context. Since gsuite etc. exists I also read the address label. So, as long as `gmail` is in the label gmail behaviour will be applied.

I feel like this should be fairly reasonable - what do you think?

2020-10-09 18:57 UTC, tecosaur commented
@A6GibKm I didn't add this because it's more a single package statement than a collection of functionality, so I thought requiring `(package! org-msg :disable t)` would be reasonable.

If we go in this direction for consitancy we'd end up with a signature like `(mu4e +gmail +html +alert)`. That doesn't look too bad though, perhapes I'll do that.

2020-10-09 19:20 UTC, tecosaur commented on modules/email/mu4e/autoload/email.el
> +Otherwise, the user is prompted for the account they wish to use."
Any progress?

2020-10-09 19:41 UTC, loafofpiecrust commented on modules/email/mu4e/config.el
> +       (string-match-p "gmail" (mu4e-message-field msg :maildir))))
@tecosaur It looks to me like you check the `:to`, `:from`, and `:maildir`. So what if I have an account `me@loafofpiecrust.com` managed with gsuite that I want to return `t` from this function? If my maildir is `~/.mail/loaf` or similar then `"gmail"` isn't matched in either of those strings.

2020-10-09 19:47 UTC, loafofpiecrust commented on modules/email/mu4e/config.el
> +       (string-match-p "gmail" (mu4e-message-field msg :maildir))))
Well the structure of the email modules in doom seems to be one context = one email address, which is why using a context variable for fixing this seemed a clear answer to me.

2020-10-09 19:50 UTC, tecosaur commented on modules/email/mu4e/config.el
> +       (string-match-p "gmail" (mu4e-message-field msg :maildir))))
See, the thing is at the moment I have a zero-config (doom-side) setup where I have no context.
I rather like that at the moment this 'just works'.

If we just use the doom variable, then this will be (as far as I'm concerned) a regression.

I wouldn't mind making this an `(or gmail-detected gmail-context-set)` though.

2020-10-09 19:59 UTC, loafofpiecrust commented on modules/email/mu4e/config.el
> +       (string-match-p "gmail" (mu4e-message-field msg :maildir))))
@tecosaur Yeah I mean that's fair, I'm just also concerned about the easy case where I have an email like `me@somethingmail.com` where `gmail` is in the string but I don't want it to be managed like a Gmail account.  I need to be able to say "this is *not* a Gmail address" too.

2020-10-10 23:10 UTC, pkazmier commented
@tecosaur Do you think you could include [mu4e-views](https://github.com/lordpretzel/mu4e-views) package in your revamp? With an emacs built with xwidget support, one can finally read emails in an embedded web browser. Here is a screenshot to illustrate.  

<img width="860" alt="image" src="https://user-images.githubusercontent.com/747855/95666850-8484f900-0b23-11eb-919c-684d48c56096.png">

My current Doom settings for this package are documented here: https://github.com/lordpretzel/mu4e-views/issues/8

2020-10-11 08:29 UTC, A6GibKm commented
mu4e-view for the momment does not support evil mode nor, gnus-view.

2020-10-11 09:47 UTC, pkazmier commented
> mu4e-view for the moment does not support evil mode nor, gnus-view.

Sure, but we can customize things, no? See the link in my prior comment to my settings. I’ve tweaked a few key bindings for xwidget WebKit as well as mu4e-view for a start to an evil experience. I, agree, we want the package maintainer to fix the bug re gnus-view, but it sounds like he’s going to do so. Even without that though, if one uses mu4e-view html view, does it matter as the view is being rendered by mu4e-view?

2020-10-11 09:55 UTC, A6GibKm commented
I suggest you to send a PR to https://github.com/emacs-evil/evil-collection for evil support with xwidget support, see https://github.com/emacs-evil/evil-collection/issues/385. On the side of mu4e-views I also think that this might be better suited for evil-collection.

About gnus-view I don't know, but the fact is that it is not working while the variable is set to `t`.

2020-10-11 14:08 UTC, pkazmier commented
> I suggest you to send a PR to https://github.com/emacs-evil/evil-collection for evil support with xwidget support, see [emacs-evil/evil-collection#385](https://github.com/emacs-evil/evil-collection/issues/385).

I didn’t know about evil-collection. Interestingly, they already have xwidget bindings, so I need to figure out why those weren’t working for me and why I ended up defining them myself. It seems they were added in Jan, and the version doom has pinned is from May, so I’m not sure what’s going on. I’ll test in the doom sandbox to make sure it’s not my config though. Thanks again for teaching me something new about the doom ecosystem.

2020-10-11 18:56 UTC, A6GibKm commented
Please, when you get into the reason for the issue, report at evil-collection. I was not aware either that they do support xwidgets.

2020-10-11 21:36 UTC, agraul commented on modules/email/mu4e/autoload/email.el
> +Otherwise, the user is prompted for the account they wish to use."
Thanks for the reminder, I'll look at it again in the next days. I already got something, but I want to change it a little before I push it

2020-10-11 22:23 UTC, pkazmier commented
> Please, when you get into the reason for the issue, report at evil-collection. I was not aware either that they do support xwidgets.

I actually opened a Doom issue: https://github.com/hlissner/doom-emacs/issues/4080

2020-10-13 07:28 UTC, tecosaur commented
@pkazmier @A6GibKm mu4e already has xwidget support in `mu4e-action-view-with-xwidget`. I'll add it to `mu4e-view-actions`.

2020-10-13 15:38 UTC, tecosaur commented on modules/email/mu4e/config.el
> +       (string-match-p "gmail" (mu4e-message-field msg :maildir))))
Done in 8adbefb8a7a66c8406c81257af4b5e204e2b362c

2020-10-13 18:39 UTC, seanfarley commented
I have some serious misgivings about enabling `org-msg` by default. For one, it regresses those of us that use inline replies. Second, the variable to turn it off is a private variable; not something that seems natural. Also, there was some pushback about enabling it by default in issue https://github.com/hlissner/doom-emacs/issues/4043.

More importantly though, I'm more worried about accidentally turning on `xwidgets` by default. `xwidgets` loads every image and thereby eliminates the privacy we currently have with not loading images. I really want to make sure that `xwidgets` stays off by default because `mu4e-views`, while cool, makes it all too easy to turn it on.

2020-10-13 18:42 UTC, tecosaur commented
Erm, please comment on what's actually in this PR, as opposed to commenting on comments :stuck_out_tongue: 

#### org-msg
It's dead easy to disable, see the readme. No private variables.

#### xwidgets
I'm not using `mu4e-views`, I just add it as a view action.

2020-10-13 19:33 UTC, loafofpiecrust commented
@tecosaur While `org-msg` might be easy to disable, wouldn't it be even easier to just make an opt-in flag here (rather than assuming that `:lang org` users want it)? Take my case, I have the `:lang org` module enabled because I use org for all kinds of stuff, but in `mu4e` I don't find `org` the right format for emails so I use some code to convert to/from markdown instead.

2020-10-13 20:08 UTC, A6GibKm commented
@seanfarley could you please elaborate on the issues with xwidget? I readed that there are issues related to it but I am ignorant about it.

2020-10-13 22:36 UTC, seanfarley commented
@tecosaur I'll be blunt: enabling `org-msg` by default is a terrible idea. If you want it so bad, make it something to easily opt into. Breaking existing users' setups is a really, really, really bad idea. Not to mention terribly rude. `org-msg` is not an option now: so there are no existing setups to break. On the other hand, `mu4e` *is* a optional module now, so you'd be breaking people's existing workflows.

@A6GibKm There's not too much wrong with it, and it is nice, but since it lots of companies put an image (usually a 1x1 pixel remote image with a unique id) to track whether a user opens the email (if they open it and load all images, the server hosting the image will see the request by a unique id), it opens up a huge privacy issue. There's nothing wrong with the code here so far, I was just cautioning against using `mu4e-views` (which isn't used here so far) since I believe it defaults to xwidgets. Anyways, having the action is fine, in my opinion.

2020-10-14 04:14 UTC, tecosaur commented
(sigh) The masses are wearing me down.
The reason why I haven't added a flag is that in Doom the general rule is that flags are used to control bundles of packages/functionality, and `org-msg` is a single thing that is disabled in a single line - `(package! org-msg :disable t)`.

I _guess_ given the demand this _could_ be made a flag though.

2020-10-14 05:20 UTC, hlissner requested changes
Please add a `+org` to the `:email mu4e` entry in `doc/modules.org`.

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +(defun ++mu4e-lock-file-updated (event)
Remove duplicate `+`

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +(defun +mu4e-lock-avalible (&optional strict)
`s/avalible/available`

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +    (let* ((pid (string-to-number (f-read-text +mu4e-lock-file 'utf-8)))
Factor out `f-read-text` for

```lisp
(with-temp-buffer
  (setq coding-system-for-read 'utf-8)
  (insert-file-contents +mu4e-lock-file)
  (buffer-string))
```

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +    (f-write-text (number-to-string (emacs-pid)) 'utf-8 +mu4e-lock-file)
Factor out `f-write-text` for

```lisp
(write-region (number-to-string (emacs-pid)) nil nil)
```

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +  (if (not (+mu4e-lock-avalible))
`s/avalible/available`

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +  (unless (+mu4e-lock-avalible)
s/avalible/available

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +  (when (+mu4e-lock-avalible)
`s/avalible/available`

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +    (ivy-read "From: " (if-let ((context-addresses
Can you generalize this to `completing-read`? (So it doesn't lock out helm users)

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +(defun +mu4e-msg-to-agenda (arg)
Should be `+mu4e/refile-msg-to-agenda` to conform to our naming conventions (and is a more descriptive name).

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +(defun +mu4e-header-colourise (str)
Should be `+mu4e--header-colorize` (consistency with colorize spelling in `doom-themes`, `transient` and `xterm.el`)

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +(defun +get-string-width (str)
Needs to be prefixed with `+mu4e-`, as per our naming conventions.

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +  :override #'mu4e~main-action-str
A `defun` with an `:override` in it. Is this supposed to be a `defadvice!` or a `defun`? If it's an advice, the function should have a `-a` suffix, as per our naming conventions.

2020-10-14 05:20 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +      (when (and +mu4e-lock-greedy (+mu4e-lock-avalible t))
`s/avalible/available`

2020-10-14 06:16 UTC, tecosaur commented on modules/email/mu4e/autoload/email.el
> +(defun +mu4e-header-colourise (str)
Grrrr. Annoying Americans.

2020-10-15 19:36 UTC, hpfr commented on modules/email/mu4e/doctor.el
> +  (wan! "Couldn't find mbsync or offlineimap command. \
s/wan/warn. Looking forward to this :D

2020-10-15 19:41 UTC, hpfr commented on modules/email/mu4e/config.el
> +(defvar +mu4e-personal-adresses 'nil
s/adresses/addresses

2020-10-15 19:42 UTC, hpfr commented on modules/email/mu4e/config.el
> +  "Alternative to mu4e-personal-adresses that can be set for each account (mu4e context).")
s/adresses/addresses

2020-10-15 19:43 UTC, hpfr commented on modules/email/mu4e/autoload/email.el
> + + `+mu4e-personal-adresses'
s/adresses/addresses

2020-10-16 00:30 UTC, seanfarley commented on modules/email/mu4e/config.el
> +        mu4e-view-use-gnus t ; the way of the future: https://github.com/djcb/mu/pull/1442#issuecomment-591695814
This is something I've asked Dirk about before and I don't understand why he keeps pointing people to the gnus view when it's so behind, feature-wise. It's not a hill I'm willing to die on, so don't feel pressured to change the code you have written. It's more of an FYI for you and @hlissner.

The reason I find the gnus view so odd is that you can't do many of things you can in the "old" view.

* [following links is disabled](https://github.com/djcb/mu/blob/9995d28927ca15a00aafd1e92203f1120813b53a/mu4e/mu4e-view.el#L808)
* [useful gnus things are disabled](https://github.com/djcb/mu/blob/9995d28927ca15a00aafd1e92203f1120813b53a/mu4e/mu4e-view.el#L817)
* [opening attachments is also disabled!](https://github.com/djcb/mu/blob/9995d28927ca15a00aafd1e92203f1120813b53a/mu4e/mu4e-view.el#L873)
* [no toggling of html view (one has to set a global variable and then re-open the message)](https://github.com/djcb/mu/blob/9995d28927ca15a00aafd1e92203f1120813b53a/mu4e/mu4e-view.el#L904)

2020-10-16 02:46 UTC, tecosaur commented on modules/email/mu4e/config.el
> +        mu4e-view-use-gnus t ; the way of the future: https://github.com/djcb/mu/pull/1442#issuecomment-591695814
I'm a bit confused about your first and third point as they seem to work for me.
Unless you don't mean just clicking on links/attachments?

![image](https://user-images.githubusercontent.com/20903656/96206899-807e2e80-0f9c-11eb-9e2b-bacc1bcca556.png)
![image](https://user-images.githubusercontent.com/20903656/96206916-883dd300-0f9c-11eb-8449-445925ed2e32.png)

2020-10-16 02:47 UTC, tecosaur commented on modules/email/mu4e/doctor.el
> +  (wan! "Couldn't find mbsync or offlineimap command. \
Gah! So many typos!

2020-10-16 02:53 UTC, tecosaur commented on modules/email/mu4e/config.el
> +        mu4e-view-use-gnus t ; the way of the future: https://github.com/djcb/mu/pull/1442#issuecomment-591695814
Oh, and just feature-wise - I started using Gnus because from my experience it does a better job with rendering HTML emails.

2020-10-16 03:21 UTC, seanfarley commented on modules/email/mu4e/config.el
> +        mu4e-view-use-gnus t ; the way of the future: https://github.com/djcb/mu/pull/1442#issuecomment-591695814
Ah, yes, sorry, I mean without clicking. (although in my own experience clicking on an attachment didn't work, I'm willing to chalk that up to me being an old dinosaur)

I never thinking about clicking (with a mouse) in emacs ... but maybe that's because I'm not hip.

2020-10-16 03:22 UTC, tecosaur commented on modules/email/mu4e/config.el
> +        mu4e-view-use-gnus t ; the way of the future: https://github.com/djcb/mu/pull/1442#issuecomment-591695814
When I say "clicking" `RET` works too :slightly_smiling_face:

2020-10-16 12:53 UTC, A6GibKm commented on modules/email/mu4e/config.el
> +        mu4e-view-use-gnus t ; the way of the future: https://github.com/djcb/mu/pull/1442#issuecomment-591695814
By the way, I used to had the issue where links wont be followed, it just turned out to be that flyspell or something similar had issues with the word under the cursor.

2020-10-16 18:07 UTC, seanfarley commented on modules/email/mu4e/config.el
> +        mu4e-view-use-gnus t ; the way of the future: https://github.com/djcb/mu/pull/1442#issuecomment-591695814
> When I say "clicking" `RET` works too 🙂

But how would the cursor even get there? I guess I could use some other method (find, ace, etc) but the current method is two keystrokes (e.g. `g 1`). 🤷

For attachements, though, I don't think that will work, or rather, it wouldn't be as easy. Anyways, as I mentioned before, it's fine as-is and this is more of a critic against mu4e not improving the gnus view if Dirk really wants that to be the future.

2020-10-16 19:06 UTC, tecosaur commented on modules/email/mu4e/config.el
> +        mu4e-view-use-gnus t ; the way of the future: https://github.com/djcb/mu/pull/1442#issuecomment-591695814
`TAB` jumps to the next link 🙂

2020-10-20 04:47 UTC, tecosaur commented
_pssst_ @hlissner how 'bout a second look?

2020-10-21 02:22 UTC, seanfarley commented
I finally checked out the branch to test this out because I wanted to see all the cool stuff you added :-) 

When I first open `mu4e` (`C-c M M`), I get this message (is it an error? or just a warning?)

```
Wrote /tmp/mu4e_lock
file-notify-add-watch: File does not exist: No such file or directory, /tmp/mu4e_lock_request
```

Unfortunately, when I try to open my inbox get this error:
```
error in process filter: format: Symbol’s value as variable is void: maildir
error in process filter: Symbol’s value as variable is void: maildir
error in process filter: format: Symbol’s value as variable is void: maildir
error in process filter: Symbol’s value as variable is void: maildir
error in process filter: format: Symbol’s value as variable is void: maildir
error in process filter: Symbol’s value as variable is void: maildir
error in process filter: format: Symbol’s value as variable is void: maildir
error in process filter: Symbol’s value as variable is void: maildir
```

With this backtrace:
```emacs-lisp
Debugger entered--Lisp error: (void-variable maildir)
  (substring maildir 1 (string-match-p "/" maildir 1))
  (format "%s" (substring maildir 1 (string-match-p "/" maildir 1)))
  (replace-regexp-in-string "^gmail" (propertize "g" 'face 'bold-italic) (format "%s" (substring maildir 1 (string-match-p "/" maildir 1))))
  (+mu4e-colorize-str (replace-regexp-in-string "^gmail" (propertize "g" 'face 'bold-italic) (format "%s" (substring maildir 1 (string-match-p "/" maildir 1)))) '+mu4e-header--maildir-colors (replace-regexp-in-string "\\`/\\([^/]+\\)/.*\\'" "\\1" (mu4e-message-field msg :maildir)))
  (lambda (msg) (+mu4e-colorize-str (replace-regexp-in-string "^gmail" (propertize "g" 'face 'bold-italic) (format "%s" (substring maildir 1 (string-match-p "/" maildir 1)))) '+mu4e-header--maildir-colors (replace-regexp-in-string "\\`/\\([^/]+\\)/.*\\'" "\\1" (mu4e-message-field msg :maildir))))((:docid 127891 :thread (:path "00" :level 0) :subject "Let’s fight the spread of COVID-19 together" :message-id "82a653cade6c4eb8bf5716cd43cb0e59@936847217" :path "/Users/sean/.mail/inbox/new/1602731040.99253_2.lap..." :maildir "/inbox" :priority normal :from (("Kaiser Permanente" . "members@respond.kaiserpermanente.org")) :to ((nil . "sean@farley.io")) :date (24454 29074 0) :size 44086 :flags (new unread)))
  #f(compiled-function (msg field) #<bytecode -0x7369ecc6013df7b>)((:docid 127891 :thread (:path "00" :level 0) :subject "Let’s fight the spread of COVID-19 together" :message-id "82a653cade6c4eb8bf5716cd43cb0e59@936847217" :path "/Users/sean/.mail/inbox/new/1602731040.99253_2.lap..." :maildir "/inbox" :priority normal :from (("Kaiser Permanente" . "members@respond.kaiserpermanente.org")) :to ((nil . "sean@farley.io")) :date (24454 29074 0) :size 44086 :flags (new unread)) :account)
  #f(compiled-function (f-w) #<bytecode 0x19226e19e6c75f21>)((:account . 12))
  mapconcat(#f(compiled-function (f-w) #<bytecode 0x19226e19e6c75f21>) ((:account . 12) (:human-date . 12) (:flags . 6) (:mailing-list . 10) (:from . 22) (:subject)) " ")
  mu4e~headers-header-handler((:docid 127891 :thread (:path "00" :level 0) :subject "Let’s fight the spread of COVID-19 together" :message-id "82a653cade6c4eb8bf5716cd43cb0e59@936847217" :path "/Users/sean/.mail/inbox/new/1602731040.99253_2.lap..." :maildir "/inbox" :priority normal :from (("Kaiser Permanente" . "members@respond.kaiserpermanente.org")) :to ((nil . "sean@farley.io")) :date (24454 29074 0) :size 44086 :flags (new unread)))
  mu4e~proc-filter(#<process  *mu4e-proc*> "\376b\377(:erase t)\n\3761a6\377(:docid 127891 :thread (:path \"...")
```

Looking into that function call, I can see that `maildir` is not local to the function ... should it be `mu4e-maildir`?

Also, (sorry for the long comment), I'm not sure if this is intended or not for the `mu4e-main-view`:

(before this branch)
<img width="1440" alt="Screen Shot 2020-10-20 at 7 18 30 PM" src="https://user-images.githubusercontent.com/20887/96665210-3af99280-1309-11eb-97ac-4ceb71f3f643.png">

(checked out branch)
<img width="1440" alt="Screen Shot 2020-10-20 at 7 11 10 PM" src="https://user-images.githubusercontent.com/20887/96665248-519fe980-1309-11eb-922d-da1b9e416a7f.png">

The brackets seem to be missing (but maybe that's intentional?) and the vertical spacing is *a little* more but not a deal breaker. Just posting it here incase those things weren't intential.

2020-10-21 03:35 UTC, tecosaur commented
Hi @seanfarley! Thanks for giving this a test &#x2014; it&rsquo;s much appreciated.

> file-notify-add-watch: File does not exist: No such file or directory, /tmp/mu4e_lock_request

Hmmm. I didn&rsquo;t expect to see this. This is from part of the module that allows different instances of Emacs to &rsquo;ask&rsquo; for the mu4e <span class='acr'>DB</span> connection. When an instance starts it adds a watcher to look for a &rsquo;request&rsquo; file (I&rsquo;m basically using `/tmp` files for inter-process communication).

```emacs-lisp
(file-notify-add-watch +mu4e-lock-request-file
                        '(change)
                        #'+mu4e-lock-request)
```

The only thing that comes to mind is that your `file-notify-add-watch` works differently to mine? But I&rsquo;ve had this work on Emacs 26.3 and (now) 27.1 &#x2014; so I&rsquo;m not sure what&rsquo;s going on.

> error in process filter: format: Symbol’s value as variable is void: maildir

Thanks for catching this (and the backtrace). Should be fixed now.

> mu4e-main-view

Yea, changing `* [xy]` to `⚫ xy` is a (<span class='acr'>IMO</span> pretty safe) stylistic choice &#x2014; as I think the keybinding information is just as clear, but it&rsquo;s presented in a visually cleaner way. So yes, this is intentional. Do let me know if you have any feedback :)

2020-10-21 23:44 UTC, seanfarley commented
> Hmmm. I didn’t expect to see this. This is from part of the module that allows different instances of Emacs to ’ask’ for the mu4e DB connection. When an instance starts it adds a watcher to look for a ’request’ file (I’m basically using `/tmp` files for inter-process communication).
> 
> ```emacs-lisp
> (file-notify-add-watch +mu4e-lock-request-file
>                         '(change)
>                         #'+mu4e-lock-request)
> ```
> 
> The only thing that comes to mind is that your `file-notify-add-watch` works differently to mine? But I’ve had this work on Emacs 26.3 and (now) 27.1 — so I’m not sure what’s going on.

The backends for `file-notify` are different between OSes. I'm on MacOS so it uses `kqueue`. If you're on a Linux, you're probably using `inotify`. There are probably implemenetation differences there. I mean, there are certainly differences in the  implementations. I just don't know if this particular error is one of them.

> Thanks for catching this (and the backtrace). Should be fixed now.

Seems to work now!

> Yea, changing `* [xy]` to `⚫ xy` is a (IMO pretty safe) stylistic choice — as I think the keybinding information is just as clear, but it’s presented in a visually cleaner way. So yes, this is intentional. Do let me know if you have any feedback :)

Ah, gotcha, and yeah it looks nice :-) I think the only thing that looks off is the narrow width for the date column in the headeres view now. Not too big of a deal but my headers view now looks like this:

<img width="1440" alt="Screen Shot 2020-10-21 at 4 41 10 PM" src="https://user-images.githubusercontent.com/20887/96801361-422da880-13bc-11eb-979e-5188382525bf.png">

2020-10-21 23:48 UTC, seanfarley commented
> This is from part of the module that allows different instances of Emacs to ’ask’ for the mu4e DB connection. When an instance starts it adds a watcher to look for a ’request’ file (I’m basically using /tmp files for inter-process communication).

Actually, I'm not sure I even understand what feature you're trying to implement or problem you're trying to solve with the lock? Are you trying to have multiple mu4e workspaces open at the same time in one emacs instance?

2020-10-22 01:43 UTC, seanfarley commented
Ah, also, I just noticed that the message for updating messages (pressing `U`) is no longer displayed so it's not apparent if it worked or is running

2020-10-22 04:55 UTC, tecosaur commented
> the only thing that looks off is the narrow width for the date column in the headeres view now

Hmmm. This is based of me shrinking the date column to exactly fit `DD/MM/YY`/ `HH:MM:SS`, however I guess since the date format is locale-dependant this doesn't work as well in practice. I could change the default date format too, but that seems a bit dodgy &#x2014; perhaps the date width should just be increaced a tad.

> The backends for file-notify are different between <span class='acr'>OS</span>es. I&rsquo;m on MacOS so it uses kqueue

Hmm. Perhaps `kqueue` doesn&rsquo;t like watching not-yet-existant files? I&rsquo;m not on a Mac so I can&rsquo;t really debug/test/develop - so perhaps I just linux-gate the feature for now and hope for a future <span class='acr'>PR</span>

> Actually, I&rsquo;m not sure I even understand what feature you&rsquo;re trying to implement or problem you&rsquo;re trying to solve with the lock? Are you trying to have multiple mu4e workspaces open at the same time in one emacs instance?

Normally if you have mu4e open in one emacs instance, and you try to open mu4e in another, it just complains that the database is already open and it can&rsquo;t share.

What this does is have the second istance say &ldquo;hey, can I get that <span class='acr'>DB</span> please&rdquo;. The instance with an open mu4e session sees that message and depending on `+mu4e-lock-relaxed` will close the mu4e session thus releasing the <span class='acr'>DB</span> to the second session.

If `+mu4e-lock-greedy` is set, whenever no other instance has the <span class='acr'>DB</span>, that istance will start a mu4e session and grab it.

This may seem like it&rsquo;s fixing a barely-existant problem, but I find that it&rsquo;s rather useful running this in my Emacs daemon with both the greedy and relaxed properties, so that I always get notifications from mu4e-alert &#x2014; while enabling me to still open temporary mu4e sessions in non-daemon instances.

2020-10-22 08:12 UTC, A6GibKm commented
Useful to have, yet, it could introduce sync issues with certain already brittle clients.

2020-10-22 08:15 UTC, tecosaur commented
@A6GibKm Hmm, I don't think so - syncing isn't done by mu4e (directly) after all. Is there a real concern I should be aware of?

2020-10-23 01:39 UTC, seanfarley commented
> Normally if you have mu4e open in one emacs instance, and you try to open mu4e in another, it just complains that the database is already open and it can’t share.

> What this does is have the second istance say “hey, can I get that DB please”. The instance with an open mu4e session sees that message and depending on +mu4e-lock-relaxed will close the mu4e session thus releasing the DB to the second session.

Ah, I see. I once tried to do something similar years ago but it was a failed experiment (it was also get alerts and imap idle working). The main issue I ran into was the syncing of flags (which is done when a buffer closes). The way mu4e writes the flags is to just blindly shell out and write them ... which potentially causes huge issues. To safely keep everything in sync, you need to closes all the mu4e buffers (headers and views; main is fine). I'm not sure how you are guaranteeing the headers and views are closed and, therefore, synced?

2020-10-23 18:15 UTC, seanfarley commented
Oh, quick nit: the bullet points at the bottom of the main page don't seem to be stylized:

<img width="665" alt="Screen Shot 2020-10-23 at 11 14 05 AM" src="https://user-images.githubusercontent.com/20887/97039249-f6e0da80-1520-11eb-9fea-e6d99d9e6e10.png">

2020-10-30 11:16 UTC, tecosaur commented
> The main issue I ran into was the syncing of flags (which is done when a buffer closes). The way mu4e writes the flags is to just blindly shell out and write them ... which potentially causes huge issues. To safely keep everything in sync, you need to close all the mu4e buffers (headers and views; main is fine). I'm not sure how you are guaranteeing the headers and views are closed and, therefore, synced?

I just call `(mu4e~stop)`. If that doesn't work please let me know.

> Oh, quick nit: the bullet points at the bottom of the main page don't seem to be stylized:

Yea, I'm aware of that but I couldn't get it to work, unfortunately :(

2020-10-30 13:01 UTC, A6GibKm commented
> Yea, I'm aware of that but I couldn't get it to work, unfortunately :(

I will insist that consistency should be the most important criteria here, I would rather have this disabled than producing inconsistencies which are visible on 1/4 of the mu4e welcome screen. 

> I just call (mu4e~stop). If that doesn't work please let me know.

The user should not have to know or think about these things. Any extra cognitive load introduced to the user introduced is actually regression and not in the spirit of good defaults. I am sure Dirk did not introduce a lock if there was a simple way around the issue.

2020-10-30 13:16 UTC, tecosaur commented
> I will insist that consistency should be the most important criteria here, I would rather have this disabled than producing inconsistencies which are visible on 1/4 of the mu4e welcome screen.

Consistancy is indded good, but at least for myself, I find the overall effect to be an improvement. I'd also welcome someone else taking a look at this to solve the remailing 1/4.

> The user should not have to know or think about these things. Any extra cognitive load introduced to the user introduced is actually regression and not in the spirit of good defaults. I am sure Dirk did not introduce a lock if there was a simple way around the issue.

Erm, 'the user' doesn't. This is a 'dev discussion'. It works as far as I can tell. Also, there's still a lock - that doesn't change.

2020-10-30 15:42 UTC, ymarco commented on modules/email/mu4e/config.el
> +    (setf (alist-get 'delete mu4e-marks)
Do you mind making these lists variables so they could be customized by the user?

2020-10-31 20:10 UTC, ymarco commented on modules/email/mu4e/config.el
> +    (setf (alist-get 'delete mu4e-marks)
Never mind I can just use a form of `setf` for this

2020-11-08 13:51 UTC, jeetelongname commented
Is there any plan mentioning sending mail in the README.org. I know that msmtp
is recommended but I was looking over the README and it was not mentioned.

The [arch wiki](https://wiki.archlinux.org/index.php/Msmtp) has a good configuration
and this snippet 
```lisp 
(setq sendmail-program (executable-find "msmtp")
      send-mail-function #'smtpmail-send-it
      message-sendmail-f-is-evil t
      message-sendmail-extra-arguments '("--read-envelope-from")
      message-send-mail-function #'message-send-mail-with-sendmail)
```
was provided for me to use msmtp in emacs.  If this was intentional do ignore me

2020-11-08 13:53 UTC, tecosaur commented
@jeetelongname erm, if you look at the PR you'll see that's already included.

2020-11-08 13:56 UTC, jeetelongname commented
Yep I cant read. ignore me

2020-11-12 21:04 UTC, seanfarley commented
Sorry, I've been super busy and haven't had time to look at the new updates yet. I'll try to do that today.

2020-11-14 22:43 UTC, seanfarley commented on modules/email/mu4e/config.el
> +                maildir)
This `maildir` symbol is still unbound for me.

2020-11-14 22:44 UTC, seanfarley commented on modules/email/mu4e/config.el
> +                              (mu4e-message-field msg :maildir)))))
It seems this line closes the `let` (see my error below) ... did you mean to close the `let` at the end of the `lambda`?

2020-11-15 01:42 UTC, seanfarley commented
Finally had some time today to look at this; sorry for the delay. The locking file is still throwing an error for me; not sure how Henrik wants to move forward on that. One could argue that the multiple client feature should instead go upstream but I dunno.

The date column is still really small and it'd be nice to update that (or figure out how to automatically set the width). I also find it mildly nails-on-blackboard with the mixture of unicode bullet points and asterisk on the mu4e main page. I'd rather not have unicode at all just to make sure them all match. One alternative coud be to instead submit a PR to mu to replace the asterisks with a variable that doom could use.

There are also a lot of changes in here that are pretty opinionated with no option that I can find to change. Things like,

* removing `auto-fill-mode` in the reply buffer (something I consider a big change)
* emojify-ing the text email (e.g. `:-)` is replaced with an image of the smiling face)
* replacing the sender's name with "To recipient"
* ~~removing the folder column~~ <- this might be me not understanding how to see the "stripe", can you post a screenshot?
* general shrinking of certain columns (above I mentioned 'date' but 'flags' is also too short to display more than one icon for me)

Perhaps, I'm just old and cranky, though.

2020-11-15 04:28 UTC, seanfarley commented on modules/email/mu4e/README.org
> +(package! org-msg :disable t)
I guess this message is now outdated

2020-11-15 04:29 UTC, seanfarley commented on modules/email/mu4e/README.org
> +This is used by default. It can be disabled in the same manner as [[*OrgMsg][OrgMsg.]]
Similarly, outdated here, too.

2020-11-17 16:24 UTC, tecosaur commented on modules/email/mu4e/README.org
> +(package! org-msg :disable t)
Yep. Thanks.

2020-11-17 16:52 UTC, tecosaur commented
Finally getting back to you @seanfarley :slightly_smiling_face: 

> Finally had some time today to look at this; sorry for the delay. The locking file is still throwing an error for me; not sure how Henrik wants to move forward on that. One could argue that the multiple client feature should instead go upstream but I dunno.

Maybe I should just linux-gate this feature? IDK. I can't exactly play around with the Mac behaviour without a Mac.

> The date column is still really small and it'd be nice to update that (or figure out how to automatically set the width). I also find it mildly nails-on-blackboard with the mixture of unicode bullet points and asterisk on the mu4e main page. I'd rather not have unicode at all just to make sure them all match. One alternative could be to instead submit a PR to mu to replace the asterisks with a variable that doom could use.

Do I just need to increase the width from 8 to 10 for the date?

A mu4e setting for this styling could be nice. I may open an issue for this at some point.

> There are also a lot of changes in here that are pretty opinionated with no option that I can find to change. Things like,
> 
>  * removing `auto-fill-mode` in the reply buffer (something I consider a big change)

I don't see that in this PR.

>  * emojify-ing the text email (e.g. `:-)` is replaced with an image of the smiling face)

I don't see that in this PR.

>  * replacing the sender's name with "To recipient"

Not quite sure what you're talking about.

> * ~removing the folder column~ <- this might be me not understanding how to see the "stripe", can you post a screenshot?

Sure, this is what I see (non-default setup, but using the stripe):

![image](https://user-images.githubusercontent.com/20903656/99420015-b0bc4280-2937-11eb-848a-8feafc0730f9.png)

Each color represents a different account/maildir.

>  * general shrinking of certain columns (above I mentioned 'date' but 'flags' is also too short to display more than one icon for me)

It should display 3 🤔. See:
```emacs-lisp
(:flags . 6) ; 3 icon flags
```
as well the 2-flag instances in my screenshot.

> Perhaps, I'm just old and cranky, though.

Perhaps 😛 but it's good feedback nether the less ... even if I'm not sure where most of it's coming from (as in code origin).

2020-11-17 17:22 UTC, A6GibKm commented
> Maybe I should just linux-gate this feature? IDK. I can't exactly play around with the Mac behaviour without a Mac.

What about putting it as an opt-in feature? Risking breaking someone's email setup sounds like a no-go to me.

2020-11-18 02:52 UTC, tecosaur commented
I don't think it risks breaking someone's email setup, it just may raise some warnings and not do the _extra stuff_ on Mac by the sound of things. If I'm wrong, a condition-case will resolve that.

As such, I'm more tempted to gate the feature to where we know it works, than add it as a flag.

2020-11-18 04:36 UTC, seanfarley commented
> I don't think it risks breaking someone's email setup, it just may raise some warnings and not do the _extra stuff_ on Mac by the sound of things. If I'm wrong, a condition-case will resolve that.
> 
> As such, I'm more tempted to gate the feature to where we know it works, than add it as a flag.

(quick reply) I believe this will affect different implementions (e.g. kqueue ones) which could also happen on BSD and not just MacOS.

2020-11-18 18:26 UTC, seanfarley commented
> I don't see that in this PR.

That ... is a good point. I'm a bit confused as well so I'm going to do a bit deeper dive to see exactly where this is diverging so much.

2020-11-24 13:15 UTC, ymarco commented
I'm against setting `mu4e-compose-format-flowed`, which is set by default in Doom. 
It inserts line breaks uncontrollably before the email is sent. It look horrible [when replying to GitHub issues](https://github.com/akirakyle/emacs-webkit/pull/15#issuecomment-732796364) and would probably ruin code formatted in emails.
Could you change it? It's set [here](https://github.com/hlissner/doom-emacs/blob/c83e5e75e24706a0d6c15f3156d33b1c4f9dc365/modules/email/mu4e/config.el#L30).

2020-11-24 13:22 UTC, tecosaur commented
Yea, IMO that's caused me more trouble than it's worth. It's mangled stuff like inline tables too. I think just composing emails with auto-fill-mode is a better solution, and due to other defaults this seems to happen anyway currently.

Unless anyone has objections, I'll just remove that assignment.

2020-11-24 20:01 UTC, seanfarley commented
I guess I'm the only one that prefers that look.

2020-11-24 20:14 UTC, A6GibKm commented
At worst it is a single easy to change line, so +1 for it. 

Even though I have to say that all depends on context and use-cases. I have send email in the past with auto-fill mode that look like garbage and the same can be said about format-flowed in certain usecases.

2020-11-24 20:44 UTC, seanfarley commented
Ah, yeah, I'm not against changing; just noting that I'm old ;-P

2020-11-29 09:14 UTC, jarifuri commented
A shamely plug only tangentially related but I could help myself - [mu4e dashboard provides a new mu4e org link type](https://github.com/rougier/mu4e-dashboard) .

2020-11-29 13:54 UTC, tecosaur commented
I've seen that. I like the look of it. I haven't tried it yet.

2020-11-29 14:19 UTC, A6GibKm commented
I wonder if it works with evil-mode, the elfeed dashboard does not at least.

2020-12-13 19:05 UTC, elken commented
This all looks pretty cool; what's blocking this from merging currently?

2020-12-13 20:39 UTC, tecosaur commented
Henrik's hectic schedule :upside_down_face:

2020-12-13 21:38 UTC, elken commented
Assumed as much, look forward to seeing it merged ☺️

2021-01-05 19:38 UTC, seanfarley commented
> Finally getting back to you @seanfarley 🙂
> 
> > Finally had some time today to look at this; sorry for the delay. The locking file is still throwing an error for me; not sure how Henrik wants to move forward on that. One could argue that the multiple client feature should instead go upstream but I dunno.
> 
> Maybe I should just linux-gate this feature? IDK. I can't exactly play around with the Mac behaviour without a Mac.

I fixed this by using this change:

```diff
diff --git a/modules/email/mu4e/autoload/mu-lock.el b/modules/email/mu4e/autoload/mu-lock.el
index 845844757..5033716ac 100644
--- a/modules/email/mu4e/autoload/mu-lock.el
+++ b/modules/email/mu4e/autoload/mu-lock.el
@@ -52,6 +52,7 @@ Else, write to this process' PID to the lock file"
       (user-error "Unfortunately another Emacs is already doing stuff with Mu4e, and you can only have one at a time")
     (write-region (number-to-string (emacs-pid)) nil +mu4e-lock-file)
     (delete-file +mu4e-lock-request-file)
+    (with-temp-buffer (write-file +mu4e-lock-request-file))
     (funcall orig-fun callback)
     (setq +mu4e-lock--request-watcher
           (file-notify-add-watch +mu4e-lock-request-file
```

Hopefully, the logic is preserved even in the `inotify` case.

> > The date column is still really small and it'd be nice to update that (or figure out how to automatically set the width). I also find it mildly nails-on-blackboard with the mixture of unicode bullet points and asterisk on the mu4e main page. I'd rather not have unicode at all just to make sure them all match. One alternative could be to instead submit a PR to mu to replace the asterisks with a variable that doom could use.
> 
> Do I just need to increase the width from 8 to 10 for the date?

I finally got my header issues sorted out. I forgot I was setting them in my own config, d'oh. It looks fine now.

> A mu4e setting for this styling could be nice. I may open an issue for this at some point.

Ah, true, maybe a good idea!

> > There are also a lot of changes in here that are pretty opinionated with no option that I can find to change. Things like,
> > 
> > * removing `auto-fill-mode` in the reply buffer (something I consider a big change)
> 
> I don't see that in this PR.

Sorry, yeah, that was my fault.

> > * emojify-ing the text email (e.g. `:-)` is replaced with an image of the smiling face)
> 
> I don't see that in this PR.

I have no idea where that came from (niether my config had emojify nor your PR) but it's gone now, so yay.

> > * replacing the sender's name with "To recipient"
> 
> Not quite sure what you're talking about.

It's due to the [change here](https://github.com/hlissner/doom-emacs/pull/3971/files#diff-e4ae34fcacdffca06aea528ca819a5b6b2332032b20005392503b6ac0e9d04aaR65). Not really that big a deal but just to explain, `:from-or-to` changes my name (e.g. "Sean Farley") to "To Sender Name".

> > * ~removing the folder column~ <- this might be me not understanding how to see the "stripe", can you post a screenshot?
> 
> Sure, this is what I see (non-default setup, but using the stripe):
> 
> ![image](https://user-images.githubusercontent.com/20903656/99420015-b0bc4280-2937-11eb-848a-8feafc0730f9.png)
>
> Each color represents a different account/maildir.

Ah, yeah, now I see it! Looks good. Is there a way to know which colors correspond to which maildir / account? It'd be nice if the main view had each maildir colored the same way as the stripe but I'm not sure how.

> > * general shrinking of certain columns (above I mentioned 'date' but 'flags' is also too short to display more than one icon for me)
> 
> It should display 3 🤔. See:
> 
> ```emacs-lisp
> (:flags . 6) ; 3 icon flags
> ```
> as well the 2-flag instances in my screenshot.

Yeah, that was my fault for not disabiling my custom settings.

> > Perhaps, I'm just old and cranky, though.
> 
> Perhaps 😛 but it's good feedback nether the less ... even if I'm not sure where most of it's coming from (as in code origin).

👴

I think, at least for me, the only points left are:
* fixing the mismatched bullet points (perhaps just upstream a new variable to control it? ... or maybe use an overlay?)
* fixing the lock file creation (hopefully that one line change is good enough)

Otherwise, I'd say it's ready for merging 🚀

2021-02-03 08:33 UTC, MaxSchlueter commented on modules/email/mu4e/autoload/email.el
> +                               (caar (plist-get msg :from)) 25 nil nil t)
This threw an error for me today, because the value returned from `caar` was `nil` (this may happen according to documentation: https://www.djcbsoftware.nl/code/mu/mu4e/Message-functions.html). We can still get the email address though, so I changed these lines to:
```
                              (truncate-string-to-width
                               (let* ((from (plist-get msg :from))
                                      (name (caar from)))
                                 (if name name
                                   (cdar from))) 25 nil nil t)
```

2021-02-03 08:35 UTC, tecosaur commented on modules/email/mu4e/autoload/email.el
> +                               (caar (plist-get msg :from)) 25 nil nil t)
Thanks Max! I'll swap in your fixed version shortly :slightly_smiling_face:

2021-02-04 04:26 UTC, tecosaur commented on modules/email/mu4e/autoload/email.el
> +                               (caar (plist-get msg :from)) 25 nil nil t)
Done.

2021-03-11 20:33 UTC, FollieHiyuki commented on modules/email/mu4e/config.el
> +      (shell-command "paplay /usr/share/sounds/freedesktop/stereo/message.oga")
Can we make this optional?
Not everyone uses `pulseaudio`.
And I personally prefer silent notifications.

2021-03-12 02:23 UTC, tecosaur commented on modules/email/mu4e/config.el
> +      (shell-command "paplay /usr/share/sounds/freedesktop/stereo/message.oga")
Thanks for the suggestion. I think a `defvar` could be introduced, how does that sound?

2021-03-12 02:45 UTC, FollieHiyuki commented on modules/email/mu4e/config.el
> +      (shell-command "paplay /usr/share/sounds/freedesktop/stereo/message.oga")
Sounds great, I would suggest 2 variables (if it doesnt make things to complicated):
- 1 for the program: aplay, paplay, pw-play... (be nil to disable playing sound)
- 1 for the sound file (`message.oga` is from a soundtheme package, not every distro ships it by default)

2021-03-20 19:49 UTC, ymarco commented
Any way to ignore emails in the gmail spam folder? They show up in my unreads list and stuff.

2021-03-21 07:46 UTC, tecosaur commented
I'd just not sync the spam folder personally. May not be the solution you're looking for though.

2021-03-21 14:47 UTC, jcf commented on modules/email/mu4e/config.el
> +      (shell-command "paplay /usr/share/sounds/freedesktop/stereo/message.oga")
@tecosaur an optional string `defvar` would be great. Yes, please!

2021-03-21 14:48 UTC, jcf commented
@tecosaur I just want to say a quick thank you for all your hard work on this. I've been regularly rebasing this branch, and loving the improvements you've made. Thank you! :heart:

2021-04-14 16:43 UTC, tecosaur commented on modules/email/mu4e/config.el
> +      (shell-command "paplay /usr/share/sounds/freedesktop/stereo/message.oga")
Implemented in e9685f6c25dfa22a42005fb1adf4fd96d3469a6d :)

2021-04-15 05:33 UTC, peterhoeg commented
This is great - I can throw away most of my fixes!

Quick thing - for the lock file locations, you probably want to do this:
```elisp
(defvar +mu4e-lock-file (format "%s/mu4e_lock" (getenv "TMP")))
(defvar +mu4e-lock-request-file (format "%s/mu4e_lock_request" (getenv "TMP"))))
```

Or use `expand-file-name` - whatever is your preference.

There is also still an issue with signatures which also exists in doom upstream where setting `(setq mu4e-compose-signature-auto-include t)` causes the mu4e signature to be added in addition to the `org-msg` signature. I'm working around this in the hooks.

And lastly if `+mu4e-personal-addresses` only has a single address (set when the context is created), just select that instead of prompting the user.

2021-04-15 21:48 UTC, hpfr commented
@peterhoeg is your Doom config public? The mu4e signature issue is not just a Doom upstream issue, but an Org-msg upstream [issue](https://github.com/jeremy-compostella/org-msg/issues/57), because the Org-msg maintainer doesn't use mu4e. If you can share the hooks I'd appreciate it.

@tecosaur the `+mu4e/capture-msg-to-agenda` integration seems to need not only the `* Email` heading but also at least one subheading present to work. If you make an empty `* Email` heading alone, it won't capture, which will be confusing for new users. But more generally, I was wondering if the text munging approach is the right move. Is it possible to leverage `org-capture` templates or another more high-level method of adding Org items rather than the current method, which seems perhaps prone to breakage or hard to configure by users?

2021-04-16 03:49 UTC, peterhoeg commented
>  If you can share the hooks I'd appreciate it.

Sure. Please note that I still get duplicate signatures for new messages from scratch, but those I would always create
as plain text mails anyway, so that's why I haven't looked into fixing it.

(defun +mu4e--signature-file (identity)
  "Return a signature file for a given `IDENTITY`"
  (format "signature.%s" identity))

(defun +mu4e--signature (&optional identity)
  "Return the default signature or the one provided by IDENTITY."
  (let* ((sig-file (if identity
                        (+mu4e--signature-file identity)
                      message-signature-file))
          (file (expand-file-name sig-file message-signature-directory)))
    (cond
      ((eq mu4e-compose-signature 't)
       (if (file-exists-p file)
          ;; instead of writing file-to-string myself, use this one from upstream
          (cvs-file-to-string file)
        (error! "Unable to find signature %s" file)))
      ((not mu4e-compose-signature)
       "")
      (t mu4e-compose-signature))))

(add-hook! 'mu4e-compose-mode-hook
  (unless (bound-and-true-p org-msg-edit-mode)
    (save-excursion
      (message-goto-body)
      (insert "\n\n")
      (insert (+mu4e--signature))
      (message-goto-body))))

2021-04-16 03:53 UTC, peterhoeg commented
And this helper is quite convenient too:

```elisp
(map!
 :leader
 :n :desc "Signature" "i g"
 (cmd!
  (save-excursion
    (insert (+mu4e--signature)))))
```

As I am top posting for the vast majority of work email, it's convenient to be able to insert it quickly when not.

2021-04-16 03:56 UTC, peterhoeg commented
One more comment - we probably want to go to the latest org-msg, specifically to get [this commit](https://github.com/jeremy-compostella/org-msg/commit/54e34b2d76e7a44be7fbd76aad67b1da903b9ab7) as the temporary file otherwise sometimes contains slashes causing emacs to prompt to create the required directory which is annoying.

2021-04-16 05:28 UTC, tecosaur commented
@peterhoeg those commits should resolve most of your suggestions :slightly_smiling_face:

2021-04-16 05:35 UTC, peterhoeg commented
Cool, I'll definitely check that out later. One last thing since you're on fire today - with `(format +onsave)` `format-all` has a tendency to kick in (and produce warnings) when writing out the various .html files. Any good ideas how to disable it completely during mu4e/org-msg without having to blacklist a whole bunch of modes manually?

2021-04-16 05:45 UTC, tecosaur commented
With `(format +onsave)`, I've given up on that in my config and can't say I'm interested in investigating it. It's too pernicious.

2021-04-16 13:21 UTC, vqhuy commented on modules/email/mu4e/autoload/email.el
> +(defun +mu4e/capture-msg-to-agenda (arg)
I think mu4e provides a function for this purpose also (see [`mu4e-org-store-and-capture`](https://www.djcbsoftware.nl/code/mu/mu4e/Org_002dmode-links.html)).
I think it's better since we can choose the header and use `org-capture` templates instead of a fixed header in the current implementation (`* Email`).

2021-04-16 14:16 UTC, tecosaur commented on modules/email/mu4e/autoload/email.el
> +(defun +mu4e/capture-msg-to-agenda (arg)
That sounds good, would be you be interested in PR-ing my PR? :smile:

2021-04-16 14:26 UTC, peterhoeg commented
> I think mu4e provides a function for this purpose also (see mu4e-org-store-and-capture).
> I think it's better since we can choose the header and use org-capture templates instead of a fixed header in the current implementation (* Email).

Using capture templates is definitely the way to go, but I had to do my own version in order to trigger a specific
template:

  (defun +org-capture-mail ()
    "Capture an email as a TODO item."
    (interactive)
    (call-interactively 'org-store-link)
    (org-capture nil "m"))

So maybe we make the capture template shortcut letter configurable:

  (defvar +mu4e-org-capture-template-letter "m"
  "The shortcut to the capture template to activate.")

  (defun +org-capture-mail ()
    "Capture an email as a TODO item."
    (interactive)
    (call-interactively 'org-store-link)
    (org-capture nil +mu4e-org-capture-template-letter))

2021-04-16 14:46 UTC, vqhuy commented on modules/email/mu4e/autoload/email.el
> +(defun +mu4e/capture-msg-to-agenda (arg)
Hmm, nothing special, when you call this function, it will call `org-capture` (the same as when you press `SPC X`).
This opens org-capture-template, which allows us to choose where to put the email to the agenda.

2021-04-17 13:38 UTC, hpfr commented
> Using capture templates is definitely the way to go, but I had to do my own version in order to trigger a specific
template:

This snippet is short enough that maybe it's worth just mentioning making a specific capture template in the docs for people who do want to capture messages directly as a special "Reply to x" task? Especially because I'd imagine most people would want to customize the template's wording, scheduling, and deadlines, eliminating some of the benefit of a default that people would just overwrite. For me, I'm content with `mu4e-org-store-and-capture`, `org-insert-link`, and my current templates.

2021-04-25 09:55 UTC, peterhoeg commented
How far is this PR from merged? It's working beautifully here!

2021-04-26 00:31 UTC, seanfarley commented
There are still some errors with locking that I'm seeing:

```
Wrote /var/folders/b8/zk9592h96cx2q51m10b2ll4c0000gn/T/mu4e_lock
file-notify-add-watch: File does not exist: No such file or directory, /var/folders/b8/zk9592h96cx2q51m10b2ll4c0000gn/T/mu4e_lock_request
```

And an error with folding:

```
mu4e-headers-toggle-at-point: Wrong type argument: overlayp, nil
```

Also, I'm very much against having the bullet points only half customized in the mu4e main screen. I'd much, much rather they all be customized, or none customized, or provide an option since we're unable to get easily get rid of this customization.

2021-04-26 02:30 UTC, seanfarley commented
> Also, I'm very much against having the bullet points only half customized in the mu4e main screen. I'd much, much rather they all be customized, or none customized, or provide an option since we're unable to get easily get rid of this customization.

I went ahead and created a pull request to mu4e to customize this behavior: https://github.com/djcb/mu/pull/1991. Included in that PR is a screenshot of the outcome.

2021-04-26 02:56 UTC, tecosaur commented
Cool! That PR looks great.

I'll look at the lock/folding errors. Worst case, I'll mention how to disable them in the readme.

2021-04-27 17:06 UTC, bdarcus commented on modules/email/mu4e/README.org
> +The install either the =isync= (=mbsync=) or =offlineimap= package.
```suggestion
Then install either the =isync= (=mbsync=) or =offlineimap= package.
```

?

2021-04-27 17:18 UTC, bdarcus commented
I've never used mu4e, but am starting to think about it, in part because of work like this:

https://www.reddit.com/r/emacs/comments/mzgsm0/mu4e_look_and_feel/

I see you already use his "folding" package. Have you thought about this also? 

https://github.com/rougier/mu4e-dashboard

2021-04-27 17:40 UTC, agraul commented on modules/email/mu4e/README.org
> +The install either the =isync= (=mbsync=) or =offlineimap= package.
You can install both, the packages don't conflict (at least not on openSUSE distros). I don't see any reason that keeps you from installing both, distros should allow that.

But I would not recommend installing both for casual mu4e users. These two tools generally serve the same purpose: ensuring that a remote IMAP mailbox is in synch with a local copy. 

I think it is better for the target audience to recommend to install one of them. Using both tools with the same local and remote mailboxes is probably a bad idea since they could step on each others feet.

2021-04-27 17:43 UTC, agraul commented
Btw @tecosaur, the thread-folding package is a bit buggy. I haven't figured out yet what causes this, but sometimes I can't fold (only the indicator changes but the number of emails that are visible stays the same). I don't know how common this is for others and how mature the package is. Maybe it's better not to include it yet.

I have enabling the thread-folding again, reproducing the error and filing an issue upstream on my to-do list.

2021-04-27 17:46 UTC, bdarcus commented on modules/email/mu4e/README.org
> +The install either the =isync= (=mbsync=) or =offlineimap= package.
> But I would not recommend installing both for casual mu4e users.

OK, I updated my suggestion to clearly state that.

Thanks.

2021-04-27 17:47 UTC, seanfarley commented
> Btw @tecosaur, the thread-folding package is a bit buggy. 

Yeah, the author himself [admitted it was not foolproof but was sometimes usable until mu4e uses `ctable`](https://github.com/djcb/mu/issues/75#issuecomment-744642916).

> I haven't figured out yet what causes this, but sometimes I can't fold (only the indicator changes but the number of emails that are visible stays the same).

I noticed that it doesn't fold unread messages; is that what you're seeing.

> I don't know how common this is for others and how mature the package is. Maybe it's better not to include it yet. I have enabling the thread-folding again, reproducing the error and filing an issue upstream on my to-do list.

That's a good question, especially given that this package is meant to be a temporary solution.

2021-04-29 10:06 UTC, agraul commented
> I noticed that it doesn't fold unread messages; is that what you're seeing.

I think that's it! I'm on many mailing lists, it would be nice to fold threads that I want to read later.

2021-05-17 14:30 UTC, wedens commented on modules/email/mu4e/config.el
> +  (mu4e-alert-enable-mode-line-display))
`mu4e-alert-enable-mode-line-display` is called twice. Either one is extra or deserves a comment why it need to be called twice :)

2021-05-17 16:07 UTC, tecosaur commented on modules/email/mu4e/config.el
> +  (mu4e-alert-enable-mode-line-display))
Thanks for the catch! Down to one now :P

2021-05-22 09:04 UTC, maxmahlke reviewed
Hi! I very much like your improvements of the module. I added one suggestion for a smoother scrolling experience with the `mu4e-thread-folding` package. However, I'm not sure if the code block I marked is meant to address this issue or another one.

2021-05-24 14:59 UTC, hlissner requested changes

2021-05-24 14:59 UTC, hlissner commented on docs/modules.org
> ++ [[file:../modules/email/mu4e/README.org][mu4e]] =+org= =+gmail= - TODO
These two flags should be in one verbatim block, and sorted alphabetically: `=+gmail +org=`

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/autoload/advice.el
> +                                           (substring img-uri 7))) ; 7=(length "file://")
`doom-call-process` returns a cons cell where `(EXITCODE . OUTPUT)`, but this use case appears to be designed as if it merely returned `OUTPUT`. Should be:

```diff
-                        (doom-call-process "identify" "-format" "%w"
-                                           (substring img-uri 7))) ; 7=(length "file://")
+                        (cdr (doom-call-process "identify" "-format" "%w"
+                                                (substring img-uri 7)))) ; 7=(length "file://")
```

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/autoload/advice.el
> +                                           (substring img-uri 7))) ; 7=(length "file://")
Side note: this seems like a hard dependency on imagemagick, could we fall back if it's absent?

```diff
-  (if +org-msg-currently-exporting
+  (if (and +org-msg-currently-exporting (executable-find "identify"))
```

Perhaps memoize the function if you expect `+org-msg-img-scale-css` to be called a lot.

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/autoload/advice.el
> +      (org-html-format-latex latex-frag 'html info))
There's no point to the second test case if `processing-type` == `t`

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +;;;###autoload
Seems `+mu4e--get-string-width` is only used in `+mu4e-normalised-icon`, so don't autoload it.

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/autoload/email.el
> +;;;###autoload
Seems `+mu4e--str-color-face` is only used in `+mu4e-colorize-str`, so don't autoload it.

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/autoload/mu-lock.el
> +;;;###autoload
Never used outside of this file. Should it be autoloaded?

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/autoload/mu-lock.el
> +;;;###autoload
Never used outside of this file. Should it be autoloaded?

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/autoload/mu-lock.el
> +;;;###autoload
Never used outside of this file. Should it be autoloaded?

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/config.el
> +    '(message-cited-text-4 :foreground nil :inherit gnus-cite-4))
This would be better suited to a theme, not a module. Would you mind giving me before/after screens of this? If it seems like a decent default I'll push it to `doom-themes`

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/config.el
> +    (add-hook
Use `add-hook!` when relying on `defun`'s return value.

`defun`'s return value is undefined (quoting its docs). It returns the function symbol for now, but there's no guarantee this will always be the case. `add-hook!` does some form scraping magic to avoid this.

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/config.el
> +  (setq +mu4e-header-colorized-faces
This is a free variable. It should be defined with `defvar`.

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/config.el
> +    "Minimum reasonable with for the header view.")
Customizable variables should be defined at the top of the module.

2021-05-24 14:59 UTC, hlissner commented on modules/email/mu4e/config.el
> +    '(mu4e-thread-folding-child-face :inherit hl-line :extend t))
Like before, `custom-set-faces!` is rarely appropriate for modules. Please show before/after shots to help me judge whether I can push it upstream.

2021-06-08 05:54 UTC, peterhoeg commented
@tecosaur do you mind bumping `org-msg`? There is newer version which doesn't force top-posting.

2021-06-08 05:57 UTC, tecosaur commented
I've been rather busy the past two weeks, but I'll be taking another look at this soon. I'll bump org-msg then.

2021-06-13 22:16 UTC, seanfarley commented
Seems Dirk-Jan doesn't want people to [modify the main view at all](https://github.com/djcb/mu/pull/1991#issuecomment-860159665). I often wonder why I bother to try and help at all.

2021-06-13 22:24 UTC, bdarcus commented
> Seems Dirk-Jan doesn't want people to [modify the main view at all](https://github.com/djcb/mu/pull/1991#issuecomment-860159665). I often wonder why I bother to try and help at all.

Wow; a pretty shocking response from him.

2021-06-14 03:23 UTC, tecosaur commented
That's pretty unfortunate :disappointed:

2021-06-14 18:54 UTC, seanfarley commented
FYI, I'm still getting: `file-notify-add-watch: File does not exist: No such file or directory, /var/folders/b8/zk9592h96cx2q51m10b2ll4c0000gn/T/mu4e_lock_request`

2021-06-14 18:56 UTC, seanfarley commented
Also, I fixed the main-view config variables not getting the prettified bullet point. I don't know how you'd like this patch (email, GH pr, etc) so here it is in case you want to just `pbpaste | git apply` it:

```patch
From 146ab2d7a3e5059e39547a38f65dbbbab2f67a32 Mon Sep 17 00:00:00 2001
From: Sean Farley <sean@farley.io>
Date: Mon, 14 Jun 2021 13:51:41 -0500
Subject: [PATCH] mu4e: also prettify the key-val string in main view

---
 modules/email/mu4e/autoload/advice.el | 5 +++++
 modules/email/mu4e/config.el          | 1 +
 2 files changed, 6 insertions(+)

diff --git a/modules/email/mu4e/autoload/advice.el b/modules/email/mu4e/autoload/advice.el
index fbfa64253..191e8e921 100644
--- a/modules/email/mu4e/autoload/advice.el
+++ b/modules/email/mu4e/autoload/advice.el
@@ -27,6 +27,11 @@ clicked."
                        (- (length newstr) 1) 'mouse-face 'highlight newstr)
     newstr))
 
+;;;###autoload
+(defun +mu4e~main-keyval-str-prettier-a (str)
+  "Replace '*' with '⚫' in STR."
+  (replace-regexp-in-string "\t\\*" "\t⚫" str))
+
 ;; Org msg LaTeX image scaling
 
 ;;;###autoload
diff --git a/modules/email/mu4e/config.el b/modules/email/mu4e/config.el
index d633238df..bc274e79e 100644
--- a/modules/email/mu4e/config.el
+++ b/modules/email/mu4e/config.el
@@ -202,6 +202,7 @@
 
   (add-hook 'mu4e-compose-pre-hook '+mu4e-set-from-address-h)
 
+  (advice-add #'mu4e~key-val :filter-return #'+mu4e~main-keyval-str-prettier-a)
   (advice-add #'mu4e~main-action-str :override #'+mu4e~main-action-str-prettier-a)
   (when (featurep! :editor evil)
     ;; As +mu4e~main-action-str-prettier replaces [k]ey with key q]uit should become quit
-- 
2.31.1

```

2021-06-15 02:35 UTC, peterhoeg commented
> Wow; a pretty shocking response from him.

I wouldn't call it shocking. I don't agree with his decision but he's of course fully in his right to say what goes in and what doesn't. IMHO, the best way forward is to either try to convince him to allow it in or simply accept the visual inconsistency. It's hardly a deal-breaker not to have unified bullet points.....

2021-06-18 19:12 UTC, seanfarley commented
@tecosaur here is the patch to fix the locking error:

```diff
From f9afda06d98d4c198ea60f8e089fcb7aa18449c0 Mon Sep 17 00:00:00 2001
From: Sean Farley <sean@farley.io>
Date: Fri, 18 Jun 2021 14:09:07 -0500
Subject: [PATCH] mu4e: `file-notify-add-watch' might not create the lock file

On some OS implementations (e.g. BSD uses kqueue),
`file-notify-add-watch' might not create the file if it doesn't exist.
This patch fixes that error. Arguably, emacs lisp should ensure the same
behavior exists across each implementation.
---
 modules/email/mu4e/autoload/mu-lock.el | 1 +
 1 file changed, 1 insertion(+)

diff --git a/modules/email/mu4e/autoload/mu-lock.el b/modules/email/mu4e/autoload/mu-lock.el
index 421952a49..c34329d6a 100644
--- a/modules/email/mu4e/autoload/mu-lock.el
+++ b/modules/email/mu4e/autoload/mu-lock.el
@@ -52,6 +52,7 @@ Else, write to this process' PID to the lock file"
       (user-error "Unfortunately another Emacs is already doing stuff with Mu4e, and you can only have one at a time")
     (write-region (number-to-string (emacs-pid)) nil +mu4e-lock-file)
     (delete-file +mu4e-lock-request-file)
+    (call-process "touch" nil nil nil +mu4e-lock-request-file)
     (funcall orig-fun callback)
     (setq +mu4e-lock--request-watcher
           (file-notify-add-watch +mu4e-lock-request-file
-- 
2.31.1
```

2021-06-18 19:25 UTC, seanfarley commented
FWIW, I give this PR my green light 🟢

2021-06-18 19:29 UTC, tecosaur commented
> do you mind bumping `org-msg`? There is newer version which doesn't force top-posting.

@peterhoeg done.

2021-06-21 09:30 UTC, gildo commented
hi @tecosaur, thanks for your fantastic work.

I have a couple of problems when applying this PR and I don't know if I'm missing something in my personal configuration:

### Composing
when composing email (after calling `+mu4e/compose` or `C-x m`):

```apply: Wrong number of arguments: ((t) (orig-fn compose-type &optional msg) "Prevent `mu4e-compose-signature' from being used with `org-msg-mode'." (let ((mu4e-compose-signature (if org-msg-mode nil mu4e-compose-signature))) (funcall orig-fn compose-type msg))), 4```

My workaround for this one is to comment [this lines of code](https://github.com/hlissner/doom-emacs/pull/3971/commits/f83f0e7ba9fe5a9833643eef4bb3ba92971c8e02)

### Notifications
mu4e is not firing desktop notification on new email, this one seems to disappear commenting:

2021-06-24 13:47 UTC, fosskers commented
It would be quite useful if we could tell, at a glance, which messages had already been refiled into the `mu4e-refile-folder`. The other ones seem to have an icon, but not refile (I called it "Archive"). Without an icon, one has to open the email message itself to see where it's currently stored.

Thank you! Otherwise everything is going great so far.

2021-06-24 15:59 UTC, fosskers commented
I've also noticed that new messages opened with `C` open via `org-msg` just fine, but replies opened with `R` open in the usual "mu4e-compose" mode.

2021-06-25 02:59 UTC, fosskers commented
> I've also noticed that new messages opened with `C` open via `org-msg` just fine, but replies opened with `R` open in the usual "mu4e-compose" mode.

Okay... strange... a reply I made just now opened in `org-msg` via `R`...

2021-06-25 03:11 UTC, peterhoeg commented
When you reply, org-msg will disable itself if the message you're replying to is plain text.

2021-07-10 23:12 UTC, hpfr commented
I've done another series of fixes to this PR; instead of going through GitHub's PR-to-a-PR song and dance I'm trying out `git format-patch`. Feel free to review it here, or you can copy it into a file and run `git am filename.patch` to apply the commits locally for testing, and then rebase from there to change, reorder, or remove things before you push. Let me know if this is inconvenient.

The major changes:
- Remove the capture function in favor of an `org-capture` template. I mentioned this earlier so I think you disagree with this, but personally, I think if you want a large custom capture routine like you have, it should stay in your personal config. `org-capture` already has all the tools to accomplish essentially the same task. You're of course welcome to change the structure of the template to whatever you prefer. If you still think your manual capture method is preferable, maybe Henrik should weigh in on it? Personally, I'm still going to override this with my own template since I include logbook drawer entries in all my templates, but I think if we're going to provide a default it should be fairly minimal.
- Remove `+mu4e-set-from-address-h`. Thanks to some fixes to `set-email-account!`, that should be all that's needed to set the `From` address, I think. It's worked for my five accounts for months, anyway.
- Add a call to [`xdg-user-dir`](https://www.mankier.com/1/xdg-user-dir) as the primary method for finding the XDG downloads directory. I'm assuming `executable-find` will fail appropriately on Windows and macOS, but if that's not the case, it will have to be fixed further.

<details>
<summary><code>mu4e-fixes-2.patch</code></summary>

```patch
From 3c6cbea99069c464e752f1a539010fbb173a14ef Mon Sep 17 00:00:00 2001
From: Liam Hupfer <liam@hpfr.net>
Date: Sat, 10 Jul 2021 13:43:26 -0500
Subject: [PATCH 1/7] mu4e: Add xdg-user-dir directory finding method

---
 modules/email/mu4e/config.el | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

diff --git a/modules/email/mu4e/config.el b/modules/email/mu4e/config.el
index bc274e79e..03ec151d6 100644
--- a/modules/email/mu4e/config.el
+++ b/modules/email/mu4e/config.el
@@ -51,9 +51,12 @@
               ((featurep! :completion helm) #'completing-read)
               (t #'ido-completing-read))
         mu4e-attachment-dir
-        (expand-file-name (or (getenv "XDG_DOWNLOAD_DIR")
-                              "Downloads")
-                          "~")
+        (if (executable-find "xdg-user-dir")
+            ;; remove trailing newline
+            (substring (shell-command-to-string "xdg-user-dir DOWNLOAD") 0 -1)
+          (expand-file-name (or (getenv "XDG_DOWNLOAD_DIR")
+                                "Downloads")
+                            "~"))
         ;; no need to ask
         mu4e-confirm-quit nil
         mu4e-headers-thread-single-orphan-prefix '("─>" . "─▶")
-- 
2.31.1


From de3733c93c6a8177ca48275e55bd6e17bd2811d0 Mon Sep 17 00:00:00 2001
From: Liam Hupfer <liam@hpfr.net>
Date: Sat, 10 Jul 2021 13:50:20 -0500
Subject: [PATCH 2/7] mu4e: Fix mu4e~context-current reference

The default-p argument to `set-email-account!` now works as intended.
---
 modules/email/mu4e/autoload/email.el | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/modules/email/mu4e/autoload/email.el b/modules/email/mu4e/autoload/email.el
index 7aab501b3..f7dc39627 100644
--- a/modules/email/mu4e/autoload/email.el
+++ b/modules/email/mu4e/autoload/email.el
@@ -39,7 +39,7 @@ default/fallback account."
                     :vars letvars)))
       (push context mu4e-contexts)
       (when default-p
-        (setq-default mu4e-context-current context))
+        (setq-default mu4e~context-current context))
       context)))
 
 
-- 
2.31.1


From 148348f87b5cdc86f9b491a320800b99c4b540ca Mon Sep 17 00:00:00 2001
From: Liam Hupfer <liam@hpfr.net>
Date: Sat, 10 Jul 2021 13:51:31 -0500
Subject: [PATCH 3/7] mu4e: Ignore case when matching mu4e context

This allows users to have different casing in their mu4e context names
and the corresponding directories.
---
 modules/email/mu4e/autoload/email.el | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/modules/email/mu4e/autoload/email.el b/modules/email/mu4e/autoload/email.el
index f7dc39627..c07686bf8 100644
--- a/modules/email/mu4e/autoload/email.el
+++ b/modules/email/mu4e/autoload/email.el
@@ -35,7 +35,7 @@ default/fallback account."
                     (lambda (msg)
                       (when msg
                         (string-prefix-p (format "/%s" label)
-                                         (mu4e-message-field msg :maildir))))
+                                         (mu4e-message-field msg :maildir) t)))
                     :vars letvars)))
       (push context mu4e-contexts)
       (when default-p
-- 
2.31.1


From 2da899f737bf619d33a421a687891ef998541012 Mon Sep 17 00:00:00 2001
From: Liam Hupfer <liam@hpfr.net>
Date: Sat, 10 Jul 2021 13:47:44 -0500
Subject: [PATCH 4/7] mu4e: Remove +mu4e-set-from-address-h

This can be accomplished via the `:match-func` definition in
`set-email-account!` in concert with `mu4e-compose-policy` and
`mu4e-compose-context-policy`.
---
 modules/email/mu4e/README.org        | 11 +++++++++++
 modules/email/mu4e/autoload/email.el | 26 --------------------------
 modules/email/mu4e/config.el         |  2 --
 3 files changed, 11 insertions(+), 28 deletions(-)

diff --git a/modules/email/mu4e/README.org b/modules/email/mu4e/README.org
index 3da30fec7..604986ef9 100644
--- a/modules/email/mu4e/README.org
+++ b/modules/email/mu4e/README.org
@@ -169,6 +169,17 @@ Then configure Emacs to use your email address:
   t)
 #+END_SRC
 
+If you use multiple email accounts, defining them with ~set-email-account!~ will
+automatically set the appropriate account context when replying to emails in
+that account's maildir. ~mu4e-context-policy~ and ~mu4e-compose-context-policy~
+can be modified to change context behavior when opening mu4e and composing
+email:
+
+#+begin_src emacs-lisp
+(setq mu4e-context-policy 'ask-if-none
+      mu4e-compose-context-policy 'always-ask)
+#+end_src
+
 *** Gmail
 With the =+gmail= flag, integrations are applied which account for the different
 behaviour of Gmail.
diff --git a/modules/email/mu4e/autoload/email.el b/modules/email/mu4e/autoload/email.el
index c07686bf8..ddf0c7341 100644
--- a/modules/email/mu4e/autoload/email.el
+++ b/modules/email/mu4e/autoload/email.el
@@ -334,29 +334,3 @@ When otherwise called, open a dired buffer and enable `dired-mu4e-attach-ctrl-c-
    (+mu4e--old-wconf
     (set-window-configuration +mu4e--old-wconf)
     (setq +mu4e--old-wconf nil))))
-
-;;;###autoload
-(defun +mu4e-set-from-address-h ()
-  "Set the account for composing a message. If a 'To' header is present,
-and correspands to an email address, this address will be selected.
-Otherwise, the user is prompted for the address they wish to use. Possible
-selections come from the mu database or a list of email addresses associated
-with the current context."
-  (unless (and mu4e-compose-parent-message
-               (let ((to (cdr (car (mu4e-message-field mu4e-compose-parent-message :to))))
-                     (from (cdr (car (mu4e-message-field mu4e-compose-parent-message :from)))))
-                 (if (member to (mu4e-personal-addresses))
-                     (setq user-mail-address to)
-                   (if (member from (mu4e-personal-addresses))
-                       (setq user-mail-address from)
-                     nil))))
-    (setq user-mail-address
-          (if (= (length +mu4e-personal-addresses) 1)
-              (car +mu4e-personal-addresses)
-            (completing-read
-             "From: "
-             (if-let ((context-addresses
-                       (when mu4e~context-current
-                         (alist-get '+mu4e-personal-addresses (mu4e-context-vars mu4e~context-current)))))
-                 context-addresses
-               (mu4e-persona [...]

2021-07-10 23:22 UTC, hpfr commented
Oh, yeah, it's come up in chat before but do people have thoughts on putting the thread folding behind a variable or flag? As discussed, it has presentation issues when you perform actions on folded threads, which could be alarming for new users trying to determine whether mu4e is eating their emails :sweat_smile:. I think the defaults for this module should try to be as stable as possible, since email is kind of important to most people

2021-07-12 07:39 UTC, agraul commented
> Remove +mu4e-set-from-address-h. Thanks to some fixes to set-email-account!, that should be all that's needed to set the From address, I think. It's worked for my five accounts for months, anyway.

What I like about `+mu4e-set-from-address-h` is that it is not restricting me to 1 account per address. I use many local-parts on my own domain, basically a separate one for each service I create an account with. I don't know if this function should be in Doom or on everyone's config who uses more than one address/alias for each account.

2021-07-22 18:25 UTC, tecosaur commented on docs/modules.org
> ++ [[file:../modules/email/mu4e/README.org][mu4e]] =+org= =+gmail= - TODO
Resolved.

2021-07-22 18:30 UTC, tecosaur commented on modules/email/mu4e/autoload/advice.el
> +      (org-html-format-latex latex-frag 'html info))
Removed `t`.

2021-07-22 18:31 UTC, tecosaur commented on modules/email/mu4e/autoload/email.el
> +;;;###autoload
Removed, along with outdated comment above.

2021-07-22 18:31 UTC, tecosaur commented on modules/email/mu4e/autoload/email.el
> +;;;###autoload
Removed.

2021-07-22 18:33 UTC, tecosaur commented on modules/email/mu4e/autoload/mu-lock.el
> +;;;###autoload
I'm pretty sure I barely understood autoloading when I was doing this :sigh:. Thanks for having the good grace to go through and catch my blunders.

2021-07-22 18:35 UTC, tecosaur commented on modules/email/mu4e/autoload/mu-lock.el
> +;;;###autoload
Looking at this now I'm pretty sure only `+mu4e-lock-start` and `+mu4e-lock-file-delete-maybe` should be autoloaded.

2021-07-22 18:36 UTC, tecosaur commented on modules/email/mu4e/autoload/mu-lock.el
> +;;;###autoload
Don't think so.

2021-07-22 18:36 UTC, tecosaur commented on modules/email/mu4e/autoload/mu-lock.el
> +;;;###autoload
Don't think so.

2021-07-22 18:57 UTC, tecosaur commented on modules/email/mu4e/config.el
> +    '(message-cited-text-4 :foreground nil :inherit gnus-cite-4))
Handled in discord.

2021-07-22 19:15 UTC, tecosaur commented on modules/email/mu4e/autoload/advice.el
> +                                           (substring img-uri 7))) ; 7=(length "file://")
I'd like to use `file`, but some less trivial parsing of the output is required (more fragile?) and it only works with PNGs, which may be a non issue giving that `dvi2png` is the standard tool Org uses here.

2021-07-22 19:15 UTC, tecosaur commented on modules/email/mu4e/autoload/advice.el
> +                                           (substring img-uri 7))) ; 7=(length "file://")
Oh, and the `doom-call-process` line has been adjusted.

2021-07-22 19:17 UTC, tecosaur commented on modules/email/mu4e/config.el
> +    (add-hook
Changed to `add-hook!`

2021-07-25 13:05 UTC, tecosaur commented on modules/email/mu4e/config.el
> +  (setq +mu4e-header-colorized-faces
Oh, I did this.

2021-07-29 10:59 UTC, tecosaur commented on modules/email/mu4e/config.el
> +    "Minimum reasonable with for the header view.")
Oh yea, I have moved this.

2021-07-29 11:00 UTC, tecosaur commented on modules/email/mu4e/config.el
> +    '(mu4e-thread-folding-child-face :inherit hl-line :extend t))
Obselete.

2021-07-29 17:56 UTC, tecosaur commented on modules/email/mu4e/autoload/advice.el
> +                                           (substring img-uri 7))) ; 7=(length "file://")
Refactored.

2021-07-31 02:22 UTC, hlissner approved these changes

2021-07-31 04:24 UTC, merged

2021-07-31 04:27 UTC, hlissner commented
And merged! There were a lot of voices in here; thank you all for helping shape this PR, and to @tecosaur for all his work (and around Doom in general, for that matter). I intend to adopt mu4e myself next month, so I'll look into polishing this module (and its documentation) further then.

Thanks again!