Bump :lang haskell
hlissner/doom-emacs pull request #3976
Opened 2020-09-24 15:46 UTC by bixuanzju

Switch to haskell-language-server, see https://neilmitchell.blogspot.com/2020/09/dont-use-ghcide-anymore-directly.html

2020-09-24 15:51 UTC, bixuanzju commented on modules/lang/haskell/+lsp.el
> -  (when IS-MAC
I’m using Mac, and I don’t need to do anything here; it works out of the box!

2020-09-25 01:04 UTC, bixuanzju commented on modules/lang/haskell/README.org
> -#+END_SRC
Well, updated platform dependent installation instructions can always be found in the link above. I don’t find it too much useful to put it here.

2020-10-05 03:31 UTC, hlissner commented
Would you mind bumping the other packages in this module (`M-x doom/bump-module RET :lang haskell`), then rewording the commit to:

```
Bump :lang haskell

emacs-lsp/lsp-haskell@17d7d4c -> emacs-lsp/lsp-haskell@a56667b
haskell/haskell-mode@41683c0 -> haskell/haskell-mode@e726776
jyp/attrap@4cf3e4a -> jyp/attrap@9c88154
jyp/dante@c516bc9 -> jyp/dante@e2acbf6

Switch to haskell-language-server, see
https://neilmitchell.blogspot.com/2020/09/dont-use-ghcide-anymore-directly.html
```

Bump commits must follow a particular format, so they are machine-readable by future CI.

2020-10-05 03:32 UTC, hlissner requested changes
Would you mind bumping the other packages in this module (`M-x doom/bump-module RET :lang haskell`), then rewording the commit to:

```
Bump :lang haskell

emacs-lsp/lsp-haskell@17d7d4c -> emacs-lsp/lsp-haskell@a56667b
haskell/haskell-mode@41683c0 -> haskell/haskell-mode@e726776
jyp/attrap@4cf3e4a -> jyp/attrap@9c88154
jyp/dante@c516bc9 -> jyp/dante@e2acbf6

Switch to haskell-language-server, see
https://neilmitchell.blogspot.com/2020/09/dont-use-ghcide-anymore-directly.html
```

Bump commits must follow a particular format, so they are machine-readable by future CI.

2020-10-05 21:27 UTC, hlissner approved these changes

2020-10-05 21:28 UTC, merged

2020-10-05 21:28 UTC, hlissner commented
Thanks for your help!