Improve fill-column module for Emacs 27+
hlissner/doom-emacs pull request #3982
Opened 2020-09-26 15:55 UTC by rushsteve1

Emacs 27 introduced `display-fill-column-indicator-mode` which replaces `hl-fill-column`. This commit adds some conditionals to use `display-fill-column-indicator-mode` on Emacs 27+, or falls back to `hl-fill-column-mode` on older versions.

This also fixes the deprecation message so I removed it. Once Emacs 27 is more common I would suggest marking it as deprecated again and removing the module entirely. I'll add the message back if you still want it there.

I suggest merging #3815 first since that adds documentation which I can update to match this change.

Any and all suggestions welcome! I'm not great at Elisp yet and in particular the `add-hook!` macro gave me trouble which led to a bit of repetition in the code.

2020-09-26 23:43 UTC, rushsteve1 commented
Two additional commits with changes suggested on Discord.

2020-10-04 22:20 UTC, hlissner requested changes

2020-10-04 22:20 UTC, hlissner commented on modules/ui/fill-column/autoload.el
> +               #'hl-fill-column-mode))
Could you replace this duplication with a delegate? e.g.

```elisp
;;;###autoload
(defun +fill-column-enable-h (&optional arg)
  (interactive "p")
  (if (fboundp 'display-fill-column-indicator-mode)
      (display-fill-column-indicator-mode arg)
    (hl-fill-column-mode arg)))
```

Then we can have only one `add-hook!`, and one `:when` check in config/default/+{evil,emacs}-bindings.el.

2020-10-05 14:16 UTC, rushsteve1 commented on modules/ui/fill-column/autoload.el
> +               #'hl-fill-column-mode))
Ah, I spent forever trying to reduce that duplication. Good to know that trick, should help me a lot.

2020-10-05 14:19 UTC, rushsteve1 commented
Thanks for the suggestions @hlissner, I made them and pushed the changes.

Also ignore the force-push, I had some weird merge commits I needed to remove.

2020-10-05 21:29 UTC, merged

2020-10-05 21:30 UTC, hlissner commented
Looks good to me. Thanks!