ui/emojis: New module for inserting/displaying emojis
hlissner/doom-emacs pull request #4001
Opened 2020-10-01 04:35 UTC by akirabaruah

Uses the emojify package to enable displaying and inserting emojis. Also
adds a new binding "SPC i e" to insert an Emoji.

2020-10-07 07:37 UTC, AlexAnarcho commented
Would be a nice feature, i m struggeling with emojis in doom emacs

2020-10-11 22:49 UTC, hlissner requested changes

2020-10-11 22:49 UTC, hlissner commented on modules/ui/emojis/config.el
> +  :defer t
Remove `:defer t`. It's redundant with `:hook`.

2020-10-11 22:49 UTC, hlissner commented on modules/ui/emojis/config.el
> +  :hook (after-init . global-emojify-mode)
Can this be deferred later? Perhaps until `doom-first-buffer-hook`? Or at most `doom-first-input-hook`?

2020-10-11 22:49 UTC, hlissner commented on modules/ui/emojis/config.el
> +                        (if (featurep! +unicode) 'unicode))))
This is emojify configuration, it should be in a `:config` of the `emojify` use-package block.

2020-10-11 22:49 UTC, hlissner commented on modules/ui/emojis/config.el
> +      (seq-filter #'identity
Use `cl-remove-if-not`. Doom loads `cl-lib` by default, but not `seq` (at least, not in interactive sessions), so there is no hard guarantee `seq-filter` will be available.

2020-10-11 22:49 UTC, hlissner commented on modules/ui/emojis/packages.el
> +  :recipe (:host github :repo "iqbalansari/emacs-emojify")
Why the explicit recipe? `emojify` appears to be on MELPA and it appears to be from the same repo.

2020-10-12 01:35 UTC, akirabaruah commented on modules/ui/emojis/config.el
> +  :hook (after-init . global-emojify-mode)
Yep, `doom-first-buffer-hook` seems more appropriate.

2020-10-12 01:46 UTC, akirabaruah commented on modules/ui/emojis/packages.el
> +  :recipe (:host github :repo "iqbalansari/emacs-emojify")
No reason besides ignorance - thanks for pointing it out!

2020-10-12 01:47 UTC, akirabaruah commented on modules/ui/emojis/config.el
> +      (seq-filter #'identity
Good to know. Fixed!

2020-10-12 01:47 UTC, akirabaruah commented on modules/ui/emojis/config.el
> +                        (if (featurep! +unicode) 'unicode))))
Done!

2020-10-12 01:47 UTC, akirabaruah commented on modules/ui/emojis/config.el
> +  :defer t
Done!

2020-10-12 01:59 UTC, hlissner approved these changes

2020-10-12 02:05 UTC, hlissner requested changes
Looks good! Two things occurred to me:

1. Could you add an entry for this module in docs/modules.org. e.g.

   ```diff
    + [[file:../modules/ui/doom/README.org][doom]] - TODO
    + [[file:../modules/ui/doom-dashboard/README.org][doom-dashboard]] - TODO
    + [[file:../modules/ui/doom-quit/README.org][doom-quit]] - TODO
   ++ emoji =+ascii +github +unicode= - Adds emoji support to Emacs
    + fill-column - TODO
    + [[file:../modules/ui/hl-todo/README.org][hl-todo]] - TODO
    + [[file:../modules/ui/hydra/README.org][hydra]] - TODO
   ```

2. Could you rename the module `:ui emoji`? There's no consensus on whether emoji plural is "emoji" or "emojis", but for the sake of keystrokes I prefer the former.

2020-10-12 02:05 UTC, hlissner commented on modules/ui/emojis/config.el
> +                                (if (featurep! +unicode) 'unicode))))
Actually, could you replace this with:

```elisp
(setq emojify-styles
      (delq
       nil (list (if (featurep! +ascii) 'ascii)
                 (if (featurep! +github) 'github)
                 (if (featurep! +unicode) 'unicode))))
```

2020-10-12 03:38 UTC, akirabaruah commented on modules/ui/emojis/config.el
> +                                (if (featurep! +unicode) 'unicode))))
Ooh that's nice and concise. Done!

2020-10-12 03:57 UTC, akirabaruah commented
1. Added `emoji` entry in `docs/modules.org`
2. Renamed module to `:ui emoji` :+1: yeah plural's awkward :sweat_smile: I speak Japanese (where "emoji" is both singular/plural), but I still find myself saying "emojis" in English :shrug:

2020-10-19 05:25 UTC, hlissner approved these changes

2020-10-19 05:25 UTC, merged

2020-10-19 05:25 UTC, hlissner commented
Looks good to me. Thanks for your help!

2020-10-19 17:05 UTC, agsdot commented
This is a pretty awesome feature add to Doom. Really appreciate this PR coming in.

2020-10-20 00:34 UTC, akirabaruah commented
@agsdot glad you found it useful 😄 

Real hats off to @iqbalansari (author of the package) and @hlissner for this awesome project!

2020-10-20 01:19 UTC, agsdot commented
Yeah, props to all of you though @akirabaruah , @hlissner and @iqbalansari. 

Before this package to generate emoji's I had to either be on my mobile device and keyboard or on a desktop and use https://emojipedia.org/. This package and nice keybinding of SPC i e, lends a very nice and rapid way to find emoji when typing.

Thanks once again!