WIP: Improvements to native-comp support
hlissner/doom-emacs pull request #4047
Opened 2020-10-07 12:47 UTC by flatwhatson

Adds ahead-of-time compilation of all packages on load-path, ensuring all core and site Elisp is actually native-compiled.

Exports `comp-deferred-compilation-black-list` to runtime, bringing us one step closer to properly supporting deferred compilation.

WARNING: There are currently some upstream bugs which makes testing this PR difficult:

1. Ensure that `~/.emacs.d/eln-cache` exists.
2. Run `emacs -q`, wait for async compilations to finish.
3. Ensure that `~/.emacs.d/.local/cache/eln` exists.
4. Run `doom sync`.
5. Run `doom build -r`, kill it when it hangs on "Waiting for NNN async jobs".
6. Run `doom build -r` again, it will work this time, wait until it finishes.
7. Run `doom build -r` again, it should have nothing to rebuild.
8. Run emacs!

2020-10-07 18:57 UTC, hlissner requested changes

2020-10-07 18:57 UTC, hlissner commented on core/packages.el
> +  :pin "728ea18ea590fcd8fb48f5bed30e135942d97221")
Would you mind moving this to a separate commit with the correct bump commit format:

```
Bump straight.el

raxod502/straight.el@0c7c7571 -> raxod502/straight.el@0728ea18
```

2020-10-07 18:57 UTC, hlissner commented on core/core.el
> -           (setq comp-eln-load-path ',(bound-and-true-p comp-eln-load-path))))
Has this been fixed upstream?

2020-10-08 01:06 UTC, flatwhatson commented on core/core.el
> -           (setq comp-eln-load-path ',(bound-and-true-p comp-eln-load-path))))
Yep!  I've pulled it out into a separate commit to make this clear.

2020-10-08 01:06 UTC, flatwhatson commented on core/packages.el
> +  :pin "728ea18ea590fcd8fb48f5bed30e135942d97221")
Done!

2020-10-08 18:00 UTC, hlissner requested changes

2020-10-08 18:00 UTC, hlissner commented on core/cli/packages.el
> +           (print! "\033[K- Waiting for %d async jobs...\033[1A" pending)
Please use the `info` subgrouping instead of manually prefixing the message with a `- `:

```lisp
(print! (info "\033[KWaiting for %d async jobs...\033[1A" pending))
```

2020-10-08 23:33 UTC, flatwhatson commented on core/cli/packages.el
> +           (print! "\033[K- Waiting for %d async jobs...\033[1A" pending)
Done!

2020-10-10 23:08 UTC, hlissner requested changes

2020-10-11 19:43 UTC, merged

2020-10-11 19:43 UTC, hlissner commented
Thanks!