fix: add explanation for php document
hlissner/doom-emacs pull request #4122
Opened 2020-10-21 13:02 UTC by wangggong

Add some explanation for phpactor server and its prerequisites in `modules/lang/php/README.org`.

2020-10-28 08:21 UTC, hlissner requested changes
Looks good to me, just one small correction.

2020-10-28 08:21 UTC, hlissner commented on modules/lang/php/README.org
> +2. If you use intelephense, ~node~ and ~npm~ is needed.
`s/is/are`

2020-10-28 08:25 UTC, wangggong commented on modules/lang/php/README.org
> +2. If you use intelephense, ~node~ and ~npm~ is needed.
done

2020-10-31 07:43 UTC, hlissner approved these changes

2020-10-31 07:43 UTC, merged

2020-10-31 07:43 UTC, hlissner commented
Thanks!