Add exunit mode for Elixir
hlissner/doom-emacs pull request #4139
Opened 2020-10-23 00:42 UTC by jsmestad

I modeled this off the definition for `rspec-mode` in the `ruby` module. Let me know if there is anything I missed or need to adjust.

🍻

2020-10-28 08:19 UTC, hlissner requested changes

2020-10-28 08:19 UTC, hlissner commented on modules/lang/elixir/config.el
> +                  :return "return" :yield "use")
Please restore the original (and correct) indentation

2020-10-28 08:19 UTC, hlissner commented on modules/lang/elixir/config.el
> +  :defer t
`:defer t` is redundant with a `:hook` property. Please remove it.

2020-10-28 08:19 UTC, hlissner commented on modules/lang/elixir/config.el
> +  :config
Replace `:config` with `:init`. Otherwise the `map!`'s deferral happens too late (making it impossible for users to override those keybinds, because `(map! :after elixir ...)` won't run late enough.

2020-10-28 16:56 UTC, jsmestad commented on modules/lang/elixir/config.el
> +                  :return "return" :yield "use")
Whooops not sure why that happend. 🙃

2020-11-12 15:59 UTC, jsmestad commented on modules/lang/elixir/config.el
> +                  :return "return" :yield "use")
@hlissner I had to manually correct the indentation. What would doom be doing that would cause what you are calling the incorrect indentation? I had to switch to fundamental mode (out of elisp mode) to get the format on save to stop messing with this.

2020-11-14 20:08 UTC, hlissner commented on modules/lang/elixir/config.el
> +                  :return "return" :yield "use")
It's possible that you are running a formatter that reformats the whole file? Emacs won't know how to indent macros that haven't been loaded yet (like `set-ligatures!`), so it'll guess.

I would highly recommend not using a formatter with elisp. [It is normally inhibited in emacs-lisp-mode for this reason](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/format/config.el#L4).

2020-11-14 20:10 UTC, hlissner requested changes

2020-11-14 20:10 UTC, hlissner commented on modules/lang/elixir/config.el
> +    "s" #'exunit-verify-single))
Please correct the indentation here. Should be

```lisp
(use-package! exunit
  :hook (elixir-mode . exunit-mode)
  :init
  (map! :after elixir-mode
        :localleader
        :map elixir-mode-map
        :prefix "t"
        "a" #'exunit-verify-all
        "r" #'exunit-rerun
        "v" #'exunit-verify
        "T" #'exunit-toggle-file-and-test
        "t" #'exunit-toggle-file-and-test-other-window
        "s" #'exunit-verify-single))
```

2020-11-14 22:34 UTC, jsmestad commented on modules/lang/elixir/config.el
> +    "s" #'exunit-verify-single))
```suggestion
(use-package! exunit
  :hook (elixir-mode . exunit-mode)
  :init
  (map! :after elixir-mode
             :localleader
             :map elixir-mode-map
             :prefix "t"
             "a" #'exunit-verify-all
             "r" #'exunit-rerun
             "v" #'exunit-verify
             "T" #'exunit-toggle-file-and-test
             "t" #'exunit-toggle-file-and-test-other-window
             "s" #'exunit-verify-single))
```

2020-11-14 22:35 UTC, jsmestad commented
@hlissner alright I should have the indent sorted

2020-11-28 03:44 UTC, hlissner approved these changes

2020-11-28 03:44 UTC, merged

2020-11-28 03:44 UTC, hlissner commented
Thanks!