Add emacs bindings and documentation in fold module
hlissner/doom-emacs pull request #4143
Opened 2020-10-23 22:59 UTC by innerout

This PR adds emacs bindings for vimish-fold when evil is disabled. It also adds documentation for the bindings. Finally, it reports a weird bug and explains a way to bypass it.

2020-10-28 08:16 UTC, hlissner requested changes

2020-10-28 08:16 UTC, hlissner commented on modules/editor/fold/config.el
> +    :init
Please use `(unless (featurep! ...)` instead of `(when (not (featurep! ...))`

2020-10-28 08:16 UTC, hlissner commented on modules/editor/fold/config.el
> +    :init
Please lazy load the package by adding `:defer t` before `:init`.

2020-10-28 08:16 UTC, hlissner commented on modules/editor/fold/config.el
> +    :init
Please use `use-package`'s `:unless` property instead of wrapping a `use-package!` block in a `when`/`unless`. e.g.

```diff
(use-package! vimish-fold
  :unless (featurep! :editor evil)
  :defer t
  :init
```

2020-10-28 08:16 UTC, hlissner commented on modules/editor/fold/config.el
> +      "C-c d a v" #'vimish-fold-delete-all)))
1. Please move these keybinds to `modules/config/default/+emacs-bindings.el`.
2. Use `map!` instead of `define-key!`.
3. Use the `+fold/*` commands where appropriate.
4. Consolidate these keys under fewer prefixes. Perhaps `C-c C-f`, since `C-c f` is used, and `C-c {f,u,d}` is a wide spread. e.g.

```elisp
(map! :leader
      (:when (featurep! :editor fold)
        (:prefix ("C-f" . "fold")
         "C-d"     #'vimish-fold-delete
         "C-a C-d" #'vimish-fold-delete-all
         "C-f"     #'+fold/toggle
         "C-a C-f" #'+fold/close-all
         "C-u"     #'+fold/open
         "C-a C-u" #'+fold/open-all)))
```

2020-10-31 13:43 UTC, innerout commented
By mistake, I deleted the branch.

2020-11-04 02:24 UTC, hlissner requested changes

2020-11-04 02:24 UTC, hlissner commented on modules/editor/fold/config.el
> +  :defer t)
Please remove this entirely. It does nothing.

2020-11-06 07:33 UTC, hlissner approved these changes

2020-11-06 07:33 UTC, merged

2020-11-06 07:33 UTC, hlissner commented
Thanks!