Enable poetry-tracking-mode (#3826)
hlissner/doom-emacs pull request #4146
Opened 2020-10-24 11:33 UTC by sei40kr

# Description

Implements #3826.

Enable `poetry-tracking-mode` in the first `python-mode` buffer (if `python +poetry` enabled).

2020-10-29 19:49 UTC, hlissner requested changes

2020-10-29 19:49 UTC, hlissner commented on modules/lang/python/config.el
> +  (add-hook! 'python-mode-hook (poetry-tracking-mode +1)))
This unnecessarily abuses inline lambdas. Use `(add-hook 'python-mode-hook #'poetry-tracking-mode)` instead.

2020-10-31 09:48 UTC, sei40kr commented on modules/lang/python/config.el
> +  (add-hook! 'python-mode-hook (poetry-tracking-mode +1)))
@hlissner 
Thank you. I've fixed the PR.

2020-11-01 04:00 UTC, hlissner approved these changes

2020-11-01 21:25 UTC, merged

2020-11-01 21:25 UTC, hlissner commented
Thanks!