Escape skk-mode on doom/escape
hlissner/doom-emacs pull request #4147
Opened 2020-10-24 11:34 UTC by sei40kr

# Description

Escape skk-mode on `doom/escape`.

2020-10-28 08:02 UTC, hlissner requested changes

2020-10-28 08:02 UTC, hlissner commented on modules/input/japanese/config.el
> +      (skk-mode -1))))
Is there any reason you can't bind `skk-mode-exit` to it instead? e.g.

`(add-hook 'doom-escape-hook #'skk-mode-exit)`

2020-10-31 07:16 UTC, sei40kr commented on modules/input/japanese/config.el
> +      (skk-mode -1))))
@hlissner 
`skk-mode-exit` looks better! I've updated the PR. Thank you.

2020-10-31 07:42 UTC, hlissner approved these changes

2020-10-31 07:42 UTC, merged

2020-10-31 07:42 UTC, hlissner commented
Thanks!