Map Tex-view to localleader-v
hlissner/doom-emacs pull request #4183
Opened 2020-10-30 23:31 UTC by innerout

Closes #4022

2020-10-30 23:37 UTC, hlissner requested changes
Please move this keybind to lang/latex/config.el, either at the bottom of the `(after! latex ...)` block or the `(after! tex ...)` block (whichever works). Please add have a blank line before it and indent it like so:

```diff
+ 
+  (map! :map LaTeX-mode-map
+        :localleader
+        :desc "View" "v" #'TeX-view))
```

2020-10-30 23:57 UTC, innerout commented
Thanks for the feedback! Is there a way to configure doom by default with the appropriate indentation settings?

2020-10-31 07:37 UTC, hlissner approved these changes

2020-10-31 07:39 UTC, merged

2020-10-31 07:40 UTC, hlissner commented
Thanks!

> Is there a way to configure doom by default with the appropriate indentation settings?

Doom is indenting things correctly. I just want people to avoid more nesting than is necessary. Not exactly something you can automatically detect and correct without a non-trivial amount of work.