Fix Issue #4212; Use Back-Slash for Win FileShares
hlissner/doom-emacs pull request #4218
Opened 2020-11-05 12:13 UTC by SirRamEsq

Fixes Windows file share paths from a forward slash to a back slash.
Has been tested and resolves #4212

2020-11-05 17:17 UTC, ymarco commented
Shouldn't this be a quadruple backslash `"\\\\"`? `"\\"` actually produces a string containing a single character because of escaping

2020-11-05 18:50 UTC, hlissner requested changes

2020-11-05 18:50 UTC, hlissner commented on modules/lang/org/config.el
> +                   (and IS-WINDOWS (string-prefix-p "\\" path))
Please change to `"\\\\"`. `"\\"` is a single, escaped backslash. `"\\\\"` is two escaped backslashes.

2020-11-06 07:31 UTC, hlissner approved these changes

2020-11-06 07:32 UTC, merged

2020-11-06 07:32 UTC, hlissner commented
Thanks!