Created PR to backport emacs-lisp org-babel evaluation to manage the UI
hlissner/doom-emacs pull request #4236
Opened 2020-11-08 07:54 UTC by eccentric-j

As of emacs 27.1 we can evaluate org-babel emacs-lisp src blocks that manage the UI. This PR comes from a discussion in the upcoming discourse to backport that functionality. 

This also preludes an experimental project to provide an interactive guide for doom-emacs to better introduce users to customizing their emacs experience with emacs-lisp in Doom.

2020-11-08 08:22 UTC, hlissner requested changes

2020-11-08 08:22 UTC, hlissner commented on modules/lang/org/config.el
> +        (apply orig-fn args)))))
The core changes are fine, but could you fix all the indentation errors this PR has introduced? i.e. revert everything but these lines.

2020-11-08 08:23 UTC, hlissner commented on modules/lang/org/config.el
> +        (apply orig-fn args)))))
`(#'set-window-configuration #'ignore))` is also incorrectly indented with one space too many.

2020-11-09 07:20 UTC, eccentric-j commented
Pushed a fix that doesn't change indentation for the file. Thanks to @gagbo for recommending disabling electric-indent-mode https://discord.com/channels/406534637242810369/406624667496087572/775013674241753099.

I auto-indented the additions so it should be correct? Please let me know if it's not.

2020-11-09 07:22 UTC, eccentric-j commented
Sorry, caught a few things. Fixing now.

2020-11-09 07:30 UTC, eccentric-j commented
This is ready for review again 🙂

2020-11-10 23:31 UTC, hlissner approved these changes

2020-11-10 23:31 UTC, merged

2020-11-10 23:31 UTC, hlissner commented
Looks good to me. Thanks for your help!