Fix behaviour without aspell
hlissner/doom-emacs pull request #4262
Opened 2020-11-13 14:43 UTC by iwahbe

If aspell (or a spell-fu acceptable equivalent) cannot be found, 
warn the user. If +spell-correct-interface is not bound, bind it.

Remove previous hack. It prevents use of +spell/correct if spell-fu does
not try to highlight a word. This is extreamly common is docstrings, for
example. I think having +spell/correct should check any word it is
called upon, even without general text highlighting.

2020-11-13 18:05 UTC, hlissner requested changes

2020-11-13 18:05 UTC, hlissner commented on modules/checkers/spell/config.el
> +      (+spell-defun-correct-interface)
Please revert this change. This needlessly complicates load order for users who want to customize the `+spell-correct-interface` variable.

2020-11-13 18:05 UTC, hlissner commented on modules/checkers/spell/autoload/+spell-fu.el
> +    (+spell-defun-correct-interface))
Instead of doing this, moving the `defvar` into the `use-package spell-fu`'s `:preface` block, instead of a function.

2020-11-13 19:53 UTC, iwahbe commented on modules/checkers/spell/autoload/+spell-fu.el
> +    (+spell-defun-correct-interface))
That is a much better idea. I didn't know that `:preface` existed. Changes made.

2020-11-14 20:06 UTC, hlissner approved these changes

2020-11-14 20:06 UTC, merged

2020-11-14 20:06 UTC, hlissner commented
Looks good to me! Thanks for your help!