[:editor god] Enable god-mode support for which-key if required
hlissner/doom-emacs pull request #4283
Opened 2020-11-18 07:31 UTC by darth10

In this change:

* Bump version pin of `god-mode`
* Call `which-key-enable-god-mode-support` after loading `which-key` to enable support for `god-mode`. Prior to this change, keys entered in `god-local-mode` will not invoke `which-key` :no_entry:

As always, any feedback is more than welcome!

2020-11-19 05:55 UTC, hlissner requested changes

2020-11-19 05:55 UTC, hlissner commented on core/core-keybinds.el
> +    (which-key-enable-god-mode-support)))
Please move this to editor/god/config.el, in an `after! which-key` block inside `god-mode`'s `:config` block.

```lisp
(after! which-key
  (which-key-enable-god-mode-support))
```

2020-11-19 06:02 UTC, darth10 commented on core/core-keybinds.el
> +    (which-key-enable-god-mode-support)))
Done!

2020-11-19 17:31 UTC, hlissner approved these changes

2020-11-20 20:28 UTC, merged

2020-11-20 20:28 UTC, hlissner commented
Thanks!