Update org-msg org-msg variable.
hlissner/doom-emacs pull request #4295
Opened 2020-11-20 18:58 UTC by ptoal

Fixes #4294.

2020-11-20 18:59 UTC, hlissner requested changes

2020-11-20 18:59 UTC, hlissner commented on modules/email/mu4e/config.el
> +        org-msg-default-alternatives `(html text)))
Please replace the backquote with a single quote.

```diff
-       org-msg-default-alternatives `(html text)))
+       org-msg-default-alternatives '(html text)))
```

2020-11-20 19:16 UTC, hlissner approved these changes

2020-11-20 19:29 UTC, ptoal commented
Sorry about that.  Having a bad git day.

2020-11-20 20:29 UTC, merged

2020-11-20 20:29 UTC, hlissner commented
No worries! Thanks for the help!

2020-11-29 18:10 UTC, tecosaur commented
Why do people keep messing with my PR :cry: 
I don't like dealing with conflicts

2020-11-30 02:48 UTC, ptoal commented
I'm sorry.  I don't understand the issue?  I found problem that was caused by upstream change in org-msg, and fixed it.  No idea what you mean about your PR?

2020-11-30 07:24 UTC, tecosaur commented
Oh, don't mind me that much - I just have a big mu4e PR that has a bunch of stuff like this already taken care of, see: https://github.com/hlissner/doom-emacs/pull/3971

2020-12-03 13:28 UTC, arvindsv commented
I'm not sure if this is the right place to mention this or if I should create a new issue, but there is a difference between:

```
org-msg-default-alternatives '(html text)
```

and

```
org-msg-default-alternatives '(text html)
```

In section 7.2.3 of , [RFC-1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) it says:

```
In general, user agents that compose multipart/alternative entities should place the body parts in increasing order of preference, that is, with the preferred format last. For fancy text, the sending user agent should put the plainest format first and the richest format last. Receiving user agents should pick and display the last format they are capable of displaying. In the case where one of the alternatives is itself of type "multipart" and contains unrecognized sub-parts, the user agent may choose either to show that alternative, an earlier alternative, or both. 
```

Since the default value was set to `'(html text)`, this caused my emails sent to favour `text over `html` in the display. Especially in GMail, it caused all formatting to be lost. I had to change it to `'(text html)` to get it to show properly.

I'm not sure what the earlier behaviour was, when `org-msg-text-plain-alternative` was set to `t`.