Elisp `eldoc': fix "Invalid format operation %-"
hlissner/doom-emacs pull request #4335
Opened 2020-11-29 08:39 UTC by nbfalcon

In `+emacs-lisp-append-value-to-eldoc-a`, if the `frame-width` of the minibuffer
is smaller than the length of the documentation + " [...]" + 1, a negative
maximum %s bound is passed, causing the error in the title.

Fix this by clamping the computed LIMIT to 0.

If needed, I can make a full issue, but I hope that from my description, the cause is clear: `limit` = `(frame-width)` (minibuffer, in eldoc) - `(length str + length " [...]" + 1)` -> can be negative -> error.

2020-11-29 18:38 UTC, hlissner requested changes

2020-11-29 18:38 UTC, hlissner commented on modules/lang/emacs-lisp/config.el
> +                (format (format "%%0.%ds%%s" (min limit 0))
Function should be `max`, not `min`.

2020-11-29 18:57 UTC, nbfalcon commented on modules/lang/emacs-lisp/config.el
> +                (format (format "%%0.%ds%%s" (min limit 0))
This is an awkward blunder... Fixed.

2020-11-29 18:58 UTC, hlissner approved these changes

2020-11-29 18:58 UTC, merged

2020-11-29 18:58 UTC, hlissner commented
Thanks!

2020-11-29 18:59 UTC, nbfalcon commented
As a side note, what `git-commit-major-mode` should I use in my commit messages when contributing? Currently, I assume and use `git-commit-elisp-text-mode`.

2020-11-29 18:59 UTC, nbfalcon commented
You may want to add that to `dir-locals`.

2020-11-29 19:01 UTC, hlissner commented
> As a side note, what git-commit-major-mode should I use in my commit messages when contributing? Currently, I assume and use git-commit-elisp-text-mode.

I've simply used the default (`text-mode`), but `git-commit-elisp-text-mode` looks interesting. I'll give it a spin before adding it to our dir-locals. Thanks!

2021-03-21 03:05 UTC, sxjune commented
This fix may cause the following problems ?
On Windows 10 Emacs 27.1, Upgrade from `Doom v2.0.9 (HEAD -> develop, origin/develop, origin/HEAD 88e18fc7c 2021-02-27 23:56:15 -0500)` to `Doom v2.0.9 (HEAD -> develop 46dedb3e3 2021-03-13 16:35:21 -0500)`.
![2021-03-21 105908](https://user-images.githubusercontent.com/59131303/111892306-3ad6fd80-8a35-11eb-91bf-626c741b8836.png)
![2021-03-21 110149](https://user-images.githubusercontent.com/59131303/111892307-3f031b00-8a35-11eb-9e2c-06f36b5b577a.png)

2021-03-21 10:59 UTC, nbfalcon commented
@sxjune I don't think your issue is caused by my PR - it is very much unrelated. You'll need to upgrade `magit` for your issue to go away, since recently we switched to the upstream safe-variable predicates. You can do this using `./bin/doom sync -u`