org: jupyter prerequisites
hlissner/doom-emacs pull request #4370
Opened 2020-12-04 14:59 UTC by benneti

Add some more instructions to use +jupyter for jupyter babel blocks.

2020-12-05 20:26 UTC, hlissner requested changes

2020-12-05 20:26 UTC, hlissner commented on modules/lang/org/README.org
> +  To use ~jupyter kernels~ you need the =+jupyter= flag, the associatet kernel as
`s/associatet/associated`

2020-12-05 20:26 UTC, hlissner commented on modules/lang/org/README.org
> +pacman -S jupyter
Make it one line:

```sh
pacman -S jupyter  # required by +jupyter
```

2020-12-05 20:26 UTC, hlissner commented on modules/lang/org/README.org
> +  # +jupyter needs jupyter
Reword: `# required by +jupyter`

2020-12-07 09:33 UTC, benneti commented
thanks for the input, changed as requested

2021-01-27 07:46 UTC, hlissner approved these changes

2021-01-27 07:46 UTC, merged

2021-01-27 07:46 UTC, hlissner commented
Sorry for the long wait. Thanks for your help!