Add word existence checking for +spell/correct
hlissner/doom-emacs pull request #4381
Opened 2020-12-06 18:27 UTC by iwahbe

`(bounds-of-thing-at-point 'word)` can return `nil`. This checks that it
does not, giving an `user-error` if no word is found. I think this is better
then the `(wrong-number-of-arguments (start . end) nil)` error message.

2020-12-06 22:47 UTC, hlissner requested changes

2020-12-06 22:47 UTC, hlissner commented on modules/checkers/spell/autoload/+spell-fu.el
> -        (bounds-of-thing-at-point 'word)
This is a roundabout way of doing this. Could you use this approach instead?

```diff
     (cl-destructuring-bind (start . end)
-        (bounds-of-thing-at-point 'word)
+        (or (bounds-of-thing-at-point 'word)
+            (user-error "No word at point"))
```

2020-12-06 22:58 UTC, iwahbe commented on modules/checkers/spell/autoload/+spell-fu.el
> -        (bounds-of-thing-at-point 'word)
I didn't know that `user-error` short circuited the function. That would work.

2020-12-06 23:33 UTC, hlissner approved these changes

2020-12-09 04:00 UTC, merged

2020-12-09 04:00 UTC, hlissner commented
Thanks!