Fix/bepo exhaustive remaps
hlissner/doom-emacs pull request #4403
Opened 2020-12-10 00:29 UTC by gagbo

Related issues : #4391 #4393 

## Draft status
This is a draft pull request because it adds a lot of changes that I'm not sure of. I'll use the module like that for a week or 2 before switching that to a PR for merge

## Summary
- Add `C-` and `M-` remaps to normal/visual/motion/operator states
- Add operator state remaps wherever normal/visual/motion was remapped
- Unbind `s` from `notmuch-common-map`

The rest is mostly comments.

## Test

You can always pull the PR to test it yourself : `git fetch origin refs/pull/{number}/head && git checkout FETCH_HEAD` will put you on this branch if you really need to try anything now

2020-12-10 00:48 UTC, hlissner requested changes

2020-12-10 00:48 UTC, hlissner commented on modules/input/layout/+bepo.el
> +      (map! :map notmuch-common-map "s" nil))
May need to add `:n` before `"s"`, since evil-collection-notmuch [binds this key in normal mode](https://github.com/emacs-evil/evil-collection/blob/master/modes/notmuch/evil-collection-notmuch.el#L119).

2020-12-10 00:48 UTC, hlissner commented on modules/input/layout/+bepo.el
> +    (after! (notmuch evil-collection-notmuch)
Waiting for `evil-collection-notmuch` shouldn't be necessary. It's part of the reason why [this file exists](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/init.el); to tame load-order with evil-collection, so users can do `(map! :after PACKAGE ...)`, whether or not `PACKAGE` is augments by `evil-collection`.

2020-12-10 00:48 UTC, hlissner commented on modules/input/layout/+bepo.el
>        (map! :map magit-mode-map "s" nil)
I know this isn't part of this PR, but shouldn't this be `:nv "s"`? Since evil-collection-magit [binds these keys in normal and visual modes](https://github.com/emacs-evil/evil-collection/blob/master/modes/magit/evil-collection-magit.el#L266) (see `states`)?

2020-12-10 00:50 UTC, gagbo commented on modules/input/layout/+bepo.el
>        (map! :map magit-mode-map "s" nil)
yeah, I actually didn't put the modes for the new line because I saw I didnt change it here

2020-12-10 21:35 UTC, gagbo commented on modules/input/layout/+bepo.el
>        (map! :map magit-mode-map "s" nil)
And adding a mode there unfixes the fix (s becomes magit-delete-thing instead of just going up). I’ll have to investigate later but it’ll stay this way for now

2020-12-22 17:38 UTC, brabalan commented
I'm giving this a try but I don't think this is working. I pulled the PR and did a `doom sync`, but I still see the same issues (`r` and `s` not correctly bound in `notmuch-show-mode`, `org-insert-link` complaining about `C-l` not being a prefix key…)

What do I need to do to test it? I did:
```
git fetch github refs/pull/4403/head
git checkout FETCH_HEAD
bin/doom sync
```
and restarted emacs.

2020-12-22 23:28 UTC, gagbo commented
That’s the correct procedure indeed, you don’t need to call `doom sync` again for this particular PR.

But I really don’t know what happens then, because I definitely can’t repro the `org-insert-link` issue (using `M-x org-insert-link` or `SPC m l l` in normal mode in an org-mode buffer I have the prompt for links as expected), and I don’t use notmuch at all, and it’s so painful to setup that I don’t think I’ll be able to properly reproduce it before trying to fix the issue :(

2020-12-24 13:03 UTC, brabalan commented
I tracked down the source of the `org-insert-link` issue to this piece of code:
```emacs-lisp
(map!
 :ie "C-h" #'backward-delete-char-untabify
 (:map (minibuffer-local-map
        minibuffer-local-ns-map
        minibuffer-local-completion-map
        minibuffer-local-must-match-map
        minibuffer-local-isearch-map
        read-expression-map)
  "C-h" #'backward-delete-char-untabify)

 (:after evil
  :map evil-ex-completion-map
  "C-h" #'backward-delete-char-untabify)

 (:after org
  :map org-mode-map
  "C-h" #'backward-delete-char-untabify)

 ;; If you use :completion ivy
 (:after ivy
  :map ivy-minibuffer-map
  "C-h" #'backward-delete-char-untabify)

 ;; If you use :completion helm
 (:after helm
  :map helm-map
  "C-h" #'backward-delete-char-untabify))
```

If I disable it, I no longer have the prefix key issue popping up.

2020-12-24 13:12 UTC, brabalan commented on modules/input/layout/+bepo.el
> +      (map! :map notmuch-common-map :n "s" nil))
I don't know if this matter, but I do not have such a map. Here it's called `notmuch-common-keymap`.

2020-12-24 13:21 UTC, brabalan commented
Regarding notmuch, here are the bindings for the `s` key (for `notmuch-search`):
```emacs-lisp
evil-collection-notmuch-common-keymap-normal-state-backup-map s
notmuch-common-keymap <normal-state> k
notmuch-common-keymap s
notmuch-hello-mode-map <normal-state> s
notmuch-search-mode-map <normal-state> s
notmuch-show-mode-map <normal-state> s
notmuch-tree-mode-map <normal-state> K
notmuch-tree-mode-map <normal-state> s
```

and the ones for the function bound to `r c` (`notmuch-mua-new-mail`):
```emacs-lisp
evil-collection-notmuch-common-keymap-normal-state-backup-map C
evil-collection-notmuch-common-keymap-normal-state-backup-map c c
evil-collection-notmuch-show-mode-map-normal-state-backup-map C
evil-collection-notmuch-show-mode-map-normal-state-backup-map c c
notmuch-common-keymap <normal-state> L
notmuch-common-keymap <normal-state> l c
notmuch-common-keymap m
notmuch-hello-mode-map <normal-state> R
notmuch-hello-mode-map <normal-state> r c
notmuch-search-mode-map <normal-state> R
notmuch-search-mode-map <normal-state> r c
notmuch-show-mode-map <normal-state> R
notmuch-show-mode-map <normal-state> r c
notmuch-tree-mode-map <normal-state> R
notmuch-tree-mode-map <normal-state> r c
```

2020-12-24 13:48 UTC, brabalan commented
With this PR I no longer know how to finalize or abort an `org-capture`, as `C-c` does not work (it calls `org-shiftleft`). I tried `C-h` (I get the usual help bindings) and `C-l` (I get `recenter-top-bottom`).

2020-12-24 14:31 UTC, gagbo commented on modules/input/layout/+bepo.el
> +      (map! :map notmuch-common-map :n "s" nil))
That’s probably my mistake yeah

2020-12-24 14:49 UTC, gagbo commented
> With this PR I no longer know how to finalize or abort an `org-capture`, as `C-c` does not work (it calls `org-shiftleft`). I tried `C-h` (I get the usual help bindings) and `C-l` (I get `recenter-top-bottom`).

Nice catch, I'll fix that, and I'm pretty sure a few other org-mode maps will need that treatment

2020-12-24 14:56 UTC, gagbo commented
> I tracked down the source of the `org-insert-link` issue to this piece of code:
> 
> If I disable it, I no longer have the prefix key issue popping up.

Is that code from your own config ? I can't find that in doom-emacs source. If so, basically we need to ensure that this `map!` call happens after all the remapping by the `:input layout` module

2020-12-24 15:10 UTC, gagbo commented
```
notmuch-common-keymap <normal-state> L
notmuch-common-keymap <normal-state> l c
notmuch-common-keymap m
notmuch-hello-mode-map <normal-state> R
notmuch-hello-mode-map <normal-state> r c
notmuch-search-mode-map <normal-state> R
notmuch-search-mode-map <normal-state> r c
notmuch-show-mode-map <normal-state> R
notmuch-show-mode-map <normal-state> r c
notmuch-tree-mode-map <normal-state> R
notmuch-tree-mode-map <normal-state> r c
```

I think that `notmuch-{hello,search,show,tree}-mode-map` are inheriting the modified `notmuch-common-keymap` and get modified just after, so there are 2 "rotations" happening on these keymaps. The `evil-collection-setup-hook` is supposed to run only once on the keymap, but somehow notmuch manages to set its maps so that it runs twice

2020-12-24 16:20 UTC, brabalan commented
After the current changes I still cannot use `s` and `r`. Here are the bindings for `notmuch-search`:
```
evil-collection-notmuch-common-keymap-normal-state-backup-map s
notmuch-common-keymap <normal-state> k
notmuch-hello-mode-map <normal-state> s
notmuch-search-mode-map <normal-state> s
notmuch-show-mode-map <normal-state> s
notmuch-tree-mode-map <normal-state> K
notmuch-tree-mode-map <normal-state> s
```

I suspect you are right regarding the parent keymap. Could you avoid doing the rotation on the `notmuch-common-keymap`?

2020-12-24 16:21 UTC, brabalan commented
Regarding the `C-h` mapping, they are from my config. I no longer need them so I'll close the issue.

2020-12-24 16:26 UTC, brabalan commented
I confirm the capture finalization works. I have found another place where bindings seem to be missing: the calendar view when doing a `org-read-date` (for instance to schedule a task). I'm used to do `C-h` to go to the previous day, `C-l` to the next day, `C-j` to the next week, and `C-k` to the previous week. I think this comes from evil-collection. Is this the right place to report such discrepancies?

2020-12-24 16:41 UTC, gagbo commented
> I confirm the capture finalization works. I have found another place where bindings seem to be missing: the calendar view when doing a `org-read-date` (for instance to schedule a task). I'm used to do `C-h` to go to the previous day, `C-l` to the next day, `C-j` to the next week, and `C-k` to the previous week. I think this comes from evil-collection. Is this the right place to report such discrepancies?

I don't know what the default keys are supposed to be, it looks like (from running `org-schedule`) that those movements are on `M-{ctsr}` now

2020-12-24 16:45 UTC, brabalan commented
`M-{ctsr}` does work, thanks.

2020-12-24 16:46 UTC, brabalan commented
The keymap reverse suggestion on discord fixes notmuch.

2020-12-27 11:02 UTC, brabalan commented
One crucial binding to deal with is one for `org-ctrl-c-ctrl-c`. I use it a lot to evaluate code blocks. Right now, it is said to be bound as:
```
Key Bindings
org-mode-map C-c C-c
```
but I have `org-shiftleft` bound to `C-c`. I think `org-shiftleft` is less useful, and binding it to `C-l` could make sense.

2020-12-27 12:06 UTC, gagbo commented
> 
> 
> One crucial binding to deal with is one for `org-ctrl-c-ctrl-c`. I use it a lot to evaluate code blocks. Right now, it is said to be bound as:
> 
> ```
> Key Bindings
> org-mode-map C-c C-c
> ```
> 
> but I have `org-shiftleft` bound to `C-c`. I think `org-shiftleft` is less useful, and binding it to `C-l` could make sense.

I keep forgetting about that, thanks for reminding me. The issue is that evil-org has the nicest API to map the "movement keys", and I forget that `C-c C-c` has such a predominant place in org-mode. I think I’ll manually add a hook to override the movement keys just for `C-c`, and maybe make it an option so users can choose whether they want it or not

2020-12-29 14:18 UTC, brabalan commented
In org-mode there is a conflict between `evil-redo` and `org-shiftright`: both are bound to `C-r`.

`evil-redo`:
```
evil-collection-evil-normal-state-map-backup-map C-r
evil-normal-state-map C-r
```

`org-shiftright`:
```
evil-org-mode-map <insert-state> C-r
evil-org-mode-map <normal-state> C-r
org-mode-map <S-right>
```

2021-01-01 11:09 UTC, brabalan commented on modules/input/layout/+bepo.el
>      (after! (evil org evil-org)
Are you sure you want all this in the `after!`? For me the changes are not applied when I start emacs, but they are if I evaluate this code block.

2021-01-01 13:11 UTC, gagbo commented on modules/input/layout/+bepo.el
>      (after! (evil org evil-org)
That should at least be `after evil-org`, but it can just be added in the map! call as well. I guess I got used to using `after!` and just put everything

2021-01-01 15:20 UTC, brabalan commented
I just noticed this error in my logs (it happened when I started an org capture): `evil-collection: error setting key in pdf-view-mode-map (error "Key sequence s b starts with non-prefix key s")`

2021-01-02 09:33 UTC, brabalan commented
Small suggestion: since you are leaving `C-c` alone for org-mode, it could be also the case for the org-capture map (at the moment capture is confirmed with `C-l C-c`).

2021-01-02 09:42 UTC, brabalan commented
I just found a small bug. In eshell, `c` is still bound to `evil-collection-eshell-evil-change`.

And please let me know if you prefer that I report such small issues in another way.

2021-01-02 10:16 UTC, brabalan commented
Another small bug: in `swipper` mode (`SPC S S`), both `C-t` and `C-s` go to the next item. I expect `C-s` to go to the previous one.

2021-02-25 19:20 UTC, hlissner approved these changes

2021-02-25 19:21 UTC, merged

2021-02-25 19:22 UTC, hlissner commented
Looks good to me! Thanks again for your help!