Do not panic when xclip is not available
hlissner/doom-emacs pull request #4433
Opened 2020-12-14 21:45 UTC by yangsheng6810

`(xclip-mode +1)` will raise an error when `xlip` is not found, which can interrupt the whole initialization process.

2020-12-14 21:47 UTC, hlissner requested changes
Please use `(ignore-errors (xclip-mode +1))` instead

2020-12-14 21:55 UTC, hlissner commented
Actually, it'd be better to do

```elisp
(and (require 'xclip nil t)
     (with-demoted-errors "%s" (xclip-mode +1)))
```

So the issue is visibly logged to \*Messages\*.

2020-12-14 22:40 UTC, yangsheng6810 commented
Force push as suggested.

2020-12-15 00:40 UTC, hlissner approved these changes

2020-12-15 09:14 UTC, merged

2020-12-15 09:14 UTC, hlissner commented
Thanks!