Markdown: add keymap for insert commands
hlissner/doom-emacs pull request #4488
Opened 2020-12-27 03:07 UTC by NathanLovato

This PR adds ~20 insert commands leader keybindings to markdown (inserting headings, code blocks...) with descriptions.

Looks like this:

![Screenshot from 2020-12-26 21-07-11](https://user-images.githubusercontent.com/12694995/103163058-59bf4e00-47be-11eb-903a-c88c06058b2a.png)

Let me know if I should change anything!

2021-01-03 23:10 UTC, hlissner requested changes

2021-01-03 23:10 UTC, hlissner commented on modules/lang/markdown/config.el
> +         :desc "Table Of Content" "t" #'markdown-toc-generate-toc
There appears to be two keybinds for `t`. Perhaps the TOC keybind should be under `SPC m i T` instead?

2021-01-04 00:50 UTC, NathanLovato commented
Thanks, just addressed it.

2021-01-09 08:12 UTC, hlissner approved these changes

2021-01-09 08:23 UTC, merged

2021-01-09 08:23 UTC, hlissner commented
Thanks!