Improving snippet lookup behavior
hlissner/doom-emacs pull request #4511
Opened 2021-01-07 08:14 UTC by samwhitlock

This enables snippets to be accessed by UUID in parent modes of the
current mode. Prior behavior was to only look up for the current mode,
but the active modes (and those suggested in the prompt) include
parent-mode snippets (e.g., text-mode snippets when major-mode is org-mode).

The method `+snippet--get-exact-template-by-uuid` was a necessary clone of `yas--get-template-by-uuid` because the latter method does not handle lookups for modes that don't have any loaded tables that may be a parent of the queried mode.

For example, folks may have snippets in org mode and text mode, but the mode / parent order produces by `yas-modes-to-activate` adds outline mode between, which likely does not have a table.

# testing

I tested a few modes by calling `+snippets/edit` to ensure that snippets for the `major-mode` were found (prior behavior) _and_ that snippets for parent modes were found. Specifically, I tested (in my config):

* org-mode (parent being text-mode and fundamental mode)
* cc-mode (parent being prog-mode and fundamental mode)

2021-01-07 09:12 UTC, hlissner requested changes

2021-01-07 09:12 UTC, hlissner commented on modules/editor/snippets/autoload/snippets.el
> +     for template = (+snippet--get-exact-template-by-uuid active-mode uuid)
Would you mind inlining `+snippet--get-exact-template-by-uuid` here? e.g.

```elisp
(defun +snippet--get-template-by-uuid (uuid &optional mode)
  "Look up the template by uuid in child-most to parent-most mode order.
Finds correctly active snippets from parent modes (based on Yas' logic)."
  (cl-loop with mode = (or mode major-mode)
           for active-mode in (yas--modes-to-activate mode)
           if (gethash active-mode yas--tables)
           if (gethash uuid (yas--table-uuidhash it))
           return it))
```

2021-01-07 10:42 UTC, samwhitlock commented on modules/editor/snippets/autoload/snippets.el
> +     for template = (+snippet--get-exact-template-by-uuid active-mode uuid)
Absolutely! This is much cleaner and I'm glad to have learned a bit more about this cl-loop construct!

2021-01-09 04:59 UTC, hlissner approved these changes

2021-01-09 08:22 UTC, merged

2021-01-09 08:22 UTC, hlissner commented
Thanks!