add selectrum module
hlissner/doom-emacs pull request #4519
Opened 2021-01-15 19:07 UTC by jethrokuan

Been meaning to try selectrum, decided to package it as a doom module. Still WIP.

2021-01-15 23:53 UTC, hlissner requested changes
We'll need selectrum-powered-alternatives for `+ivy/project-search`, `+ivy/project-search-from-cwd`, and a project-wide search+replace workflow to replace `SPC s p` + `C-c C-e`.

Reaching parity with our ivy module is important, so it's unlikely that this PR (or any selectrum PR) will be merged soon, but it will be a helpful reference when I get around to it.

2021-01-15 23:53 UTC, hlissner commented on modules/completion/selectrum/config.el
> +(when (featurep! +prescient)
Use `use-package!`'s `:when` instead of surrounding the `use-package` in a `when` form. e.g.

```diff
-(when (featurep! +prescient)
   (use-package! selectrum-prescient
+    :when (featurep! +prescient)
     :after selectrum
     :hook ((doom-first-input . selectrum-prescient-mode)
            (doom-first-input . prescient-persist-mode))))
```

2021-01-15 23:53 UTC, hlissner commented on modules/completion/selectrum/config.el
> +(use-package! consult-flycheck)
Lazy load this package.

2021-01-15 23:53 UTC, hlissner commented on modules/completion/selectrum/config.el
> +(use-package! embark
Lazy load this package.

2021-01-15 23:53 UTC, hlissner commented on modules/completion/selectrum/packages.el
> +(package! marginalia)
Pin these packages.

2021-01-15 23:53 UTC, hlissner commented on modules/completion/selectrum/config.el
> +           (doom-first-input . prescient-persist-mode))))
Attach these modes to `selectrum-mode-hook`, rather than `doom-first-input-hook`.

2021-01-16 06:11 UTC, loafofpiecrust commented
`consult` now has `consult-ripgrep` and `consult-find` which bring us much closer to parity with the ivy module. There's just a few missing I think, like jumping to symbol in the project. I was actually planning on making a PR this weekend but here's my [code so far](https://github.com/loafofpiecrust/dotfiles/tree/main/emacs/.config/doom/modules/completion/selectrum). I've bound more consult commands and got embark working with which-key more effectively.

2021-01-16 12:30 UTC, jethrokuan commented
I've added a function for selectrum project search in this PR.

2021-01-16 13:04 UTC, loafofpiecrust commented
What does your custom function for project search do that `consult-ripgrep` doesn't? I think we should focus on making that function great, if they're missing something not doom specific to make a PR to consult.

2021-01-16 13:15 UTC, jethrokuan commented
> What does your custom function for project search do that consult-ripgrep doesn't?

It's doom-specific stuff:
- whether to search in hidden files
- which directory to search in
- Making the prompt more meaningful

These are mainly so that the signature of the functions align with that of ivy and helm, I suppose.

2021-01-16 16:24 UTC, loafofpiecrust commented
- You can change consult-ripgrep-command to set whether to search hidden files.
- you can pass the directory as first argument into consult-ripgrep or consult-find
- I agree that "Ripgrep in project X" could maybe use improvement, but that doesn't feel worth a redefinition here.

It seems like `(consult--grep "Search" '("rg" "--whatever") custom-directory nil)` gives you most of this, no?

2021-01-16 17:44 UTC, jethrokuan commented
> It seems like (consult--grep "Search" '("rg" "--whatever") custom-directory nil) gives you most of this, no?

That's exactly how it's implemented now.

2021-01-17 05:10 UTC, loafofpiecrust commented
Totally my bad, I looked first on my phone and clearly didn't read the code closely enough.

2021-01-20 03:29 UTC, Townk reviewed
I have Selectrum & friends working on my personal config, so I though that I could point some things that stood out for me on this PR.

2021-01-24 13:54 UTC, minad commented
@loafofpiecrust @jethrokuan I am looking forward to seeing the Selectrum/Consult/Embark suite of packages in Doom. Please let me know if you need anything on the side of Consult. I saw that you are offering a modified project search command here. Maybe some things should be exposed better on the Consult side to reduce the amount of code needed here? You are setting the `consult-project-root-function`; you should already get a project search which works out of the box. But maybe not as full featured as what you are implementing here?

2021-01-24 13:59 UTC, minad commented on modules/completion/selectrum/config.el
> +(use-package! selectrum
Setting separate refine and highlight functions is *not necessary* since Selectrum picks up the completion style, see https://github.com/raxod502/selectrum/pull/330. However you should still set them in order to improve performance, since then Selectrum is applying highlighting only to the items which match the filter criterion! Note that the combination of Orderless and Prescient is a bit fragile since both packages compete about the filtering. I haven't checked what you are doing here, but selectrum-prescient-mode should be activated first, then orderless should overwrite the filter/highlighting functions. Furthermore orderless should be set as completion style.

2021-01-24 14:01 UTC, minad commented on modules/completion/selectrum/config.el
> +    :hook ((selectrum-mode . selectrum-prescient-mode)
See my comment above, about the order of selectrum-prescient-mode and orderless.

2021-01-24 14:04 UTC, minad commented on modules/completion/selectrum/config.el
> +(use-package! orderless
It should be installed as completion-style, I recommed against loading it lazily.

2021-01-24 14:09 UTC, jethrokuan commented
fwiw my usage of the selectrum/consult/embark suite has been very minimal, and I'm likely to have gotten many things wrong here. Perhaps someone with more experience can provide a better PR.

2021-01-24 17:47 UTC, bdarcus commented
FWIW, looks like a selectrum port of ivy/helm-bibtex should be coming soon.

https://github.com/tmalsburg/helm-bibtex/issues/353

2021-01-25 21:03 UTC, Townk commented on modules/completion/selectrum/config.el
> +    :hook ((selectrum-mode . selectrum-prescient-mode)
If you don't enable `selectrum-prescient-mode`, you can use prescient sorting plus storing with orderless filter and highlights with no problem. If the user don't want this combination, then you don't need to worry as I comment, but overall, my suggestion is to get this decision path:

```emacs-lisp
(cond ((and (featurep! +prescient) (featurep! +orderless)) (set-functions-manually))
       ((featurep! +prescient) (enable-selectrum-prescient-mode))
       ((featurep! +orderless) (only-enable-orderless)))
```

So, the `use-package!` for `selectrum` would be something like this:

```emacs-lisp
(use-package! selectrum
  :init
  (when (and (featurep! +prescient) (featurep! +orderless))
    (setq selectrum-refine-candidates-function #'orderless-filter 
          selectrum-highlight-candidates-function #'orderless-highlight-matches 
          selectrum-preprocess-candidates-function #'selectrum-prescient--preprocess)

    (add-hook 'selectrum-candidate-selected-hook #'selectrum-prescient--remember)
    (add-hook 'selectrum-candidate-inserted-hook #'selectrum-prescient--remember))
  :config
  ;; other configurations...
  )
```

And `selectrum-prescient` would be:

```emacs-lisp
(use-package! selectrum-prescient
    :if (featurep! +prescient) 
    :after selectrum
    : init
    (when (not (featurep! +orderless))
      (add-hook 'selectrum-mode-hook 'selectrum-prescient-mode))
    :config
    ;; other configurations
    )
```

2021-01-25 21:19 UTC, Townk commented on modules/completion/selectrum/config.el
> +(use-package! orderless
Just for context, this is the `use-package! orderless` section on my config:

```emacs-lisp
(use-package! orderless
  :defer t
  :init
  (setq orderless-component-separator "[ &]"
        orderless-matching-styles '(orderless-prefixes
                                    orderless-initialism
                                    orderless-regexp))
  :custom
  (completion-styles '(orderless))
  :config
  (custom-set-faces!
    '('orderless-match-face-0 :background "#435300" :foreground "#b5bd68")
    '('orderless-match-face-1 :background "#4C2E60" :foreground "#b294bb")
    '('orderless-match-face-2 :background "#644E00" :foreground "#f0c674")
    '('orderless-match-face-3 :background "#1B2E47" :foreground "#81a2be"))

  (add-hook 'minibuffer-exit-hook #'orderless-remove-transient-configuration))
```

2021-01-25 21:27 UTC, minad commented on modules/completion/selectrum/config.el
> +(use-package! orderless
I just checked, the orderless completion style and its corresponding completion style functions are indeed marked as autoload. Lazy loading works indeed :+1:

2021-01-29 22:05 UTC, gagbo commented on modules/completion/selectrum/autoload/selectrum.el
> +                         (mapconcat #'shell-quote-argument args " ")))
Why is there a space in front of `--hidden` but not `--maxdepth 1` or `--null` ?

2021-01-30 19:54 UTC, Townk commented
Hy @jethrokuan, would you be able to commit a new patch with the requested changes, or do you prefer one of us to take over?

2021-01-31 14:46 UTC, jcf commented
I've been using Selectrum, Orderless, Consult, and Embark for the last couple of weeks, and I'm loving it. I've found a few useful snippets in this pull request and in various repos that I thought I'd share: https://gist.github.com/jcf/ac6f57a5b0c49263619e4d2ee4a0c00a

I see [Jethro mentioned](https://github.com/hlissner/doom-emacs/pull/4519#issuecomment-766354286) someone with more experience might want to take the reigns on this pull request. While I'm not sure that's me I'd be happy to help test out any changes, and will keep sharing any useful code I add to my own configuration.

2021-01-31 17:41 UTC, jethrokuan commented
> Hy @jethrokuan, would you be able to commit a new patch with the requested changes, or do you prefer one of us to take over?

Do make another pull request, I started this because I was surprised to see that none has been made yet. My time is tied working on org-roam.

2021-01-31 18:18 UTC, Emiller88 commented
@Townk I think it sounds like you might be the best to take over, and then people and PR to your branch. Do you have a link to your personal config btw?

2021-01-31 20:06 UTC, Townk commented
> @Townk I think it sounds like you might be the best to take over, and then people and PR to your branch. Do you have a link to your personal config btw?

I'm working on a refactor for my config after my 1000th bankruptcy :P, but you can follow along here: https://github.com/Townk/doom-emacs-private

I'm trying a literate config this time. Let's see if I can finish.

Regarding the PR, let me work a bit on it today and see where I can get with it. Most likely I will need two PRs in order to get Selectrum fully working, and I won't push anything until later tonight or tomorrow morning (my 2 and 4 yo kids usually get in the way of such things).

2021-02-10 10:42 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq completion-styles '(orderless)))
Here one may consider `'(substring orderless)` which ensures that TAB prefix completion works under more circumstances. Since substring matches a subset of orderless, this generally works well. Furthermore one could even set `'(basic substring orderless)`, but in this case basic matches strictly less, so this can lead to unexpected behavior but ensures that matches with the current prefix are preferred.

2021-02-14 21:00 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq completion-styles '(orderless)))
The current recommended Selectrum+Orderless configuration is as follows, which is compatible with completion styles and optimizes orderless highlighting.

~~~ elisp
(setq orderless-skip-highlighting (lambda () selectrum-active-p))
(setq selectrum-highlight-candidates-function #'orderless-highlight-matches)
~~~

2021-02-18 12:04 UTC, bdarcus commented
> Most likely I will need two PRs in order to get Selectrum fully working ...

So @Emiller88 opened up a new PR for selectrum in #4664. 

But we need another for the workspace module, to [replace persp-mode with perspective](https://github.com/Townk/doom-emacs-private/blob/master/config.org#workspaces)?

2021-02-18 12:18 UTC, minad commented
@bdarcus Regarding Selectrum and Persp-Mode, I wonder why there is a problem. Selectrum is not doing anything out of the ordinary, relying on nothing else than the minibuffer. Did you open an issue on the perp-mode repository or the Selectrum repository?

2021-02-18 12:28 UTC, bdarcus commented
> @bdarcus Regarding Selectrum and Persp-Mode, I wonder why there is a problem. Selectrum is not doing anything out of the ordinary, relying on nothing else but the minibuffer. Did you open an issue on the perp-mode repository or the Selectrum repository?

No; I'm not familiar with the details. Was just summarizing the status, based on what @townk concluded. Perhaps he could submit a bug report?

I did find that the current code project search functionality doesn't work correctly though. Maybe that has something to do with it?

2021-02-19 03:00 UTC, jethrokuan commented
Closing in favour of #4664

2021-02-19 03:00 UTC, closed without merging