Improved Helm module
hlissner/doom-emacs pull request #4561
Opened 2021-01-22 19:36 UTC by elken

+ Added README
Mostly based on ivy, but I tested locally
+ Added posframe
Might need to tidy up the code a bit (at your behest) but it at least works now
+ Added icons
There's currently a bug with `helm-icons` I'm trying to fix with the `all-the-icons` backend, but the `treemacs` backend should work fine

Likely to be the first of many but I know you're not very busy ;)

2021-02-08 04:39 UTC, hlissner requested changes

2021-02-08 04:39 UTC, hlissner commented on modules/completion/helm/config.el
> +  (helm-icons-enable))
Put `:config` before `(helm-icons-enable)`

2021-02-08 04:39 UTC, hlissner commented on modules/completion/helm/config.el
> +
Add another blank newline before `helm-icons`' `use-package!` block, for consistency.

2021-02-08 04:39 UTC, hlissner commented on modules/completion/helm/config.el
> +              helm-posframe-poshandler +helm-posframe-handler)
There's no compelling reason to have this indirection anymore. Set `helm-posframe-parameters` and `helm-posframe-poshandler` to the values of `+helm-posframe-parameters` and `+helm-posframe-handler` here, directly, and remove the latter variables.

2021-02-08 04:39 UTC, hlissner commented on modules/completion/helm/packages.el
> +  (package! helm-posframe :pin "b107e64eedef6292c49d590f30d320c29b64190b"))
Is there a reason to switch to `helm-posframe`? Doom used to use it, but I opted out of it because of general bugginess -- it was simpler to DIY.

2021-02-08 04:54 UTC, elken commented on modules/completion/helm/packages.el
> +  (package! helm-posframe :pin "b107e64eedef6292c49d590f30d320c29b64190b"))
I was trying to create a 1:1 experience between Helm and Ivy but yes I agree with you. 

When I get some time I'll see if I can fix any of it but for the sake of this I might remove for now

2021-02-08 04:54 UTC, elken commented
Thanks for reviewing, I'll make the changes in the next day or so

2021-02-16 19:08 UTC, elken commented
Removed helm-posframe, probably for good

2021-02-24 16:02 UTC, hlissner approved these changes

2021-02-24 16:02 UTC, merged

2021-02-24 16:02 UTC, hlissner commented
Looks good to me! Thanks!