Add Selectrum module Round 2
hlissner/doom-emacs pull request #4664
Opened 2021-02-16 23:12 UTC by Emiller88

This is a work in progress, to quote the great @mjlbach "be the PR you want to see in the repo".

The only thing I take credit for so far is pinning the packages and copying and pasting @Townk's config ontop of @jethrokuan's PR (#4519) so I'll only take it personally if you rip up the way I pinned the repos.

2021-02-16 23:17 UTC, ymarco commented on modules/completion/selectrum/config.el
> +    (use-package! selectrum-prescient
Could use `(use-package! ... :when (featurep! ...))` to save one nesting level.
I'm not sure if nested `use-package`s are good practice though.

2021-02-17 00:56 UTC, Emiller88 commented on modules/completion/selectrum/config.el
> +    (use-package! selectrum-prescient
I think you're right, it should be after `selectrum` instead

2021-02-17 15:40 UTC, bdarcus commented
I'm a newbie on this ecosystem of packages, but would `consult-ripgrep` be useful somewhere here?

2021-02-17 16:06 UTC, Emiller88 commented
> I'm a newbie on this ecosystem of packages, but would `consult-ripgrep` be useful somewhere here?

I think that's what `+selectrum-file-search` is aiming to replace.

2021-02-17 19:23 UTC, bdarcus commented
> I think that's what `+selectrum-file-search` is aiming to replace.

OIC; thanks.

I just quickly tested the branch. It seems that marginalia didn't load, and I needed to manually activate it.

2021-02-17 21:44 UTC, bdarcus commented on modules/completion/selectrum/TODO.org
> +** TODO Add vanilla keybindings
```suggestion
** TODO Add vanilla keybindings
*** TODO Add keybinding for embark-act
```

2021-02-19 14:56 UTC, bdarcus commented on modules/completion/selectrum/TODO.org
> +*** TODO Add keybinding for embark-act
```suggestion
```

I think I missed this earlier; the binding is there now at least.

2021-02-19 15:05 UTC, Emiller88 commented on modules/completion/selectrum/TODO.org
> +*** TODO Add keybinding for embark-act
On evil yes, but is it there on vanilla?

2021-02-19 15:10 UTC, bdarcus commented on modules/completion/selectrum/TODO.org
> +*** TODO Add keybinding for embark-act
> On evil yes, but is it there on vanilla?

Oh, IDK.

Is there a difference in this context, where you are invoking the command on a selected candidate?

2021-02-19 15:23 UTC, bdarcus commented on modules/config/default/+evil-bindings.el
> +        "C-c C-c" #'embark-act-noexit
This command has been removed. 

https://github.com/oantolin/embark/#breaking-news

> The command embark-act-noexit has been removed and a variable embark-quit-after-action now controls whether embark-act quits the minibuffer or not.

2021-02-19 15:25 UTC, Emiller88 commented on modules/completion/selectrum/TODO.org
> +*** TODO Add keybinding for embark-act
It's a difference in keybindings, `evil` vs `emacs`. I haven't added any to emacs yet, just been adding them to evil.

2021-02-19 15:26 UTC, Emiller88 commented on modules/config/default/+evil-bindings.el
> +        "C-c C-c" #'embark-act-noexit
Thanks, I'll add this in a bit!

2021-02-19 15:53 UTC, bdarcus commented
As I'm playing with the module, another little thing, which I'm not sure about:

By default, `embark-collect-snapshot` brings up a buffer with a simple list view, without any highlighting.

But one can set this [defcustom](https://github.com/oantolin/embark/blob/master/embark.el#L973) to use the `zebra` view instead, which seems like it would be better?

2021-02-19 15:59 UTC, Emiller88 commented
Could you drop a screenshot of the difference? Should just be `(setq embark-collect-initial-view-alist ...)` away, but what values are you using?

2021-02-19 16:18 UTC, bdarcus commented
> Could you drop a screenshot of the difference? Should just be `(setq embark-collect-initial-view-alist ...)` away, but what values are you using?

Lemme experiment a bit and get back to you.

2021-02-20 02:44 UTC, bdarcus commented
> Lemme experiment a bit and get back to you.

Maybe I'm just missing something (say interaction between font faces and themes?), but I can't see any difference between the views. So maybe just skip this.

2021-02-21 10:26 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
consult--grep is not a command. Why do you overwrite this-command? Should not be necessary.

2021-02-21 10:27 UTC, minad commented on modules/completion/selectrum/config.el
> +        selectrum-fix-minibuffer-height t)
selectrum-fix-minibuffer-height has been deprecated.

2021-02-21 10:28 UTC, minad commented on modules/completion/selectrum/config.el
> +        selectrum-refine-candidates-function #'orderless-filter))
The selectrum-refine-candidates-function should not be set. Only selectrum-highlight-candidates-function is necessary in order to get highlighting, when orderless-skip-highlighting is set.

2021-02-21 10:33 UTC, minad commented
When grepping the doom-emacs codebase for `ivy-read` there seem to be a few other places where a `completing-read` implementation is missing and there are also a few TODO marks.

2021-02-21 16:00 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  :hook (doom-first-input . marginalia-mode)
This is saying to load marginalia after selectrum; right?

But note: I have to manually turn on marginalia-mode.

2021-02-21 16:04 UTC, minad commented on modules/completion/selectrum/config.el
> +  :hook (doom-first-input . marginalia-mode)
It is important that `marginalia-mode` is turned on automatically. Otherwise it won't add completion categories and annotations to existing commands. This is important for Embark which uses the completion category to associate the minibuffer action keymap.

2021-02-21 20:28 UTC, Emiller88 commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
Not sure, I didn't write it and can't get it to work for me :man_shrugging: Which is really slowing my development down on this because file `+ivy-file-search` is the foundation of my text-editing experience.

It looks like to me, they were trying to mimic what was done in `+ivy-file-search`, which uses `counsel-rg`. Any pointers you might have on this would be helpful.

2021-02-21 20:37 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
My suggestion would be to get started with a simpler version based on `consult-ripgrep`. And then extend it step by step until you have all the functionality you want for `+selectrum-file-search`.

2021-02-21 20:37 UTC, Emiller88 commented on modules/completion/selectrum/config.el
> +  :hook (doom-first-input . marginalia-mode)
@minad So, it's not clear should it be after selectrum or not?

2021-02-21 20:41 UTC, minad commented on modules/completion/selectrum/config.el
> +  :hook (doom-first-input . marginalia-mode)
This does not matter. It should only be loaded before the first minibuffer interaction. Activating Selectrum and Marginalia on first input sounds okay.

2021-02-21 20:42 UTC, Emiller88 commented
@minad I appreciate the review! Few questions on either and I'd love any further input you have.

2021-02-21 20:46 UTC, Emiller88 commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
I appreciate the advice that definitely gets me working faster!

2021-02-21 20:47 UTC, Emiller88 commented on modules/completion/selectrum/config.el
> +  :hook (doom-first-input . marginalia-mode)
Gotcha, I'll resolve this since it looks good to me then.

2021-02-22 12:44 UTC, bdarcus commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
Note earlier offer from @minad to tweak `consult-ripgrep` (I think) to better support doom's project search functionality, if helpful.

https://github.com/hlissner/doom-emacs/pull/4519#issuecomment-766351863

2021-02-22 13:12 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
> Note earlier offer from @minad to tweak consult-ripgrep (I think) to better support doom's project search functionality, if helpful.

We can modify/extend consult-ripgrep as long as it reasonably fits into the Consult picture. However if you want to replicate the ivy project search behavior in Doom or have very Doom-specific requirements (it looks like this), it does not make sense to add the command in the given form to the Consult package.

2021-02-22 15:35 UTC, bdarcus commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
> We can modify/extend consult-ripgrep as long as it reasonably fits into the Consult picture. However if you want to replicate the ivy project search behavior in Doom or have very Doom-specific requirements (it looks like this), it does not make sense to add the command in the given form to the Consult package.

Sure. 

But in any case, it's worth using `consult-ripgrep` for both `+selectrum-file-search` and `+selectrum-project-search`, right?

I had asked about up that above.

2021-02-22 15:51 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
I think consult--grep ist more appropriate since it allows setting the command string.

2021-02-22 21:31 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  (setq selectrum-highlight-candidates-function #'orderless-highlight-matches)
```suggestion
  (setq selectrum-highlight-candidates-function #'orderless-highlight-matches))
```
Syntax error ;-)

2021-02-22 21:34 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  :hook (doom-first-input . marginalia-mode)
> Gotcha, I'll resolve this since it looks good to me then.

It looks good to me too, but doesn't work on my end. Does it on your's?

2021-02-22 21:50 UTC, Emiller88 commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
I agree with @minad on using `consult--grep` but I've cut it down to just `consult-ripgrep` for now @bdarcus. Open to anyone who wants to beat me to figuring it out.

2021-02-23 05:13 UTC, jethrokuan commented
Why is `+selectrum-file-search` reverted to `consult-ripgrep`? Wouldn't it then fail to handle `+fuzzy`, and also searching the correct directory?

2021-02-23 14:30 UTC, bdarcus commented
I've run into what I guess is some sort of keybinding conflict, explained here:

https://github.com/tmalsburg/helm-bibtex/pull/355#issuecomment-784224200

To summarize: 

If one runs `embark-act` via the `C-o` keybinding defined here from selectrum, it works; it correct invokes the command.

But if one from there runs `embark-collect-snapshot` (`S`) and goes to that collect buffer, the same keybinding doesn't work in that context. You have to do `M-x embark-act` to access the commands.

2021-02-23 16:06 UTC, bdarcus commented
> Why is `+selectrum-file-search` reverted to `consult-ripgrep`? Wouldn't it then fail to handle `+fuzzy`, and also searching the correct directory?

See the sub-thread above @jethrokuan:

https://github.com/hlissner/doom-emacs/pull/4664#discussion_r579785461

It's just temporary.

2021-02-24 04:18 UTC, Emiller88 commented
> Why is `+selectrum-file-search` reverted to `consult-ripgrep`? Wouldn't it then fail to handle `+fuzzy`, and also searching the correct directory?

I couldn't get your version to work locally the first time I tried it, so I was using a combination of pieces that others had written, but kept not getting anywhere, so I took @minad's advice and cut it down. Anyways, I gave yours another go to confirm, and it appears to be working now.

2021-02-24 05:47 UTC, jethrokuan commented
I didn't really know what I was doing wrt to the `this-command` override either, but it was working for me then 🤷 . Maybe it's safe to remove that clause.

2021-02-24 09:39 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +    (consult--grep prompt ripgrep-command directory query)))
I don't believe that this command works as is. You pass `ripgrep-command` which is a list, however I changed this such that `consult--grep` accepts a shell quoted string now. Please take a look at `consult-ripgrep-command` for reference. I think @jethrokuan wrote this command a longer while ago.

2021-02-28 15:59 UTC, bdarcus commented
Not sure if this is just a problem with my install, but if I add this to my private config file, so as to bind a keymap to `embark-act`, I get a void symbol error:

``` elisp
(add-to-list 'embark-keymap-alist '(bibtex . bibtex-completion-map))
```

To fix it, I have to add `(use-package! embark)` to the config file.

2021-02-28 18:12 UTC, bnjmnt4n commented
I believe you can use the `after!` macro: something like `(after! embark (...))`.

2021-02-28 21:31 UTC, bdarcus commented
I was just reading discord, and saw @Emiller88's wrote the following. 

> And I need help on the marginila and embark side, still trying to wrap my head around what's the point of them beyond just covering the ivy stuff.

In case this might be helpful for the docs:

On "the point": marginalia adds annotations to commands in emacs, so in that sense obviously enhances things like `M-x` with command descriptions and such.

But (I think) those annotations can also provide helpers to embark, which is described as conceptually like a contextual menu, which I think is a good description. 

Its core value is it allows you to bind commands (via `embark-act`) to completion categories.

So, for example, I'm working on a PR for bibtex-completion, that turns its functions (used in helm-bibtex and ivy-bibtex via helm and ivy wrappers) into interactive commands.

If I simply add the keymap to an embark alist variable, those commands are contextually available whenever searching items of category "bibtex", without having to do anything else.

And so, you'll note the available actions changes depending on what category of completion you are doing.

There are other cool aspects too, like `embark-collect-snapshot`, which is similar to `ivy-occur`; it allows you to pull out some subset of candidates, and run actions on them.

2021-03-03 16:22 UTC, Emiller88 commented on modules/completion/selectrum/autoload/selectrum.el
> +    (consult--grep prompt ripgrep-command directory query)))
Gotcha, are we pinned to an earlier commit than when you introduced that?

2021-03-03 16:23 UTC, bdarcus commented
I think there may be some theme font face conflict, as I don't see the match highlighting I see on this example from the selectrum README, which I believe should be on by default.

![highlighting](https://github.com/raxod502/selectrum/raw/55fffe21e5708443342d720eb940f1cc7a12f52b/images/commands.png)

2021-03-03 16:28 UTC, Emiller88 commented
@bdarcus See here for discussion on the themes https://github.com/hlissner/emacs-doom-themes/pull/574

You shouldn't get the same thing out of the box unless the screenshot was using doom-themes. But I think it's a good goal.

2021-03-03 16:31 UTC, bdarcus commented
I wasn't expecting the same; I just don't see anything.

2021-03-03 16:33 UTC, Emiller88 commented
Can you screenshot what you see? What theme are you on?

2021-03-03 16:42 UTC, bdarcus commented
> Can you screenshot what you see? What theme are you on?

Yep; below?

Hmm, is it there, but just so subtle (one shade of gray very close to another) that hard to notice?

![sel-fonts](https://user-images.githubusercontent.com/1134/109839620-493faf80-7c15-11eb-8b99-9207c11caa8b.jpeg)

2021-03-03 16:46 UTC, Emiller88 commented
So we're seeing different things. What commit are you on for doom-themes?

On a fresh start(on `doom-one`):
![image](https://user-images.githubusercontent.com/20095261/109840285-e1eb2500-7c3f-11eb-9c8c-c1264eb8225e.png)

2021-03-03 16:50 UTC, bdarcus commented
That looks perfect.

I'm just on your branch, and haven't updated beyond that.

I'll look into it on my end.

2021-03-03 16:53 UTC, Emiller88 commented
I have doom-themes unpinned, I'm guessing that's what your issue is. Let me bump the package in the PR.

2021-03-03 16:56 UTC, Emiller88 commented
Alright it should be on the right commit of `doom-themes` now. If anyone knows a better workflow to rebase this PR than force push with lease, let me know.

2021-03-03 17:11 UTC, bdarcus commented
And while we're at it on git questions, can someone tell me how best to update @Emiller88's branch?

If I do this, I get a merge conflict:

``` console
git pull git@github.com:hlissner/doom-emacs.git refs/pull/4664/head
```

2021-03-04 11:00 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +    (consult--grep prompt ripgrep-command directory query)))
Probably. Please don't pin to an outdated commit. I recently released 0.6. you may want to.pin to that version. But note that there is still development going on. My suggestion would be to pin the packages here right before the PR gets merged.

2021-04-15 21:21 UTC, jcf commented
I'm in the process of merging my private Selectrum configuration on top of this awesome work, and have a few (subjective) niceties that I thought worth sharing.

With `+orderless`, Selectrum uses Orderless to highlight matches, but with this I get Orderless filter logic, which I've become quite accustomed to.

``` emacs-lisp
(setq selectrum-refine-candidates-function #'orderless-filter)
```

I've added even more annotations to Projectile via Marginalia by detecting Projectile's prompts. Maybe this is possible by hooking into the commands instead.

``` emacs-lisp
(add-to-list 'marginalia-prompt-categories '("Find file" . file))
(add-to-list 'marginalia-prompt-categories '("Switch to project" . file))
```

When I have several matches, I sometimes want to quickly select an option quickly. With the snippet below, I can hit `C-o N` to select the numbered candidate (this only works with up to ten candidates of course).

``` emacs-lisp
(setq selectrum-show-indices t)

(map! :map selectrum-minibuffer-map
      "C-o" #'embark-export

      (:prefix ("C-c" . "C-c")
       "C-c" #'embark-act
       "C-e" #'embark-collect-snapshot

       (:prefix ("C-o" . "select")
        :desc "Select candidate 1"  "1" (cmd! (selectrum-select-current-candidate 1))
        :desc "Select candidate 2"  "2" (cmd! (selectrum-select-current-candidate 2))
        :desc "Select candidate 3"  "3" (cmd! (selectrum-select-current-candidate 3))
        :desc "Select candidate 4"  "4" (cmd! (selectrum-select-current-candidate 4))
        :desc "Select candidate 5"  "5" (cmd! (selectrum-select-current-candidate 5))
        :desc "Select candidate 5"  "5" (cmd! (selectrum-select-current-candidate 5))
        :desc "Select candidate 6"  "6" (cmd! (selectrum-select-current-candidate 6))
        :desc "Select candidate 7"  "7" (cmd! (selectrum-select-current-candidate 7))
        :desc "Select candidate 8"  "8" (cmd! (selectrum-select-current-candidate 8))
        :desc "Select candidate 9"  "9" (cmd! (selectrum-select-current-candidate 9))
        :desc "Select candidate 10" "0" (cmd! (selectrum-select-current-candidate 10)))))
```

I also have a few Embark shortcuts mixed in there that I've been quite enjoying. Maybe someone else has a better way of exporting/acting/snapshotting with Embark?

One small issue I've fixed in https://github.com/jcf/doom-emacs/commit/70fcd4f3b5e71c0b32d1da9a1205ebb075aa32b6… it looks like the `define-key!` ends prematurely in Consult's `use-package!`. I think it should look like this:

``` emacs-lisp
(define-key!
  [remap apropos]                       #'consult-apropos
  [remap bookmark-jump]                 #'consult-bookmark
  [remap evil-show-marks]               #'consult-mark
  [remap goto-line]                     #'consult-goto-line
  [remap imenu]                         #'consult-imenu
  [remap locate]                        #'consult-locate
  [remap load-theme]                    #'consult-theme
  [remap man]                           #'consult-man
  [remap recentf-open-files]            #'consult-recent-file ; <-- the closing paren used to be here
  [remap switch-to-buffer]              #'consult-buffer
  [remap switch-to-buffer-other-window] #'consult-buffer-other-window
  [remap switch-to-buffer-other-frame]  #'consult-buffer-other-frame
  [remap yank-pop]                      #'consult-yank-pop)
```

If I find anything else, I'll post an update here, and I've uploaded my relatively minimal modifications to this [Gist](https://gist.github.com/jcf/d0cd078d86200e4649216e1939e29d6a).

Thank you to everyone for sharing their work on this. Selectrum with Consult, Embark, and Marginalia are proving to be delightful, and I can't wait to see this land in Doom. It's a lot of fun extending Emacs with these amazing libraries!

If there's anything I can do to help, please let me know. Stay safe, y'all!

2021-04-15 21:30 UTC, bdarcus commented
> I've added even more annotations to Projectile via Marginalia by detecting Projectile's prompts. Maybe this is possible by hooking into the commands instead

Does, or should, this line up with embark?

BTW, I started a linked discussion on the embark issue tracker thinking ahead on how to align doom menus with embark act menus. Seems that will depend on an in-progres which-key PR from @loafofpiecrust.

2021-04-16 00:57 UTC, Emiller88 commented
@jcf Thanks I fixed those in a05662edf! 

Thanks for also using this and adding your own modifications through the module system! Feel free to PR anything you want to upstream (maybe `(setq selectrum-refine-candidates-function #'orderless-filter)`) or any fixes!

2021-04-16 05:29 UTC, Townk commented
Hey guys, I'm not sure if you fixed the `selectrum-file-search` already but here is my version of the fixed function:

```emacs-lisp
(cl-defun my-selectrum-file-search (&key query in all-files (recursive t) prompt args)
  "Conduct a file search using ripgrep.
:query STRING
  Determines the initial input to search for.
:in PATH
  Sets what directory to base the search out of. Defaults to the current
  project's root.
:recursive BOOL
  Whether or not to search files recursively from the base directory."
  (declare (indent defun))
  (unless (executable-find "rg")
    (user-error "Couldn't find ripgrep in your PATH"))
  (require 'consult)
  (let* ((this-command 'consult-ripgrep)
         (project-root (or (doom-project-root) default-directory))
         (directory (or in project-root))
         (ripgrep-command (mapconcat #'identity (seq-remove 'null
                                      (append (butlast (split-string consult-ripgrep-command " +"))
                                              (list
                                               (when all-files "-uu")
                                               (unless recursive " --maxdepth 1")
                                               "--hidden"
                                               "-g!.git")
                                              args
                                              '("-e"))) " "))
         (prompt (or prompt
                     (format "%s [%s]: "
                             ripgrep-command
                             (cond ((equal directory default-directory) "./")
                                   ((equal directory project-root) (projectile-project-name))
                                   ((file-relative-name directory project-root))))))
         (query (or query
                    (when (doom-region-active-p)
                      (replace-regexp-in-string
                       "[! |]" (lambda (substr)
                                 (cond ((string= substr " ") "  ")
                                       ((string= substr "|") "\\\\\\\\|")
                                       ((concat "\\\\" substr))))
                       (rxt-quote-pcre (doom-thing-at-point-or-region))))
                    " ")))
    ;; (setq deactivate-mark t)
    (consult--grep prompt ripgrep-command directory query)))
```

2021-04-27 02:50 UTC, minad commented on modules/completion/selectrum/TODO.org
> +Probably due to live preview, but gets much faster on subsequent calls.
You can disable previews or use manual previews for those commands? You may also consider to use manual preview for `consult-grep` or your project search. Maybe you could dedicate a key to manual preview which you use for the commands which perform more expensive previews like opening files.

2021-04-27 02:57 UTC, minad commented on modules/completion/selectrum/TODO.org
> +does something else (give you previously used isearch search terms).
May I suggest you use the plain isearch instead? 

Then there is isearch-mb which enhances isearch to use the minibuffer and allow jumping from candidate to candidate using the up/down navigational keys. See https://github.com/astoff/isearch-mb/blob/main/isearch-mb.el. This package is experimental so I am wary to recommend it yet. It has been discussed if such a feature should be included in Emacs itself. More probably it will become an ELPA/MELPA package at some point.

And then there is the package ctrlf which provides search. I don't think you use that in Doom already. But I don't know much about ctrlf since I am not using it myself. I am sufficiently happy with the isearch which is integrated intimately in Emacs.

2021-04-27 03:00 UTC, minad commented on modules/completion/selectrum/TODO.org
> +In ivy, backspace on =/foo/bar/!= (where =!= is the cursor) leads to =/foo/!=
See `selectrum-fido-backward-updir` on the wiki https://github.com/raxod502/selectrum/wiki/Ido,-icomplete(fido)-emulation. The Selectrum default is to behave like `fundamental-mode` where you can delete words with M-DEL instead of DEL.

2021-04-27 06:26 UTC, sebastiansturm commented on modules/completion/selectrum/TODO.org
> +does something else (give you previously used isearch search terms).
isn't `consult-line` the drop-in replacement for swiper/swoop? That's what I'm using it for and I'm pretty happy with it so far

2021-04-27 06:34 UTC, minad commented on modules/completion/selectrum/TODO.org
> +does something else (give you previously used isearch search terms).
`consult-line` is *mostly* a drop-in replacement, but simpler and more focused than Swiper. A power-user of Swiper user will surely miss some things. Then there is `swiper-isearch` which is something else. It is not line-based but shows a list of matches - it aims to replace isearch. My comment related to `swiper-isearch`.

2021-04-27 06:45 UTC, sebastiansturm commented
I tried this PR out of my addiction to shiny new stuff, and I think it's an excellent alternative to the ivy layer in many respects but I did notice a few ways in which working with it seemed a bit cumbersome or buggy:
* `SPC h t` invokes `consult-theme`, which at least with my config doesn't seem to work well together with doom's modifications to `load-theme`; apart from the fact that themes are selected immediately due to consult's on-by-default autopreview (which would be OK or even a nice feature if it worked well), I never got a consistent set of colors after theme selection; plain vanilla `load-theme`, OTOH, works well. Maybe this is in some way caused by my config; does anyone else see similar issues?
* I think `+default/search-buffer` still calls swiper but IMO should call `consult-line` if the `selectrum` module is in use (or maybe I'm confused about this PR's scope, as this is provided by `consult`, not `selectrum`?)
* I think auto-preview shouldn't be enabled by default because it can come at a high latency cost, especially when buffers are being previewed that invoke heavy-duty language servers or stuff like that; I'm currently setting `consult-preview-key` to `nil`, not sure if that's the preferred way to go
* I think `xref-show-xrefs-function` and `xref-show-definitions-function` should be bound to `consult-xref` (again, unless consult is out of scope for this PR); when bound, this works beautifully in my experience
* I'm sometimes running into situations where I'm pressing keys that don't do what I expect them to do, such as C-l to descend into directories, or typing `//` to jump to the file system top level and kill the current input line during file selection. Not sure if this module is supposed to offer a muscle-memory-compatible alternative to ivy (in which case I'd probably add the few key bindings I miss the most in day-to-day use) or not (in that case I'd rather reeducate myself)?
* I guess `projectile-completion-system` should be set to `default` if the selectrum module is in use? Though with selectrum enabled, neither `projectile-switch-project` nor `projectile-find-file` currently work for me (using either `default` or `ivy` completion, doesn't matter); the candidates are shown but selecting them won't do anything. With selectrum disabled, these commands work as expected, haven't yet tried to find out why.

How would you like to push this PR forward, collect code snippets in the comment section and include what you like, or would you rather see PRs to your `selectrum` fork?

2021-04-27 09:36 UTC, bdarcus commented
> SPC h t invokes consult-theme, which at least with my config doesn't seem to work well together with doom's modifications to load-theme; apart from the fact that themes are selected immediately due to consult's on-by-default autopreview (which would be OK or even a nice feature if it worked well), I never got a consistent set of colors after theme selection; plain vanilla load-theme, OTOH, works well. Maybe this is in some way caused by my config; does anyone else see similar issues?

Yes. I saw the same when I tested this yesterday.

2021-04-27 14:26 UTC, Emiller88 commented on modules/completion/selectrum/TODO.org
> +Probably due to live preview, but gets much faster on subsequent calls.
Yeah, I think we're going to go with manual preview. What function could we call do to that?

2021-04-27 14:30 UTC, Emiller88 commented
Yeah, I'm aware of the `consult-theme` issue as well. Maybe it's the preview or maybe just going to load theme will be best.

> How would you like to push this PR forward, collect code snippets in the comment section and include what you like, or would you rather see PRs to your `selectrum` fork?

I think PRs is easiest, the single comment thread will get cluttered.

2021-04-27 14:31 UTC, minad commented on modules/completion/selectrum/TODO.org
> +Probably due to live preview, but gets much faster on subsequent calls.
I think it is best to configure the manual preview only for the problematic commands, which introduce large latencies (consult-recent-file, consult-grep/ripgrep/git-grep). The other commands should be fine. And you definitely want to have automatic preview for commands like `consult-line` and `consult-yank-pop`. 

See the README for the configuration of individual commands, including the preview key: https://github.com/minad/consult/#fine-tuning-of-individual-commands.

2021-04-27 15:54 UTC, bdarcus commented
> Yeah, I'm aware of the `consult-theme` issue as well. Maybe it's the preview or maybe just going to load theme will be best.

I find two issues with it:

1. the preview is flakey; sometime it previews, and sometimes not
2. the selection doesn't seem to work at all; if I hit return on a theme, it doesn't load

Ideally this would work, of course, because it's nice to be able to preview the theme before selecting it.

cc @minad just FYI, though am not sure it's his problem.

2021-04-27 15:58 UTC, minad commented
@bdarcus It is not a pure Consult problem, but some interaction issue with the doom theming code. There is some doom-specific code in core-ui.el, which advices the theme functions.

2021-04-27 20:16 UTC, sebastiansturm commented on modules/completion/selectrum/TODO.org
> +does something else (give you previously used isearch search terms).
thanks for clearing that up. I misunderstood your comment (and apparently I've never used swiper to its full potential so far). Would you think `counsel-line` is a good enough default for `+default/search-buffer`, or would you consider it too limited for that purpose too?

2021-04-28 13:27 UTC, sebastiansturm commented
I'm sorry, I think I should only have bound `xref-show-xrefs-function` to `consult-xref`, not `xref-show-definitions-function`; at least with clangd, the latter is giving me errors and I wouldn't expect several definitions to choose from anyway. Will open another mini-pr

2021-04-29 15:05 UTC, Emiller88 commented
@bdarcus PR or just comment what you'd like bound to `SPC n b` to mimic `helm-bibtex` and `ivy-bibtex`

2021-04-29 15:17 UTC, bdarcus commented
> @bdarcus PR or just comment what you'd like bound to `SPC n b` to mimic `helm-bibtex` and `ivy-bibtex`

Thanks for asking @Emiller88!

I'm not super sure how best to do this, so will just comment.

I want to add this to `+biblio` once this module is merged.

https://github.com/bdarcus/bibtex-actions

You can see the list of commands in the keymap I include (mostly for embark integration) here:

https://github.com/bdarcus/bibtex-actions/blob/d6882c29978f0223dbbc01e84b449e111ba9de4f/bibtex-actions.el#L90

`Ivy-bibtex` and `helm-bibtex` hide the same basic actions behind those single commands.

Upshot, I'm thinking what is now `SPC n b` probably should be a prefix map, and those existing commands accessed via `SPC n b s` (for "search").

And then when I proposed my package, we'd end up with bindings like:

- `SPC n b c` -> `bibtex-actions-insert-citation`
- `SPC n b k` -> `bibtex-actions-insert-key`

etc.

Not sure what do then with a command like`bibtex-actions-open-notes` though; just `SPC n b n` as well?

WDYT @Emiller88?

2021-04-29 15:26 UTC, Emiller88 commented
Hmm, I like that personally, I'll have to think about how to do that in a clever way. This currently just pulls up `bibtex-actions-insert-key`
```lisp
       (:when (featurep! :tools biblio)
        :desc "Bibliographic entries"        "b"
        (cond ((featurep! :completion ivy)   #'ivy-bibtex)
              ((featurep! :completion helm)  #'helm-bibtex)
              ((featurep! :completion selectrum)
               :desc "Insert Citation" "c" #'bibtex-actions-insert-citation
               :desc "Insert Key" "k" #'bibtex-actions-insert-key)))
```

2021-04-29 18:59 UTC, jcf commented
I've rebased these commits on top of `develop` and fixed an obsolete variable over in [my fork](https://github.com/jcf/doom-emacs/tree/selectrum). I've also posted a few updates to my [comment from a couple of weeks ago](https://github.com/hlissner/doom-emacs/pull/4664#issuecomment-820739128) with things I've added to my private Doom configuration.

If there's anything I can do to help get this into Doom, just holla! 🙇

2021-04-29 19:33 UTC, iyefrat commented
@jcf thanks for the tip! When you find things like that the best option is to sent a PR with the fix.

2021-04-29 21:27 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +In ivy, backspace on =/foo/bar/!= (where =!= is the cursor) leads to =/foo/!=
Thank you! I'll add this to the module soon.

2021-04-29 21:28 UTC, bdarcus commented
> I've advised `consult-find` to improve support for `fd` ...

That seems something potentially worth submitting to consult?

2021-04-29 21:47 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +does something else (give you previously used isearch search terms).
`consult-line` is already bound to `SPC s b`, I figured there wasn't much of a point in doubling up. I considered binding plain isearch, but doom is very much oriented around ivy/selectrum like workflows for things that aren't just vim (at least for evil users), so on top of the fact that I'd guess that most people use `/`, isearch is also already bound to `C-s`, so I'd thought I'd leave it empty until Henrik gets around to reviewing the module (or someone else decides to do something there).

2021-04-29 21:53 UTC, minad commented
@bdarcus

> That seems something potentially worth submitting to consult?

No, but the advice is actually not a good solution for the problem. Simply write a wrapper command as I have documented in the wiki of Consult: https://github.com/minad/consult/wiki#find-files-using-fd.

2021-04-29 22:02 UTC, gagbo commented on modules/completion/selectrum/README.org
> ++ ~+orderless~ Enables prescient filtering Selectrum searches.
s/prescient/orderless/

2021-04-29 22:03 UTC, gagbo commented on modules/completion/selectrum/README.org
> +#+end_quote
Should probably be removed

2021-04-29 22:06 UTC, gagbo commented on modules/completion/selectrum/README.org
> ++ [[https://github.com/BurntSushi/ripgrep][ripgrep]] (rg)
As rg is a hard dep of Doom already, I'm not sure it's necessary to reiterate. Or maybe leave it and mention that it should already be there ?

2021-04-29 22:06 UTC, gagbo commented on modules/completion/selectrum/README.org
> +* PROJ Features
s/PROJ//

2021-04-29 22:07 UTC, jcf commented
> When you find things like that the best option is to send a PR with the fix.

@iyefrat where should I send a PR? This is a pull request so are you suggesting I open a pull request to pull into this pull request or something else? I'd usually cherry-pick someone else's commits into my PR…

> Alternatively adjust the variable consult-find-command globally, in case you only want to use fd instead of find.

@minad my understanding is that `consult-find-command` is a variable that can't be changed beyond some interpolation of `ARG` and `OPTS`. With `fd` command of `fd --color=never --hidden --full-path ARG OPTS` you'll find unexpected results due to `fd` matching all the way up the path. For example, in a project named "foo", a search for "foo" matches everythind because "foo" is in the full path. I have wrapper functions elsewhere but in this case, I think `consult-find` is missing a necessary feature to get `fd` working the way I need it to.

2021-04-29 22:07 UTC, iyefrat commented
One of the things I'm a bit stuck on is replicating the live previews. Setting `C-SPC` as the preview key for `consult` commands is simple enough, but I haven't been able to get it to work for regular selecrum commands yet. The ivy module does this with `ivy-call`, which seems to have an analogue in say:
```lisp
(let ((embark-quit-after-action nil))
    (map! :map minibuffer-local-map "C-SPC" #'embark-default-action)))
```
But this doesn't open the buffers in the main window, rather it opens them in a smaller window that closes when I exit the minibuffer. Furthermore, It moves the cursor to the new buffer, which I think is the intended behavior here, from the "thing-manager" description in the README, but doesn't lend itself very well to being a preview where one would want to skim many previews one after the other. `embark-consult-preview-at-point` seemed like it would be the solution but it only works on collect buffers.

Maybe the best solution is to try and upstream some sort of `embark-preview` function, or maybe I'm just missing something.

2021-04-29 22:09 UTC, iyefrat commented on modules/completion/selectrum/README.org
> ++ ~+orderless~ Enables prescient filtering Selectrum searches.
whoops

2021-04-29 22:09 UTC, iyefrat commented on modules/completion/selectrum/README.org
> +#+end_quote
all the other completion modules have quotes, i figured this one would eventually get one too

2021-04-29 22:11 UTC, iyefrat commented on modules/completion/selectrum/README.org
> ++ [[https://github.com/BurntSushi/ripgrep][ripgrep]] (rg)
Honestly I just copied it from the ivy module, was rg not a hard dependency in the past?

2021-04-29 22:13 UTC, iyefrat commented
@jcf you can just submit pr's to @Emiller88's repo, it's how I work on the module.

2021-04-29 22:23 UTC, gagbo commented
> @minad my understanding is that `consult-find-command` is a variable that can't be changed beyond some interpolation of `ARG` and `OPTS`. With a custom `fd` command of `fd --color=never --hidden --full-path ARG OPTS` you'll find unexpected results due to `fd` matching all the way up the path. For example, in a project named "foo", a search for "foo" matches everything because "foo" is in the full path.

Is it bad ? I kind of expect all files to be hit if you `fd` for `"project_name"` inside a `project_name` folder with a `--full-path` flag. If you really really want to change that, it's not an advice you need, you'd need to write another consult command with the proper "transformer" that will strip the prefix path from the candidates before making it a candidate

2021-04-29 22:24 UTC, minad commented
@jcf      

> With a custom fd command of fd --color=never --hidden --full-path ARG OPTS you'll find unexpected results due to fd matching all the way up the path. For example, in a project named "foo", a search for "foo" matches everything because "foo" is in the full path.

Cool, so by the adjustment you prevent `fd` from matching on the full path and it only matches on the subdirectories and file name? This is actually some deficiency of `fd`, which I found annoying when `consult-fd` was proposed for addition and Consult. Among other reasons, this was one of the reasons which ultimately led me to not add a separate `consult-fd` command. Then the usage of an advice is certainly advised :smile:

2021-04-29 22:26 UTC, minad commented
@gagbo I found this `fd` behavior pretty bad, for example when I am in `/home/user` and search for `user` it will find every file.

2021-04-29 22:27 UTC, jcf commented
> This is actually some deficiency of fd, which I found annoying when consult-fd was proposed for addition and Consult.

@minad you are exactly right! I've plugged away at a few options to get `fd` working the way I want. I don't think typing my username should return every file in a repo that lives in my home directory, and you have to use `--full-path` to match on directory names, which I definitely do want. 🤷 

Maybe I should just stick with the `find` support that comes out of the box. It works really well, and performance is perfectly adequate. I guess I'm just attracted to new and shiny things.

2021-04-29 22:27 UTC, minad commented
@iyefrat

> One of the things I'm a bit stuck on is replicating the live previews. Setting C-SPC as the preview key for consult commands is simple enough, but I haven't been able to get it to work for regular selecrum commands yet. The ivy module does this with ivy-call, which seems to have an analogue in say:

This is what `embark-act` is for. You can always invoke `embark-act` on a candidate and press `RET` to run the default action. Maybe there is also a command `embark-act-run-default` which does it directly. I recall that it has been discussed, but I would have to look up if it exists.

2021-04-29 22:43 UTC, iyefrat commented
@minad 
>This is what embark-act is for. You can always invoke embark-act on a candidate and press RET to run the default action. Maybe there is also a command embark-act-run-default which does it directly. I recall that it has been discussed, but I would have to look up if it exists.

Yeah, this is what i was hoping for with the aforementioned binding, but as I said the implementation I managed to work out left a lot to be desired. A custom embark action is probably the way to go, but it'd be a shame for it to step on the toes of the built in consult previews since those work great.

2021-04-30 14:38 UTC, iyefrat commented
@Emiller88 can you rebase the branch henrik recently fixed an annoying startup bug #4925

2021-04-30 21:03 UTC, bdarcus commented
I recall recently someone asked about having `orderless` the default completion style. But it's still behind a flag.

Is there any good reason not to make that change?

WDYT?

2021-04-30 21:08 UTC, bdarcus commented on modules/tools/biblio/packages.el
> +  (package! bibtex-actions :pin "743f548c0cd46e3418a7ca4736bde8c86f97c073"))
```suggestion
  (package! bibtex-actions :pin "b1ddbb32373ac01b6bb46dfc4cdc143461e3c14c"))
```

I imagine you'll be bumping packages before merging, but I flag this because it adds a feature that requires a minibuffer keybinding (though the commands work fine without it), which is included in the extended `use-package` example. 

https://github.com/bdarcus/bibtex-actions#basic

This is another case where I'm unsure how best to adapt this to `doom` though.

2021-05-01 10:33 UTC, minad commented
@bdarcus My recommendation is to only use Orderless. The completion systems (default completion, Selectrum, Icomplete, Vertico) all sort by history by default. Prescient for sorting only offers minimal benefits on top of that, namely its additional freceny based ranking. 

If Prescient is used for filtering, you don't get an all-encompassing solution, since Prescient is not a completion style in contrast to Orderless. Prescient will only work with completion systems with explicit Prescient support, Selectrum, Company, Ivy, etc.

There are these possibilities:

* Orderless for filtering + default sorting (my recommendation)
* Orderless for filtering + Prescient only for sorting by frecency
* Prescient for filtering and sorting by frecency, but there are still the Emacs completion styles which are not affected by the configuration

2021-05-01 10:48 UTC, bdarcus commented
> My recommendation is to only use Orderless.

Thanks @minad!

@iyefrat @Emiller88 - can we do this then? 

So remove the orderless flag and make orderless default?

Maybe even remove the prescient flag too?

2021-05-01 11:11 UTC, iyefrat commented
@bdarcus I agree that orderless should be on by default, I'll add it in my next batch (should be later today). Regarding the prescient flag, It might be a good idea to move it to just use it for sorting, as the whole frecency might be useful (I'm honestly not sure how much I use it since i just search for stuff), but that would mean we end up installing two packages for what is essentially the same thing. Until we get more input I'll leave prescient as is, we can always change that flag later. I don't think that prescient working just with selectrum is a huge issue either way since we are only talking about the selectrum module anyway, and not a standalone prescient module.

2021-05-01 11:21 UTC, minad commented
@bdarcus @iyefrat I guess it may still make sense to offer the configuration options, such that you can use each of the three options:

* Orderless for filtering + default sorting
* Orderless for filtering + Prescient only for sorting by frecency
* Prescient for filtering and sorting by frecency
* Prescient only for filtering + default sorting (I forgot this above, this is also possible)

Regarding Prescient only being available for Selectrum is not a significant problem if you assume that completion-styles only matter for minibuffer completion (completing-read). There is also completion-in-region, which is an additional story. You may either use `consult-competion-in-region` or `selectrum-completion-in-region`. But from what I understood Doom does not make use of this functionality directly and uses Company, relying on capf backends. The capf backends are also affected by completion styles, so for Company you may want to use a separate completion style.

I used something like this for a while:

~~~~ elisp
  (advice-add #'company-capf--candidates :around
              (lambda (orig input)
                (let ((completion-styles '(basic orderless))) ;; basic+substring+orderless?
                  (funcall orig input))))
~~~

But these wider integration issues should be answered by someone who knows how everything fits together in Doom.

2021-05-01 12:02 UTC, iyefrat commented
@minad The module flags are there to be sane defaults, I think the more refined orderless/prescient configuration options are probably best left for users to implement themselves. 

> But these wider integration issues should be answered by someone who knows how everything fits together in Doom.

yeah, probably

2021-05-01 12:47 UTC, bdarcus commented
Aside, @minad:

> Prescient for sorting only offers minimal benefits on top of that, namely its additional freceny based ranking.

Is there any reason that "frecency-based-ranking" feature couldn't or shouldn't be added as an option to `selectrum`, `vertico`, et al?

2021-05-01 12:49 UTC, iyefrat commented on modules/tools/biblio/packages.el
> +  (package! bibtex-actions :pin "743f548c0cd46e3418a7ca4736bde8c86f97c073"))
@bdarcus I'm looking into bibtex-actions at the moment (cool package btw! took me a while to realise that you're the author), but it seems that it is not initializing automatically under the current config when i open a latex file. does this happen on your end? any idea on what we could use to load it only when needed? (the readme has it load right after embark as i understand it which is suboptimal)

2021-05-01 13:08 UTC, bdarcus commented on modules/tools/biblio/packages.el
> +  (package! bibtex-actions :pin "743f548c0cd46e3418a7ca4736bde8c86f97c073"))
@iyefrat

> I'm looking into bibtex-actions at the moment (cool package btw! took me a while to realise that you're the author), but it seems that it is not initializing automatically under the current config when i open a latex file. 

So the commands aren't available to you when loading a latex file?

I don't see that on my end, using the "run.sh" script in the test directory, which loads `emacs -Q`.

> does this happen on your end? any idea on what we could use to load it only when needed? (the readme has it load right after embark as i understand it which is suboptimal)

This package is my "learning emacs/elisp as I go" package, so I'm learning these sorts of details as a part of that.

In short, I'm not sure, but welcome suggestions.

Should I change that example to only load for obvious text editing modes (org, latex, markdown)?

The current biblio module also doesn't seem to tie loading to those modes, so we should figure out a solution that works well for all of them.

2021-05-01 13:28 UTC, iyefrat commented on modules/tools/biblio/packages.el
> +  (package! bibtex-actions :pin "743f548c0cd46e3418a7ca4736bde8c86f97c073"))
@bdarcus It seems that doom loads ivy-bibtex first thing, so we should probably do that here too, so just loading it after embark is probably fine.

2021-05-01 13:30 UTC, bdarcus commented on modules/tools/biblio/packages.el
> +  (package! bibtex-actions :pin "743f548c0cd46e3418a7ca4736bde8c86f97c073"))
> It seems that doom loads ivy-bibtex first thing, so we should probably do that here too, so just loading it after embark is probably fine.

I think the logic of that (I submitted the initial PR for that module, but it's been awhile), was just that we can imagine a user wanting access to the commands outside of obvious editing modes.

2021-05-01 16:11 UTC, minad commented
@bdarcus It is better to keep the complexity of Prescient outside of packages like Selectrum, Ivy and Vertico. Ideally one can reuse the functionality in multiple completion systems, e.g., Prescient can be used with Selectrum and Ivy. However we could compute a frecency based ranking using the history directly in Selectrum/Vertico, by counting the frequencies and reordering accordingly. But I think the benefits would be marginal, not justifying the added complexity. It may also slow down the sorting a little bit.

2021-05-01 16:16 UTC, bdarcus commented
@iyefrat @Emiller88 - I just installed the fork and fresh installed doom with it.

But I get two void variable errors:

1. from `bibtex-completion` though possible my fault (not sure)
2. `Error in private config: config.el, (void-variable embark-keymap-alist)`

2021-05-02 07:32 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +        orderless-matching-styles '(orderless-prefixes
The defaults are literal, initialism, and regexp.

1. Why is prefixes replacing literal here?
2. I wonder if this and the lack of flex accounts for the problems I see?

2021-05-02 08:19 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  (defun +selectrum--orderless-first-initialism (pattern index _total)
```suggestion
  (defun +selectrum--orderless-first-initialism (_pattern index _total)
```

To fix an unused lexical variable warning.

2021-05-03 07:49 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (defun +selectrum--orderless-first-initialism (pattern index _total)
i fixed this on my branch, it'll be added in the next batch

2021-05-03 07:50 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +        orderless-matching-styles '(orderless-prefixes
I'll look into this later when i have time

2021-05-04 07:49 UTC, gagbo commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
This `setq` should be moved to the `:init` section. Otherwise even customizing the `orderless-style-dispatchers` in my private `config.el` with

```lisp
(setq orderless-style-dispatchers '(+selectrum--orderless-flex-if-twiddle
                                      +selectrum--orderless-without-if-bang))
```

keeps that "first initialism" bit as orderless is loaded on my first selectrum selection appearing...

2021-05-04 07:54 UTC, minad commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
Regarding the orderless style dispatchers you may also want to take a look at the configuration I added to the Consult wiki:

https://github.com/minad/consult/wiki#orderless-style-dispatchers-ensure-that-the--regexp-works-with-consult-buffer

2021-05-04 07:59 UTC, gagbo commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
I'll check that, I guess a more complex dispatcher will need to be done at some point... My main problem with that  first-initialism is that I never want to use it, but I'm "forced" to by the dispatcher. And it's especially frustrating to see the file you want to choose "go away" because I started to type its actual name, or seeing corfu being confused by what I type as well

2021-05-04 08:03 UTC, gagbo commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
Or maybe another way to deal with this issue is to actually `:demand` orderless

2021-05-04 08:05 UTC, minad commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
Okay, I have not seen any such issues but I am loading the completion style eagerly. The style dispatcher and configuration I am using is pretty simple, with a few minor tweaks.

2021-05-04 09:02 UTC, minad commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
@iyefrat Take a look at the links in the wiki which provide more information. These are disambiguation suffixes used by Consult for some commands, e.g., consult-buffer and consult-line.

2021-05-04 09:18 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
@minad ah yes i missed the fact that the explanation was in the comments, thanks!

2021-05-04 09:47 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
> I agree, the first initialism is not that useful and a counter-intuitive default, I was already going to remove it in the next PR batch.

I added this originally, but agree makes sense to remove.

2021-05-04 10:01 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
@gagbo moving the definition to `:init` doesn't fix the problem for me, did you do anything else other than that?

2021-05-04 10:11 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
It seems that after removing `:after selectrum`, moving them to the init does work. This was originally introduced in order to get orderless to load in the first place, but seems to no longer be needed.

2021-05-04 10:21 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
@Townk why did you put this configuration in `:init` and not `:config`?

2021-05-04 10:47 UTC, gagbo commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
I think I'm on d3e03a222 but I don't really remember if I did anything else, I mostly end up evaluating the `setq` from my config manually when I notice it

2021-05-04 11:06 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
Aside from that, seems we just want the default space separator; no?

2021-05-04 11:33 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
yeah i agree, i'm also not sure if we want to change the default matching styles, i'm mainly wondering if @Townk did this because of some hidden gotcha or just because

2021-05-04 13:14 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
@minad in the configureation [here](https://github.com/minad/consult/wiki#orderless-style-dispatchers-ensure-that-the--regexp-works-with-consult-buffer), what is the purpose of the following:
```
completion-category-overrides '((file (styles . (partial-completion))))
```
even after this `find-file` seems to use the `orderless` completion style (checked by using the defined dispatchers from the above config), and I can't really think of a reason to prefer this to orderless anyway.

2021-05-04 14:18 UTC, minad commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
@iyefrat Depending on what you are typing either one or the other completion style will be used. If you type for example "/u/s/e" it will show you the files where each subdirectory matches one of the characters. Orderless will not be used in this case or would return you zero matches. Note that all these things are well documented (https://www.gnu.org/software/emacs/manual/html_node/emacs/Completion-Styles.html). Please take a look at the documentation and see also the variable documentation for example of `completion-styles`, `completion-styles-alist` and `completion-category-overrides`.

2021-05-05 16:12 UTC, Townk commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
Yes I did. The `&` separator is to be able to use orderless with Company (since company ends the completion with a space).

2021-05-05 16:14 UTC, Townk commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
And to actually answer the question, the main reason is that I usually add variable assignment on `:init`, unless the package in question does not define them with `defvar` or `defcustom`, but to be honest I don't even know if this is a good practice or not, is just  habit I got back on my C/C++ days.

2021-05-05 17:22 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
> Yes I did. The `&` separator is to be able to use orderless with Company (since company ends the completion with a space).

OIC; explained here:

https://github.com/oantolin/orderless#company

So I guess this would just need to be let-bound however one configures company?

2021-05-05 18:06 UTC, minad commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
My Corfu package does not need the additional separator character. It will work with orderless and space ootb.

2021-05-05 18:12 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
> My Corfu package does not need the additional separator character. It will work with orderless and space ootb.

And the ampersand here also wouldn't be a problem?

2021-05-05 18:42 UTC, Townk commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
> So I guess this would just need to be let-bound however one configures company? Or is that not necessary

I'm not sure if you can get away with let bind here. As far as I understood, the documentation recommends to set this variable. Perhaps we could add a let bind on an advice? Or maybe is not worth it, and we want to let it be this way.

2021-05-05 18:54 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +                                      +selectrum--orderless-without-if-bang)))
@minad I see. I did go over the docs before I messaged you, but was confused since they seemed to conflict with the way completion worked in practice. It was because of selectrum's built in completion that i didn't manage to figure out exists, and the fact that the documentation was unclear that `completion-category-overrides` are additional completion styles to `completion-styles`, which means that `find-file` ends up using both `orderless` and `partial-completion` (at least that is my understanding after testing it out sans selectrum. Thank you for the input.

2021-05-05 19:30 UTC, minad commented on modules/completion/selectrum/config.el
> +                                    orderless-regexp))
@bdarcus No problem. I would probably refrain from adding such hackish/workaround configurations here or at least document it clearly. I spent a bit of time fiddling with company to work as I want it. See https://github.com/oantolin/orderless/issues/35#issue-800865251 and the monster configuration in https://github.com/company-mode/company-mode/issues/1061#issuecomment-771635807. But now I have Corfu :smile:

2021-05-06 05:39 UTC, minad commented on modules/completion/selectrum/TODO.org
> +- pass (creating embark-pass can't be that hard)
Is this what you are looking for? https://github.com/oantolin/embark/wiki/Additional-Actions#password-store-actions-using-password-storeel

Maybe check out the Selectrum, Embark and Consult wikis from time to time. We are adding new stuff there if something comes up.

2021-05-06 05:40 UTC, minad commented on modules/completion/selectrum/TODO.org
> +- counsel-minibuffer-history analogue
`consult-history` covers `counsel-minibuffer-history`. Documented at https://github.com/minad/consult#histories.

2021-05-06 16:52 UTC, Emiller88 commented
@minad Do you have any examples of wgrep used with consult that you know of?

I'm just getting `wgrep-prepare-header/footer: Invalid search bound (wrong side of point)` when trying to call it currently.

2021-05-06 22:55 UTC, bdarcus commented
Just confirming, @iyefrat, all working MUCH better with your latest commits!

A question just occurred to me about a minor issue: what are thoughts about default state for marginalia annotations?

2021-05-07 07:42 UTC, minad commented
@Emiller88 If wgrep does not work correctly for you with embark-export, please open an issue at https://github.com/oantolin/embark.

2021-05-07 14:36 UTC, jcf commented
After syncing up with the changes in `develop` and this PR, I encountered the following error when running `doom sync -up`:

```
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.config/emacs/.local/env"
    ✓ Successfully generated "~/.config/emacs/.local/env"
  > Installing packages...
Package cl is deprecated
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
  > Updating packages (this may take a while)...
    x The package manager threw an error.
    x Last 25 lines of straight's error log:
      4dbde92542fc7ad61df38776980905a4721d642e
      [Return code: 0]
      $ cd /home/jcf/.config/emacs/.local/straight/repos/jade-mode/
      $ git rev-parse HEAD
      4dbde92542fc7ad61df38776980905a4721d642e
      [Return code: 0]
      $ cd /home/jcf/.config/emacs/.local/straight/repos/org-msg/
      $ git rev-parse HEAD
      b0765b2d0bc06cdd1fd78836ef958eb81e603dd1
      [Return code: 0]
      $ cd /home/jcf/.config/emacs/.local/straight/repos/notmuch/
      $ git rev-parse HEAD
      6a20478abb517a8c6c046a1ff640fa02d118aa88
      [Return code: 0]
      $ cd /home/jcf/.config/emacs/.local/straight/repos/org-mime/
      $ git rev-parse HEAD
      eb21c02ba8f97fe69c14dc657a7883b982664649
      [Return code: 0]
      $ cd /home/jcf/.config/emacs/.local/straight/repos/consult-notmuch/
      $ git rev-parse HEAD
      HEAD
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      [Return code: 128]
    ! Extended backtrace logged to ~/.config/emacs/.local/doom.error.log
```

I've disabled the `:email notmuch` module to sidestep needing to clone `consult-notmuch`.

https://github.com/emacsmirror/consult-notmuch
https://codeberg.org/jao/consult-notmuch

While this doesn't fix the underlying issue, I thought I'd share just in case it helps someone else out.

Ciao!

2021-05-07 16:44 UTC, Emiller88 commented
> @Emiller88 If wgrep does not work correctly for you with embark-export, please open an issue at https://github.com/oantolin/embark.

@minad I think I figured out the issue. It was with the custom which key function. I'm not sure what the purpose of it was, I pulled it from @Townk's config, so maybe he can give us some insight.

So I've gotten wgrep working, it's not as clean as the ivy stuff yet.

1. `SPC /` & search
2. `C-o` `E`
3. `C-c C-p`
4. Edit and follow normal wgrep stuff.

I kinda like the option to export, but it'd be nice if we could convert the pop up buffer to be like Ivy and have it under `C-c C-e`

2021-05-07 17:02 UTC, minad commented
@Emiller88 
> So I've gotten wgrep working, it's not as clean as the ivy stuff yet.

Yes, going via consult-ripgrep->embark-export->wgrep may have a few more rough edges than Ivy which does more out of the box. I suggest you don't try to create a 100% clone of the Ivy setup. While I think the coverage provided by the Selectrum/Consult/Embark ecosystem of packages is good, for me it is not a goal to replicate all the Ivy/Counsel features.

> I kinda like the option to export, but it'd be nice if we could convert the pop up buffer to be like Ivy and have it under C-c C-e

What do you mean exactly here? If it is desired, you can bind embark-export or embark-snapshot to `C-c C-e`.

2021-05-07 17:08 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +- pass (creating embark-pass can't be that hard)
It might be, this list was just a quick catalogue of things to look into more deeply later that didn't seem to have an obvious complete solution. I haven't looked into how doom handles pass yet beyond skimming the module.

2021-05-07 17:08 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +- counsel-minibuffer-history analogue
neat, thanks for the pointer.

2021-05-07 17:10 UTC, iyefrat commented
> After syncing up with the changes in `develop` and this PR, I encountered the following error when running `doom sync -up`:
@jcf I can't reproduce this, I think it has to do with a recent `straight` update. Deleting your `~/.emacs.d/.local/straight` and syncing should solve it

2021-05-07 17:14 UTC, iyefrat commented
@Emiller88 I think that the solution here is to create a `+selectrum/wgrep` function that is the analogue of `+ivy/woccur`, that basically streamlines the process of running the embark command followed by turning on editing. I can work on this if you'd like (this was next on my todo list), but I'd rather not double up effort so if you're working on it I'll do something else.

2021-05-07 17:14 UTC, bdarcus commented
> I suggest you don't try to create a 100% clone of the Ivy setup.

100% agree!

2021-05-07 17:16 UTC, Emiller88 commented
@iyefrat go for it! I just needed to get this much working to hold me over so I can use the selectrum module as a daily driver.

2021-05-07 17:36 UTC, iyefrat commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
@Emiller88 after removing this I don't get a whichkey prompt for the possible embark actions, is this also true for you? What did this have to do with getting wgrep to work? Also emacs errors on launch with `(void-variable embark-action-indicator)`. I'm working on fixing it but I'm wondering what this is all like from your end.

2021-05-07 17:47 UTC, iyefrat commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
@Emiller88 I can't reproduce your wgrep error (but I do have to manually invoke `wgrep-change-to-wgrep-mode` in order to get `C-c C-p` to work).

2021-05-07 17:50 UTC, iyefrat commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
yeah, which means that a. we should keep it and b. it's surprising that this has to do with wgrep at all; so there is probably a solution that will let us keep both. but since i can't reproduce @Emiller88's error i can't really figure it out yet.

2021-05-07 18:14 UTC, bdarcus commented
BTW, there's an option to sort the which-key menus by command for embark.

That's wise in the absence of further config options for these menus, since
it will at least group commands together.

2021-05-07 20:03 UTC, Emiller88 commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
Hmm that's weird. Sorry about that my issue was with embark and which-key then. So this is definitely a problem with me. I get the error when I reloaded.

But I still get the which-key error now after reverting that commit. Can either of you confirm your packages are up to date with `doom s -u`?

2021-05-07 20:13 UTC, iyefrat commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
@Emiller88 yeah my packages are up to date. Can you check if you still get the error in a `C-c C-p` doom sandbox?

2021-05-07 20:18 UTC, bdarcus commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
I'm on latest. What causes your error @Emiller88?

BTW, here's the setting to sort the which-key descriptions in the embark menu:

``` elisp
(setq which-key-sort-order 'which-key-description-order)
```

2021-05-07 20:45 UTC, iyefrat commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
@Emiller88 In the mean time, could you drop the which-key commit it kind of makes embark unusable at the moment unless you memorized the keybindings

2021-05-07 20:57 UTC, Emiller88 commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
I get the error on any selectrum buffer and calling `embark-act`.

2021-05-07 21:01 UTC, bdarcus commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
"Selectrum buffer"?

`embark-act` works fine for me with the menus.

2021-05-08 07:51 UTC, iyefrat commented
@bdarcus 
> BTW, there's an option to sort the which-key menus by command for embark.

i'm not sure this is a good default, since everywhere else in doom `which-key` is sorted by binding and not description

2021-05-08 10:11 UTC, bdarcus commented
> @bdarcus
> 
> > BTW, there's an option to sort the which-key menus by command for embark.
> 
> i'm not sure this is a good default, since everywhere else in doom `which-key` is sorted by binding and not description

The problem ATM is that whatever commands you have bound to a particular completion type get listed alongside a handful of general embark commands.

I did put in two issues on the embark issue tracker related to this, one of which applies here: https://github.com/oantolin/embark/issues/207.

That would be the ideal solution in my eyes.

@oantolin did say he supports adding something like that.

2021-05-08 14:09 UTC, Emiller88 commented on modules/completion/selectrum/config.el
> -  (setq embark-action-indicator #'+embark-which-key-action-indicator
Sorry, I meant the consult buffer. I blew away my doom install last night and did a clean, and it works for me now :upside_down_face: . I apologize for the confusion, must have been some weird local state.

2021-05-08 15:49 UTC, minad commented on modules/lang/org/config.el
> +         "g" #'consult-outline)
There is also `consult-org-heading` and `consult-org-agenda`. These commands are probably similar to "g" and "G" from the helm bindings?

2021-05-08 16:32 UTC, minad commented on modules/completion/selectrum/config.el
> +        completion-category-overrides '((file (styles . (partial-completion))))
I recently removed `orderless-initialism` from the default orderless matching styles in order to mitigate performance issues with long candidate strings. You may still want to have explicit initialism via the style dispatcher (see https://github.com/minad/consult/wiki#orderless-style-dispatchers-ensure-that-the--regexp-works-with-consult-buffer, where I am using ` as initialism style dispatcher. I am using ` since \\` is used in regexps to denote the beginning.)

See also https://github.com/oantolin/orderless#defining-custom-orderless-styles in case you want to build custom orderless styles, which can be used for special categories. I am using the custom `orderless+initialism` completion style for the symbol and command category (M-x, describe-variable, ...).

2021-05-08 16:36 UTC, minad commented on modules/lang/org/config.el
> +         "g" #'consult-outline)
> Wow how did I miss those. 

These commands are new and were added just two weaks ago (https://github.com/minad/consult/pull/276).

> Consult doesn't seem to have "search across all buffers" type commands at the moment either way. Thanks!

Yes, it does not have that. But at some point we may get `consult-line` across project buffers or `consult-outline` across project buffers. There is only `consult-project-imenu` which lets you navigate across imenus from open project buffers. This is similar to imenu-anywhere, which you may know. But probably such a command is less useful in times of lsp, where you can easily jump between symbols in a project.

2021-05-08 16:48 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +        completion-category-overrides '((file (styles . (partial-completion))))
I see. Thanks for the detailed rundown!

2021-05-08 17:37 UTC, oantolin commented
> The problem ATM is that whatever commands you have bound to a particular completion type get listed alongside a handful of general embark commands.

"Handful" is a euphism: if you use embark-consult, you have 17 general actions. Even without embark-consult you have 8 general actions. That's why this is a problem. If you know what you want to search for completion is fine, but if you are actually browsing, that's a lot of junk to wade through.

Being mentioned here in an _extremely_ popular repo shamed me into action. 😛 I put the general actions into a submenu in the completing read prompter a few minutes ago (see oantolin/embark@16023eeecf29b488187d43f0593cc599a492cba6).

2021-05-08 18:18 UTC, bdarcus commented
> "Handful" is a euphism: if you use embark-consult, you have 17 general actions. 

So three+ handfuls ;-)

> Being mentioned here in an extremely popular repo shamed me into action. 😛 I put the general actions into a submenu in the completing read prompter a few minutes ago ...

Thanks! Definitely no shame intended!

2021-05-08 20:05 UTC, minad commented on modules/app/irc/autoload/irc.el
> +(defun +irc/selectrum-jump-to-channel (&optional this-server)
Instead or additionally to this command, would an IRC channel buffer source be useful? See https://github.com/minad/consult/wiki#erc-buffers. Then you could select from the IRC channels using the usual Consult narrowing, e.g., by typing `c SPC`? As far as I know, Ivy doesn't support custom buffer sources, therefore in Ivy this has to be a separate command.

2021-05-08 20:44 UTC, iyefrat commented on modules/app/irc/autoload/irc.el
> +(defun +irc/selectrum-jump-to-channel (&optional this-server)
This looks like a good idea, I'll try using this approach later. If I'm successful I'll add it to the wiki.

2021-05-08 20:49 UTC, minad commented on modules/app/irc/autoload/irc.el
> +(defun +irc/selectrum-jump-to-channel (&optional this-server)
> If I'm successful I'll add it to the wiki.

Yes, please do that in case it works out. I always appreciate additions to the wiki!

2021-05-08 21:23 UTC, bdarcus commented
> put the general actions into a submenu in the completing read prompter a few minutes ago

Just to update @iyefrat - we had a bit of miscommunication (my fault), so this does not address the `which-key` issue.

@minad provides a suggestion for how to address that here, but it appears to be conditioned on fixing a related issue.

https://github.com/oantolin/embark/issues/207#issuecomment-835518230

I think it's fine to keep things as is for now, and see if somehow that issue can get resolved.

2021-05-14 19:25 UTC, bdarcus commented
@iyefrat - I think I again, or still (not sure which), have something funky going on with orderless. See below.

![Screenshot from 2021-05-14 15-22-42](https://user-images.githubusercontent.com/1134/118319126-59eb8c00-b4c8-11eb-9328-d45a8ee80979.png)

2021-05-14 19:49 UTC, iyefrat commented
@bdarcus this is the `orderless-initialism` matching style, which is on by default (see `orderless-matching-styles`). In the next bump of orderless it won't be by default anymore, and I haven't decided what exactly I want to do with it. I might do what @minad describes [here](https://github.com/hlissner/doom-emacs/pull/4664#discussion_r628769975), not sure.

2021-05-14 20:02 UTC, bdarcus commented
> In the next bump of orderless it won't be by default anymore, 

:+1: 

> and I haven't decided what exactly I want to do with it. I might do what @minad describes [here](https://github.com/hlissner/doom-emacs/pull/4664#discussion_r628769975), not sure.

You mean his use of the style dispatchers in general, and the ` initialism?

I don't feel super strongly, FWIW, other than that it should not be default. 

I notice his recommended dispatches have prefix and suffix (`=literal=`), while the one on the orderless docs have one or the other.

I wonder what the advantage of that is.

2021-05-14 21:07 UTC, iyefrat commented
@bdarcus 
> other than that it should not be default.

why not?

> I wonder what the advantage of that is.

probably that you can decide on the filter type both before and after you type the word

2021-05-14 21:09 UTC, bdarcus commented
> @bdarcus
> 
> > other than that it should not be default.
> 
> why not?

Sorry; I realize I wasn't specific about the referent.

By "this" I meant the current initialism behavior.

2021-05-14 21:11 UTC, iyefrat commented
@bdarcus yeah i getcha, why do you think initialisms should not be on by default?

2021-05-15 00:16 UTC, bdarcus commented
@iyefrat - I actually don't mind it now that I think about it more,
but there are some situations where it just feels less-than-intuitive.

I think it's mainly that I expect to have to put a space between
letters for the matches to span across words, whereas the example I
posted does that without the space.

2021-05-15 05:10 UTC, minad commented
@iyefrat Initialisms and flex should not on by default since those are potentially slow. They should be used only on short candidates where it makes sense (e.g. symbols and commands, M-x, ...). Using the regexps on long candidates allows regexp denial of service, see https://github.com/oantolin/orderless/issues/39 ;) Note that this is not an issue of orderless but a more general problem of regexps.

2021-05-15 22:06 UTC, andreiltd commented on modules/completion/selectrum/TODO.org
> +does something else (give you previously used isearch search terms).
Isn't [ctrlf](https://github.com/raxod502/ctrlf) a swiper/swoop replacement from the same universe as selectrum?

2021-05-15 22:25 UTC, oantolin commented
To add to what @minad said, initialisms and flex is only noticeably slow on fairly long candidates. They are fine for Emacs commands or variable names, but if you use commands that produce many long completion candidates you probably don't want initialisms or flex on by default. Examples of such commands are `consult-line` and any of @bdarcus's bibtex-action commands. I bet people with 2000 entry bibtex files would tell you that initialism are both slow and not very helpful for bibtex-actions commands.

2021-05-15 22:47 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +does something else (give you previously used isearch search terms).
@andreiltd ctrlf is kind of independent from the whole `completing-read` stuff this module deals with, if we want to add it to doom it would probably fit best in it's own module.

2021-05-15 22:49 UTC, iyefrat commented
@minad @oantolin makes sense. I assume that regexp is on by default because it's too useful not to, and that you can force literal matching on long candidates if you need it?

2021-05-16 20:59 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +          (embark--quit-and-run
Duplicating the Embark internals seems like a recipe for breakage. Why are you not using `embark-export` and then change to wgrep mode?

2021-05-16 21:01 UTC, minad commented on modules/app/irc/autoload/irc.el
> +(defun +irc/selectrum-jump-to-channel (&optional this-server)
@iyefrat Thanks for the addition of the buffer source to the Consult wiki!

2021-05-16 22:33 UTC, iyefrat commented on modules/completion/selectrum/autoload/selectrum.el
> +          (embark--quit-and-run
@minad primarily the fact that currently `embark-consult-export-grep` uses `switch-to-buffer` and so doesn't open in a popup/other window (see oantolin/embark#216). I'm going to submit a PR soon to use `pop-to-buffer` for exports as @oantolin seemed amicable to the idea (main reason I haven't yet is that `embark-export-dired` is a bit finicky).

2021-05-16 22:36 UTC, oantolin commented on modules/completion/selectrum/autoload/selectrum.el
> +          (embark--quit-and-run
I'd appreciate a PR that does that, @iyefrat.

2021-05-16 23:20 UTC, oantolin commented on modules/completion/selectrum/config.el
> +  (embark-collect-mode . embark-consult-preview-minor-mode))
`embark-consult-preview-minor-mode` has been generalized and moved to Consult, you should use `consult-preview-at-point-mode` now instead.

2021-05-16 23:53 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (embark-collect-mode . embark-consult-preview-minor-mode))
@oantolin Thanks for the pointer, I'll keep that in mind in the next bump.

2021-05-17 04:26 UTC, minad commented on modules/completion/selectrum/TODO.org
> +~+selectrum-file-search~ is defined with ~cl-defun~?
The problem is that you overwrite `this-command` with `consult--grep`, see https://github.com/hlissner/doom-emacs/pull/4664/files#r579785461.

2021-05-17 04:27 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +  (let* ((this-command 'consult--grep)
@iyefrat See here regarding this-command.

2021-05-17 04:32 UTC, minad commented on modules/completion/selectrum/TODO.org
> +so it might be caused by some nontrivial doomism in the area.
@iyefrat The problem is that you overwrite the Selectrum filter and highlighting function with the orderless filter/highlighting function. This bypasses the completion styles logic. If you remove these function overrides you should be good. Unfortunately the highlighting won't be optimized then until https://github.com/raxod502/selectrum/issues/539 is implemented.

2021-05-17 04:56 UTC, minad commented on modules/completion/selectrum/TODO.org
> +so it might be caused by some nontrivial doomism in the area.
As a stop gap measure you may want to set the orderless-matching-styles to always include orderless-initialism. And then remove the custom orderless+initialism style you defined. Then potential downside is then that you may observe slowdown in some rare cases (see https://github.com/oantolin/orderless/issues/39 and https://github.com/oantolin/orderless/pull/51).

2021-05-17 10:21 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +~+selectrum-file-search~ is defined with ~cl-defun~?
@minad ah yes, you're right! seems this was a left-over from when this function was converted from ivy.

2021-05-17 10:38 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +so it might be caused by some nontrivial doomism in the area.
@minad I see, thanks!. I'll go with the unoptimized highlighting for now, from poking around with it the performance penalty isn't really noticeable. Do you know when it becomes relevant?

2021-05-17 12:30 UTC, iyefrat commented
@minad Ah, in that case I'll change the commit.

However, this caused me to realize, the initialisms aren't' even working on `describe-variable`, even on `emacs -Q` and without selectrum, while on e.g. `describe-function` they do. Can you replicate this? On emacs 27.2, open `emacs -Q` and eval the following:

```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)
(package-install 'orderless)
(require 'orderless)
(setq completion-styles '(orderless))
(orderless-define-completion-style orderless+initialism
  (orderless-matching-styles '(orderless-initialism
                               orderless-literal
                               orderless-regexp)))
(setq completion-category-overrides
      '((command (styles orderless+initialism))
        (symbol (styles orderless+initialism))))
(package-install 'marginalia)
(require 'marginalia)
(marginalia-mode +1)
```
After this `C-h f` gets initialisms but `C-h v` doesn't.

2021-05-17 12:32 UTC, minad commented
@iyefrat This does not work since variables get a separate `variable` category with Marginalia.

2021-05-17 12:37 UTC, iyefrat commented
@minad gotcha. @oantolin, you might want to note on the orderless readme that marginalia categories and emacs 28 categories are not exactly the same, I'd imagine `C-h v` not getting initialisms would trip a lot of people up when copy pasting from the readme.

2021-05-17 13:22 UTC, oantolin commented
> you might want to note on the orderless readme that marginalia categories and emacs 28 categories are not exactly the same

When they differ it's because Marginalia assigns a category and Emacs does not! I don't think we change any existing category, do we @minad?

2021-05-17 13:58 UTC, minad commented
@oantolin Yes, we do not change existing categories. This should stay like this, at least in the default configuration. But users are of course free to define arbitrary custom categories which refine the existing categories.

2021-05-18 11:05 UTC, minad commented on modules/completion/selectrum/config.el
> +   '(consult-bookmark consult-recent-file consult--grep consult-theme)))
@iyefrat You may also want to replace consult--grep with the actual command names, e.g. consult-ripgrep, consult-grep, your project search command etc. It is a bit tedious, since you have to mention every command individually.

2021-05-18 11:18 UTC, minad commented on modules/completion/selectrum/TODO.org
> +** TODO selectrum =SPC /= is much slower than ivy =SPC /=
@iyefrat We've made a few performance improvements in various packages, including Orderless, Consult, Selectrum and Vertico. If you bump the packages you can give it a check if the situation did indeed improve. Generally a profile would be helpful to locate the bottlenecks in the use case you are testing. From my latest tests, most time and memory is spent in `consult--grep-matches`.

2021-05-18 11:21 UTC, iyefrat commented
@minad @oantolin maybe I misunderstood, but from what minad said it seemed that for `C-h v` marginalia provides the `variable` category, while emacs 28 provides the `symbol` cateogry, meaning that following the instructions [here](https://github.com/oantolin/orderless#defining-custom-orderless-styles) stating that if you don't have emacs 28 installed you can just use marginalia might lead to confusion, sense users would expect `symbol` to over `C-h v` as well. I haven't been able to figure out where the documentation is for the built in emacs category stuff though, so I might be totally off.

2021-05-18 11:23 UTC, minad commented
@iyefrat 

> while emacs 28 provides the symbol cateogry

This is not correct. Emacs 28 does not provide a category. Take a look at `help--symbol-completion-table`.

2021-05-18 11:24 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +   '(consult-bookmark consult-recent-file consult--grep consult-theme)))
@minad good catch, I didn't notice that this didn't work on the search command.

2021-05-18 11:27 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +** TODO selectrum =SPC /= is much slower than ivy =SPC /=
@minad Neat, I'll look into this later and report back.

2021-05-18 11:33 UTC, minad commented on modules/completion/selectrum/TODO.org
> +** TODO selectrum =SPC /= is much slower than ivy =SPC /=
Note that the bottlenecks are highly dependent on how you interact with the UI. E.g. when you are scrolling around heavily probably more time is spent in the display functions. If you do not interact and let `consult-ripgrep` finish, then the bottleneck is mainly `consult--grep-matches`. These scenarios should be distinguished in case you collect some profiles.

2021-05-18 14:18 UTC, oantolin commented
> I haven't been able to figure out where the documentation is for the built in emacs category stuff though

THERE IS NONE. Or alternatively: THE ONLY DOCUMENTATION IS THE SOURCE CODE. 😛

2021-05-20 18:13 UTC, minad commented on modules/completion/selectrum/TODO.org
> +post-hoc changes to your typing), but having a one-off extention is inconsistant
My suggestion is to allow only `!not` and not `not!`. I originally had it like this and added the suffix variant only for consistency. When you type a negated literal you mostly know beforehand that you type something negated so the ! can always come first. Also `set!=` should dispatch to literal.

2021-05-20 18:39 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +post-hoc changes to your typing), but having a one-off extention is inconsistant
Yes this is my preference as well, I'll just change it, Henrik can always change it back if he disagrees.

2021-05-20 22:07 UTC, iyefrat commented
@oantolin true, but I'd prefer to export to a grep buffer if possible for consistency.

2021-05-20 22:18 UTC, oantolin commented
> @oantolin true, but I'd prefer to export to a grep buffer if possible for consistency.

Oh, I'd say there's no point in that, but of course, you should do that if you feel like it. I'm not sure how easy it will be. Both `consult-line` and `occur-mode` work with buffer, whether or not those buffers visit files. Maybe `grep-mode` and `wgrep` can also work with non-file buffers, but I'd be a little surprised if they do. If you insist on `wgrep` you might have to either generalize grep-mode and wgrep first, or give up on part of the functionality of `consult-line`.

2021-05-21 10:00 UTC, iyefrat commented
@oantolin Huh, I was unaware of this distinction. It sounds like using `occur-edit-mode` is indeed the more natural choice, I'll just document it under design decisions as it does slightly break the `C-c C-e`=`wgrep` convention.

2021-05-21 11:51 UTC, Zetagon commented
I get the error below when calling `embark-become` after calling `consult-buffer`. 
Ran in sandbox without personal config, and up to date packages (by running `doom sync -u`).

```
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) (map _target) (which-key--show-keymap "Embark" map nil nil 'no-paging) #'which-key--hide-popup-ignore-command) 1)
  (closure (t) (map _target) (which-key--show-keymap "Embark" map nil nil 'no-paging) #'which-key--hide-popup-ignore-command)((keymap (keymap (67 keymap (98 . consult-buffer)) (76 . find-library) (108 . locate) (98 . switch-to-buffer) (114 . recentf-open-files) (112 . project-find-file) (46 . find-file-at-point) (102 . find-file)) keymap (8 . embark-keymap-help)))
  embark--show-indicator((closure (t) (map _target) (which-key--show-keymap "Embark" map nil nil 'no-paging) #'which-key--hide-popup-ignore-command) (keymap (keymap (67 keymap (98 . consult-buffer)) (76 . find-library) (108 . locate) (98 . switch-to-buffer) (114 . recentf-open-files) (112 . project-find-file) (46 . find-file-at-point) (102 . find-file)) keymap (8 . embark-keymap-help)) nil)
  embark--with-indicator((closure (t) (map _target) (which-key--show-keymap "Embark" map nil nil 'no-paging) #'which-key--hide-popup-ignore-command) embark-keymap-prompter (keymap (keymap (67 keymap (98 . consult-buffer)) (76 . find-library) (108 . locate) (98 . switch-to-buffer) (114 . recentf-open-files) (112 . project-find-file) (46 . find-file-at-point) (102 . find-file)) keymap (8 . embark-keymap-help)))
  embark-become(nil)
  funcall-interactively(embark-become nil)
  call-interactively(embark-become nil nil)
  command-execute(embark-become)
  embark--act(embark-become "*scratch*" t)
  embark-act(nil)
  funcall-interactively(embark-act nil)
  call-interactively(embark-act nil nil)
  command-execute(embark-act)
  read-from-minibuffer("Switch to: " nil (keymap (8388619 . selectrum-goto-beginning) (8388618 . selectrum-goto-end) (backspace . +selectrum/backward-updir) (3 keymap (5 . +selectrum/embark-export-write) (15 . embark-export)) (15 . embark-act) (insert-state keymap (11 . previous-line) (10 . next-line) "Auxiliary keymap for Insert state") (33554443 . selectrum-previous-page) (33554442 . selectrum-next-page) (11 . selectrum-previous-candidate) (26 closure (t) (&rest _) (interactive) (condition-case nil (progn (call-interactively #'undo)) (error nil))) (23 . doom/delete-backward-word) (22 . yank) (21 . evil-delete-back-to-indentation) (18 . evil-paste-from-register) (1 . move-beginning-of-line) (escape . abort-recursive-edit) (19 . consult-history) (9 . selectrum-insert-current-candidate) (10 . selectrum-next-candidate) (C-M-backspace . selectrum-backward-kill-sexp) (27 keymap (11 . selectrum-previous-candidate) (10 . selectrum-next-candidate) (13 . selectrum-submit-exact-input) (109 . selectrum-quick-select) (105 . selectrum-quick-insert) (113 . selectrum-cycle-display-style) (67108991 . selectrum-backward-kill-sexp)) (remap keymap (backward-kill-sexp . selectrum-backward-kill-sexp) (previous-matching-history-element . selectrum-select-from-history) (kill-ring-save . selectrum-kill-ring-save) (end-of-buffer . selectrum-goto-end) (beginning-of-buffer . selectrum-goto-beginning) (minibuffer-beginning-of-buffer . selectrum-goto-beginning) (scroll-up-command . selectrum-next-page) (scroll-down-command . selectrum-previous-page) (exit-minibuffer . selectrum-select-current-candidate) (next-line-or-history-element . selectrum-next-candidate) (previous-line-or-history-element . selectrum-previous-candidate) (next-line . selectrum-next-candidate) (previous-line . selectrum-previous-candidate) (minibuffer-keyboard-quit . abort-recursive-edit) (keyboard-quit . abort-recursive-edit)) keymap (remap keymap (previous-matching-history-element . selectrum-select-from-history)) (insert-state keymap "Auxiliary keymap for Insert state" (11 . previous-line) (10 . next-line)) (33554443 . scroll-down-command) (33554442 . scroll-up-command) (11 . previous-line) (26 closure (t) (&rest _) (interactive) (condition-case nil (progn (call-interactively #'undo)) (error nil))) (23 . doom/delete-backward-word) (22 . yank) (21 . evil-delete-back-to-indentation) (18 . evil-paste-from-register) (1 . move-beginning-of-line) (escape . abort-recursive-edit) (19 . consult-history) (menu-bar keymap (minibuf "Minibuf" keymap (previous menu-item "Previous History Item" previous-history-element :help "Put previous minibuffer history element in the min...") (next menu-item "Next History Item" next-history-element :help "Put next minibuffer history element in the minibuf...") (isearch-backward menu-item "Isearch History Backward" isearch-backward :help "Incrementally search minibuffer history backward") (isearch-forward menu-item "Isearch History Forward" isearch-forward :help "Incrementally search minibuffer history forward") (return menu-item "Enter" exit-minibuffer :key-sequence "\15" :help "Terminate input and exit minibuffer") (quit menu-item "Quit" abort-recursive-edit :help "Abort input and exit minibuffer") "Minibuf")) (10 . next-line) (13 . exit-minibuffer) (7 . abort-recursive-edit) (C-tab . file-cache-minibuffer-complete) (9 . self-insert-command) (XF86Back . previous-history-element) (up . previous-line-or-history-element) (prior . previous-history-element) (XF86Forward . next-history-element) (down . next-line-or-history-element) (next . next-history-element) (27 keymap (60 . minibuffer-beginning-of-buffer) (114 . previous-matching-history-element) (115 . next-matching-history-element) (112 . previous-history-element) (110 . next-history-element))) nil consult--buffer-history #("*scratch*􀀁" 9 10 (invisible t consult-strip t)))
  selectrum--read("Switch to: " nil :initial-input nil :default-candidate #("*scratch*􀀁" 9 10 (invisible t consult-strip t)) :require-match nil :history consult--buffer-history :mc-table #f(compiled-function (str pred action) #<bytecode 0x1c9ae71>) :mc-predicate consult--multi-predicate)
  selectrum-completing-read("Switch to: " #f(compiled-function (str pred action) #<bytecode 0x1c9ae71>) consult--multi-predicate nil nil consult--buffer-history #("*scratch*􀀁" 9 10 (invisible t consult-strip t)) nil)
  completing-read("Switch to: " #f(compiled-function (str pred action) #<bytecode 0x1c9ae71>) consult--multi-predicate nil nil consult--buffer-history #("*scratch*􀀁" 9 10 (invisible t consult-strip t)))
  #f(compiled-function () #<bytecode 0x1c9adb1>)()
  consult--with-preview-1(any #f(compiled-function (arg0 restore) #<bytecode 0x1c9b9e5>) #f(compiled-function (input cand) #<bytecode 0x1c9b63d>) #f(compiled-function (&rest args2) #<bytecode 0x1c9b65d>) #f(compiled-function () #<bytecode 0x1c9adb1>))
  consult--read-1((#(" *Minibuf-0*􀀀" 0 12 (consult-multi ... face consult-buffer) 12 13 (invisible t consult-strip t)) #(" *code-conversion-work*􀀀" 0 23 (consult-multi ... face consult-buffer) 23 24 (invisible t consult-strip t)) #(" *Echo Area 0*􀀀" 0 14 (consult-multi ... face consult-buffer) 14 15 (invisible t consult-strip t)) #(" *Echo Area 1*􀀀" 0 14 (consult-multi ... face consult-buffer) 14 15 (invisible t consult-strip t)) #("*scratch*􀀁" 0 9 (consult-multi ... face consult-buffer) 9 10 (invisible t consult-strip t)) #("*Messages*􀀁" 0 10 (consult-multi ... face consult-buffer) 10 11 (invisible t consult-strip t)) #("*doom*􀀁" 0 6 (consult-multi ... face consult-buffer) 6 7 (invisible t consult-strip t)) #("~/.emacs.d/.local/etc/work..." 0 41 (consult-multi ... face consult-file) 41 42 (invisible t consult-strip t)) #("~/.emacs.d/.local/etc/book..." 0 31 (consult-multi ... face consult-file) 31 32 (invisible t consult-strip t)) #("~/Documents/dvkand/exjobb/..." 0 52 (consult-multi ... face consult-file) 52 53 (invisible t consult-strip t)) #("~/Documents/dvkand/exjobb/..." 0 47 (consult-multi ... face consult-file) 47 48 (invisible t consult-strip t)) #("~/Documents/dvkand/exjobb/..." 0 50 (consult-multi ... face consult-file) 50 51 (invisible t consult-s [...]

2021-05-21 15:09 UTC, iyefrat commented
This seems to be an upstream issue, reported on oantolin/embark#230

2021-05-21 22:41 UTC, hugonobrega commented
The default `embark-act` keybind `C-o` doesn't play well with evil-mode when one has `evil-want-minibuffer` set to true (because in that case `C-o` in the minibuffer does "toggle evil/emacs state for the next command")

2021-05-21 22:45 UTC, hugonobrega commented
This is a half-baked idea but could it make sense to have a "minibuffer-leader" key, and then have all of these minibuffer `selectrum-*`, `embark-*`, etc., commands under that key? I know `embark` things are also for regular buffers, so that may confuse things rather than help

2021-05-21 22:46 UTC, iyefrat commented
@hugonobrega 
> The default embark-act keybind C-o doesn't play well with evil-mode when one has evil-want-minibuffer set to true (because in that case C-o in the minibuffer does "toggle evil/emacs state for the next command")

Things like this are why I want to rebind it to `C-,` (or at least not `C-o`), as this interferes with using `embark-act` on regular buffers as well. I'm waiting to hear back from henrik before I do as I don't want to change keybindings a third time if we end up going with something else, but given this I might do it early. If anyone has any other suggestions I'd love to hear them, also for a leader key based binding if you have one (`:leader a` might end up being too ambitious since it's a top level binding, we'll see).

2021-05-21 22:48 UTC, iyefrat commented
@hugonobrega 
> This is a half-baked idea but could it make sense to have a "minibuffer-leader" key, and then have all of these minibuffer selectrum-*, embark-*, etc., commands under that key? I know embark things are also for regular buffers, so that may confuse things rather than help

The `embark-act` is basically that leader key, and I'm not really sure what minibuffer selectrum commands there are that would fit there. There are a few others, `C-c C-e` is staying there due to convention, but `C-c C-o` might change, especially if we move `C-o`

2021-05-21 22:52 UTC, hugonobrega commented
@iyefrat 
> The `embark-act` is basically that leader key, and I'm not really sure what minibuffer selectrum commands there are that would fit there. There are a few others, `C-c C-e` is staying there due to convention, but `C-c C-o` might change, especially if we move `C-o`
I am counting 12 `selectrum-*` commands that are bound to top-level keys for me in the minibuffer. But, just like with `ivy`, the fact that they are not under some prefix makes them hard to discover just using `which-key` (as you know, this is part of why I am writing that other package to help with discovery)

2021-05-21 22:55 UTC, iyefrat commented
@hugonobrega true, but I don't think any of them really fit under a prefix key, so it's best to just use the other package anyway for this type of thing I think

2021-05-21 22:58 UTC, hugonobrega commented
I disagree, in my opinion I could see myself really liking a keybind like `<leader> a q` for `selectrum-quick-select` (which is currently under `M-m` in the minibuffer)

2021-05-22 01:56 UTC, hugonobrega commented
I'm very bad at collaborating on github, so I know this isn't the best way to do this, but anyway this:
```
(use-package! embark-consult
  :after (embark consult)
  :demand t
  :hook
  (embark-collect-mode . consult-preview-minor-mode))
```
should be
```
(use-package! embark-consult
  :after (embark consult)
  :demand t
  :hook
  (embark-collect-mode . embark-consult-preview-minor-mode))
```

2021-05-22 02:39 UTC, oantolin commented
@hugonobrega this depends on the versions of the packages that have been pinened. For older versions of consult and embark-consult you are correct, but I believe they've pinned more recent version where embark-consult-preview-minor-mode has been removed. In these recent version it shouldn't be `consult-preview-minor-mode` however, but `consult-preview-at-point-mode`.

2021-05-22 13:36 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +  (unless (string-match-p "^consult" (symbol-name selectrum--last-command))
Alternatively you can use `(bound-and-true-p consult--preview-function)` instead of `(string-match-p "^consult" (symbol-name selectrum--last-command)`. This variable will only be set by Consult commands with preview and is probably more what you are looking for here, since there are also Consult commands without preview.

2021-05-22 13:39 UTC, minad commented on modules/completion/selectrum/config.el
> +     consult--grep consult-grep consult-ripgrep consult-git-grep +default/search-project)))
I just added a `consult-customize` macro which should make this use case a bit simpler:

~~~ elisp
  (consult-customize
   consult-ripgrep consult-git-grep consult-grep consult-bookmark consult-recent-file
   +default/search-project ;; TODO add more search-project commands, e.g., search at point
   consult--source-file consult--source-project-file consult--source-bookmark
   :preview-key (list (kbd "C-SPC") (kbd "C-M-j") (kbd "C-M-k"))
~~~

Note that every command and buffer source must be listed individually.

2021-05-22 20:19 UTC, iyefrat commented on modules/completion/selectrum/autoload/selectrum.el
> +  (unless (string-match-p "^consult" (symbol-name selectrum--last-command))
Ah, much better. Thanks!

2021-05-22 20:19 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +     consult--grep consult-grep consult-ripgrep consult-git-grep +default/search-project)))
Great, I'll change it to this after the next package bump.

2021-05-23 12:15 UTC, iyefrat commented
Attention Selectrum PR users! The `embark-act` binding has changed. It is now bound to both `<leader> a` and `C-;`, since these conflict less with evil (like `C-o` does), and are nicer. Note that there are **not final**, and are subject to change at Henrik's eventual review.

2021-05-23 14:05 UTC, oantolin commented
> C-;

That's what I use. 😃

2021-05-23 21:31 UTC, bdarcus commented
You notice this @iyefrat?

``` console
In +selectrum-orderless-match-with-one-face:
autoloads.28.0.50.el:712:448: Warning: Unused lexical variable
    `orderless-match-faces'
```

2021-05-23 21:52 UTC, iyefrat commented
@bdarcus yeah it's documented under TODO.org, I just haven't figured out how to solve it yet.

2021-05-25 07:26 UTC, Zetagon commented
With the latest commits (with the new keybinding for embark-act) I get this warning `Warning (iedit): Iedit default key "C-;" is occupied by embark-act.` when I use `projectile-switch-project`. It's (very mildly) annoying at worst.

2021-05-25 09:23 UTC, iyefrat commented
@Zetagon I can't reproduce this, assuming that what you meant is doing `SPC p p` to switch projects. Does this warning show up in a backtrace? are your github dotfiles up to date?

2021-05-26 00:05 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +     consult--grep consult-grep consult-ripgrep consult-git-grep +default/search-project)))
@minad in `consult--customize-set` the `user-error` is missing the input for `%s` which leads to unhelpful error messages. I'd PR the fix but I don't have copyright assignment :).

2021-05-26 00:11 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +   :preview-key (list (kbd "C-SPC") (kbd "C-M-j") (kbd "C-M-k")))
@minad all of the `+default/search-.*` commands are there because it seems I can't say "anything that uses `consult--grep`". Is this something that is feasible to add to `consult-customize`?

2021-05-26 05:37 UTC, minad commented on modules/completion/selectrum/config.el
> +   :preview-key (list (kbd "C-SPC") (kbd "C-M-j") (kbd "C-M-k")))
No there is no inheritance mechanism. Commands must be listed individually.

2021-05-26 05:47 UTC, minad commented on modules/completion/selectrum/config.el
> +   :preview-key (list (kbd "C-SPC") (kbd "C-M-j") (kbd "C-M-k")))
1. I could define a consult-file-preview-key which is then used by default for the grep commands. But this would introduce a second configuration mechanism on top on top of consult-customize.
2. I could introduce an inheritance mechanism or you define it yourself. For example add consult--parent-command which is set in consult--grep to 'consult--grep or even a list of parent commands.

I am not sure if these are worth the complications.

2021-05-26 07:25 UTC, Zetagon commented
> I can't reproduce this, assuming that what you meant is doing `SPC p p`
> to switch projects. Does this warning show up in a backtrace? are your github
> dotfiles up to date?
I think the relevant parts of my github dotfiles are up to date. I tried with the sandbox without my config but the warning still appears. I'm not sure which commands that trigger this, today I tried with `consult-recent-file` which also gives the same warning. Additionally I got this warning: `Ignoring unsafe form in file local variable: (progn (require 'projectile) (puthash (projectile-project-root) "cask exec buttercup -L ." projectile-test-cmd-map))` 

It does not trigger anything a backtrace with `M-x toggle-debug-on-init`

2021-05-26 09:06 UTC, Zetagon commented
With `find-file` `.` is not an available candidate. In the ivy module the current directory is the default candidate which is useful because it makes it easy to switch directories this way.  It might make sense to have it be this way in the selectrum module too.


`dired-do-rename` gives the first file as default target. This is potentially harmful because it can overwrite files. It is better to give the directory as default target here so that by default no file name change happens (but directory changes, i.e. moving the file still happpens).

2021-05-26 09:34 UTC, iyefrat commented
> With find-file . is not an available candidate. In the ivy module the current directory is the default candidate which is useful because it makes it easy to switch directories this way. It might make sense to have it be this way in the selectrum module too.

This seems to be default selectrum behavior. I would at least like to have the option to do this, but it requires further investigation

> dired-do-rename gives the first file as default target. This is potentially harmful because it can overwrite files. It is better to give the directory as default target here so that by default no file name change happens (but directory changes, i.e. moving the file still happpens).

I agree, which is odd because if you just do `find-file` you have no default target, unsure what's happening there.

2021-05-28 12:59 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
By using `minibuffer-local-map` instead of `selectrum-minibuffer-map` everywhere in this PR, this module can work with different completion UIs like Icomplete-vertical or my Vertico. Besides some explicit calls to some Selectrum functions there are no features here which necessarily tie this PR to Selectrum. By decoupling that a little more you can test against different other existing completion UIs (at least Vertico and Icomplete-vertical, which work sufficiently similar to Selectrum). Hopefully this also helps with long-term maintenance.

However the name of the module is not such a good fit anymore then. What about some acronym module name?

* +comes (consult, orderless, marginalia, embark, selectrum)
* +moves (marginalia, orderless, vertical or vertico :D, embark, selectrum)
* +coves (consult, orderless, vertical or vertico :D, embark, selectrum)

Another alternative would be `+standard` since we are just plugging components together here, which revolve around the standard completion system. But I guess that's too bold ;)

It seems there is a long list of TODOs here and my intention is not to derail any of the existing discussions. And you are already using more than enough of my packages. So I hope this does not come across too much as me trying to sell you more of my stuff. The thing what I would rather like to sell you is the idea of having these composable building blocks, where you keep the ability to replace components ;)

In my personal config I have selectrum, vertico and icomplete-vertical installed since I need all of those for testing. I can switch between the UIs by executing ` (vertico-mode -1) (selectrum-mode 1)` and vice versa.

2021-05-28 13:14 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
I've mentioned this on discord recently as well; the general idea to avoid unnecessary dependency on selectrum, and also a more general name to reflect that.

I think it's better for both doom and for its users long-term to keep this as flexible as possible. 

For me personally, I sometimes go back-and-forth between selectrum and vertico, and I see no reason why that shouldn't be possible. Indeed, for my simple use cases, vertico already works well with this module.

@minad - the `+` convention signals module flags. So really what we're talking is something like `(standard +vertico)` or `(standard +selectrum)`.

2021-05-28 13:45 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
I had actually raised this on discord yesterday, and @hlissner has pushed back a bit.

Here's the reply I just posted, which hopefully makes sense:

> Both selectrum and vertico are vertical completing-read based completion UIs. I personally slighly prefer vertico, though they are pretty equivalent. But who knows how that evolves in the future. Vertico, for example, is on ELPA. Perhaps it, or something similar, ends up in core Emacs at some point?
>
> The distinctiveness of the selectrum module, and very different from the ivy and helm equivalents, is it's based on this new generation of packages, all of which are based on the built-in completing-read API, and  so one can mix-and-match different pieces of functionality. 
>
> Even if you don't want to formally include vertico now, it might be wise to have a broader name for the module, and have selectrum a flag. 
>
> Then, if some other completion UI, vertico or something else, made sense in the future, it would just be a question of adding a flag for it, as opposed to an entire module.

2021-05-28 17:45 UTC, Zetagon commented
I think I've found a bug. Seems to appear when selectrum and embark interact. I've been able to reproduce in the doom sandbox (-my config). It doesn't happen when only `embark` is loaded.

To reproduce:
1) `embark-act` in a normal buffer
2) Press `C-h` 
2) Press `C-g`
3) Now most keybindings are undefined. The only consistent way to get out of this state that I have been able to find is to press `m` which brings up a compose email buffer.

2021-05-28 20:03 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
Yeah I agree that things that aren't selectrum specific should be bound to `minibuffer-local-map`, But some of them are (like `selectrum-next-candidate` etc.

There has been some discussion on the discord regarding adding a vertico flag to the module, and personally I'm not opposed to it if the maintenance burden is small, but Henrik has final say on this sort of thing and he seemed unsure on what the benefit would be. I think the only time we use something that directly depends on selectrum is `selectrum-repeat`, since I don't think that vertico has that, but I haven't properly checked. I always meant to try out using vertico with this module instead of selectrum just for fun, but haven't really gotten around to that yet (which is why I only have an educated guess on the maintenance burden being small).

Regarding the potential name if we do end up doing this, I'm a bit split, because on the one had I want to say that the acronyms aren't that descriptive to the end user, but neither is something like `standard` or `built-in` (since they don't mention completion, which is the category name so it can't really be used). The acronyms do refer back to the module name though so that might be enough, it's just something that you can't google directly, but then again what does doom have documentation for. But an acronym name does lock the module into those specific packages, and if the whole point is composability they might change over time.

Oh and also feel free to derail this thread at literally any time, I value your input. The ship has sailed on having a concise thread anyway, might as well enjoy the advantages of having a neverending one :D.

2021-05-28 20:15 UTC, iyefrat commented
@Zetagon wow that is weird. Seems like this is because you get dropped to using the `minibuffer-inactive-mode-map` somehow. You can also get out of it by clicking on the buffer with your mouse. I'll look into it.

2021-05-28 20:46 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
(oh also for some reason the webpage didn't load anything past minad's first post until I refreshed it, which is why don't acknowledge the fact that @bdarcus already mentioned the discord discussion)

2021-05-28 21:23 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
Yes, a repeat command does not exist, but I have an independent replacement in https://github.com/minad/uchronia. I haven't found a real need for such a command, therefore I haven't packaged that up properly.

About the acronym you are of course right. I just thought it could be a good starting point to find a name in the style of embark etc ;)

I think the most important point is to have everything here as generic as possible. Only reference consult/selectrum/embark etc where strictly necessary. Then the module can be adapted to a changing landscape.

2021-05-29 11:54 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
> Yes, a repeat command does not exist, but I have an independent replacement in https://github.com/minad/uchronia. I haven't found a real need for such a command, therefore I haven't packaged that up properly.

My main use for it is when using grep type commands and moving through the options, but using `embark-export` is probably a better way to go about that in the long run (although for the moment there are some odd window opening issues with that)

> About the acronym you are of course right. I just thought it could be a good starting point to find a name in the style of embark etc ;)

lmao embark being an acronym totally went over my head until now

> I think the most important point is to have everything here as generic as possible. Only reference consult/selectrum/embark etc where strictly necessary. Then the module can be adapted to a changing landscape.

I agree 100%

2021-06-01 12:57 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq embark-target-finders
setq is not a good idea here. Better use add-to-list for your custom extensions instead and ensure via some other means that you target finder appears at the right spot.

2021-06-01 13:08 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (setq embark-target-finders
@minad I assume it isn't a good idea because more target finders might be added in the future? Either way, do you have a recommendation for how to make sure it appears in the right spot without doing that? I thought of using `add-hook` with the `depth` input but it seems that the `defcustom` puts all of them at depth 0.

2021-06-01 13:09 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq embark-target-finders
Think of it as a hook list. Other packages also add their hooks there, e.g., embark-consult. And I am pretty sure embark will add more finders over time. All good reasons to not use the setq sledgehammer here.

Btw I like what you are doing here - I assume there are many more doomisms for which you could add special actions. This is a great use of Embark! I believe @oantolin also has a few more custom finders in his config, at least he experimented with hyperbole style links a short while ago.

2021-06-01 13:13 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq embark-target-finders
Maybe use some insert-before or insert-after list functions? Sth like this probably exists in seq or dash.

2021-06-01 17:50 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq embark-target-finders
Looks pretty complicated your solution. Is there no helper function you could use or write? add-to-list-after?

2021-06-01 21:59 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (setq embark-target-finders
The function `list-utils-insert-before` does exactly what I want, but doom doesn't use the `list-utils` library (or `dash` for that matter) so I'm only left to use default libraries. A more readable solution might have been to use `seq-take` and `seq-drop` instead of `cl-callf2, but since doom loads `cl-lib` by default but not `seq`, I thought it would be best to stick to the all `cl-lib` solution. Also credit where credit's due @ymarco came up with most of it.

2021-06-02 00:03 UTC, ymarco commented on modules/completion/selectrum/config.el
> +        (search-backward "(")
You probably want to make the 3th argument to `search-backward` (`noerror`) to `t`; otherwise you crash embark when the search is not found. Actually, why not use `doom--package-at-point`? (I figured doom would have something like this so I looked into how `doom/bump-package-at-point` is implemented.)

2021-06-02 00:09 UTC, ymarco commented on modules/completion/selectrum/config.el
> +  (setq embark-target-finders
That code definitely deserves at least a comment

2021-06-02 07:42 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq embark-target-finders
Off-topic: I wonder about dash. Of course I appreciate it if one stick only to the built-ins. For example I am only using `seq` and `cl-lib` in my packages which are good enough and I don't really see a need to use any of s,f,ht,dash. But isn't it the case that Doom necessarily depends on a package which pulls in dash as a transitive dependency? This is what I had assumed. But even then in the light of replacing components, the decision to rely only on built-ins is a good one :)

2021-06-02 08:50 UTC, iyefrat reviewed
wait i have no idea why but github isn't letting me reply to the review thread. it automatically converts it to a general review, and doesn't even let me cancel the comment. weird.

2021-06-02 08:54 UTC, minad commented
> ...does actually get dash through a transitive dependency. I don't know from where though, and relying on that seems like bad practice.

Of course, it would only be a good practice if dash gets formally upgraded to a direct dependency after realizing that it is a necessary transitive dependency. Since this seems not to be the case in the Doom core, you are correct to not use it.

2021-06-02 12:11 UTC, ymarco commented
> but doom-core (the portion of doom that gets loaded even if you have no modules activated, modules being doom's built in "batteries included defaults" for various things more or less) does actually get dash through a transitive dependency. 

Maybe from `helpful`? [helpful uses dash](https://github.com/Wilfred/helpful/blob/7e4b1f0d5572a4e2b8ee7a9b084ef863d0315a73/helpful.el#L9), [doom core installs helpful](https://github.com/hlissner/doom-emacs/blob/4dceae18269629e99dd51a3d0b6826a84a256133/core/packages.el#L37).
I agree that since dash isn't a direct dependency, not making it one is probably better.

2021-06-02 12:14 UTC, iyefrat reviewed
@ymarco honestly i wouldn't be surprised if there are multiple packages in doom core that depend on dash (this is a review because github is dumb)

2021-06-04 11:27 UTC, bdarcus commented
@iyefrat - not sure if this is something about the config here, but there is one piece of awkwardness for me when using `find-file`.

If I have a directory of, for example, multiple "foo" file names, with different extensions (in this case, an  org file and different tex files), if I type "f" and hit tab, it will simply complete the first one fully, without stopping at the period (which is what I expect). So I then have to backspace, etc.

2021-06-04 12:00 UTC, minad commented
@bdarcus This is expected behavior in Selectrum and Vertico. Tabbing inserts the currently selected candidate. This is different from usual TAB completion, which does prefix completion and does not take the current selection into account. Furthermore prefix completion does not work at all nicely with orderless, since the orderless filter string is usually not a prefix but an unordered list of filter words. See https://github.com/minad/vertico#tab-completion for more information.

2021-06-04 12:11 UTC, minad commented
@bdarcus to expand a bit on this - there are the two "philosophies" of doing completion, either using (1) TAB/shell-style/prefix completion or using (2) orderless-style completion.

(1) Enter "foo TAB", completes to "foobar.", enter "org RET"
(2) Enter "foo SPC org RET"

Usually it does not make sense to combine the two completion approaches and Selectrum/Vertico focus on (2). But both should also support TAB completion if one rebinds the usual `minibuffer-complete` commands. See also https://github.com/raxod502/selectrum/issues/272.

2021-06-04 12:29 UTC, bdarcus commented
Thanks @minad.

So what do you suggest for this module: simply clear documentation?

2021-06-04 12:33 UTC, minad commented
No idea honestly, it is very much a matter of taste. If one chooses (2) a lot of shell-style-completion fans will come and complain and tell you that they want to complete prefixes. Then the (2) defenders will tell you that prefix completion does not lead to progress (this is not strictly true, but almost).

2021-06-04 13:01 UTC, iyefrat commented
@bdarcus I noticed this awkwardness too but didn't give it much thought until you mentioned it explicitly. This is one of those things for Henrik to ultimately decide on but since I'm pro orderless style completion for basically the same reasons that @minad said, for the time being I'll document it in the readme and add a note. Imo once you consciously realize what is happening you can just fix your muscle memory and not lose any benefits.

2021-06-09 19:02 UTC, bdarcus commented
@iyefrat - I see you've done a bit with at-point and embark, which I only learned about today.

Am I correct in my thinking here, that what this would mean in practice is if one has point on an `org-cite` citation, and an associated keymap configured for `embark`, invoking `embark-act` would bring up a which-key menu with those commands?

https://github.com/bdarcus/bibtex-actions/issues/141

As in, effectively this will give us an extremely lightweight and flexible alternative to `org-ref`?

2021-06-11 13:06 UTC, iyefrat commented
@bdarcus I'm not really familiar with `org-ref`, but I think so. Imo a good mental model for `embark-act` is a context sensitive leader key.

2021-06-13 20:28 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! "C-;"               #'embark-act  ; to be moved to :config default if accepted
@iyefrat You may also want to bind `embark-dwim`? `embark-dwim` is like left-click and `embark-act` is like a right-click context menu :)

See https://github.com/oantolin/embark/commit/206e626fb50aab9ef0af4f2d861ea5f6950b6e49 (merged just now)

2021-06-14 14:23 UTC, minad commented on modules/completion/selectrum/config.el
> +   :preview-key (list (kbd "C-SPC") (kbd "C-M-j") (kbd "C-M-k"))))
@iyefrat One more recent preview addition is debouncing, e.g., 

~~~ elisp
(consult-customize consult-theme :preview-key '(:debounce 0.5 any))
~~~

You may want to use this for the commands where preview is a bit slow, e.g., `consult-theme`, but where an automatic preview is still desired.

2021-06-16 11:24 UTC, daanturo commented on modules/completion/selectrum/config.el
> +  (setq completion-styles '(orderless)
Code completion with `company` was so weird when `completion-styles` is set to `'(orderless)` only.

In Emacs Lisp mode, when I type `set`, the first candidate to appear was `(setf seq-elt)` even though `set`, `setq`, `setf`, etc. were expected instead.
![image](https://user-images.githubusercontent.com/32123754/122210157-87fd2b00-cecf-11eb-834e-f0e2df4d9ca9.png)

Appending, rather than setting so a single style, seems to revert `company` to it's old behavior but `M-x` is still sorted.
```lisp
(add-to-list 'completion-styles 'orderless t)
```

2021-06-16 16:40 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (map! "C-;"               #'embark-act  ; to be moved to :config default if accepted
@minad Yeah probably. It seems like `embark-dwim` is primarily meant to be used on buffers, yeah? Since when using embark on the minibuffer it does the same thing as `RET` as far as i can tell from the keymaps.

2021-06-16 16:42 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +   :preview-key (list (kbd "C-SPC") (kbd "C-M-j") (kbd "C-M-k"))))
@minad Oh this is a very good addition to consult! There was a good chance that automatic previews on `consult-theme` would end up being deactivated by default due to doom's focus on responsiveness, but this might keep them around. At the very least I'll keep this around in my private config :grin:

2021-06-16 17:06 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (setq completion-styles '(orderless)
@daanturo Hmm. I'm not sure if this is the best way to solve this, I need to look into it more to make sure there aren't any unintended consequences. There also seem to be some discussions in orderless issues that relate to this as well.

2021-06-16 18:15 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! "C-;"               #'embark-act  ; to be moved to :config default if accepted
It does the same as RET, however it is useful if you want to keep the minibuffer open.

2021-06-16 18:17 UTC, minad commented on modules/completion/selectrum/config.el
> +   :preview-key (list (kbd "C-SPC") (kbd "C-M-j") (kbd "C-M-k"))))
Very good. Consult generally also has a focus on responsiveness or at least it can be configured to be responsive. But these configurations must really be done on a per command basis, since it all depends. For example consult-buffer previews are always responsive in my configuration. But this is not generally the case - in some setups buffer switching is more expensive and profits from debouncing.

2021-06-16 18:19 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq completion-styles '(orderless)
In my opinion completion at point (Company, Corfu etc) should be treated differently than minibuffer completion. Therefore you may want to configure a separate completion style for company. Unfortunately this is not possible ootb and requires advices to Company/Corfu such that a special completion style is used.

2021-06-16 18:46 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (map! "C-;"               #'embark-act  ; to be moved to :config default if accepted
ah, right.

2021-06-16 18:49 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (setq completion-styles '(orderless)
yeah but the weird thing is that it seems under `C-h f` for example, it seems to prioritize the shorter matches first, while in company it seems to just sort them in alphabetical order. Do selectrum and vertico add some extra sorting on the list of matched candidates or something?

2021-06-16 20:36 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq completion-styles '(orderless)
I don't know about the Company sorting, this should be unaffected. Vertico and Selectrum sort by history position, length and alphabetical.

2021-06-17 15:48 UTC, bdarcus commented
@iyefrat - on the "bibtex-actions improvements?" todo issue about menus.

We actually have a WIP progress PR to add `embark-act` at-point functionality, which includes as well a keymap specific to that.

Ideally, I'd like to get these "simple menus" with descriptoins working in `which-key` and, by extension, Doom. 

https://github.com/bdarcus/bibtex-actions/pull/57/commits/33a9617194b31dbfd036513a7cf05b6b8c2a534e

But I never had any success, and it seems it has to wait on an unmerged, and stagnant, `which-key` PR.

If necessary, I can just provide the Doom-specific mapping, so we get nice and consistent menus with `embark-act` both at-point and in-buffer.

2021-06-18 15:32 UTC, minad commented on modules/app/irc/autoload/selectrum.el
> +  (consult--multi (list (plist-put +irc--consult-circe-source
plist-put modifies the list in place. You may want to use `(plist-put (copy-sequence ...) ...)` instead.

2021-06-18 20:19 UTC, iyefrat commented on modules/app/irc/autoload/selectrum.el
> +  (consult--multi (list (plist-put +irc--consult-circe-source
ack! damn side effects. will fix!

2021-06-18 20:28 UTC, iyefrat commented
@bdarcus the main issue is that it seems you can't to autoload keymaps, meaning that I can't just bind `bibtex-actions-map` to `SPC n b` which would be the best solution. The `embark-act` functionality is cool, but sort of separate from this since the binding doesn't necessarily act on a thing at point.

I have tried to just copy the keymap by hand to doom, which unfortunately means that we'd have to keep it up to date manually, but that is probably not that much work. The main reason I haven't added it to the pr yet is that I couldn't get the which-key descriptions to work (seems to be some issue with adding the descriptions to the keymap and not the bindings, but doom seems to be able to handle that in other cases).

Also do note that the bibtex-actions pin in doom is pretty out of date, I plan on updating it when the PR is close to merging in order to reduce noise in the commit history, but I'll bump it early if it's required for configuration, if that's relevant.

2021-06-19 23:02 UTC, bdarcus commented
FYI, new `which-key` PR in need of testing; adds simple menu support, which in turns works with `embark-act`.

https://github.com/justbur/emacs-which-key/pull/308

![Screenshot from 2021-06-19 18-57-31](https://user-images.githubusercontent.com/1134/122657304-6fd81680-d130-11eb-84c5-0673ef977bc1.png)

2021-06-20 19:28 UTC, minad commented
@bdarcus 

> I'm starting to wonder if which-key is the right interface for embark-act. I can override it to use the completing-read prompter, but might be nice to have this a customization option?

Note that which-key is not the prompter. Embark uses the keymap prompter by default, which is efficient to use! If you press C-h then you get the completing-read prompter. But I don't recommend to use the completing-read prompter by default.

Which-key is only the action indicator which indicates that the keymap prompter is active. You could write your own action indicator which opens a window and shows all the actions in a hydra-style for example. But since Embark uses keymaps which-key seems to be exactly the right UI for this. This will help consistency in the overall configuration.

It is a matter of preference if a timer-based which-key is a desired UI. As I mentioned before, I am not using it anymore. I don't want to see spurious which-key popups or I don't want to wait for the popup to arrive in case I don't recall the keybinding. Then I prefer to press C-h and summon `embark-prefix-help-command` which is once again a completing read prompter :)
I assume doom has an option to disable which-key or to summon it explicitly?

2021-06-20 20:37 UTC, bdarcus commented
> 2\. embark-prefix-help-command after C-h keypress (my config)

So to get this behavior in the current branch code, one would need to do this I guess?

``` elisp
;; turn off which-key prompter
(setq embark-action-indicator nil)
(setq prefix-help-command #'embark-prefix-help-command)
```

> which-key timer-based (doom uses this by default?)

Yes.

2021-06-21 07:53 UTC, minad commented
> So to get this behavior in the current branch code, one would need to do this I guess?

Not exactly. The action indicator is unrelated from the `prefix-help-command`.  If you don't want to use the which-key action indicator you should leave the action indicator at the default value, which shows the overlay "Act" in the minibuffer. The `embark-prefix-help-command` is an alternative to `describe-prefix-bindings` but is not related to actions. It just happens to be part of Embark since Embark already comes with the prompter infrastructure. Therefore the `embark-prefix-help-command` was a cheap and natural addition there.

2021-06-25 11:51 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
Given the complexity of this PR you may also want to consider writing your own repeat command :grimacing

For example the following simple snippet provides a generic `minibuffer-repeat` command:

~~~ elisp
(defvar minibuffer-repeat--input nil)
(defvar minibuffer-repeat--command nil)

(defun minibuffer-repeat--record-input ()
  (setq minibuffer-repeat--input (minibuffer-contents-no-properties)))

(defun minibuffer-repeat--setup ()
  (let ((cmd (if (boundp 'minibuffer-current-command)
                 minibuffer-current-command
               this-command)))
    (unless (eq cmd #'minibuffer-repeat)
      (setq minibuffer-repeat--command cmd)
      (add-hook 'post-command-hook #'minibuffer-repeat--record-input nil 'local))))

(defun minibuffer-repeat ()
  (interactive)
  (unless minibuffer-repeat--command
    (user-error "No repeatable command"))
  (minibuffer-with-setup-hook
      (lambda ()
        (delete-minibuffer-contents)
        (insert minibuffer-repeat--input))
    (command-execute minibuffer-repeat--command)))

(add-hook 'minibuffer-setup-hook #'minibuffer-repeat--setup)
(global-set-key (kbd "M-r") #'minibuffer-repeat)
~~~

This does not restore the full state of the completion UI (only the input string).

2021-06-26 12:38 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
@minad The advantage of this being that the repeat would work for all minibuffer commands rather than just selectrum commands yeah? (and also that it would work if we ever want to add a vertico flag or something, which is not super likely, but who knows).

> This does not restore the full state of the completion UI (only the input string).

Is `selectrum-repeat` supposed to do that? Because it not doing this is something I've been meaning to bring up as an issue, I've just been a bit busy lately. It's useful for going through a bunch of options one at a time,l although a good alternative for that workflow is using a persistent embark export window instead, which has a window layout bug at the moment.

2021-06-26 12:52 UTC, iyefrat commented
@bdarcus @minad is is not really clear what the `menu-item` support does here, and looking it up in the docs hasn't really led to anywhere clear. It looks like it is a round about way for getting `which-key` descriptions?

re: doom and `which-key`, it's a core package, so the assumption is that most people will use it. I generally use it for embark discoverability, but using `embark-prefix-help-command` and searching for keywords might be faster :stuck_out_tongue:. Either way it would be good if the `C` binding had a description on it with which key, which it might with the new `menu-item` additions, i haven't checked yet, but this isn't a very high priority so I haven't really looked into it yet.

2021-06-26 14:03 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
> and also that it would work if we ever want to add a vertico flag or
  something, which is not super likely, but who knows

Yes, I meant in case you want to support other completion UIs. A side effect is
that one could restart other minibuffer commands, but maybe that's not even
desired. As I mentioned before, I consider such a repeat command a misfeature.
There is already embark-export and the minibuffer history etc. A repeat command
is a fragile ad-hoc addition which does not fit very well together with the
other features.

> Is selectrum-repeat supposed to do that?

I am not sure. I think `selectrum-repeat` has a few issues. We have even
discussed a while ago on the Selectrum tracker to drop this command. But I don't
think that this will happen now since users rely on this functionality.

> (and also that it would work if we ever want to add a vertico flag or
  something, which is not super likely, but who knows).

Regarding supporting different UIs via feature flags - I am not sure if this is
needed. It is easier to decide on one UI and use this one throughout. But the
way the module is made now locks you to Selectrum and this does not seem like a
fortunate decision, since you restrict your ability to replace this component.
Given that a bit of work has gone into this PR, it would be good if this ends up
in a form which is "future proof". This does not mean that no other completion
system can come along which changes everything. But at least the area of modest
completion systems which rely on the Emacs APIs as much as possible could be
covered by this module in the longer term.

Admittedly not every component of the setup can be replaced easily. By their
nature, Embark and Consult are hard to replace. But at least for the completion
styles/orderless and the UIs there exist multiple viable alternatives. Note that
Emacs 28 will come with an improved icomplete-vertical-mode. Probably only a
name change of the module would do. Unfortunately I don't have good names
besides the acronyms I proposed before.

> a persistent embark export window instead, which has a window layout bug at
  the moment.

Which bug is that? You probably reported it on the Embark issue tracker?

Btw. are there hard blockers for this PR?

2021-06-26 14:05 UTC, minad commented
> edit: hmm it also seems that which-key doesn't refresh when pressing C. Not sure if that's a doom thing or a general bug, I'll check later.

See https://github.com/oantolin/embark/issues/139

2021-06-26 15:03 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
> Regarding supporting different UIs via feature flags...

I haven't properly checked yet by trying to use Vertico instead, but I'm pretty sure that the module isn't tied that much to Selectrum.  The only Selectrum specific things are the Selectrum `use-package`, `selectrum-prescient` which will likely be dropped after the review anyway, the navigation keybindings and `selectrum-repeat`, which I would have to recreate for e.g. Vertico because I don't think that having a minibuffer version is a good idea, since it'll get a bunch of false positives from evil commands. My estimate for moving the module to use Vertico instead is like a few hours, but famous last words. But at any rate I'm not sure how the module could be made to be more completion pakcage agnostic than it already is.

> Which bug is that? You probably reported it on the Embark issue tracker?
Btw. are there other hard blockers for this PR?

The hard blockers are the following (from the `TODO.org`):

```org
* PROJ Review blocking Issues

** TODO Embark export window buffer switching logic
If we export bookmarks, grep session, or ~find-file~ session, when pressing
enter, it opens the new buffer in another window rather than the main one, even
though at least the bookmark function ostensibly uses
~pop-to-buffer-same-window~. Ivy gets the window switched in the bookmarks and
grep case due to a custom ivy occur window switching function.

** TODO Icons
Partially solved, seems to have interaction with selectrum height issue, so not yet implemented.

** TODO Profile selectrum =SPC /= vs ivy =SPC /=

** TODO ~(defadvice! +orderless-match-with-one-face..~ causes lexical error
probably caused by some doomism
https://github.com/oantolin/orderless/issues/41
```
I think the export window one is a doom specific bug, caused by the `display-buffer-alist` modifications, but I'm not sure, I checked this out a while ago and kind of left it aside, but I'll look into it again soon as it's one of the few things left.

The Icon one is blocked due to the fact that icons with varying hights cause weird selectrum resizing issues, which will probably require upstream fixes. I have no idea why `all-the-icons` even has icons of varying size in the first place, but I haven't looked into it enough.

The profiling one is kind of a soft blocker since It might not have any actual implications but I still want to do it (maybe using affe will help somewhat with the delay, I have no idea I haven't looked into it yet)

The lexical error one is also a soft blocker since I might just submit the PR for review with it, Henrik has a better understanding of the lexical/dynamic binding wizardry at play, but I want to at least take another crack at it.

There is also an undocumented (In the TODO) doom specific bug that causes emacs 28 to crash when moving through previews in `consult-theme` that happens if I rebase the branch on the newest `develop`, probably due to the changes that happened in [doom-themes](https://github.com/) that I need to investigate, but in the mean time I've left the PR branch 12 commits behind.
 
I would also like to solve raxod502/selectrum#491 before merging since it kind of leads to bad UX, but I'm not going to have that as a review blocker since scrolling all the way down will be less important after I fix the export issue.

But the main hard blocker is Henrik having the time to review the PR. He's been working on a major rewrite for the doom CLI (responsible for managing your doom installation, installed package, private config, whole bunch of stuff, see #4273 for a list of things that it'll do, but the checkboxes aren't really maintained wrt progress) that is higher on the priority list since getting it done is a huge blocker for a bunch of other stuff. There is also the public launch of the [doom discourse](https://discourse.doomemacs.org/) which should happen soon:tm: that is a similar blocker for a bunch of stuff. The PR will get reviewed properly and merged after those two things are done, but also probably after the `mu4e` revamp PR (#3971) and biblio PR (#2888) since they've been waiting a lot longer :stuck_out_tongue:. 
 
Henrik is also on break right now due to some irl stuff, but it'll probably get merged sometime later this summer as it's a blocker for doom 3.0. But I'll mark the PR for review as soon as the major blockers listed above are done so Henrik can do drive-by reviews in the mean time and weigh in on the bunch of design descisions listed in `TODO.org` which might require further work.

2021-06-26 15:17 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
> I haven't properly checked yet by trying to use Vertico instead, but I'm pretty sure that the module isn't tied that much to Selectrum.

You should; it's easy enough.

I think I've mentioned before that I periodically test this (turning off `selectrum` and turning on `vertico`), and it's worked fine for me.

There are just a few little funky details I've noticed, like if I do `leader b b` with `vertico`, the window height is very low. But I assume that's easily tweaked in a user config.

2021-06-26 15:24 UTC, bdarcus commented
> @bdarcus @minad is is not really clear what the `menu-item` support does here, and looking it up in the docs hasn't really led to anywhere clear. It looks like it is a round about way for getting `which-key` descriptions?

@iyefrat - yes.

I was just interested in this thinking about consistency of menus between doom and embark. Otherwise, you could have a description in the doom which-key menu, and the command name in the embark which-key menu.

Maybe it's not a problem though; IDK.

And yeah, per @minad, there's currently a bug in embark that needs to be fixed for that work well here.

2021-06-26 15:43 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
> But at any rate I'm not sure how the module could be made to be more completion pakcage agnostic than it already is.

Yes I agree. I don't think anything should be done now, except maybe finding a more general name for the module, such that it is less biased to Selectrum. Such a change would be better before merging the PR. But naming is hard :)

> selectrum-prescient which will likely be dropped after the review anyway

Makes sense. Selectrum/Vertico/etc already sort by recency (history position). The additional frecency sorting offers only minor advantages over this. And unfortunately Prescient filter is not a completion style and is slower than Orderless. This does not fit very well with the philosophy of relying on Emacs APIs. I think Prescient should be reconsidered when it is a completion style. But even then I would probably prefer two separate packages for the two orthogonal concerns (one for filtering and one for sorting).

> The Icon one is blocked due to the fact that icons with varying hights cause weird selectrum resizing issues, which will probably require upstream fixes. I have no idea why all-the-icons even has icons of varying size in the first place, but I haven't looked into it enough.

There have been some resizing issues with Selectrum, which may be the problem here too. But having different icon sizes does not sound good. How does this look in other UIs like Ivy? I only tried all-the-icons briefly at one point and iirc I've also observed such different icon sizes. This led me to quickly ejecting all-the-icons again from my config - I don't see a point in a package smashing together all icons without ensuring coherence ;)

> The profiling one is kind of a soft blocker since It might not have any actual implications but I still want to do it (maybe using affe will help somewhat with the delay, I have no idea I haven't looked into it yet)

Could you be a bit more specific with regards to the delay? When do you observe a delay? The initial delay? This can be adjusted by reducing the value of `consult-async-input-debounce`. Affe is not really a replacement for `consult-ripgrep` and friends, since it will only work well on smaller projects. The reason is that affe filters *all lines*. For small projects it is very fast, so it may still be interesting for users. But it is simple enough to be installed by hand if a user likes it - I would not recommend it for addition here as of now.

> There is also an undocumented (In the TODO) doom specific bug that causes emacs 28 to crash when moving through previews in consult-theme that happens if I rebase the branch on the newest develop, probably due to the changes that happened in doom-themes that I need to investigate, but in the mean time I've left the PR branch 12 commits behind.

Crash? This should in any case be reported upstream via `report-emacs-bug`.

> I would also like to solve raxod502/selectrum#491 before merging since it kind of leads to bad UX, but I'm not going to have that as a review blocker since scrolling all the way down will be less important after I fix the export issue.

This issue is not present in Vertico, so it should be possible to merge this part of Vertico into Selectrum. There are a few other improvements present in Vertico which could also be merged if someone is interested in doing this.

2021-06-26 15:49 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
@bdarcus 

> There are just a few little funky details I've noticed, like if I do leader b b with vertico, the window minibuffer height is very low. But I assume that's easily tweaked in a user config.

Adjust `vertico-count`?

2021-06-27 15:17 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  (map! "C-;"               #'embark-act  ; to be moved to :config default if accepted
We recently merged embark at-point support here https://github.com/bdarcus/bibtex-actions/commit/ba8f4e5a5ef394aad5af64b9cadad834fef0b248, which includes `embark-dwim`.

I guess `embark-dwim` isn't bound yet. What should the binding be? `RET`?

I didn't write that code, so still trying to understand how embark should work ideally in-buffer.

2021-06-27 16:54 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
@minad - 

> Adjust vertico-count?

I think it's `selectrum-fix-vertical-window-height`. It's a minor thing, but I guess `vertico` doesn't have an equivalent ATM?

Another minor issue: the doom themes have definitions for `selectrum`. Is there an easy way to get `vertico` to just reference those in my local config?

2021-06-27 17:09 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
@bdarcus 

> I think it's selectrum-fix-vertical-window-height. It's a minor thing, but I guess vertico doesn't have an equivalent ATM?

This should do it:

~~~ elisp
(setq vertico-count 20
      resize-mini-windows nil) ;; nil=fixed, grow-only, t=shrink/grow
~~~

> Another minor issue: the doom themes have definitions for selectrum. Is there an easy way to get vertico to just reference those in my local config?

What about creating quick PRs to those themes adding Vertico support? This should be pretty easy to do since you can mostly copy the Selectrum config. Personally, I am using modus as you are probably aware. These themes are incredible comprehensive and well thought out :)

2021-06-27 17:21 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
@minad 

> What about creating quick PRs to those themes adding Vertico support?

I thought about that, but then thought we might need some buy in first on the general proposition this PR should be tied to selectrum.

But I can give it a try.

2021-06-27 18:29 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
> I thought about that, but then thought we might need some buy in first on the general proposition this PR should not be tied tightly to selectrum, and that vertico should work with it.

No idea about the Doom themes - but usually themes are pretty agnostic to what people use. The Modus policy is to support everything :) Furthermore people may use the Doom themes also outside of Doom, so independent of what lands in Doom, it is still useful to have support in the themes.

2021-06-27 20:55 UTC, bdarcus commented on modules/completion/selectrum/config.el
> +  (map! :map selectrum-minibuffer-map
PR submitted; I just copy-and-pasted the definitions for `selectrum-current-candidate`, which was the only `selectrum` face I found in the theme repo.

https://github.com/hlissner/emacs-doom-themes/pull/628

2021-06-28 07:18 UTC, gagbo commented on modules/tools/lsp/+lsp.el
> +  :commands consult-lsp-symbols)
That `:commands` is unnecessary because the command is autoloaded. Just having a `:defer t` should be enough

2021-06-28 07:19 UTC, gagbo commented on modules/tools/lsp/packages.el
> +    (package! consult-lsp :pin "ed3cfd2e67fc5117819c0c739814780bb4c2d716")))
Depending on the version of consult you want to use, you might need to bump this to https://github.com/gagbo/consult-lsp/commit/c882749e91e4de3bae17d825ac9950cc074b1595 But I didn't check consult pin, and I don't know if pin-correctness is relevant just now anyway. Just a heads up

2021-06-28 21:16 UTC, iyefrat commented
@minad responding here because i think that talking over there was getting a bit out of hand:

> But naming is hard :)

True! But I don't think it would be that bad to change it later if some good idea comes along.

> There have been some resizing issues with Selectrum, which may be the problem here too. But having different icon sizes does not sound good. How does this look in other UIs like Ivy? I only tried all-the-icons briefly at one point and iirc I've also observed such different icon sizes. This led me to quickly ejecting all-the-icons again from my config - I don't see a point in a package smashing together all icons without ensuring coherence ;)

Ivy uses the width of the tallest row to calculate the window size, which means that the gap between the lowest row and the bottom of the window varies when you scroll. Selectrum seems to just use the first row or something, so the bottom row sometimes is only half onscreen or entirely off, and the highlighted row scrolls off the screen when you get to the bottom row because of this (probably the same bug as the other resizing one). Vertico seems to display fine :)

> Could you be a bit more specific with regards to the delay? When do you observe a delay? The initial delay? This can be adjusted by reducing the value of consult-async-input-debounce. Affe is not really a replacement for consult-ripgrep and friends, since it will only work well on smaller projects. The reason is that affe filters all lines. For small projects it is very fast, so it may still be interesting for users. But it is simple enough to be installed by hand if a user likes it - I would not recommend it for addition here as of now.

Huh. It seems that the guy one of the configs that served as a starting point for the PR set the async debounce and throttle to higher than default values for some reason. Lowering the debounce to 0.2 helps a lot. I assume that the throttle is set to 0.5 because it otherwise stutters on large projects?

> Crash? This should in any case be reported upstream via report-emacs-bug.

Yeah, I'll do that as soon as I narrow it down enough to something reportable, I'm making progress but not there yet. Whatever it is, it's caused by [this `solaire-mode` commit](https://github.com/hlissner/emacs-solaire-mode/commit/56f6d9ea9cfa3f3fd5d64d995381fdb0da898b28), and is independent of native-comp. With some luck I'll get a MWE this weekend or something.

> This issue is not present in Vertico, so it should be possible to merge this part of Vertico into Selectrum. There are a few other improvements present in Vertico which could also be merged if someone is interested in doing this.

Yeah, I looked into the vertico solution a while back and the translation did not seem trivial so I put it on the backburner

2021-06-28 21:16 UTC, iyefrat commented on modules/tools/lsp/+lsp.el
> +  :commands consult-lsp-symbols)
gotcha, thanks!

2021-06-28 21:18 UTC, iyefrat commented on modules/tools/lsp/packages.el
> +    (package! consult-lsp :pin "ed3cfd2e67fc5117819c0c739814780bb4c2d716")))
ditto

2021-06-28 21:27 UTC, bdarcus commented
> > But naming is hard :)
> 
> True! But I don't think it would be that bad to change it later if some good idea comes along.

I still think a boring generic name would be better to start.

The functionality in this module, after all, is about so much more than selectrum.

2021-06-28 21:32 UTC, iyefrat commented
> I still think a boring generic name would be better to start.
> The functionality in this module, after all, is about so much more than selectrum.

Yeah that's true, but `:completion built-in` is kind of misleading and I don't really have a good alternative. `:completion selectrum-et-al`? `:completion modular`? I've gotten so used to calling it the Selectrum PR all other options sound weird :). If we change the name it'll probably be one of the last things before the merge.

2021-06-28 21:49 UTC, bdarcus commented
I hadn't thought about "modular", but that could be a good one!

2021-06-30 15:17 UTC, iyefrat commented
@minad (replying here because it takes me forever to find the thread up there)
> This should do it:
>
> ```emacs
> (setq vertico-count 20
>       resize-mini-windows nil) ;; nil=fixed, grow-only, t=shrink/grow
> ```
This configuration has an unfortunate side effect: making multiline `pp-eval-expressions` entries much harder to write because now the minibuffer won't expand to accommodate them. I don't know if being able to have a fixed minibuffer size only for vertico is within its design/minimalism goals, but I think it would be a good feature to have.

2021-06-30 15:20 UTC, minad commented
@iyefrat I am aware of this and I think I will introduce a `vertico-resize` variable instead of reusing `resize-mini-windows`. Vertico takes it a bit too far with reusing the variable - I acknowledge that one may want to have different resizing behavior for `read-from-minibuffer` and Vertico's `completing-read` :D

2021-06-30 15:54 UTC, minad commented
@iyefrat @bdarcus

> I hadn't thought about "modular", but that could be a good one!

"modular" is maybe a bit too generic, but I would generally like something like this. Maybe modular-/mod- completion/complete/comp/cr?

> Yeah, I looked into the vertico solution a while back and the translation did not seem trivial so I put it on the backburner

Since we are talking about Vertico here, I want to give you the current picture as I see it. Of course this is biased since I made some design choices. But I try to be fair. If it does not seem so, please ask or correct me. For me, Vertico is Selectrum plus lessons learned or Selectrum as it is supposed to be. There is not much design freedom if you want a correct `completing-read` UI and Vertico is supposed to be just that. I think there are two possibilities regarding Selectrum - either it changes its internal architecture to a similar architecture as Vertico or keeps its current architecture and patches up the small issues and edge cases which are mostly excluded in Vertico by construction. Note, the current status is that Selectrum is usable - it is about details. From what I know, these are the differences as of today.

* Vertico supports all completion configurations, completion tables and completion commands correctly, Selectrum does not. The only tables which do not work with Vertico are the ones which are "broken". Org has a few of those unfortunately. Take a look at the Vertico readme.
* Vertico has an optimized sorting function, Selectrum does not. This is a necessity in Vertico, since Vertico has to compute the candidates more often to support all completion features. Selectrum basically assumes that completion tables are static and precomputes everything once. This is not correct. Therefore Selectrum does not sort if the flex completion style is used.
* Vertico supports group rotation commands (like helm source rotations), Selectrum does not
* Selectrum has a horizontal display, Vertico does not, can be implemented as supplementary, but it is a bit of work
* Selectrum supports a buffer display, Vertico does not, but can be easily implemented as supplementary https://github.com/minad/vertico/issues/19#issuecomment-823689341
* Selectrum supports Avy-style quick keys and selection by numeric prefix argument, Vertico does not
* Selectrum does fancy truncation of multi-line candidates, Vertico does not. This basically only affects `consult-yank-*`. Since `consult-yank-*` preview the current candidate in the buffer I have not seen the need to implement a more advanced truncation in Vertico.
* Selectrum modifies the CRM prompt and removes the already selected candidates. Vertico avoids modifying existing completion tables and avoids advices as much as possible due to their intrusiveness (hard to undo for the user, conflicting side effects, etc). Still if this is desired in Vertico, CRM improvements could be implemented using advices on the level of the user configuration.
* Selectrum annotates environment variables, Vertico does not. Environment variables are also annotated by Marginalia, which gives the same result with Vertico.
* Selectrum performs additional caching if Tramp is used, Vertico does not. I do not really know the background of this - I believe the caching in Selectrum is only necessary to work around performance issues due to the Selectrum architecture itself. Vertico relies on the Tramp caching, which seems to be sufficient.
* Selectrum provides a `completion-in-region` function. Vertico does not, but there is `consult-completion-in-region` which provides additional preview! This is probably irrelevant for you since you rely on Company.
* Selectrum provides `selectrum-repeat`, Vertico does not.
* Selectrum supports Prescient, Vertico does not. I consider the Prescient frecency sorting to be unnecessary given the recency sorting which both Selectrum/Vertico support out of the box. Prescient filtering is not supported by Vertico since Prescient does not provide a completion style. Prescient filtering works with Selectrum since Selectrum uses its own filtering infrastructure which deviates from the Emacs facilities.

As you know, these packages are designed to be complementary and should integrate with each other. I really like the idea of having the pluggable packages maintained by different people. So my point is not about convincing you to use my packages. I would like it much more if I would not be the one who maintains Vertico/Selectrum/whatever. It just turned out that the Vertico approach (which is very similar to Icomplete, so it is a proven design) seems to be less work than trying to patch up Selectrum step by step. Vertico is a bottom up design, starting from the completion facilities as they are given (if you take them as given and try not to reinvent them - once again, there is not much design freedom here) and then adding features carefully and gradually. Selectrum is about a year older than Vertico. It could be that there are issues with Vertico which have not been found yet since Selectrum got more exposure. I only trust Vertico because of its simpler architecture and because it is similar to Icomplete. Hopefully Vertico will not require significant maintenance due to that, but this remains to be seen.

2021-06-30 16:08 UTC, bdarcus commented
> "modular" is maybe a bit too generic, but I would generally like something like this. Maybe modular-/mod- completion/complete/comp/cr?

I'm terrible with names, but FYI, here's an example of the context in which users will see the name; from my `init.el` file:

``` elisp
       :completion
       (company +tng)      ; the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       selectrum
       ;;ivy               ; a search engine for love and life
```

... and then you end up with code like this:

``` elisp
(when (featurep :completion selectrum) ...
```

2021-06-30 16:11 UTC, minad commented
@bdarcus 

> I'm terrible with names, but FYI, here's an example of the context in which users will see the name; from my init.el file:
> ... and then you end up with code like this:

Yes, since the feature checks and the names end up in user configurations I think it is better to settle on a name sooner than later.

2021-06-30 17:12 UTC, iyefrat commented
@minad @bdarcus 

> "modular" is maybe a bit too generic, but I would generally like something like this. Maybe modular-/mod- completion/complete/comp/cr?

Yeah after some more thought I realized this isn't a great name, because the doom naming conventions have functions as `+module/foo`, which here would be `+modular/foo`, which is kind of confusing because the context of completion is lost. The more I think about it, the more I want to find a more generic name for the module though. Right now I'm leaning for `modcomp` as short for `modular completion`, but that's a bikeshed best left for the review since I'm sure Henrik will have input.

> /state of vertico speech/

To be entirely honest with you I've been meaning to introduce an experimental `+vertico` flag to try out as a potential selectrum replacement for the module (before the PR gets merged of course), since it seems that most of the weird edge cases don't happen in vertico, like raxod502/selectrum#491 or raxod502/selectrum#561. It's why I asked about the resizing thing, because I was working on implementing the flag. I would have already pushed it, but I want to wait for hlissner/emacs-doom-themes#628 to be merged first because the default highlighting has some usability issues with a lot of the doom themes.

I will probably have some more pointed follow ups to your detailed explanation (which I really appreciate by the way) later, but I need to look in to the whole thing a bit more before I have anything meaningful to say about it.

By the way, would you consider submitting vertico to melpa as well? By default `straight` installs packages from an elpa mirror, citing usability concerns with the build system (which to be entirely honest I'm not qualified to judge the merits of), but the mirror destroys the git history and I'd rather not have to explicitly like to the git repo since who knows if that might change at some point. Also weirdly there don't seem to be docs on how to use gnu-devel elpa instead of gnu elpa which is really weird, but that's neither here nor there, since doom is probably going to continue using the mirror for elpa packages.

2021-06-30 17:19 UTC, minad commented
> By the way, would you consider submitting vertico to melpa as well?

I don't really see a need to do this. You can either pull from https://github.com/minad/vertico or from https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/?h=externals/vertico. These repositories are kept in sync.

2021-06-30 17:25 UTC, iyefrat commented
> I don't really see a need to do this. You can either pull from https://github.com/minad/vertico ...

Fair enough, this is what I do currently, and the inconvenience is very minor.

2021-07-02 13:59 UTC, iyefrat commented
Attention selectrum PR users! I'm seriously considering switching the vertical completion part of the module to use vertico instead of selectrum, due to it being in general less buggy, and the feature disparity not seeming to be that big (and in some cases work out in vertico's favor). For more details see the section on this in TODO.org.

To this end I've added a `+vertico` flag to the module as an initial stage. I've tested it out before pushing it, and there aren't any real usability issues, but I'd appreciate further testing. If you feel like helping out with that, enable flag and report back (both positive and negative feedback!).

2021-07-02 14:02 UTC, minad commented on modules/config/default/config.el
> +                 '(selectrum-minibuffer-map))))
@iyefrat Why is it needed to register the `selectrum-minibuffer-map` here? Both `selectrum-minibuffer-map` and `vertico-map` derive from `minibuffer-local-map`, which is also registered in this list.

2021-07-02 14:04 UTC, iyefrat commented
There is one thing though: for some reason when using vertico, `find-library` returns about 4,000 extra `./` options (selectrum doesn't). I haven't been able to reproduce this on `emacs -Q` yet. @minad any idea what could cause something like this?

2021-07-02 14:14 UTC, iyefrat commented on modules/config/default/config.el
> +                 '(selectrum-minibuffer-map))))
You're right, this is a mistake. Thanks!

2021-07-02 14:14 UTC, minad commented
> There is one thing though: for some reason when using vertico, find-library returns about 4,000 extra ./ options (selectrum doesn't). I haven't been able to reproduce this on emacs -Q yet. @minad any idea what could cause something like this?

I am aware of this issue. This is an Emacs bug if you ask me - a completion table should not return duplicates. However the default completion UI filters out consecutive duplicates. If you look at minibuffer.el, the filtering has been made some time later on. So I assume that the minibuffer completion facilities when originally designed did not filter out duplicates and there was no intention to do so. Selectrum does not have this issue since it replaces the `read-library-name` function with its own version (https://github.com/raxod502/selectrum/blob/a19bbe94de492bf504399c093cfc5695eb630fa8/selectrum.el#L2882).

I have not yet decided on how to handle this issue in Vertico:

1. Remove the hack from minibuffer.el, which removes consecutive duplicates. Fix the library completion table and maybe other completion tables. Do nothing in Vertico.
2. Only fix the library completion table and maybe other completion tables, keep the minibuffer.el duplicate removal. Do nothing in Vertico.
3. Filter out consecutive duplicates in Vertico. Do not fix upstream.

Of course, option (1) is my favorite solution but it may involve long emacs-devel discussions.

2021-07-02 14:30 UTC, iyefrat commented
@minad I see, that is unfortunate. If you don't end up doing 4 I'll just add the fix in Doom, it will not be the first such hack in the codebase :D. Hopefully this can be smoothly patched upstream.

2021-07-02 14:48 UTC, minad commented
There is another thing holding me back. At some point I considered allowing duplicates for completing-read and disambiguating the duplicates based on object identity, but I've given up on that idea mostly. Nevertheless I am still unhappy with the duplicate filtering since it should not be necessary. The user of `completing-read` should make sure that no duplicates are passed as candidates. The problem with `completing-read` is that it never got properly specified, it is specified by the implementation of the default UI. Now if someone manages to get in a bad patch like https://github.com/emacs-mirror/emacs/commit/cc37e70f6699cbadb1a8f5467e8dc9fcea986aa1#diff-9fe92bd4449f8efe346fc61ec3ba7e772b1d500ea79254dac58b040a9d1f688b the specification has changed to the worse. Since this happened in 2012 there is maybe no chance to revert this. 

After looking at this 2012 patch, I should correct myself - minibuffer.el does two things: It filters duplicates in general (delete-dups) and it also filters consecutive duplicates when displaying the `*Completions*` buffer. As far as I see it, this duplicate duplicate filtering does not make sense.

Note that Selectrum also does not filter out duplicates in general. I have to check if Ivy or Helm do that. At least consecutive duplicate filtering is very cheap. Filtering general duplicates is more costly due to the hash table, so a compromise could be to just implement filtering consecutive duplicates in Vertico.

2021-07-02 14:55 UTC, minad commented on core/autoload/projects.el
> +           (call-interactively #'find-file))
Why not remove these two lines and instead adjust the ivy and helm checks.

You could check if `helm-mode` (`ivy-mode`) is `bound-and-true-p` and then call `helm-find-file` (`counsel-file-jump`). Otherwise it will fallthrough to the default `find-file`. There is no need for special casing this module since it relies on the default function.

2021-07-02 15:04 UTC, minad commented
@iyefrat Btw you made a change in the consult wiki regarding the `completion-category-overrides`, which is unclear to me. I've reverted this for now. Even if you specify `completion-category-overrides`, the `completion-styles` (including orderless) are still taken into account. With your change `orderless` will take precedence before `partial-completion`, which is undesired since then `partial-completion` only sets in when `orderless` does not return any results. The order 1. partial-completion, 2. orderless is the correct one imo. Therefore I've documented it like this in the wiki.

2021-07-02 20:21 UTC, iyefrat commented on core/autoload/projects.el
> +           (call-interactively #'find-file))
Yeah, this is definitely at least better than the current solution.

2021-07-02 20:27 UTC, iyefrat commented
@minad Personally I only want `partial-completion` for the globbing, but I can see how that might be unwanted for some people. I'll add it to the bikeshed pile.

re: `orderless+initialism`,  raxod502/selectrum#539 caused it to not highlight correctly, but I can add it back in now for vertico, Forgot about that.

2021-07-03 08:51 UTC, bdarcus commented
> I'm seriously considering switching the vertical completion part of the module to use vertico instead of selectrum, due to it being in general less buggy ...

FWIW, @iyefrat, in testing a new org-mode feature, its developer and I ran into a minor selectrum crm bug that is not present in vertico.

https://lists.gnu.org/archive/html/emacs-orgmode/2021-07/msg00053.html

2021-07-03 11:52 UTC, minad commented on modules/completion/selectrum/config.el
> +        projectile-completion-system 'default)
This is unnecessary, projectile autodetects the completion system. I would remove the setting of `projectile-completion-system` everywhere, also in the helm, ivy and ido modules. See https://github.com/bbatsov/projectile/blob/da08a9103b5ba3b38ef031a9627a19436eb318b5/projectile.el#L1886-L1892.

2021-07-03 11:53 UTC, minad commented on modules/completion/selectrum/config.el
> +        projectile-completion-system 'default)
Same here with projectile-completion-system.

2021-07-03 11:56 UTC, minad commented on modules/completion/selectrum/config.el
> +  (map! "C-;"               #'embark-act  ; to be moved to :config default if accepted
I am using `C-.` for `embark-act` and `M-.` for `dm/embark-dwim`. This makes a lot of sense since `M-.` generalizes `xref-find-definitions` at point. However it may not be a good fit for Doom.

~~~ elisp
  (defun dm/embark-dwim (&optional arg)
    (interactive "P")
    (if (or arg (not (embark--target))) ;; if prefix argument is given or no target, call the xref function
        (call-interactively #'xref-find-definitions)
      (embark-dwim)))
~~~

2021-07-03 12:10 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +        projectile-completion-system 'default)
Ah, this was copied over from the ivy module configuration, that added this before projectile added the autodetection. I'll write a PR to remove them, it's probably better behavior anyway (if you for some reason turn off `ivy-mode` and turn on `helm-mode`, it would be nice if more things worked properly).

2021-07-03 12:17 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (map! "C-;"               #'embark-act  ; to be moved to :config default if accepted
`C-.` is probably not a good fit since it conflicts with `evil-repeat-pop`, which I don't personally use but some people probably do. However, one of the other options for `embark-act` was `C-,`, so that might be a good fit. Not too sure about the `xref` stuff, doom already has it's own lookup xref extension backend that's accessed by `gd`, so any more things in this area probably shouldn't be done without consolation with Henrik.

2021-07-03 12:30 UTC, minad commented on modules/completion/selectrum/config.el
> +        projectile-completion-system 'default)
> I'll write a PR to remove them, it's probably better behavior anyway (if you for some reason turn off ivy-mode and turn on helm-mode, it would be nice if more things worked properly).

Yes, this should give better behavior overall as long as it is removed everywhere.

2021-07-03 12:31 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +#+end_src
@minad btw, after some bikeshedding on the discord I came out with the following proposal for a generic module name that I like.

2021-07-03 12:43 UTC, minad commented on modules/completion/selectrum/TODO.org
> +#+end_src
> compleseus     ;; a search engine with all the planks replaced

Lol! Is this a riddle or an inside joke? Maybe some users who are not familiar with the modules read through the list of modules so it could be helpful to have a more obvious description?

2021-07-03 12:44 UTC, minad commented on modules/completion/selectrum/TODO.org
> +#+end_src
Lol https://www.google.com/search?q=compleseus+a+search+engine+with+all+the+planks+replaced

2021-07-03 13:05 UTC, minad commented on modules/completion/selectrum/TODO.org
> +#+end_src
What about this?

~~~
compleseus     ;; Theseus' search engine with all the planks replaced
~~~

But then it is probably too obvious. Maybe keep it as you have it. The ship of theseus reference is also unclear for someone unfamiliar with the modular system, where you have replaced all the planks. So I guess it won't matter anyways. Doom uses the Compleseus completion system, sounds fun at least :rofl:

2021-07-03 13:39 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +#+end_src
@minad The thing is, people don't know what `ivy` and `helm` are when skimming the module list for the first time (and if they do, they can probably infer that it's similar to `ivy` and `helm`), and the modularity aspect is explained in the readme (I still need to improve the description). I'm okay with the comment being a bit vague, most of them are on the jokey side (see [here](https://github.com/hlissner/doom-emacs/blob/2731685095d1e6101b3215aa689426e1834ce00f/init.example.el)). Another thing I considered was just calling it `theseus`, but then you lose on the completion aspect being obvious, and unlike `ivy` and `helm` it doesn't refer to a package name, so I feel this is a good middle ground.

2021-07-03 14:06 UTC, minad commented on modules/completion/selectrum/TODO.org
> +#+end_src
I think it is a great name, clearly better than theseus. Name relates to completion+modularity and it is unique and sufficiently short. I will refer to the package combination (consult, embark, marginalia, orderless, vertico) as compleseus from now on :rofl:

If everything is documented clearly it will be alright!

2021-07-04 08:33 UTC, minad commented on modules/completion/selectrum/TODO.org
> +  feature advantage of using Selectrum.
Note that Vertico of course supports `completing-read-multiple`. It just avoids making adjustments to the implementation. In contrast, Selectrum replaces `completing-read-multiple` with its own implementation, which is necessary since the default crm implementation does not work with Selectrum due to Selectrum not supporting dynamic completion tables. Regarding the caching, Vertico relies on the Tramp caching - this means caching is present and fully functional. Selectrum has its own caching since it replaces the `read-file-name-function`. This is unnecessary in Vertico since Vertico just relies on the built-in `read-file-name-default` function as given.

2021-07-04 08:46 UTC, minad commented on modules/completion/selectrum/config.el
> +        completion-in-region-function #'consult-completion-in-region
consult-completion-in-region has been set above already

2021-07-04 08:49 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq completion-in-region-function #'consult-completion-in-region)
@iyefrat You may want to guard consult-completion-in-region (see the discussion in https://github.com/minad/consult/issues/350), such that it is only active with Vertico or Selectrum.

~~~ elisp
;; Use `consult-completion-in-region' if Vertico is enabled.
(add-hook 'vertico-mode-hook (lambda ()
                               (setq completion-in-region-function
                                     (if vertico-mode
                                         #'consult-completion-in-region
                                       #'completion--in-region))))
~~~

2021-07-04 15:47 UTC, bdarcus commented on modules/completion/selectrum/TODO.org
> +  feature advantage of using Selectrum.
> Note that Vertico of course supports `completing-read-multiple`. It just avoids making adjustments to the implementation.

One of those little "adjustments" I like from selectrum is for those crm-separators in `selectrum--crm-separator-alist`, upon hitting `TAB`, selectrum will select the candidate and add the `crm-separator`.

By contrast, Vertico will add the candidate to the prompt, but the user must then insert the `crm-separator`, which I guess then selects it.

So the selectrum optimization there feels cleaner and more efficient to me.

I think I've run into a minor bug, but will report on the vertico tracker.

But otherwise, yeah, they're equivalent, @iyefrat.

As @minad knows, while my package relies on CRM, I'm not fond of the implementation. 

We did discuss some ideas to borrow from and improve on the `helm` approach to this, but not sure if, when, or where this will ever be implemented.

But ... if I have understood recent conversations with @minad correctly, one advantage of Vertico over Selectrum is that, because Vertico supports programmable/dynamic tables, I can effectively replace CRM with an alternative tweaked to better work with long candidates, etc.

2021-07-06 11:43 UTC, bdarcus commented
@iyefrat et al - @minad has opened a PR for a `consult-completing-read-multiple`, which I want to suggest should be used on this module instead of CRM.

https://github.com/minad/consult/pull/352

Please give it a test, provide feedback, etc.

To replace CRM with this, you only need to do:

``` elisp
(advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)
```

2021-07-06 20:23 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +  feature advantage of using Selectrum.
@minad Great! But this means that the Vertico comparison on the Selectrum readme is pretty outdated. I assumed that there was some meaningful difference on the userside for the different ways Vertico and Selectrum do Tramp caching, but it sounds like that isn't the case (I don't use Tramp for anything myself).

re: @bdarcus's crm comment it seems that there's a lot of further stuff on that later on so I'll read that before responding.

2021-07-06 20:43 UTC, iyefrat commented on modules/completion/selectrum/config.el
> +  (setq completion-in-region-function #'consult-completion-in-region)
@minad Ah, I've run into minad/consult#350 as well, I just hadn't investigated it's origins yet. I'm a bit unclear on how `consult-completion-in-region` is problematic in general and is therefore targeted at experienced users (other than the specific `lsp-mode` problems). Perhaps it's because Doom uses company for in-buffer completion, but I haven't really encountered any rough edges even when falling back to `completion-at-point`

2021-07-06 21:23 UTC, iyefrat commented
@bdarcus @minad, regarding the enhanced `completing-read-mulitiple` function, this seems to be a great addition to compleseus, but since I don't use `crm` in my day to day, and from reading the issues involved the design challenges seem to be pretty nuanced, I'm don't think I have anything meaningful to add on the subject at the moment. What do you use it for other than bibtex citations?

2021-07-06 21:35 UTC, bdarcus commented
@iyefrat - it might take awhile to settle the details for a release, depending on some decisions still to be made. But I just think it provides a better, more consistent, UI, in general, and certainly for UIs with longer candidate strings.

Now, you basically have two very different UIs: CR, where you select a candidate from the vertical list, and hit RET to run the command on it, and CRM, where you have a text prompt, and add candidates to it, with a crm-separator between them, then hit RET.

I know not everyone agrees with me, but I just think that's bad design.

In this UI, you just select and deselect candidates more directly. Here's a screenshot from my package of its current state:

![Screenshot from 2021-07-06 14-32-22](https://user-images.githubusercontent.com/1134/124649899-12013980-de67-11eb-9f61-bd31d191afeb.png)

But the nice thing about the work that @minad is doing on this is whatever the ultimate solution, it will be a drop-in replacement. So it's not something you really need to worry about; just thought you might be interested.

2021-07-06 22:09 UTC, minad commented
@iyefrat I am still a bit in a limbo regarding crm. Currently we don't have special support for crm - only the basic comma separated default implementation, which I agree with @bdarcus is lacking. However as soon as you explore crm thoroughly you somehow open the floodgates to many more possibilities and things get unwieldy. Ultimately features have to carry their weight, if it is a vast complication which is used only in a handful of scenarios, this is not the case. bibtex-actions is the first application which would profit from enhanced crm (but what about ivy-bibtex, which also does not support multi selections). Besides that one can get away with the basic implementation.

2021-07-07 09:35 UTC, minad commented on modules/completion/selectrum/config.el
> +  (setq completion-in-region-function #'consult-completion-in-region)
I updated the consult readme a bit regarding consult-completion-in-region. Please check it out and let me know if you have further questions.

2021-07-07 21:03 UTC, bdarcus commented
> But the nice thing about the work that @minad is doing on this is whatever the ultimate solution, if he publishes it, I expect it will be a drop-in replacement.

Just to update, @minad merged this, and you can play with it if curious by updating Consult, and just adding:

``` elisp
(advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)
```

Beyond my package, `describe-face` is a good one that shows it in action.

2021-07-08 11:39 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
https://github.com/minad/vertico/wiki#vertico-repeat-repeat-last-vertico-session

2021-07-08 11:50 UTC, Zetagon commented
I think I've found a bug, maybe in marginalia.  `M-x flycheck-error-list-set-filter` brings up a minibuffer-prompt, with alternatives for which error level to report. One of them is `info`. Beside `info` the keybinding for `M-x info` is shown. 
```lisp
(defun warning ()
  (interactive))
(map! 
:leader "ol" #'warning)
```
With the above `warning` also gets a keybinding

2021-07-09 09:00 UTC, iyefrat commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
Thanks!

2021-07-09 09:19 UTC, minad commented on modules/completion/selectrum/TODO.org
> +  feature advantage of using Selectrum.
> I assumed that there was some meaningful difference on the userside for the different ways Vertico and Selectrum do Tramp caching, but it sounds like that isn't the case (I don't use Tramp for anything myself).

No, as far as I understand this - Selectrum has to do additional caching since it uses its own replacement of `read-file-name`. Vertico just uses the default and the already existant Tramp-caching works reliably - Vertico+Tramp works well. I updated the description in https://github.com/raxod502/selectrum#vertico. Basically only Avy-quick keys are missing and the additional features to adjust the display to use a buffer. But the display code of Vertico is trivial to hack for users with special requirements (see for example https://github.com/minad/vertico/issues/19). Therefore I think it is okay that Vertico only offers the standard minibuffer display out of the box.

2021-07-09 09:20 UTC, iyefrat commented
@Zetagon this is an upstream bug in flycheck (I think), I can reproduce it in `emacs -Q`. It looks like `flycheck-read-error-level` gets the symbol annotation type for some reason, where it should probably get none (or it's own thing, but the names are pretty self explanitory). It also looks like choosing `info` or `error` bump them up in the `C-h f` history independently of marginalia (but not `warning`, which according to the marginalia annotation gets classified as the warning face, but doesn't shoot up in the history of `describe-face`). I'd guess that when you don't provide an annotation category of any type for a list like `'(info warning error)` in just interprets it as a list of symbols (which it kind of is) and just runs with that, which causes all these weird consequences.

This can be fixed in marginalia (or Doom) by adding a custom `marginalia-prompt-categories` entry for this prompt, but if it's possible to fix it at the source it would probably be best since the history behavior is an issue with flycheck itself it seems.

2021-07-09 09:23 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
Maybe you could maintain this here as a small compleseus-repeat.el file? Alternatively I considered adding some kind of auxillary extensions to Vertico, which are separate files in the Vertico repository which could be installed manually, but which are not part of the main package. There could be vertico-repeat.el, vertico-reverse.el (top to bottom display) and vertico-quickkeys.el for example.

2021-07-09 09:25 UTC, minad commented
@iyefrat @Zetagon This is just a false positive in the Marginalia classifier. I don't think one can consider this a bug. The fix you describe (adding a custom marginalia-prompt-categories) would work, but I rather recommend to overwrite this in `marginalia-command-categories`, which is precisely meant to be used to fix false positives on a per-command basis.

2021-07-09 09:41 UTC, iyefrat commented
@minad Doing this:
```emacs
(nconc marginalia-command-categories '((flycheck-error-list-set-filter . builtin)))
```
fixes the annotation, but still gets `info` and `error` into the recently used list when using `C-h f`, even though they are different functions of the same name.

2021-07-09 09:58 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +  feature advantage of using Selectrum.
@minad I updated this part of the todo in a force push a few days ago (trying to keep the commit history clean) to better reflect the current status. Let me know if you think I still missed something there.

2021-07-09 10:04 UTC, iyefrat commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
Maintaining it within the module is my current plan, but honestly I think that having Vertico extensions in separate files is a pretty good idea, as it would reduce doubling of work (especially if people are just copy pasting from the wiki, if there are any updates to the wiki they have to check and add them manually).

2021-07-09 10:17 UTC, minad commented
> fixes the annotation, but still gets info and error into the recently used list when using C-h f, even though they are different functions of the same name.

This happens since the `minibuffer-history` is shared by these commands.

2021-07-09 10:19 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
I decided to add extensions: see https://github.com/minad/vertico/blob/main/extensions/vertico-repeat.el. Hopefully you can just pull the vertico-repeat package from there.

2021-07-09 11:15 UTC, iyefrat commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
Sweet! I'm having a bit of load order trouble here I think. It works fine when doing this in `emacs -Q`:
```emacs
(add-to-list 'load-path "~/.emacs.d/.local/straight/repos/vertico")
(add-to-list 'load-path "~/.emacs.d/.local/straight/repos/vertico/extensions")
(require 'vertico)
(require 'vertico-repeat)
(vertico-mode +1)
```
But when I try to add in in doom using `use-package`, either by:
```emacs
(use-package! vertico
  :hook (doom-first-input . vertico-mode)
  :config
  (require 'vertico-repeat))
```
or by adding this instead of the `require`:
```emacs
(use-package! vertico-repeat
  :after vertico)
```
It does repeat the command, but doesn't insert the input for some reason. Any idea what could be causing this?

2021-07-09 11:29 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
No idea, sorry. But it should be fairly easy to debug. Just add a few print statements to `vertico--save` and `vertico--restore` to see what is going on.

2021-07-09 11:32 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +      (call-interactively 'backward-delete-char))))
There is also `vertico-ido-delete-char` now, which is very similar to what you have here. It should also work with Selectrum.

2021-07-09 12:01 UTC, iyefrat commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
I've figured out the issue but I'm not sure why it happens. It's because of the fact that I call `vertico-repeat` from within an interactive function, here:
```emacs
(defun +selectrum/repeat ()
  "Repeat the last selectrum/vertico command."
  (interactive)
  (if (featurep! :completion selectrum +vertico)
      (vertico-repeat)
    (selectrum-repeat)))
```
(This can be reproduced on `emacs -Q` with binding some dummy interactive function that only calls `vertico-repeat`).
It seems that the fact that this resets `vertico-repeat--input` for some reason, not sure why though, as the Vertico advice only effects `completing-read` stuff. I can resolve this within doom by moving the logic elsewhere to avoid the wrapper function, but the behavior is still weird.

2021-07-09 12:08 UTC, iyefrat commented on modules/completion/selectrum/autoload/selectrum.el
> +      (call-interactively 'backward-delete-char))))
I'll move over to using this if the module moves to just using Vertico (which will probably happen, I just need to run it by Henrik first). Even though it works with Selectrum, using this requires downloading the Vertico package which I'd rather not do if I can get away with it.

2021-07-09 13:03 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +      (call-interactively 'backward-delete-char))))
You are right, only `vertico-ido-delete-char` is independent of Vertico but the `vertico-ido-exit` function is not.

2021-07-09 13:11 UTC, minad commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
`vertico-repeat--save` checks if the current command is the repeat command. If you use a wrapper this logic will break.

2021-07-09 13:25 UTC, iyefrat commented on modules/completion/selectrum/autoload/selectrum.el
> +      (user-error "The vertico flag doesn't support repeating commands (yet)")
Thanks! Can confirm that this fixes the issue.

2021-07-09 14:30 UTC, minad commented on modules/completion/selectrum/TODO.org
> +  feature advantage of using Selectrum.
With https://github.com/minad/vertico#extensions there is mostly feature parity I guess. I really like the idea of extensions, this will keep the core simple and small. It fits the spirit of baking your own completion system by plugging together components depending on your preferences.

2021-07-09 16:21 UTC, iyefrat commented
Attention PR users! Later today I'll be pushing commits that replace Selectrum with Vertico as the vertical completion component of the module. The module is also being renamed from `:completion selectrum` to `:completion vertico`. As much as I like `compleseus`, Henrik said that it's too confusing for new users, and he's probably right. Also Vertico is unlikely to be replaced as the UI portion of the module once it's merged.

2021-07-09 17:53 UTC, iyefrat commented on modules/completion/selectrum/TODO.org
> +  feature advantage of using Selectrum.
I will say that for the record i like horizontico but understand why you renamed it :)

2021-07-10 01:16 UTC, minad commented
@iyefrat I would have loved the `compleseus` name ;-( Also this is now the 401. comment on this PR.

2021-07-10 07:41 UTC, iyefrat commented
Me too! Not a huge deal though.

2021-07-10 13:14 UTC, iyefrat commented
Hey @sebastiansturm, I know it's been a while but do you remember why you removed the `xref-show-definitions-function` part of the `consult-xref` setup (commit 2c8cba2e9195bee48516cf61972e7a79af8f8b89)? It goes against what's done in the `ivy` module and the `consult` documentation, so I want to remove the commit, but I thought I'd ask first. Were you running Emacs 26 at the time?

2021-07-10 16:04 UTC, sebastiansturm commented
not really; I believe selecting something wouldn't make it jump to point, either in general or when there only was one candidate to select. Not a subtle effect, so if setting `xref-show-definitions-function` to `consult-xref` works both with one and several candidates, then there's no point in keeping my change. I've been running emacs 28 at the time (either after the native-comp merge, or the native-comp branch)

2021-07-10 16:08 UTC, iyefrat commented
@sebastiansturm can you give me step by step instructions on how to reproduce that? I don't use `xref` stuff much.

2021-07-10 16:09 UTC, sebastiansturm commented
I'll try; I hope it still happens, as I don't know if any of the changes made in the meantime (such as exchanging selectrum for vertico) are relevant

2021-07-10 16:28 UTC, bdarcus commented
FWIW, it's my impression those sort of UI oddities are completion package specific.

E.g. I've run into some in Selectrum, but different ones in Vertico.

2021-07-10 16:29 UTC, iyefrat commented
@bdarcus like what?

2021-07-10 16:31 UTC, bdarcus commented
I don't mean current bugs. I ran into one little one in Vertico a couple of weeks ago, for example, that @minad promptly fixed.

I just mean to say I bet that problem isn't present in Vertico.

2021-07-10 16:53 UTC, sebastiansturm commented
@iyefrat tried with a recent version of the PR (after the `vertico` rename) and AFAICT, setting `xref-show-definitions-function` to `#'consult-xref` no longer causes any issues for me

2021-07-10 16:53 UTC, minad commented
@iyefrat @sebastiansturm @bdarcus Afaik the bug that @sebastiansturm is referring to is about `consult-xref` not jumping directly for single candidates. But this has been fixed a long time ago. Generally the best approach to handle such issues is to always report them upstream instead of working around them.

2021-07-10 16:58 UTC, minad commented
Btw, I made a handful of extensions in the meantime: https://github.com/minad/vertico/#extensions. I think all of them are quite neat, but personally I am only using vertico-directory and vertico-quick. Maybe some of them are interesting for you too? The nice thing is that you can really bake the UI according to your liking, e.g., vertico-flat+vertico-directory is like ido-mode, of course better ;) In any case, if someone is interested - I would like to hear some feedback.

2021-07-10 17:00 UTC, sebastiansturm commented
@minad thanks for the info and yes, I should have tried to find the root cause of the issue back then; my bad for not doing that, sorry!

2021-07-10 17:00 UTC, iyefrat commented
> @iyefrat @sebastiansturm @bdarcus Afaik the bug that @sebastiansturm is referring to is about consult-xref not jumping directly for single candidates. But this has been fixed a long time ago in Consult. It has nothing to do with Vertico/Selectrum. Generally the best approach to handle such issues is to always report them upstream instead of working around them.

@minad In that case I feel pretty comfortable just purging the revert commit from history (@sebastiansturm but if you could just tell me how to reproduce the issue anyway that would be cool), I've been trying to minimize cruft (hence the recent force-push party). Wish it would obliterate the recent comments on the webpage though.

2021-07-10 17:02 UTC, minad commented
> @minad In that case I feel pretty comfortable just purging the revert commit from history (@sebastiansturm but if you could just tell me how to reproduce the issue anyway that would be cool), I've been trying to minimize cruft (hence the recent force-push party). Wish it would obliterate the recent comments on the webpage though.

As far as I know, there is no issue. You can revert to the configuration as described in the consult README. You can always revisit later if something comes up. Maybe it was this issue https://github.com/minad/consult/issues/296?

2021-07-10 17:03 UTC, iyefrat commented
> Btw, I made a handful of extensions in the meantime: https://github.com/minad/vertico/#extensions. I think all of them are quite neat, but personally I am only using vertico-directory and vertico-quick. Maybe some of them are interesting for you too? The nice thing is that you can really bake the UI according to your liking, e.g., vertico-flat+vertico-directory is like ido-mode, of course better ;) In any case, if someone is interested - I would like to hear some feedback.

@minad I saw! You've really been going ham there. I've been holding out on bumping the package pin until it looks like things calm down a bit since there are a bunch of them. Not too sure about what should be included by default though, since doom users can trivially enable extensions themselves if they want. I'll talk about that with Henrik during the review.

2021-07-10 17:07 UTC, minad commented
>  Not too sure about what should be included by default though, since doom users can trivially enable extensions themselves if they want.

Yes, there is probably no need to include any by default. Maybe a pointer in the documentation would be helpful, but I guess you are referring to the package documentations anyways.

2021-07-10 17:10 UTC, iyefrat commented
yeah I'm working on an overhaul to the readme that's one of the last things I have left to do before I submit the PR for review, I feel like there should be a bit more pointed advice than "go read the package docs". Reading the package docs is good and everyone should do it, but I feel like having a few pointers like "look into vertico extentions", "you probably want to modify `marginalia-annotator-registry` and `orderless-style-dispatchers`" will make that sort of thing more approachable for users that don't really know where to start.

2021-07-10 17:19 UTC, bdarcus commented
Don't we need a binding for `embark-dwim`? 

If `embark-act` is `space a` in evil, ideally I'd guess it should be `space d`?

2021-07-10 17:25 UTC, iyefrat commented
@bdarcus Yeah but I'm leaving that for the review, the embark bindings are on slightly shaky ground

2021-07-10 17:26 UTC, bdarcus commented
> @bdarcus Yeah but I'm leaving that for the review, the embark bindings are on slightly shaky ground, having module specific top level bindings isn't something that's taken lightly

Yes, but you should put something there for review, so it's clear it needs one that works with the existing one.

2021-07-10 18:08 UTC, minad commented on modules/completion/vertico/config.el
> +        [backspace] #'+vertico/backward-updir))
Instead of your backward-updir function you may want to use 

~~~ elisp
;; Configure directory extension
(use-package vertico-directory
  ;; More convenient directory navigation commands
  :bind (:map vertico-map
              ("RET" . vertico-directory-enter)
              ("DEL" . vertico-directory-delete-char)
              ("M-DEL" . vertico-directory-delete-word))
  ;; Tidy shadowed file names
  :hook (rfn-eshadow-update-overlay . vertico-directory-tidy))
~~~

Note that I moved `vertico-directory-tidy` out of vertico core to the vertico-directory.el extension. This function cleans up shadowed paths.

2021-07-10 18:13 UTC, minad commented on modules/completion/vertico/config.el
> +  (set-face-bold 'completions-first-difference nil))
You may want to reconsider orderless+initialism now? This is my full configuration btw.

~~~ elisp
;; filtering system
(use-package orderless
  :demand t
  :config
  (defun dm/orderless-dispatch (pattern _index _total)
    (cond
     ;;((and completion-in-region-mode (= index 0)) `(orderless-regexp . ,(concat "^" pattern)))
     ;; Ensure that $ works with Consult commands, which add disambiguation suffixes
     ((string-suffix-p "$" pattern) `(orderless-regexp . ,(concat (substring pattern 0 -1) "[\x100000-\x10FFFD]*$")))
     ;; File extensions
     ((string-match-p "\\`\\.." pattern) `(orderless-regexp . ,(concat "\\." (substring pattern 1) "[\x100000-\x10FFFD]*$")))
     ;; Ignore single !
     ((string= "!" pattern) `(orderless-literal . ""))
     ;; Without literal
     ((string-prefix-p "!" pattern) `(orderless-without-literal . ,(substring pattern 1)))
     ((string-suffix-p "!" pattern) `(orderless-without-literal . ,(substring pattern 0 -1)))
     ;; Initialism matching
     ((string-prefix-p "`" pattern) `(orderless-initialism . ,(substring pattern 1)))
     ((string-suffix-p "`" pattern) `(orderless-initialism . ,(substring pattern 0 -1)))
     ;; Literal matching
     ((string-prefix-p "=" pattern) `(orderless-literal . ,(substring pattern 1)))
     ((string-suffix-p "=" pattern) `(orderless-literal . ,(substring pattern 0 -1)))
     ;; Flex matching
     ((string-prefix-p "~" pattern) `(orderless-flex . ,(substring pattern 1)))
     ((string-suffix-p "~" pattern) `(orderless-flex . ,(substring pattern 0 -1)))))
  (orderless-define-completion-style orderless+initialism
    (orderless-matching-styles '(orderless-initialism orderless-literal orderless-regexp)))

  (defun dm/basic-remote-try-completion (string table pred point)
    (and (vertico--remote-p string)
         (completion-basic-try-completion string table pred point)))

  (defun dm/basic-remote-all-completions (string table pred point)
    (and (vertico--remote-p string)
         (completion-basic-all-completions string table pred point)))

  (add-to-list
   'completion-styles-alist
   '(dm/basic-remote dm/basic-remote-try-completion dm/basic-remote-all-completions nil))

  (setq-default completion-styles '(orderless) ;; substring+orderless?
                ;;completion-ignore-case t
                completion-category-defaults nil
                completion-category-overrides
                '((file (styles dm/basic-remote partial-completion orderless+initialism))
                  (buffer (styles orderless+initialism))
                  (consult-multi (styles orderless+initialism))
                  (command (styles orderless+initialism))
                  (variable (styles orderless+initialism))
                  (symbol (styles orderless+initialism)))
                orderless-style-dispatchers '(dm/orderless-dispatch)
                orderless-matching-styles '(orderless-literal orderless-regexp)
                ;;orderless-component-separator "[ ߊ]+"  ;; special character for company!
                ))
~~~

2021-07-10 18:19 UTC, minad commented
@iyefrat Overall this looks pretty solid what you have here :+1:

2021-07-10 18:24 UTC, minad commented on modules/completion/vertico/autoload/vertico.el
> +(defun +vertico/next-candidate-preview ()
Pass the prefix argument to `vertico-next` for consistency?

2021-07-10 18:24 UTC, minad commented on modules/completion/vertico/autoload/vertico.el
> +(defun +vertico/previous-candidate-preview ()
Prefix argument?

2021-07-10 18:26 UTC, minad commented on modules/config/default/autoload/search.el
> +            #'swiper-isearch))
Why do you use `swiper-isearch` for helm btw?

2021-07-10 18:28 UTC, minad commented on modules/tools/lookup/config.el
> +    :init (setq xref-show-xrefs-function #'consult-xref)))
Here is this xref setting we talked about, it should be fine to use this:

~~~ elisp
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)
~~~

2021-07-10 19:57 UTC, gagbo commented on modules/config/default/autoload/search.el
> +            #'swiper-isearch))
Because it was already the case by default

https://github.com/hlissner/doom-emacs/blob/13958c81a66dc1b4f7d76f6337cfff817436a879/modules/config/default/autoload/search.el#L23-L31

It’s probably something that can be cleaned up, but it’s better if the discussion happens in another issue/PR

2021-07-10 22:57 UTC, iyefrat commented on modules/completion/vertico/config.el
> +        [backspace] #'+vertico/backward-updir))
Yeah I'll use some of these after the next package bump (current pin still has `vertico-ido`), not sure I want `vertico-directory-enter` though, I can just use tab for that and I sometimes want to open a dired buffer.

2021-07-10 22:59 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (set-face-bold 'completions-first-difference nil))
Oh right, I probably will add those back after a bit of testing. I also need to integrate the workarounds mentioned in the vertico readme. Need to run the TRAMP stuff by someone that actually uses TRAMP though, so it might be a review point.

2021-07-10 22:59 UTC, iyefrat commented
> @iyefrat Overall this looks pretty solid what you have here +1

@minad Thanks!

2021-07-10 22:59 UTC, iyefrat commented on modules/completion/vertico/autoload/vertico.el
> +(defun +vertico/next-candidate-preview ()
Yep good catch.

2021-07-10 23:02 UTC, iyefrat commented on modules/tools/lookup/config.el
> +    :init (setq xref-show-xrefs-function #'consult-xref)))
Yeah I intend to fix by editing history to get it right the first time, this since reverting a revert commit feels a bit funny, and this part of the code wasn't really touched since it got introduced. Correct me if I'm wrong, but the `:commands (consult-xref)` is redundant as `consult-xref` is already autoloaded, right?

2021-07-10 23:26 UTC, hlissner commented on modules/config/default/autoload/search.el
> +            #'swiper-isearch))
Because helm-swoop (the closest helm analogue) was terribly buggy at the time I tried it. There was also no acceptable alternative at the time. Swiper was simply the best option, so it was used for both completion backends.

2021-07-10 23:28 UTC, hlissner commented on modules/tools/lookup/config.el
> +    :init (setq xref-show-xrefs-function #'consult-xref)))
> the :commands (consult-xref) is redundant as consult-xref is already autoloaded, right?

Correct.

2021-07-11 04:27 UTC, minad commented on modules/completion/vertico/config.el
> +        [backspace] #'+vertico/backward-updir))
Yes, I am also not using `vertico-directory-enter`. This is only useful to emulate Ido behavior.

2021-07-11 04:29 UTC, minad commented on modules/tools/lookup/config.el
> +    :init (setq xref-show-xrefs-function #'consult-xref)))
Note that `consult-xref` is not even a command :)

2021-07-11 08:04 UTC, iyefrat commented on modules/tools/lookup/config.el
> +    :init (setq xref-show-xrefs-function #'consult-xref)))
Not sure why, but last night when I looked into the documentation in the `use-package` I came away with the understanding that `:commands` can be used to autoload any function/variable. I blame the late hour :D

2021-07-11 14:50 UTC, hlissner commented on modules/tools/lookup/config.el
> +    :init (setq xref-show-xrefs-function #'consult-xref)))
@iyefrat Your understanding was correct (for functions, not variables). `:commands` is a misnomer; a function doesn't have to be interactive (i.e. a command) to be autoloaded with it. Might've been more appropriately called `:autoload`.

2021-07-11 15:15 UTC, iyefrat commented on modules/tools/lookup/config.el
> +    :init (setq xref-show-xrefs-function #'consult-xref)))
@Henrik gothca

2021-07-11 17:12 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (set-face-bold 'completions-first-difference nil))
@minad why do you use `:demand t` here? it Doesn't basically do nothing because you don't have anything to defer loading?

2021-07-11 17:16 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (embark-collect-mode . consult-preview-at-point-mode))
@minad what is the usecase for this hook? The embark readme isn't that clear on how to produce previews in collect buffers (just moving the cursor to the buffer and moving around doesn't seem to work). I think it only serves a purpose if you aren't using a completion framework like vertico, but I'm not sure, it was added before my time.

2021-07-11 17:47 UTC, minad commented on modules/completion/vertico/config.el
> +  (embark-collect-mode . consult-preview-at-point-mode))
Yes, it works with embark-live-completions, embark-live/snapshot-collect and the default completion buffer as long as the minibuffer is still open while moving around in the buffer.

2021-07-12 03:18 UTC, dsdshcym commented on modules/config/default/autoload/search.el
> +         ((featurep! :completion vertico) #'isearch-forward))))
```suggestion
         ((featurep! :completion vertico) #'consult-line))))
```
why fallback to isearch for vertico? 🤔

2021-07-12 10:27 UTC, minad commented on modules/completion/vertico/config.el
> +  (set-face-bold 'completions-first-difference nil))
I believe I have set `use-package-always-defer` in my config

2021-07-12 10:46 UTC, minad commented on modules/config/default/autoload/search.el
> +         ((featurep! :completion vertico) #'isearch-forward))))
I believe because there is no exact substitute for `swiper-isearch` in Consult. As far as I know `counsel-isearch` delays the search until you typed a few characters? The Consult equivalent would look a bit like the following, but so far I have not seen the need to add such a command to Consult.

~~~ elisp
;; -*- lexical-binding: t -*-

(defun consult-line-delayed-async (async)
  (lambda (action)
    (if (and (stringp action) (not (equal action "")))
        (let ((lines))
          (with-current-buffer (window-buffer (minibuffer-selected-window))
            (save-excursion
              (goto-char (point-min))
              (while (search-forward-regexp action nil t 1)
                (push (consult--location-candidate
                       (consult--buffer-substring (line-beginning-position)
                                                  (line-end-position)
                                                  'fontify)
                       (point-marker) (line-number-at-pos))
                      lines))))
          (funcall async 'flush)
          (funcall async lines))
      (funcall async action))))

(defun consult-line-delayed ()
  (interactive)
  (let ((consult-async-split-style 'space))
    (consult--read
     (thread-first (consult--async-sink)
       (consult--async-refresh-immediate)
       (consult-line-delayed-async)
       (consult--async-split))
     :lookup #'consult--lookup-location
     :state (consult--jump-state))))
~~~

2021-07-12 11:10 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (embark-collect-mode . consult-preview-at-point-mode))
Ah I've finally figured out what my issue was with getting it to work, for `consult-grep` the `consult-customize` preview settings carry over so it wasn't automatic. Kind of obvious in retrospect.

2021-07-12 11:14 UTC, iyefrat commented on modules/config/default/autoload/search.el
> +         ((featurep! :completion vertico) #'isearch-forward))))
The main difference and reason why I didn't use `consult-line` there is that `swiper-isearch` will give you multiple candidates for the same line if it has multiple matches, while `consult-line` just gives you the line.

2021-07-12 11:29 UTC, minad commented on modules/config/default/autoload/search.el
> +         ((featurep! :completion vertico) #'isearch-forward))))
> will give you multiple candidates for the same line if it has multiple matches, while consult-line just gives you the line.

`consult-line-delayed` should also give you a separate candidate line for each match. `counsel-isearch/consult-line-delayed` is like some hybrid between line-based search (consult-line/consult-grep) and per-match search (plain isearch). I remain unconvinced.

2021-07-12 13:53 UTC, dsdshcym commented on modules/config/default/autoload/search.el
> +         ((featurep! :completion vertico) #'isearch-forward))))
`consult-line` works well-enough for me, at least the behavior is closer to `swiper` than `isearch-forward` 😂

2021-07-12 14:04 UTC, iyefrat commented on modules/config/default/autoload/search.el
> +         ((featurep! :completion vertico) #'isearch-forward))))
Yeah but it's already on `SPC s b`, so i feel like `isearch-forward` is a more natural thing to have at `SPC s s`

2021-07-12 14:07 UTC, minad commented on modules/config/default/autoload/search.el
> +         ((featurep! :completion vertico) #'isearch-forward))))
@iyefrat Yes, `isearch-forward` is the better choice. However I wonder - why not drop the binding completely? I assume Isearch is already available on some global binding - I mean it is the standard Emacs search.

2021-07-13 02:00 UTC, bdarcus commented
@iyefrat - shouldn't this code work at this point?

``` elisp
(if (featurep :completion vertico)
```
I'm getting this:

``` elisp
*** Eval error ***  Symbol’s value as variable is void: vertico
```

2021-07-13 03:05 UTC, daanturo commented on modules/completion/selectrum/config.el
> +  (setq completion-styles '(orderless)
Sorting Company's candidates can be done using [company-prescient](https://github.com/raxod502/prescient.el)

But without a package, we can achieve it by adding a sorter function to `company-transformers` (found this after inspecting how Prescient perform sorting for Company)

```lisp
(add-hook 'company-transformers
          (lambda (cands)
            ;; LSP servers usually provide smarter sorting, as suggested by Prescient
            (if (bound-and-true-p lsp-mode) 
                cands
              (sort
               cands
               (lambda (s0 s1)
                 (< (length s0) (length s1)))))))
```

Or even reuse `vertico`'s one
```lisp
(add-hook 'company-transformers
          (lambda (cands)
            (if (bound-and-true-p lsp-mode)
                cands
              (vertico-sort-length-alpha cands))))
```

2021-07-13 04:00 UTC, daanturo commented on modules/completion/vertico/autoload/vertico.el
> +        (completion-styles '(basic orderless)))
```suggestion
        (completion-styles +vertico-company-completion-styles))
```

2021-07-13 13:08 UTC, iyefrat commented on modules/config/default/autoload/search.el
> +         ((featurep! :completion vertico) #'isearch-forward))))
Mainly because Doom centers itself around a leader key workflow, and most default global emacs bindings have additional bindings under some leader key. For example, `C-x b` is also bound under `SPC b B` (`SPC b b` is gives you only buffers in your current workspace), `C-x C-f` is also `SPC .`, etc..

2021-07-13 13:09 UTC, iyefrat commented
> @iyefrat - shouldn't this code work at this point?
> 
> ```emacs-lisp
> (if (featurep :completion vertico)
> ```
> 
> I'm getting this:
> 
> ```emacs-lisp
> *** Eval error ***  Symbol’s value as variable is void: vertico
> ```

You should use `featurep!` for this, `featurep` is a built-in emacs thing

2021-07-13 13:26 UTC, iyefrat commented on modules/completion/vertico/autoload/vertico.el
> +
Hmm. I agree that `partial-completion` should be here by default, but I'm not sure about adding `+vertico-company-completion-styles`, users can also just modify the advice.  @hlissner what do you think? If it's not clear from context, this is advice for `company` to use vanilla completion styles before trying `orderless` (because it gives way too many answers that are usually not what you want when using company).

2021-07-13 14:15 UTC, minad commented on modules/completion/vertico/autoload/org.el
> +              :items    ,(lambda () (mapcar #'buffer-name (org-buffer-list)))))
@iyefrat One remark regarding the buffer sources: With every buffer source you are adding you are slowing down `consult-buffer`, so one should probably be a bit careful with that. In particular it will cause autoloading of org here. Is this always desired?

One alternative would be to hide the sources by default and only populate them lazily if they are shown. However this lazy population is not yet implemented in Consult - but I've considered it. It would also allow a more expensive project file source, which actually accesses the filesystem (https://github.com/minad/consult/issues/315). The project would only be scanned when `p` is pressed, but then it would happen synchronously. I have not yet implemented this because of the limited usefulness, it would only help hidden sources while they are hidden.

Another option to consider is to add asynchronous buffer sources (https://github.com/minad/consult/issues/196), but so far I've avoided this. I would probably not like asynchronously populated sources popping up in `consult-buffer`. This is different from `consult-ripgrep`, where I find it perfectly fine that new results come in with time.

2021-07-13 14:51 UTC, smsegal commented
Hey all, I've been using this PR as my primary editor for a couple weeks now. Great job! 

I'm trying out the `vertico-buffer` extension and it works great as well, however enabling `+icons` breaks the line formatting. It looks like the line width might have to be adjusted to a smaller value (though I'm not sure how the internals of `marginalia` and `all-the-icons-completion` interact). Since the vertico extensions aren't officially in scope of this PR, would you like me to open an issue against the `all-the-icons-completion` repo? 


![Screen Shot 2021-07-13 at 10 49 17 AM](https://user-images.githubusercontent.com/7110093/125473671-4b39f4d5-4bd5-45d5-8fd7-59a438d16a8a.png)

2021-07-13 15:23 UTC, iyefrat commented on modules/completion/vertico/autoload/org.el
> +              :items    ,(lambda () (mapcar #'buffer-name (org-buffer-list)))))
> One remark regarding the buffer sources: With every buffer source you are adding you are slowing down consult-buffer, so one should probably be a bit careful with that. In particular it will cause autoloading of org here. Is this always desired?

Good point. I've tried to check the performance difference, and it doesn't seem like it's noticeable (although it might be on slower machines), but now sometimes I get a void variable error on `org-buffer-list` when trying to run `consult-buffer` after startup, without any pattern I can discern. If I can't figure out the source of that error I'll remove the commit until I can resolve the issue. 

Another option would be to only add `+vertico--consult-org-source` after org is loaded, which would sidestep autoloading org. The use case for wanting to pick up orgmode buffers before you've opened one seems rather small, unless when you open a saved buffer configuration it doesn't load the major modes for them until you actually visit the buffers.

I actually implicitly assumed that `consult-buffer` behave in an asynchronous manner like you described for hidden sources, but I'm not sure adding it would be that useful, as you can generally use other commands for the same purpose.

2021-07-13 15:24 UTC, iyefrat commented
@smsegal Hi! It would be best to report this in the `all-the-icons-completion` repo. Please provide step by step instructions on how to reproduce the issue (starting from the PR is fine).

2021-07-13 15:38 UTC, iyefrat commented on modules/completion/vertico/autoload/org.el
> +              :items    ,(lambda () (mapcar #'buffer-name (org-buffer-list)))))
I think this probably has to do with some magic doom does to incrementally load org. I'll change this to getting defined after org loads and add a note.

2021-07-13 15:39 UTC, minad commented on modules/completion/vertico/autoload/org.el
> +              :items    ,(lambda () (mapcar #'buffer-name (org-buffer-list)))))
Yes, I want to keep things simple and immediate, supporting only fast synchronous buffer sources which populate quickly. Helm supports combining multiple asynchronous sources, but I believe it is getting complicated and brittle when doing that. As far as I can tell these are the two unique features that Helm has: Multiple asynchronous sources and acting on multiple candidates at once. We discussed with @bdarcus recently if multi actions would be a possibility in Embark and (https://github.com/oantolin/embark/issues/166, https://github.com/oantolin/embark/issues/256) and completing-read-multiple (https://github.com/minad/vertico/pull/74, https://github.com/minad/consult/pull/352). Long discussions...

2021-07-13 15:53 UTC, daanturo commented on modules/completion/vertico/autoload/vertico.el
> +
> users can also just modify the advice

Users can certainly remove the advice, but using internal symbols here will definitely uglify their customization code

```lisp
(advice-remove 'company-capf--candidates '+vertico--company-capf--candidates-a)
```

To alleviate garbled candidates, we can force `company` to sort by length without resorting to advices by adding a candidate sorter to `company-transformers` (`vertico-sort-length-alpha` can be used), just like what `company-prescient` does.

What I got looked quite neat compared to the unsorted candidates but just like other `orderless` results, the first character is not guaranteed to be a prefix for the candidates.


![image](https://user-images.githubusercontent.com/32123754/125470040-45206c9b-4b7c-4409-b946-714dfeda3890.png)

We may be able to delegate `company` completion to an `orderless` dispatcher if a flag that indicates whether `company` is active exists:
[orderless/issues/48#issuecomment-831603317](https://github.com/oantolin/orderless/issues/48#issuecomment-831603317)

(I have tried `company-point`, but it was shaky)

2021-07-14 14:05 UTC, daanturo commented on modules/completion/vertico/config.el
> +  :config
Let's add a popup rule for \*Embark Collect\* buffers here, for consistency with \*ivy-occur\*.
```suggestion
  :config
  (set-popup-rule! "^\\*Embark Collect\\*" :size 0.35 :ttl 0 :quit nil)
```
Also, it usually splits on the right by default, which will truncate a large part of annotations.

2021-07-14 15:05 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  :config
This actually used to be in the module, but it got removed because It cause an issue with the window opening logic when clicking on things like grep links. I didn't notice it splits off to the right because I almost always have emacs open on half a screen so it gets opened on the bottom. I'll look into how to get this to work properly. Thanks!

2021-07-14 21:09 UTC, minad commented on modules/completion/vertico/TODO.org
> +left, which we don't have here.
@iyefrat See https://github.com/minad/vertico/commit/bf727c25a7f069f8c6167d45c9c88f16f9c6b9e9. Please always report such details or oddities, this was an oversight of mine. The Emacs builtin pcm filter shows exactly this behavior regarding hidden files.

2021-07-14 21:38 UTC, iyefrat commented on modules/completion/vertico/TODO.org
> +left, which we don't have here.
@minad Aw man I liked that it shows me hidden files (https://xkcd.com/1172/ :stuck_out_tongue:).
I just assumed this was something extra that ivy did. However after updating Vertico to the latest commit it still shows me hidden files if there are other options.

2021-07-14 22:01 UTC, minad commented on modules/completion/vertico/TODO.org
> +left, which we don't have here.
Ah okay I misunderstood. Hidden files are shown, except if the are registered in completion-ignored-extensions. I adjusted the behavior of this filtering. When all files are ignored, no candidates left, then show the ignored files too.

2021-07-14 22:05 UTC, minad commented on modules/completion/vertico/TODO.org
> +left, which we don't have here.
There is no configuration as of now to hide hidden files in Vertico except by extension. So yes, this is something extra that Ivy does. But the behavior is easy to override by advising the vertico--file-filter.

2021-07-14 22:15 UTC, iyefrat commented on modules/completion/vertico/TODO.org
> +left, which we don't have here.
Ah, gotcha. This does indeed work as expected.

2021-07-18 14:31 UTC, iyefrat commented
@minad, have you considered adding a path expander to `vertico-directory-up` like I have here in `+vertico/bacward-updir`? I find it very useful for backspacing past `~/` to get to the root directory and do stuff.

2021-07-18 17:31 UTC, minad commented
@iyefrat No, usually you switch directories via shadow paths. See also vertico-directory-tidy.

2021-07-18 18:05 UTC, oantolin commented
I agree with @minad. Using Emacs's built-in path syntax, the shadow paths @minad mentioned, is faster for directory switching. For example if you are at `~/docs` and want to go to `/usr/bin`, you can just type `//usr/bin`, instead of deleting `docs` to get `/home/me`, deleting `me`, deleting `home`, and finally typing `usr/bin`.

2021-07-18 18:24 UTC, iyefrat commented
@minad @oantolin Fair enough, I should probably try to actively build up some muscle memory with shadow paths workflow because I always forget that it's there :stuck_out_tongue:. I will keep the built in path expansion though, It's more beginner friendly.

2021-07-18 18:31 UTC, bdarcus commented
> I will keep the built in path expansion though, It's more beginner friendly.

IDK about that. I sometimes find myself annoyed when typing backspace because of a typo.

I didn't even know about shadow paths though!

2021-07-18 18:35 UTC, iyefrat commented
> IDK about that. I sometimes find myself annoyed when typing backspace because of a typo.

It's what the `ivy` module does, and I think that for a beginner it's more intuitive to try this then the shadowed paths approach (which you sort of have to find out about from somewhere). In the`ivy` module I think you can't even delete `~/` manually, here you can do that here without the auto path expansion. In both cases if you press backspace you are out of the home directory though.

2021-07-18 18:56 UTC, minad commented
@iyefrat I won't add this to vertico or the extension, since we already have shadow paths which are better I think. @bdarcus seems to agree? You can of course stay with your own command here in case you prefer the ivy behavior.

2021-07-18 19:02 UTC, iyefrat commented
@minad Yeah, I understood that from what you said. I agree that it's the right call on your end, but I'm leaning slightly towards keeping the ivy behavior here. I added a note on that though, as it might be a good idea to not let people get into bad habits and just document how shadowed paths work in the readme or something, and to generally use upstream things instead of reimplementing them. But it also might cause a bunch of user questions on why can't they backspace through `~/`, so I'm not sure.

2021-07-18 19:03 UTC, iyefrat commented
At any rate, the PR is officially ready for review :tada: ! The status should be updated soon.

2021-07-19 09:07 UTC, hlissner requested changes
Nice work guys; this looks great! I'm eager to make this module our default completion module. I'm not fond of the direction ivy et co have grown. (I'm tempted to drop the ivy module altogether, frankly, though I likely won't) 

Anyhow, I have some misgiving about the current state of the PR, but take them with a grain of salt; some of them I can't resolve without sitting down and driving the module for an extended period of time:

+ The `TODO.org` should be updated and moved out of the repo and onto Discourse.
+ I'm not convinced `orderless` and `embark` need to be eagerly loaded, and would like to find a way not to.
+ At a glance I'm not convinced embark is necessary. It _sounds_ redundant with the leader key, and that any gap could be closed with more leader keys, which non-vertico users could benefit from as well.
+ Not a big fan of hard-coding `completion-styles` for `company-capf--candidates`. I would much rather we have separate variables for each, e.g. company-completion-styles, vertico-completion-styles, etc. -- so users have a way to avoid stepping on toes.
+ A lack of "search all open buffers" command bothers me, but I'll see if I can extend `consult-line` to scratch that itch.

In any case, once the changes I've annotated below are addressed this should be ready to merge, and we can work from there.

2021-07-19 10:03 UTC, minad commented
@hlissner I want to comment regarding Embark. If you want actions in the minibuffer in the style of Ivy, Embark is a requirement. I am not sure if this functionality is up to debate. Personally I am getting a lot of value from Embark actions and Embark collect buffers. I would not want to use Vertico and Consult without them.

The way Embark is implemented is quite generic. Minibuffer commands are augmented with actions based on the completion category. Actions at point in general buffers feel like the next logical step. The actions in the minibuffer and the actions at point in normal buffers are reused which gives a coherent experience overall.

However if you have already solved context dependent actions at point via leader keys, this Embark functionality may be less appealing. One could bind the Embark keys only in the mini buffer. Users who want to embrace Embark fully can bind the action keys globally in their user config. This may be an acceptable compromise since you keep the module "pure" by not binding global keys and it is still easy enough for the user to opt in to that functionality.

2021-07-19 10:56 UTC, bdarcus commented
> If you want actions in the minibuffer in the style of Ivy, Embark is a requirement. 

Indeed. I certainly think we need actions?

> However if you have already solved context dependent actions at point via leader keys, the Embark at point functionality in buffers may be less appealing. 

But it's really not "solved" in Doom to the same degree Embark does.

Context for the Doom keys is pretty general; like a major-mode.

Context in Embark can be really granular, like in #5212 (the screenshot at top uses this), an org-mode citation, or a link, etc.

2021-07-19 13:32 UTC, minad commented
Yes embark has support for ivy. And one could add support for more systems. It could be maintained in a separate module. However for now I would put it in this module, as a first step.

2021-07-19 17:26 UTC, bdarcus commented
> ... I could consider retrofitting embark into the lookup module,

I'm guessing this might be an interesting possibility.

There's I guess overlap of at-point functionality in different places.

- the `:tools lookup` module here
- `org-open-at-point`
- `embark`
- no doubt others

FWIW, in bibtex-actions-org-cite, for [`org-open-at-point` integration](https://github.com/bdarcus/bibtex-actions/blob/6b9a075aebd85fee8a071ffbbada1158ecd470d4/bibtex-actions-org-cite.el#L58) (via its "follow processor"), I just have a defcustom to allow the user to select what function to use, with default `embark-dwim`. But if they substitute `embark-act`, they get the contextual menu.

And this is [the target finder](https://github.com/bdarcus/bibtex-actions/blob/6b9a075aebd85fee8a071ffbbada1158ecd470d4/bibtex-actions-org-cite.el#L70), which mostly wraps generic at-point finder code from bibtex-completion.

What's great is that little bit of code, plus a keymap, gets the at-point bindings and menu, which works inside and outside Doom.

In any case, have fun testing it all out.

2021-07-20 12:03 UTC, iyefrat commented on init.example.el
> +       ;;vertico       ; the search engine of the future
Oops, slipped by. I'll fix this and the typo one in history, since I'd like to avoid typo fixing commits while I can, so I'll do these last in order to not muck up the comment display.

2021-07-20 12:08 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (set-face-attribute 'completions-first-difference nil :inherit nil))
This doesn't seem to get overridden when changing themes. Either way I don't really see how this can be left to the themes, since this setting only really makes sense if you both have `(setq completion-styles '(orderless)` and `(setq        completion-category-overrides '((file (styles . (orderless partial-completion))))`. I can just leave it off, but then highlighting during file completion sessions can kind of weird. Arguably, I'd also set `completions-common-part` to `orderless-match-face-0` for consistency.  The result of this is that when doing for example `find-file`, the file category override means that if you start doing glob matching (e.g. `~/**/init.el`), It'll do those with `partial-completion`. But `partial-completion` has a different highlighting scheme than orderless. which looks kind of weird if not changed.

2021-07-20 12:15 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  :config
It's possible to load it `:after vertico`, but that does mean that if you edit a file and use `company`, the completion behavior will be slightly different until you load a vertico session for the first time (because you can use `&` as an orderless separator). I don't think any other completion session uses something that isn't vertico.

2021-07-20 12:18 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (recentf-mode)
`consult-recent-file` doesn't work if you don't have the mode on, which makes using `SPC f r` on startup to open back some recently used file not work.

2021-07-20 12:22 UTC, iyefrat commented on modules/completion/vertico/config.el
> +(use-package! embark
Good point. I can't think of a way that would cause issues, I'll test it out for a bit and change it with the rest of the fixes.

2021-07-20 12:24 UTC, iyefrat commented on modules/completion/vertico/config.el
> +    [remap describe-bindings] #'embark-bindings)
Will do

2021-07-20 12:25 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (defun +vertico--embark-target-package! ()
> Rmove the ! in the name. This is the wrong naming convention for this type of function.

Good point, it's probably clear enough from the docstring that this targets `package!` statements specifically.

2021-07-20 12:28 UTC, iyefrat commented on modules/config/default/+emacs-bindings.el
> +         :desc "Jump to symbol in any workspace"     "J"   (lambda () (interactive)
Why `'(4)`? Does it have any special meaning in the context of passing a universal argument?

2021-07-20 12:29 UTC, iyefrat commented on modules/lang/org/config.el
> +         "G" #'consult-org-agenda)
Will do.

2021-07-20 12:29 UTC, iyefrat commented on modules/tools/lsp/+lsp.el
> +  :defer t)
Huh, true.

2021-07-20 12:29 UTC, iyefrat commented on modules/ui/workspaces/config.el
> +  (setq projectile-switch-project-action (lambda () (progn (+workspaces-set-project-action-fn) (+workspaces-switch-to-project-h)))
Will do.

2021-07-20 12:32 UTC, iyefrat commented
@hlissner No idea why on that one message it doesn't let me reply, but with regards to:
> Please use consult-line instead. SPC s commands are meant to be a collection of search commands conducted in the active completion framework. isearch (or an isearch-like) is not that, and is already globally available on / for evil users and C-s otherwise.

The issue I had with using `consult-line` here is that it only gives matches for the first match in each line. Is that still fine?

2021-07-20 12:36 UTC, iyefrat commented on modules/completion/vertico/config.el
> +                                         #'completion--in-region))))
Good point.

2021-07-20 12:36 UTC, gagbo commented on modules/completion/vertico/config.el
> +  :config
Is there still `doom-first-input-hook` ?

2021-07-20 12:37 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (add-hook 'rfn-eshadow-update-overlay-hook  #'vertico-directory-tidy)
Sure, in the mean time here's the explanation: when you type `~/foo/bar` -> `~/foo/bar/~/` to get back to the home directory, it automatically erases the `~/foo/bar/` part instead of just greying it out.

2021-07-20 12:38 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  :config
Oh yeah, that's a slam dunk

2021-07-20 12:38 UTC, gagbo commented on modules/config/default/+emacs-bindings.el
> +         :desc "Jump to symbol in any workspace"     "J"   (lambda () (interactive)
it means "`C-u` 1 time" https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Command-Arguments.html

2021-07-20 12:53 UTC, iyefrat commented
@hlissner Regarding this:

> Not a big fan of hard-coding completion-styles for company-capf--candidates. I would much rather we have separate variables for each, e.g. company-completion-styles, vertico-completion-styles, etc. -- so users have a way to avoid stepping on toes.

I feel like the best way to use this was to just have `+company-completion-styles` as a settable variable (which would have to be set in the `:comletion company` module I think for consistency), and just have vertico use the default `completion-styles`, no?

2021-07-20 12:58 UTC, iyefrat commented
There is also [this PR](https://github.com/Emiller88/doom-emacs/pull/23) by @daanturo. I'm not really sure what to make of it, I'm unfamiliar with `[menu]` key based workflows.

2021-07-20 15:15 UTC, daanturo commented on modules/completion/vertico/config.el
> +  :config
AFAIK we don't need to resort to hooks, since the `orderless` is automatically injected into `completion-styles-alist`. 
Unless we make use of `orderless-define-completion-style` to define a completion style, only 
`:init (setq completion-styles '(orderless))`
is enough. 
The aforementioned `orderless` style will automatically trigger `orderless-try-completion` & `orderless-all-completions`, which are autoloaded.

2021-07-20 15:29 UTC, gagbo commented on modules/completion/vertico/config.el
> +  :config
If that's true, I think @oantolin should update the README of https://github.com/oantolin/orderless to remove the `(require 'orderless)` from the second example

2021-07-21 04:11 UTC, hlissner commented
> The issue I had with using consult-line here is that it only gives matches for the first match in each line. Is that still fine?

@iyefrat Yes, for the time being anyway.

> There is also this PR by daanturo

I'll sit on that until I've assessed embark-act.

2021-07-24 10:46 UTC, minad commented
@iyefrat You may want to bump `flyspell-correct`. I made a few nice improvements to the `completing-read` interface, in particular I added shortcut keys which allow quick action and candidate selection.

2021-07-24 12:05 UTC, bdarcus commented
> @iyefrat You may want to bump `flyspell-correct`. I made a few nice improvements to the `completing-read` interface, in particular I added shortcut keys which allow quick action and candidate selection.

That reminds me: I'm not super knowledgeable about the emacs spell-checking landscape, but the default spell-checker in Doom is `emacs-fu`. Do we need something similar for that?

2021-07-24 14:26 UTC, iyefrat commented on init.example.el
> +       ;;vertico       ; the search engine of the future
fixed (in history)

2021-07-24 14:26 UTC, iyefrat commented on modules/completion/vertico/README.org
> +he packages in this module modify and use the built-in ~completing-read~
fixed (in history)

2021-07-24 14:26 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  :config
fixed

2021-07-24 14:26 UTC, iyefrat commented on modules/completion/vertico/config.el
> +(use-package! embark
fixed

2021-07-24 14:26 UTC, iyefrat commented on modules/completion/vertico/config.el
> +    [remap describe-bindings] #'embark-bindings)
fixed

2021-07-24 14:26 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (defun +vertico--embark-target-package! ()
fixed

2021-07-24 14:27 UTC, iyefrat commented on modules/config/default/+emacs-bindings.el
> +         :desc "Jump to symbol in any workspace"     "J"   (lambda () (interactive)
fixed

2021-07-24 14:27 UTC, iyefrat commented on modules/config/default/+evil-bindings.el
> +                                                             (call-interactively #'consult-lsp-symbols)))
fixed (in history)

2021-07-24 14:27 UTC, iyefrat commented on modules/lang/org/config.el
> +         "G" #'consult-org-agenda)
fixed (in history)

2021-07-24 14:27 UTC, iyefrat commented on modules/tools/lsp/+lsp.el
> +  :defer t)
fixed (in history)

2021-07-24 14:27 UTC, iyefrat commented on modules/ui/workspaces/config.el
> +  (setq projectile-switch-project-action (lambda () (progn (+workspaces-set-project-action-fn) (+workspaces-switch-to-project-h)))
fixed (in history)

2021-07-24 14:27 UTC, iyefrat commented on modules/completion/vertico/config.el
> +                                         #'completion--in-region))))
fixed

2021-07-24 14:27 UTC, iyefrat commented on modules/completion/vertico/config.el
> +                                         #'completion--in-region))))
fixed (in a different way than suggested)

2021-07-24 14:28 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (add-hook 'rfn-eshadow-update-overlay-hook  #'vertico-directory-tidy)
fixed

2021-07-24 14:28 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (fset 'multi-occur #'consult-multi-occur)
fixed

2021-07-24 14:28 UTC, iyefrat commented on modules/completion/vertico/config.el
> +    (add-hook 'marginalia-mode-hook #'all-the-icons-completion-marginalia-setup))
fixed

2021-07-24 14:28 UTC, iyefrat commented on modules/completion/vertico/config.el
> +        embark-become-indicator embark-action-indicator)
fixed

2021-07-24 14:30 UTC, iyefrat commented
@hlissner
I've done most of the requested changes (the new commits are start after 33b6d8c78 "vertico: use `vertico-directory-tidy`").

[Here](https://github.com/hlissner/doom-emacs/pull/4664#pullrequestreview-709054880) is a link to the initial review comment for ease of access as it got buried by the push. Since I can't mark requested changes as done, I just left a comment there (some of the changes were fixed in history due to lack of interaction with the rest of the module, indicated in the comment).

A few notes/questions:

The two changes I've purposely not fixed yet are the inclusion of `(recentf-mode)` ([see comment](https://github.com/hlissner/doom-emacs/pull/4664#discussion_r673069452)) and the `set-face-attribute` one ([see comment (https://github.com/hlissner/doom-emacs/pull/4664#discussion_r673062892)])

I've rebased on the latest doom commit, bumped the module, bumped `:tools biblio` (since I've avoided bumping `bibtex-acitons` until the merge so there will only be one bump commit, so it's heavily out of date) and bumped `:checkers spell` since it contains some relevant improvements.

I haven't yet moved `TODO.org` to the discourse, primarily because it contains some org file links in the "HACKs that need looking over" section that break when moving to markdown (and out of repo). These are minor things that imo should be fixed or acknowledged as fine as is before the merge anyway, so I'll move it to the discourse after that.

`embark` has recently added exporters for the `face` and `variable` categories, which export them to a customize buffer. Since Doom discourages use of `M-x customize`, should these be disabled?

Would you like me to add myself as a maintainer for the module? I plan on continuing to work on it post-merge regardless.

2021-07-24 14:32 UTC, iyefrat commented
Regarding the spelling stuff:
@minad Thanks for the heads up! I've bumped the spelling module, the improvements are nice.
@bdarcus I don't think that anything special needs to be done with `spell-fu`

2021-07-24 14:42 UTC, bdarcus commented
Awseome work @iyefrat - thank you!

On this ...

> @bdarcus I don't think that anything special needs to be done with `spell-fu`

... forgive the user support question, but then how do I correct a word using `spell-fu` with this module?

2021-07-24 15:01 UTC, minad commented
@iyefrat 

> embark has recently added exporters for the face and variable categories, which export them to a customize buffer. Since Doom discourages use of M-x customize, should these be disabled?

Damn, I had hoped we could smuggle in some of the sweet customize interface into Doom, but of course you would notice ;)

Seriously, neither @oantolin nor I are heavy customize users. I keep all my settings in the init.el. However the customize interface is actually not that bad for exploration. With the recently added Embark exporter one can filter the variables/faces in the minibuffer using your favorite completion style and then look at them in the customization view. I disable custom-buffer-verbose-help and custom-search-field, since the completion search functionality makes customize-apropos and the search field entirely redundant, so it does not even look that bad. Another advantage of the customize UI is that you can specify type information and provide example settings, which also helps for exploration. I recently added these:

* https://github.com/minad/vertico/blob/d651ad24131a712439249e768e8438a1c4d7a7c0/vertico.el#L78-L86
* https://github.com/minad/consult/blob/28f9ba8bdfdb13257862a658715b6ceb96f4951e/consult.el#L281-L287

So my current approach is to embrace the good sides of the customize interface :)

2021-07-24 15:10 UTC, iyefrat commented
> ... forgive the user support question, but then how do I correct a word using `spell-fu` with this module?

@bdarcus `z=` seems to work just like with flyspell (assuming that you're on evil mode). I don't use `spell-fu` day to day since the highlighting errors out when you use multiple dictionaries, but that doesn't have anything to do with the vertico module.

2021-07-24 15:16 UTC, iyefrat commented
@minad IIRC, Doom doesn't have a strong opposition to the customize interface on the UI level, but the way that it sets variables using themes, which has some weird interactions with they way doom lazy loads a lot of it's things, so things can get overridden by accident. It's a shame to lose out on the type information stuff though.

2021-07-24 15:17 UTC, bdarcus commented
> `z=` seems to work just like with flyspell (assuming that you're on evil mode).

Confirmed. Thanks.

2021-07-24 18:13 UTC, bdarcus commented
I was asking @iyefrat about this on discord, so thought I'd move the question here in case @minad @oantolin want to weigh in.

Can we make the configuration of `which-key` for the presentation of `embark-act` commands optional?

If yes, what's the best alternative option?

I've been trying for months to figure out how to address some design limitations of which-key, and a key bug, and am thinking now it's just the wrong tool, and that I'd rather using completing-read if I don't remember the bindings.

2021-07-24 18:23 UTC, oantolin commented
I know embark's completing-read prompter is a little offbeat, but I like it a lot better than which-key because I usually have some idea of what the action I want is and just forgot the keybinding. In that situation which-key forces you to visually scan a large list of command names, while with the completing-read prompter I just type 2 consecutive letters I remember from the command name and boom, I have a very short list to scan visually. And, if I do want to just read through all the actions, the completing-read prompter is good for that too: I think that for perusal a vertical list of all actions with first lines of docstrings that you can scroll through at your leisure is nicer than a cramped which-key display.

2021-07-24 18:31 UTC, iyefrat commented
To recap the discussion, @bdarcus was asking about having the following behind a feature flag:
```lisp
(setq embark-prompter #'embark-completing-read-prompter
         prefix-help-command #'embark-prefix-help-command)
```
Personally I think that `(setq prefix-help-command #'embark-prefix-help-command)` should be set by default, I think it's a much more intuitive interface than `describe-prefix-binding`. That might be added in a later PR though, I'm not sure I want to add more features while this one is under active review, and the approach @hlissner said he wants to take is to merge this as is (after a few obvious fixes) and continue to work on it in-tree.

I'm less sure about `(setq embark-prompter #'embark-completing-read-prompter)`, primarily because if you already remember the binding, it means that you have to press more keys. I feel like having it behind `C-h` is the best of both worlds.

Either way, I think these options are too small for a feature flag. Whatever isn't on by default would be better served by a mention in the configuration section of the readme.

2021-07-24 18:34 UTC, bdarcus commented
> That might be added in a later PR though, I'm not sure I want to add more features while this one is under active review, and the approach @hlissner said he wants to take is to merge this as is (after a few obvious fixes) and continue to work on it in-tree.

I just wasn't sure of the situation there, but that's totally fine by me.

> Either way, I think these options are too small for a feature flag. Whatever isn't on by default would be better served by a mention in the configuration section of the readme.

Also agree.

2021-07-24 18:37 UTC, minad commented
@iyefrat 

> I'm less sure about (setq embark-prompter #'embark-completing-read-prompter), primarily because if you already remember the binding, it means that you have to press more keys. I feel like having it behind C-h is the best of both worlds.

Imho the completing-read-prompter is a bad default. It only makes sense as C-h fallback.

2021-07-24 18:38 UTC, bdarcus commented
But how do I turn off which-key in my own config here?

If I add the config lines I mentioned, I get both UIs.

2021-07-24 18:42 UTC, bdarcus commented
> @iyefrat
> 
> > I'm less sure about (setq embark-prompter #'embark-completing-read-prompter), primarily because if you already remember the binding, it means that you have to press more keys. I feel like having it behind C-h is the best of both worlds.
> 
> Imho the completing-read-prompter is a bad default. It only makes sense as C-h fallback. So I agree that this configuration should not be provided explicitly here.

So what's the ideal default then? What do you have in your config, for example?

2021-07-24 18:48 UTC, oantolin commented
> I'm less sure about `(setq embark-prompter #'embark-completing-read-prompter)`, primarily because if you already remember the binding, it means that you have to press more keys. I feel like having it behind `C-h` is the best of both worlds.

I agree with this 100%! I certainly prefer to use the keymap prompter as the default (which is why it _is_ the default in embark). Well, maybe I only agree 99%: in my personal configuration I don't have the completing-read prompter on `C-h` but on `?` instead. I find that I often want to use some commands in the `C-h` prefix as actions. I've even thought of changing the default in Embark, but like that `C-h` matches what Emacs uses for prefix keymaps.

2021-07-24 19:08 UTC, bdarcus commented
> > I'm less sure about `(setq embark-prompter #'embark-completing-read-prompter)`, primarily because if you already remember the binding, it means that you have to press more keys. I feel like having it behind `C-h` is the best of both worlds.
> 
> I agree with this 100%! I certainly prefer to use the keymap prompter as the default (which is why it _is_ the default in embark). Well, maybe I only agree 99%: in my personal configuration I don't have the completing-read prompter on `C-h` but on `?` instead. I find that I often want to use some commands in the `C-h` prefix as actions. I've even thought of changing the default in Embark, but like that `C-h` matches what Emacs uses for prefix keymaps.

One little suggestion, @oantolin: the initial prompt that shows "Act" in prominent blue: is there some way to more subtly signal that one should use `C-h` for the command list?

Is there some general convention for that in Emacs that might work?

I expected a bit, but wasn't happy with any obvious solution.

2021-07-24 19:14 UTC, oantolin commented
@bdarcus The "Act" thing is configurable, you could set it to "Act (C-h for help)" or something like that (and you can highlight only the "Act" part). I didn't do it because, `embark-act` conceptually acts like a prefix key, and prefix keys also have this `C-h` feature and also don't advertise it. I thought Emacs users would simply expect to be able to pres C-h to get a reminder of key bindings, that is, I thought it would be discoverable even for people who don't read docstrings.

2021-07-24 19:25 UTC, iyefrat commented
>  I thought Emacs users would simply expect to be able to press C-h to get a reminder of key bindings,

@oantolin  To be fair this is probably true, just not among doom users who are used to `which-key` being on by default. The vertico module will probably keep the current indicator (at least for the time being), since `which-key` is a core Doom package. If it gets moved to it's own module (which I think is a thing that's happening down the line? maybe?) That might be a good thing to add, but then again, doom users with which-key off will be much more used to a `C-h` eccentric workflow, so maybe the `(C-h for help)` won't be needed.

2021-07-24 22:06 UTC, hlissner commented on modules/completion/vertico/config.el
> +  (set-face-attribute 'completions-first-difference nil :inherit nil))
It depends on the theme whether or not it gets overwritten when (re)loading a theme. In `doom-themes` case, we don't set `completions-first-difference`, but that will change soon. I'll fix when that happens post-merge.

2021-07-24 22:08 UTC, hlissner commented on modules/completion/vertico/config.el
> +  (recentf-mode)
Ah. I can probably do some voodoo with advice to have recentf load before `consult-recent-file` gets called. I'll look into this post merge. Thanks!

2021-07-24 22:13 UTC, hlissner approved these changes

2021-07-25 04:36 UTC, daanturo commented on modules/config/default/+evil-bindings.el
> +         "M-RET" #'vertico-exit-input
`vertico-exit-input` is already bound to [C-return] by default [vertico.el](https://github.com/minad/vertico/blob/51152475cf96c78a795525675999f6d12545c0ec/vertico.el#L120), making this looks redundant

(Also in ivy, M-RET is `ivy-call` - previewing without quitting.)

2021-07-25 08:12 UTC, merged

2021-07-25 08:12 UTC, hlissner commented
And bam! Thanks for all your help guys, especially @iyefrat. Looking forward to giving this a spin!

2021-07-25 08:18 UTC, iyefrat commented
I would also like to say thanks to all the people that worked on, reviewed, and beta tested the module. Particularly to @minad, but the full list is too long for me to write out without forgetting someone by accident.

2021-07-26 05:31 UTC, ttys3 commented
Finally, this get merged! Cheers