Add support for parinfer-rust-mode
hlissner/doom-emacs pull request #4671
Opened 2021-02-18 20:53 UTC by johanthoren

This commit adds support for the `parinfer` module flag `+rust`, which will use `parinfer-rust-mode`
instead of `parinfer-mode`. `parinfer-rust-mode` makes use of an external library named `parinfer-rust`
to do the heavy lifting. As such, `--with-modules` must be enabled.

This is the suggested solution to [issue 4635](https://github.com/hlissner/doom-emacs/issues/4635).

2021-02-20 19:14 UTC, hackeryarn commented
Since `parinfer` is deprecated, as per their repo readme, would it make sense to completely replace `parinfer` with `parinfer-rust-mode`?

It could probably keep the same module name, just use `parinfer-rust-mode` behind the scenes.

2021-02-20 19:15 UTC, hackeryarn commented
Sorry just noticed the discussion is taking place in another issue.

2021-02-27 02:47 UTC, hlissner requested changes
Please create a doctor.el file in the module with the following:

```elisp
;;; editor/parinfer/doctor.el -*- lexical-binding: t; -*-

(when (featurep! +rust)
  (unless (fboundp 'module-load)
    (warn! "Your emacs wasn't built with dynamic modules support. `parinfer-rust-mode' won't work")))
```

With that and the commented fixes we should be good to go. In the long term, the `parinfer` package is now deprecated and will remain for a year or two (or until it breaks, whichever comes first) before it is removed.

2021-02-27 02:47 UTC, hlissner commented on modules/editor/parinfer/config.el
> +(if (not (featurep! +rust))
Rather than wrapping them in an `if` statement, use `use-package`'s `:if` parameter instead. e.g.

```elisp
(use-package! parinfer
  :unless (featurep! +rust)
  ...)

(use-package! parinfer-rust-mode
  :when (featurep! +rust)
  :when (bound-and-true-p module-file-suffix)
  ...)
```

This has some compile-time benefits that aren't seen otherwise.

2021-02-27 02:47 UTC, hlissner commented on modules/editor/parinfer/config.el
> +                                              "parinfer-rust-windows.dll")))
Please inline this into the `setq!` statement below.

2021-02-27 02:47 UTC, hlissner commented on modules/editor/parinfer/config.el
> +    (setq! parinfer-rust-library (concat user-emacs-directory
`s/setq!/setq`. There is no benefit to triggering setters before the package is loaded (they will be triggered when the package is later loaded, if any).

2021-02-27 02:47 UTC, hlissner commented on modules/editor/parinfer/config.el
> +          :desc "Temporarily disable parinfer-rust-mode" "M"
Please remote these `:desc`s. Which-key doesn't support them on minor modes, and they will end up overwriting the label for these key sequences globally instead.

2021-02-27 02:47 UTC, hlissner commented on modules/editor/parinfer/packages.el
> +  (package! parinfer :pin "8659c99a9475ee34af683fdf8f272728c6bebb3a"))
Could you replace `(package! parinfer ...)` with

```elisp
(package! parinfer
  :recipe (:host github :repo "emacsattic/parinfer")
  :pin "8659c99a9475ee34af683fdf8f272728c6bebb3a")
```

The package is no longer in MELPA or emacsmirror, so it won't be found otherwise.

2021-02-28 04:55 UTC, hlissner approved these changes

2021-02-28 04:56 UTC, merged

2021-02-28 04:56 UTC, hlissner commented
Looks good to me! Thanks for your help!