Set default eshell TERM
hlissner/doom-emacs pull request #4678
Opened 2021-02-22 06:37 UTC by elken

Makes eshell more ansi-friendly ootb. I'm not 100% tied to it being `xterm` if you think there's a better option.

2021-02-23 19:30 UTC, hlissner requested changes

2021-02-23 19:30 UTC, hlissner commented on modules/term/eshell/config.el
> +    (setenv "TERM" "xterm-256color")
Use `(setq eshell-term-name "xterm-256color")` instead, and move it out of the hook as it should be set globally so that it is easily changed.

That said, this may have other side effects. Please keep a look out for them. If folks report issues after this change I may revert it later.

2021-02-23 19:33 UTC, elken commented on modules/term/eshell/config.el
> +    (setenv "TERM" "xterm-256color")
Yeah good point, I will.

I've been using it myself and it hasn't _caused_ any issues yet but it certainly helps modernise eshell a bit. I'll add a README note too

2021-02-24 00:38 UTC, hlissner approved these changes

2021-02-24 00:38 UTC, merged

2021-02-24 00:39 UTC, hlissner commented
Looks good to me. Thanks!