Purescript mode improvements
hlissner/doom-emacs pull request #4683
Opened 2021-02-23 06:51 UTC by rgrinberg

- Add keybindings
- Enable flycheck
- Add psci based repl

2021-02-23 15:42 UTC, hlissner requested changes

2021-02-23 15:42 UTC, hlissner commented on modules/lang/purescript/config.el
> +    (set-repl-handler! 'purescript-mode #'psci))
Replace with `(set-repl-handler! 'purescript-mode #'psci)`. Autodefs like `set-repl-handler!` implicitly no-op if their defining module isn't enabled (`:tools eval` in this case).

2021-02-23 15:42 UTC, hlissner commented on modules/lang/purescript/packages.el
> -;;(package! flycheck-purescript :pin "30f0435d5e")
Don't we need this?

2021-02-23 15:42 UTC, hlissner commented on modules/lang/purescript/packages.el
> -;;(package! flycheck-purescript :pin "30f0435d5e")
And is the original issue resolved? `flycheck-purescript` is abandoned and hasn't been updated in 4-5 years, well before the date this module was introduced (bd84e90f809a).

2021-02-23 15:42 UTC, hlissner commented on modules/lang/purescript/config.el
> +  :hook (purescript-mode . flycheck-purescript-setup))
Please replace with:

```elisp
(use-package! flycheck-purescript
  :when (featurep! :checkers syntax)
  :after purescript-mode
  :config (flycheck-purescript-setup))
```

`flycheck-purescript-setup` mutates global state, so it is poorly suited to a mode hook (even if it may work by happy accident). The above takes this into account.

2021-02-23 16:11 UTC, rgrinberg commented on modules/lang/purescript/packages.el
> -;;(package! flycheck-purescript :pin "30f0435d5e")
Yeah, I think `flycheck-purescript` is abandoned. In any case psc-ide is frequently updates and has flycheck support.

2021-02-23 16:30 UTC, rgrinberg commented on modules/lang/purescript/config.el
> +    (set-repl-handler! 'purescript-mode #'psci))
Done

2021-02-23 16:46 UTC, rgrinberg commented on modules/lang/purescript/config.el
> +  :hook (purescript-mode . flycheck-purescript-setup))
done

2021-02-24 00:34 UTC, hlissner requested changes

2021-02-24 02:39 UTC, rgrinberg commented on modules/lang/purescript/config.el
> +  :config (psc-ide-flycheck-setup))
Done. Thanks for your patience.

2021-02-24 06:22 UTC, hlissner approved these changes

2021-02-24 06:22 UTC, merged

2021-02-24 06:22 UTC, hlissner commented
Looks good to me. Thanks!