Fix +debug/start for dap-based debuggers.
hlissner/doom-emacs pull request #4708
Opened 2021-02-28 21:18 UTC by he-la

Reworks the internals of how the debugger module stores the last-used
configuration:
- car of the configuration indicates whether it is a realgud or a dap-based configuration.
- For dap-based debuggers, the entire dap configuration is stored, with code copied from `dab-debug`.
- When inside a project, don't store the configuration as a buffer-local variable, but instead as a project-local variable using `projectile-variable`.

Fixes #2367.

2021-02-28 22:18 UTC, hlissner requested changes
I agree with the premise of this PR, but please factor out the dependency on `dash` and `projectile-variable`. Doom doesn't guarantee dash's availability, and projectile is on a long-term crash course for replacement with project.el. Scoping data to a project can be done with the `doom-cache-*` API (using project roots as the key).

2021-03-01 07:21 UTC, he-la commented
`projectile-variable` does not actually depend on projectile (it uses emacs symbol properties), so replacing `projectile-project-p` with `doom-project-p` would fully remove projectile as a dependency. I am not sure which API you mean by `doom-cache-*`. There is a `doom-cache-dir` where I could write to, but that doesn't make too much sense to me. I could also add the few relevant lines from `projectile-variable` to doom's `projects.el` to implement the functionality of project-specific variables across doom.

2021-03-06 00:43 UTC, hlissner commented
Ah, my bad. I meant the `doom-store-*` API (`doom-cache-*` was its old name), which makes projectile-variable redundant (and comes with the extra nicety of persistent storage, across sessions). In any case, I've implemented it in cf086d0 along with a few minor changes:

- I've replaced projectile API calls with `doom-project-*` (as you mentioned) so we're prepared for the inevitable project.el switch, whenever that may happen.
- There was a string comparison preformed with `eq`, which will never return `t`, because `eq` compares object identity rather than equality. i.e. `(eq "test" "test")` will return `nil`.
- I've renamed internal functions according to convention (with the extra dash), to indicate they shouldn't be used outside of the module. This is not an issue for this PR, however, they were incorrectly named before it.

In any case, thanks for your help! I will merge this as soon as I've pushed a couple needed updates to the `doom-store-*` API.

2021-03-06 01:14 UTC, hlissner approved these changes

2021-03-06 01:14 UTC, merged

2021-03-06 07:43 UTC, he-la commented
Awesome, thanks for the tips!

I think you forgot to remove the `use-package!` call for `projectile-variable` in `config.el`, sorry about that.