Add module for the dhall config language
hlissner/doom-emacs pull request #4791
Opened 2021-03-13 02:50 UTC by rgrinberg

Title explains everything

2021-04-15 04:34 UTC, hlissner requested changes
Also:

1. Please add an entry for `:lang dhall` to `docs/modules.org`.
2. And add a dummy README.org using the `__doom-readme` snippet for this module.

2021-04-15 04:34 UTC, hlissner commented on modules/lang/dhall/config.el
> +(use-package! dhall-mode
Add `:defer t`, otherwise the package is eagerly loaded at startup.

2021-04-15 04:34 UTC, hlissner commented on init.example.el
> +       ;;dhall
Please sort this alphabetically (below `dart`)

2021-04-15 04:34 UTC, hlissner commented on modules/lang/dhall/config.el
> +  (map! :after dhall-mode
Remove `:after dhall-mode`, it's redundant with nesting this `map!` in `dhall-mode`'s `:config` block.

2021-04-15 04:34 UTC, hlissner commented on modules/lang/dhall/config.el
> +  (map! :after dhall-mode
Please add `(setq dhall-format-at-save (featurep! :editor format +onsave))` on the line between `set-repl-handler!` and `map!`.

2021-04-15 05:21 UTC, rgrinberg commented
Thanks for the review!

2021-08-03 05:50 UTC, hlissner approved these changes

2021-08-03 05:51 UTC, merged

2021-08-03 05:51 UTC, hlissner commented
Sorry for the _tremendously_ late reply. Thanks for the PR!