notmuch -- respect +afew feature flag, fix sync buffer kill
hlissner/doom-emacs pull request #4838
Opened 2021-04-04 05:22 UTC by nackjicholson

When #3933 was closed, part of it's documentation snuck in. The part about the `+afew` feature flag is in the docs, but it's not respected.

This change will make it be respected. It also edits the notmuch sync function to use `compile` in order to address the problems described in https://github.com/hlissner/doom-emacs/issues/3188

Please consider this for merge.

2021-04-13 23:18 UTC, hlissner requested changes

2021-04-13 23:18 UTC, hlissner commented on modules/email/notmuch/config.el
> +        :desc "Sync email" "u" #'+notmuch/update
Please align `"u"` with `"c"` in the line above.

2021-04-13 23:18 UTC, hlissner commented on modules/email/notmuch/autoload.el
> +                     "mbsync -c \"$XDG_CONFIG_HOME\"/isync/mbsyncrc -a && notmuch new")
Could these two be merged? i.e. If `$XDG_CONFIG_HOME/isync/mbsyncrc` exists, inject `-c $XDG_CONFIG_HOME/isync/mbsyncrc` into the command, otherwise, don't.

2021-04-14 15:14 UTC, nackjicholson commented on modules/email/notmuch/autoload.el
> +                     "mbsync -c \"$XDG_CONFIG_HOME\"/isync/mbsyncrc -a && notmuch new")
I don't know. Since I don't personally use mbsync I didn't want to mess with it on the off chance that changing it might break something for someone else. I didn't write this part of the code, I only moved it.

2021-04-14 16:47 UTC, hlissner approved these changes

2021-04-14 16:47 UTC, hlissner commented on modules/email/notmuch/autoload.el
> +                     "mbsync -c \"$XDG_CONFIG_HOME\"/isync/mbsyncrc -a && notmuch new")
Very well. I'll make the change later. Thanks.

2021-04-14 16:47 UTC, merged

2021-04-14 16:47 UTC, hlissner commented
Thanks!