Improve factor configuration
hlissner/doom-emacs pull request #4841
Opened 2021-04-11 22:40 UTC by rgrinberg

* Add bindings to fuel-help-mode
* Add more bindings to factor mode
* Add more bindings to fuel-listener mode

2021-04-13 23:14 UTC, hlissner requested changes

2021-04-13 23:14 UTC, hlissner commented on modules/lang/factor/config.el
> +(map! :after fuel-help-mode
`s/fuel-help-mode/fuel-help`. [The package that defines `fuel-help-mode-map`](https://github.com/factor/factor/blob/master/misc/fuel/fuel-help.el) is called `fuel-help`, not `fuel-help-mode`, therefore these keybinds will never take effect.

2021-04-13 23:36 UTC, rgrinberg commented on modules/lang/factor/config.el
> +(map! :after fuel-help-mode
Fixed. Thanks for the review.

2021-04-14 00:15 UTC, hlissner approved these changes

2021-04-14 00:15 UTC, merged

2021-04-14 00:15 UTC, hlissner commented
Thanks!