Bump :editor evil
hlissner/doom-emacs pull request #4873
Opened 2021-04-16 13:44 UTC by jcf

emacs-evil/evil-collection@b45ec5b → emacs-evil/evil-collection@b6025cf
emacs-evil/evil@7eace67 -> emacs-evil/evil@d998a81

The register system has been rejigged in the last week, and some
packages in the Evil ecosystem are already making use of the new vars.

emacs-evil/evil@229ebb4
mamapanda/evil-owl#10

2021-04-16 13:46 UTC, jcf commented
I'm not sure if I got the format of the commit message right. Apologies!

I did try to run `doom/commit-bumps` but it looks like that function needs to be written?

``` elisp
;;;###autoload
(defun doom/commit-bumps ()
  (interactive))
```

I'm guessing it won't be trivial to implement, but will take a quick stab at it.

2021-04-16 17:28 UTC, hlissner requested changes
Thanks for the PR! The commit message is perfect, but would you mind also bumping `evil-collection` as well? 

There's a subtle difference between `Bump package-name` and `Bump :editor evil`. The latter implies you've bumped the whole module and any packages that haven't been bumped either a) have no updates or b) are blocked by something else. The former explicitly means "I'm only bumping this one package."

Given that evil-collection has updates and, after looking through them, there are no blockers, I'd rather expand the scope of this PR.

> re:doom/commit-bumps

Don't waste any time on `doom/commit-bumps`. The reason this isn't implemented (and may never be) is because that functionality is being implemented elsewhere (as part of #4273). 

The new CLI will introduce CI/CD for bumping packages or modules with the `bin/doom` tool. e.g. `doom bump evil` (bumps the package) or `doom bump :lang evil` (bumps all packages in the module). This will then open $EDITOR with a pre-filled commit message (plus a `-f` switch or similar to skip that step).

This will be automated much later, and tied to a web interface outdated pins can be tracked. (Not to mention, folks will be able to request out-of-band bumps on our Discourse).

2021-04-16 20:56 UTC, jcf commented
> There's a subtle difference between Bump package-name and Bump :editor evil. The latter implies you've bumped the whole module and any packages that haven't been bumped either a) have no updates or b) are blocked by something else. The former explicitly means "I'm only bumping this one package."

@hlissner that makes sense. I thought my use of `:editor evil` might be a little… excessive. I've bumped evil-collection as requested, and force pushed a new commit with an update commit message.

I'm already subscribed to #4273, so will keep an eye on things there, and help out wherever I can.

Thanks!

2021-04-17 04:33 UTC, hlissner approved these changes

2021-04-17 04:33 UTC, merged

2021-04-17 04:34 UTC, hlissner commented
Looks good to me! Thanks again!