fix and add keybinds in :lang scheme, with descriptions
hlissner/doom-emacs pull request #4890
Opened 2021-04-19 01:03 UTC by hugonobrega

Some keys were bound to no-longer-existing commands, or commands which changed
name.

Others only made sense in the REPL, or /also/ in the REPL, so the keybinds are
now in `scheme-mode-map', `geiser-repl-mode-map', or both accordingly.

(recreating PR #4889 which was closed by accident)

2021-04-19 21:36 UTC, hlissner requested changes

2021-04-19 21:36 UTC, hlissner commented on modules/lang/scheme/config.el
> +         :desc "Collapse macro by one step" "c" #'macrostep-collapse)))
1. Remove the `c` keybind. expand/collapse keybinds are exposed when your point is over expanded regions.
2. Move `macrostep-expand` and `macrostep-geiser-expand-all` back to `SPC m m` and `SPC m M`. This is to be consistent with macrostep keybinds in our lisps (e.g. [common-lisp](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/common-lisp/config.el#L93) and [emacs-lisp](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/emacs-lisp/config.el#L132)).

2021-04-19 21:36 UTC, hlissner commented on modules/lang/scheme/config.el
> +  (map!
To be consistent with other uses of `map!` please:

1. Place `:localleader on the same line as `map!` (and reindent the whole form),
2. Align the keys.

i.e.

```elisp
(map! :localleader
      (:map (scheme-mode-map geiser-repl-mode-map)
       :desc "Toggle REPL"                  "'"  #'switch-to-geiser
       :desc "Connect to external Scheme"   "\"" #'geiser-connect
       :desc "Toggle type of brackets"      "["  #'geiser-squarify
       :desc "Insert lambda"                "\\" #'geiser-insert-lambda
       :desc "Set Scheme implementation"    "s"  #'geiser-set-scheme
       :desc "Reload Geiser buffers+REPLs"  "R" #'geiser-reload
       (:prefix ("h" . "help")
        :desc "Show callers of <point>"     "<" #'geiser-xref-callers
        :desc "Show callees of <point>"     ">" #'geiser-xref-callees
        :desc "Toggle autodoc mode"         "a" #'geiser-autodoc-mode
        :desc "Show autodoc of <point>"     "s" #'geiser-autodoc-show
        :desc "Search manual for <point>"   "m" #'geiser-doc-look-up-manual
        :desc "Show docstring of <point>"   "." #'geiser-doc-symbol-at-point)
       (:prefix ("r" . "repl")
        :desc "Load file into REPL"         "f" #'geiser-load-file
        :desc "Restart REPL"                "r" #'geiser-restart-repl))
      (:map scheme-mode-map
       (:prefix ("e" . "eval")
        :desc "Eval buffer"                 "b" #'geiser-eval-buffer
        :desc "Eval buffer and go to REPL"  "B" #'geiser-eval-buffer-and-go
        :desc "Eval last sexp"              "e" #'geiser-eval-last-sexp
        :desc "Eval definition"             "d" #'geiser-eval-definition
        :desc "Eval defn. and go to REPL"   "D" #'geiser-eval-definition-and-go
        :desc "Eval region"                 "r" #'geiser-eval-region
        :desc "Eval region and go to REPL"  "R" #'geiser-eval-region-and-go)
       (:prefix ("r" . "repl")
        :desc "Load current buffer in REPL" "b" #'geiser-load-current-buffer))
      (:map geiser-repl-mode-map
       :desc "Clear REPL buffer"            "c" #'geiser-repl-clear-buffer
       :desc "Quit REPL"                    "q" #'geiser-repl-exit)))
```

2021-04-19 21:36 UTC, hlissner commented on modules/lang/scheme/config.el
> -
Please restore this blank line. Two blank lines between top-level `use-package!` and `after!` forms is one of Doom's conventions.

2021-04-19 21:36 UTC, hlissner commented on modules/lang/scheme/config.el
> +         :desc "Collapse macro by one step" "c" #'macrostep-collapse)))
Please restore second blank newline between `use-package!` for `macrostep-geiser` and `flycheck-guile`. Two blank lines between top-level use-package! and after! forms is one of Doom's conventions.

2021-04-20 00:18 UTC, hugonobrega reviewed
Implements all changes requested by @hlissner

2021-05-01 06:02 UTC, hlissner approved these changes

2021-05-01 06:02 UTC, merged

2021-05-01 06:02 UTC, hlissner commented
Sorry for the late response. Thanks again for your help!