Bump lsp-sourcekit and add support for sourcekit-lsp bundled with Xcode
hlissner/doom-emacs pull request #4912
Opened 2021-04-23 14:04 UTC by 5t111111

## Bump lsp-sourcekit
Bump the version of lsp-sourcekit used in :lang `swift`.

https://github.com/emacs-lsp/lsp-sourcekit/commit/ff204ed820df8c3035ebdc4b5a583640d52caeeb → https://github.com/emacs-lsp/lsp-sourcekit/commit/aafa9878a3df2f08e5a9c846d91fd53350ce3c99

## Add support for sourcekit-lsp bundled with Xcode

Recent Xcode ships with the `sourcekit-lsp` server and the latest lsp-soucekit package [supports that bundled `sourcekit-lsp` as the default configuration](https://github.com/emacs-lsp/lsp-sourcekit/blob/aafa9878a3df2f08e5a9c846d91fd53350ce3c99/README.md#quickstart), so I have inserted the bundled `sourcekit-lsp` server path to the first place of the executable list.

Also, since the new version of lsp-sourcekit package changes the default executable from `sourcekit` to `soucekit-lsp`, I modified the executable list to fit to that.

Although lsp-sourcekit package [now has nicer executable lookup method](https://github.com/emacs-lsp/lsp-sourcekit/commit/aafa9878a3df2f08e5a9c846d91fd53350ce3c99), I leave the executable list for backward compatibility.

2021-04-23 16:54 UTC, hlissner requested changes
Please bump the whole `:lang swift` module with `M-x doom/bump-packages-in-buffer` and reword the commit message to:

```
Bump :lang swift

swift-emacs/swift-mode@95ff004 -> swift-emacs/swift-mode@ad12a30
emacs-lsp/lsp-sourcekit@ff204ed -> emacs-lsp/lsp-sourcekit@aafa987

Adds support for sourcekit-lsp bundled with Xcode
```

Bump commits must adhere to this template in order to remain machine readable by future CI.

2021-04-24 01:18 UTC, 5t111111 commented
@hlissner 

Thnaks for you review.

> Bump commits must adhere to this template in order to remain machine readable by future CI.

I'm sorry I didn't notice that required commit message regulations.

- Bump whole swift module using `doom/bump-packages-in-buffer` as well 
- Reword commit message
- Modified pull request title and body to meet that commit

Please have a look again!

2021-04-29 17:45 UTC, hlissner approved these changes

2021-04-29 17:46 UTC, merged

2021-04-29 17:46 UTC, hlissner commented
Thanks for your help!