Bind TeX-view in LaTeX-mode-map too
hlissner/doom-emacs pull request #4945
Opened 2021-04-28 22:07 UTC by ymarco

I know https://github.com/hlissner/doom-emacs/commit/0d6c32ff25292ecdef7ecdfd1542bb65807c4d9a was supposed to fix *something*, but I'm just unable to use any keybind on latex-mode-map.
Binding it on both is the safest bet I think.

2021-04-28 22:10 UTC, ymarco commented
Hold on, `map!` expands incorrectly here

2021-05-01 05:39 UTC, hlissner requested changes
Does it work if you combine the two `map!` calls with `:map (latex-mode-map LaTeX-mode-map)` instead?

2021-05-01 13:45 UTC, ymarco commented
> Does it work if you combine the two `map!` calls with `:map 
> (latex-mode-map LaTeX-mode-map)` instead?

Yes, but LaTeX-mode-map might not be bound after only auctex's 
tex.el loads. It's declared in auctex's latex.el.
latex-mode-map is defined in tex-mode.el, packaged with Emacs. The 
built-in latex-mode is used by auctex's TeX-mode.
Can we maybe bind TeX-view to TeX-mode-map?
What a mess.

2021-08-01 07:16 UTC, ymarco commented
The issue is still present...

2021-08-01 19:14 UTC, hlissner approved these changes

2021-08-01 19:15 UTC, merged

2021-08-01 19:16 UTC, hlissner commented
Sorry for the late response. It is frustrating that this is necessary, but I'll see if I can refactor it later. Thanks for the help!