notmuch: remove org-mime
hlissner/doom-emacs pull request #5008
Opened 2021-05-08 03:21 UTC by nackjicholson

Hi Henrik,

I'm not sure about this one. Feel free to decline.

This module is minimally configured and we're not providing anything extra on top with it. There may be many people that use this module and don't know `org-mime` is available to them. This PR removes `org-mime` and adds a section to the readme under a heading "Writing HTML Emails."

If you have ideas for why this module should stay, please share.

Best,
Will

2021-05-08 03:26 UTC, hlissner requested changes
Rather than remove it, put it behind an `+org` flag, like [the new mu4e module](https://github.com/hlissner/doom-emacs/pull/3971) does. Frankly, it's only there for mu4e parity, but I'd like to stick to that.

2021-05-08 17:52 UTC, nackjicholson commented
@hlissner I will make that change. Thanks for the guidance!

2021-05-11 04:19 UTC, nackjicholson commented
@hlissner I altered the commit to put org-mime behind a new +org flag. Please consider for merge at your convenience. Thank you!

2021-05-15 20:57 UTC, merged

2021-05-15 20:58 UTC, hlissner commented
Thanks for the help!