Updated documentation with potential fix
hlissner/doom-emacs pull request #5017
Opened 2021-05-09 10:24 UTC by skyler544

I've added the code I used to finally fix modeline icon misalignment
problems in my own setup as a suggestion in the Troubleshooting section.

2021-05-09 17:01 UTC, hlissner requested changes

2021-05-09 17:01 UTC, hlissner commented on modules/ui/modeline/README.org
> +4. If the previous suggestions don't fix the issue, try the following code:
This summary is unhelpful. Change to

> 4. Change the width of icon characters in `char-width-table`:

2021-05-09 19:28 UTC, skyler544 commented on modules/ui/modeline/README.org
> +       (add-hook 'doom-modeline-mode-hook #'set-modeline-icon-width))
As usual, your code is clearer and conciser than anything I can write. I've added a new commit with the requested changes.

2021-05-09 19:29 UTC, skyler544 commented on modules/ui/modeline/README.org
> +4. If the previous suggestions don't fix the issue, try the following code:
Agreed, that's better. I've added this in a second commit.

2021-05-09 19:31 UTC, skyler544 reviewed
This commit contains the requested changes.

2021-05-10 01:38 UTC, hlissner approved these changes

2021-05-10 08:56 UTC, merged

2021-05-10 08:56 UTC, hlissner commented
Good work. Thanks for the help!