fix(input layout bepo): remap visual-line-mode-map
hlissner/doom-emacs pull request #5019
Opened 2021-05-09 10:38 UTC by gagbo

Fixes #5002

Draft because untested.

2021-05-09 11:43 UTC, gagbo commented
Ready for review : to squash before merging

2021-05-09 17:17 UTC, hlissner requested changes
Save for the annotated change, code seems alright to me, so if it works for you this should be good to go.

2021-05-09 17:17 UTC, hlissner commented on modules/input/layout/+bepo.el
> +            :m "V" 'evil-visual-screen-line)))
Please sharp-quote functions (e.g. `#'evil-next-visual-line`)

2021-05-09 22:30 UTC, hlissner approved these changes

2021-05-10 08:57 UTC, merged

2021-05-10 08:57 UTC, hlissner commented
Thanks again!