(wip): ophints: Add hooks for lispyville
hlissner/doom-emacs pull request #5023
Opened 2021-05-10 00:18 UTC by Grazfather

Because lispyville (depending on how you configure it) replaces some
evil-mode mappings with its own function, we lose the indication of our
deletions/yanks/etc. This change adds all lispyville functions to the
evil-goggles--commands list.

2021-05-10 05:49 UTC, hlissner requested changes

2021-05-10 05:49 UTC, hlissner commented on modules/ui/ophints/config.el
> +  (progn (pushnew! evil-goggles--commands
`:config`'s body is implicitly wrapped in a progn, so this is redundant. Please remove it.

2021-05-10 16:59 UTC, Grazfather commented on modules/ui/ophints/config.el
> +  (progn (pushnew! evil-goggles--commands
Done

2021-05-10 23:04 UTC, hlissner approved these changes

2021-05-15 20:58 UTC, merged

2021-05-15 20:58 UTC, hlissner commented
Thanks!