fix typo in how to set custom elfeed.org
hlissner/doom-emacs pull request #5045
Opened 2021-05-13 01:37 UTC by jrmiller82

Per https://github.com/remyhonig/elfeed-org, the `modules/core/RSS` README.org had the incorrect command for setting a custom elfeed.org file. It was missing a `list` in the elisp.

2021-05-13 02:01 UTC, hlissner requested changes

2021-05-13 02:01 UTC, hlissner commented on modules/app/rss/README.org
> ++ If you don't want to use ~org-directory/elfeed.org~ file you can specify it with ~(setq rmh-elfeed-org-files (list "path/to/your/elfeed/file.org))~
Please quote it instead: 

```diff
- If you don't want to use ~org-directory/elfeed.org~ file you can specify it with ~(setq rmh-elfeed-org-files (list "path/to/your/elfeed/file.org))~
+ If you don't want to use ~org-directory/elfeed.org~ file you can specify it with ~(setq rmh-elfeed-org-files '("path/to/your/elfeed/file.org))~
```

2021-05-13 02:07 UTC, jrmiller82 commented on modules/app/rss/README.org
> ++ If you don't want to use ~org-directory/elfeed.org~ file you can specify it with ~(setq rmh-elfeed-org-files (list "path/to/your/elfeed/file.org))~
I was just using the exact example from upstream; I'll update shortly.

2021-05-13 02:11 UTC, jrmiller82 commented on modules/app/rss/README.org
> ++ If you don't want to use ~org-directory/elfeed.org~ file you can specify it with ~(setq rmh-elfeed-org-files (list "path/to/your/elfeed/file.org))~
Fixed.

2021-05-13 07:42 UTC, hlissner approved these changes

2021-05-15 20:59 UTC, merged

2021-05-15 20:59 UTC, hlissner commented
Thanks!

2021-05-17 14:52 UTC, jrmiller82 commented
You're welcome! Thanks for the work you do on doom emacs!