rss - podcast tagging and youtube feeds
hlissner/doom-emacs pull request #5055
Opened 2021-05-15 17:45 UTC by nackjicholson

Adds functionality to help users be able to manage downloads from
youtube channels, users, and playlists through youtube-dl.

This is based on the functionality that @skeeto uses in his own configs [here](https://github.com/skeeto/.emacs.d/blob/master/etc/feed-setup.el). I learned of this approach on [a reddit post](https://www.reddit.com/r/emacs/comments/7usz5q/youtube_subscriptions_using_elfeed_mpv_no_browser/dtntty8/?utm_source=reddit&utm_medium=web2x&context=3) by skeeto too. If you want to know more check it out. This change should also play nice with `emms` if you make the `youtube-dl-directory` the same as the `emms-directory`.

Fixes #0000 

{{{ Summarize what you've changed HERE and why }}}

2021-07-24 22:35 UTC, hlissner requested changes

2021-07-24 22:35 UTC, hlissner commented on modules/app/rss/autoload.el
> +;;;###autoload
`s/autoload/autodef`

2021-07-24 22:35 UTC, hlissner commented on modules/app/rss/autoload.el
> +(defmacro +rss-elfeed-config! (&rest feeds)
Rename `set-elfeed!`, to conform to naming conventions for autodefs.

2021-07-24 22:35 UTC, hlissner commented on modules/app/rss/autoload.el
> +(defmacro +rss-elfeed-config! (&rest feeds)
Should also be a function, not a macro.

2021-07-24 22:35 UTC, hlissner commented on modules/app/rss/autoload.el
> +  `(setf elfeed-feeds (mapcar #'+rss--elfeed-expand ',feeds)))
Use `setq` instead of `setf`. The latter isn't needed here.

Wrap in `(after! elfeed ...)` after converting this to a function.

2021-10-31 07:10 UTC, nackjicholson commented on modules/app/rss/config.el
> +  :when (featurep! +media))
The `youtube-dl-list` function does have an autoload declaration. I added the :after poperty.

2021-10-31 07:11 UTC, nackjicholson commented on modules/app/rss/config.el
> +    (map!
Moved and using :when

2021-10-31 07:11 UTC, nackjicholson commented on modules/app/rss/autoload.el
> +
Removed

2021-10-31 07:11 UTC, nackjicholson commented on modules/app/rss/autoload.el
> +
Moved

2021-10-31 07:11 UTC, nackjicholson commented on modules/app/rss/autoload.el
> +;;;###autoload
Not necessary once it's a function right?

2021-10-31 07:12 UTC, nackjicholson commented on modules/app/rss/autoload.el
> +(defmacro +rss-elfeed-config! (&rest feeds)
Renamed and made it a function. Did I get the name right? Or should I drop the +rss part?

2021-10-31 07:13 UTC, nackjicholson commented on modules/app/rss/autoload.el
> +  `(setf elfeed-feeds (mapcar #'+rss--elfeed-expand ',feeds)))
Using setq.

I can't get configs to work correctly if I wrap it in `after`. Left it.

2022-03-15 06:15 UTC, nackjicholson commented
This code will now live in my config files, it continues to be something I use often.

2022-03-15 06:15 UTC, closed without merging