Added Flycheck documentation
hlissner/doom-emacs pull request #5111
Opened 2021-05-29 15:09 UTC by destroyer449

- [x] It targets the develop branch
- [x] I've searched for similar pull requests and found nothing
- [x] This change is NOT in Doom's do-not-PR list: https://doomemacs.org/d/do-not-pr
- [x] If I've bumped any packages, I've done so according to https://doomemacs.org/d/how2bump
- [x] I've linked any relevant issues and PRs below
- [x] All my commit messages are descriptive and distinct

Fixes #1166 

Adds documentation for the flycheck module. I was not sure what to put for the since option, so I left that as ???. If anyone knows what should be placed here, tell me and I'll fix it.

2021-05-29 15:17 UTC, iyefrat commented
put `#+SINCE:  v3.0.0`, since that is the next version of doom that will come out

2021-05-29 15:24 UTC, hlissner requested changes

2021-05-29 15:24 UTC, hlissner commented on modules/checkers/syntax/README.org
> +#+SINCE:   ???
Change to:

```diff
-#+DATE:    May 28, 2021
+#+DATE:    February 20, 2017
-#+SINCE:   ???
+#+SINCE:   v2.0
```

2021-05-29 15:30 UTC, destroyer449 commented
I fixed the date and since fields. Is there anything else that needs to be done before this can be merged?

2021-05-29 18:48 UTC, hlissner approved these changes

2021-06-04 18:21 UTC, merged

2021-06-04 18:21 UTC, hlissner commented
Looks good to me, thanks!