docs/mu4e: configure for other than IMAP backends
hlissner/doom-emacs pull request #5134
Opened 2021-06-04 16:05 UTC by jman-schief

- [x] It targets the develop branch
  - [x] I've searched for similar pull requests and found nothing
  - (no idea) This change is NOT in Doom's do-not-PR list: https://doomemacs.org/d/do-not-pr
  - [ ] If I've bumped any packages, I've done so according to https://doomemacs.org/d/how2bump
  - [ ] I've linked any relevant issues and PRs below
  - [x] All my commit messages are descriptive and distinct

Slightly improve documentation on how to configure the `mu4e` module when not using an IMAP backend (i.e. neither `offlineimap` nor `mbsync`). This is mentioned in the [config.el](https://github.com/hlissner/doom-emacs/blob/f408016c6ff6c3fe02f7b43125e6adb587a34bdb/modules/email/mu4e/config.el#L4) but took me a while to figure this out.

I'm not sure about the Org formatting, in case please let me know!

thanks for reviewing this small patch

2021-06-04 16:12 UTC, hlissner requested changes

2021-06-04 16:12 UTC, hlissner commented on modules/email/mu4e/README.org
> +(mu4e-get-mail-command "mpop account1")
Replace with

```elisp
;; in ~/.doom.d/config.el
(after! mu4e
  (setq mu4e-get-mail-command "mpop account1"))
```

2021-06-04 16:12 UTC, hlissner commented on modules/email/mu4e/README.org
> +In case you are neither using =offlinemap= nor =mbsync= (example you're syncing using POP3(s) protocol instead of IMAP(s)), you need to disable the mu4e backend and manually set your mail retrieval c
Please run `M-x org-fill-paragraph` on this paragraph.

2021-06-04 16:12 UTC, hlissner commented on modules/email/mu4e/README.org
> ++ Either ~mbsync~ (default) or ~offlineimap~ (to sync IMAP mail with). In case of a different backend, please read below
Please run M-x org-fill-paragraph on this paragraph.

2021-06-04 16:12 UTC, hlissner commented on modules/email/mu4e/README.org
> ++ Either ~mbsync~ (default) or ~offlineimap~ (to sync IMAP mail with). In case of a different backend, please read below
Add a period to end of the sentence.

2021-06-04 16:28 UTC, jman-schief commented
@hlissner force pushed your suggestions

2021-06-05 17:18 UTC, hlissner requested changes

2021-06-05 17:18 UTC, hlissner commented on modules/email/mu4e/README.org
> +
Remove this. It's unnecessary if you're setting `mu4e-get-mail-command` yourself.

2021-06-06 11:19 UTC, jman-schief commented on modules/email/mu4e/README.org
> +
> Remove this. It's unnecessary if you're setting `mu4e-get-mail-command` yourself.

But it is documented in the [config.el](https://github.com/hlissner/doom-emacs/blob/f408016c6ff6c3fe02f7b43125e6adb587a34bdb/modules/email/mu4e/config.el#L4) file. I'm asking because the whole point of this small patch is that I could not overwrite the default behaviour without setting `mu4e-backend` to nil. Allow me to clarify:

```
;; in ~/.doom.d/config.el
(setq mu4e-backend nil) 
(setq mu4e-get-mail-command "mpop --all-accounts")
```
The above successfully contacts the mail server (using `mpop` as MUA)

```
;; in ~/.doom.d/config.el
;; (setq mu4e-backend nil) 
(setq mu4e-get-mail-command "mpop --all-accounts")
```
The above triggers this error message `/bin/bash: line 1: mbsync: command not found`

I can verify that `mbsync` is not overwritten by observing the setting value with this hook:
```
(add-variable-watcher 'mu4e-get-mail-command
                      (lambda (sym new-value operation where)
                        (message ">>> Value for %s getting modified to %s with
                           %s in buffer %s"
                                 sym new-value operation where)))
```

the output of the watcher is:
```
>>> Value for mu4e-get-mail-command getting modified to mpop --all-accounts with set in buffer nil
>>> Value for mu4e-get-mail-command getting modified to mpop --all-accounts with set in buffer nil
>>> Value for mu4e-get-mail-command getting modified to mbsync -a with set in buffer nil
>>> Value for mu4e-get-mail-command getting modified to mbsync -a with set in buffer nil
```

2021-06-06 13:33 UTC, jman-schief commented on modules/email/mu4e/README.org
> +
I did investigate this a bit more, I think I'm confused on how Doom configuration actually works.
My actual mu4e config is more complex and is inherited from my previous emacs vanilla:
```
(use-package! mu4e
  :load-path "~/.local/share/emacs/site-lisp/mu4e/"
  :commands mu4e

  :init
  ;; various init commands ...

  :config
  ;; various config stuff ...

  :custom
  ;; moar config ...
)
```

I think that the `use-package!` macro is then overriden by Doom's defaults and this is why you were suggesting to use the `after!` macro - am I correct? This would explain why my `(setq...)` directives inside the (use-package! mu4e ...)` macro are ignored/overrriden. I'm confused :-/

2021-09-06 16:14 UTC, jman-schief commented
closing, probably this patch would't add much value to the documentation

2021-09-06 16:14 UTC, closed without merging