getting_started.org: Gentoo Linux install guide
hlissner/doom-emacs pull request #5165
Opened 2021-06-10 03:05 UTC by mjkalyan

Added installation instructions including Emacs & dependencies for Gentoo/Portage users to the getting_started.org file for the sake of completeness.

2021-06-18 04:32 UTC, TheGreatMcPain commented
You might want to mention that the `xft` use flag must be enabled for `app-editors/emacs` in order for the fonts to render correctly.

See #4876

2021-07-08 22:03 UTC, hlissner requested changes

2021-07-08 22:03 UTC, hlissner commented on docs/getting_started.org
> +#+end_src
Can this be updated with 27.x installation instructions? Doom no longer officially supports 26.x.

2021-07-23 02:14 UTC, mjkalyan commented on docs/getting_started.org
> +#+end_src
Done!

2021-07-24 22:22 UTC, hlissner approved these changes

2021-07-24 22:22 UTC, merged

2021-07-24 22:22 UTC, hlissner commented
Looks good to me. Thanks!