Add org-cite support to biblio module
hlissner/doom-emacs pull request #5212
Opened 2021-06-29 15:21 UTC by bdarcus

I am opening this as a draft PR, in part to facilitate alignment between this and #2888.

## Background

In April of 2020, @brianmcgillion opened #2888, mostly to add `org-ref` support.

That PR has languished, but is planned for merger for 3.0.

Since then, work on native org citation support, called the `org-cite` module, has almost wrapped up, and the feature will be merged to master "any day."

OC will supplant much of the functionality in `org-ref`, and the latter will likely be rewritten in the future to target the former.

## What this adds

Configuration for the new OC functionality:

1. setting up the different "processors"
2. setting the bib file paths, but using the new variable for this in #2888.
3. installing the `citeproc`, which is the backend required for the `oc-csl` "export processor"

## Status

Just waiting on OC merger, and feedback from its author.

2021-06-29 15:28 UTC, iyefrat commented
@bdarcus what alignment do you need to do with the selectrum PR?

2021-06-29 15:37 UTC, iyefrat commented
Your best bet to fix the git history is with git rebase (I assume you are using magit):
- when this branch on the status screen, put your cursor on the earliest commit in this branch (https://github.com/hlissner/doom-emacs/pull/5212/commits/0635fe123cb2f2ce435eef82d0618489b283c080)
- press `r i` to start interactive rebase
- move the cursor on each dummy commit and press `d` to drop
- `C-c C-c` to rebase
- force push with `p -f p` from magit status screen

I don't know how familliar you are with magit, but the manual is very good, and so are the git man pages. However note that the man page for a git subcommand `git foo` is under `man git-foo`, so e.g. the man page for rebasing is `git-rebase`.

2021-06-29 15:38 UTC, bdarcus commented
> @bdarcus what alignment do you need to do with the selectrum PR?

@iyefrat - now that I think of it, really nothing is necessary. 

But I could include the `bibtex-actions` and `embark` stuff that's there here.

For example, I currently define a `bibtex-actions` "follow processor" here, which can use `embark` to bind actions to citations via `org-open-at-point`.

But that isn't strictly necessary for this PR. Really just depends on how the timeline plays out on these pieces.

2021-06-29 15:42 UTC, bdarcus commented
> Your best bet to fix the git history is with git rebase (I assume you are using magit):

While I know I should use magit, I usually just use the command line, including for rebasing.

2021-06-29 15:46 UTC, iyefrat commented
In that case you can do `git rebase -i 0635fe1`, the rest is the same except you do `:wq` to save and quit instead of `C-c`, and force pushing is done with `git push --force-with-lease`

2021-06-29 16:06 UTC, bdarcus commented
> In that case you can do `git rebase -i 0635fe1`, the rest is the same except you do `:wq` to save and quit instead of `C-c`, and force pushing is done with `git push --force-with-lease`

Done.

I still have the merge commit though.

2021-06-29 16:08 UTC, iyefrat commented
yeah my bad, you need to rebase on one commit before that, do `git rebase -i 0635fe1~`

2021-06-29 16:13 UTC, bdarcus commented
There we go; thank you @iyefrat!!

2021-06-29 16:19 UTC, bdarcus commented
Actually, spoke too soon. There was then a subsequent conflict with the files, that I resolved, but squashing those doesn't appear to be straightforward.

Is that OK do you think?

Or should I just start over?

2021-06-29 16:27 UTC, iyefrat commented
try the following: `git rebase -i` and change the merge commit to a fixup commit by pressing `f` on it. this should work but there might be shenanigans do to it being a merge commit

2021-06-29 17:12 UTC, bdarcus commented
If I do, for example, `git rebase -i HEAD~2`, I get another long list of individual commits; I don't get the merge commit to edit.

2021-06-29 17:22 UTC, iyefrat commented
At this point I think your best bet is to just delete the branch locally, redo it with the one good commit, and force push.

2021-06-29 18:33 UTC, bdarcus commented
> At this point I think your best bet is to just delete the branch locally, redo it with the one good commit, and force push.

I thought I did, but it just got worse :-)

I'll take another look tomorrow.

2021-06-30 10:40 UTC, iyefrat commented
@bdarcus good! I suggest you mark the troubleshooting comments as off topic since git shenanigans are not really of interest to anyone taking a look at the PR (with maybe this one left for context as to why there are a bunch of off topic comments).

2021-06-30 11:21 UTC, bdarcus commented
> @bdarcus good! I suggest you hide the troubleshooting comments since git shenanigans are not really of interest to anyone taking a look at the PR (with maybe this one left for context as to why there are a bunch of hidden comments).

Done, but at the cost of another off-topic comment, I can't hide your's.

2021-07-01 19:41 UTC, bdarcus commented
@iyefrat - do you agree with my assessment that I need to condition line 36 on #4664, given it depends on `bibtex-actions` and `completing-read`?

2021-07-02 12:28 UTC, iyefrat requested changes

2021-07-02 12:28 UTC, iyefrat commented on modules/tools/biblio/packages.el
> +  (package! helm-bibtex :pin "ca09076c3d6e51cc4ffe208c8176fccf3710fcc6"))
Is bumping these packages necessary to get the functionality in this PR to work? If so, bump them in a separate bump commit following [this format](https://discourse.doomemacs.org/t/how-to-contribute/44#bump-outdated-packages). If this is unclear, look at doom's commit history for any commit starting with "Bump", and note the notice with the pin symbol after section 8.2.

2021-07-02 12:28 UTC, iyefrat commented on modules/tools/biblio/config.el
> +        (setq org-cite-follow-processor 'bibtex-actions))
Indeed, this part depends on the selectrum PR.

2021-07-02 12:28 UTC, iyefrat commented on modules/tools/biblio/config.el
> +      (require 'oc-csl-activate)
Generally package specific configuration is done inside of `use-package` statements. I'm unsure as to the exact correct semantics for doing that here (is org-cite provided as a single package that you can load? @tecosaur what is the way to load things here?). [https://github.com/jwiegley/use-package](use-packagel) is a bit daunting, but the readme is very comprehensive. Ask on the discord if you run into trouble

2021-07-02 12:35 UTC, bdarcus commented on modules/tools/biblio/config.el
> +      (require 'oc-csl-activate)
If using `use-package` for this, would that not suggest this goes in the `org` module, and then `when` statement would condition on `biblio`? So the reverse of what I have?

2021-07-02 16:51 UTC, bdarcus commented on modules/tools/biblio/config.el
> +      (require 'oc-csl-activate)
I pushed a commit that makes the change to `use-package!`. 

It seems to work, and I checked with the OC author if he had any input, but he doesn't use `use-package`.

2021-07-14 11:43 UTC, bdarcus commented
@iyefrat - I ended up adding bibtex-actions to package.el here, though per my note on discord, whether this is actually a bump here or not vis-a-vis the vertico PR, will depend on timing of all of this.

2021-07-14 13:15 UTC, iyefrat commented
If you add the package under the `:completion vertico` flag, this PR should probably be merged after the Vertico PR anyway.

I do have a question about this though. How well does `bibtex-actions` work without Vertico and Embark? It might be worth considering adding it independently of `:completion vertico`. It does look like from the readme that in order to play well with `embark` you need to load the package after embark, but maybe that can change upstream. The only other issue I can think of from my brief familiarity with the package is the lack of ability to bind `bibtex-actions-map` before loading the package, which means that you can't bind in onto `<leader> n b`, and only having`bibtex-actions-open-entry` there without the ability to chose alternate actions on it with `embark` is a bit of a usability issue.

2021-07-14 13:27 UTC, bdarcus commented
> If you add the package under the `:completion vertico` flag, this PR should probably be merged after the Vertico PR anyway.

Yes, my thinking. I added a note saying as much to the main post.
 
> I do have a question about this though. How well does `bibtex-actions` work without Vertico and Embark? 

The commands should work in any vertical completing-read-compliant interface, including the now built-in icomplete one, so that `M-x bibtex-actions-open` and such should work.

You just don't get the additional contextual actions that come with Embark.

> It might be worth considering adding it independently of `:completion vertico`. 

Given what I say above, WDYT? It probably wouldn't work well with horizontal completion UIs, for example.

> It does look like from the readme that in order to play well with `embark` you need to load the package after embark, but maybe that can change upstream. 

Am not following here. Can you please rephrase?

> The only other issue I can think of from my brief familiarity with the package is the lack of ability to bind `bibtex-actions-map` before loading the package, which means that you can't bind in onto `<leader> n b`, and only having`bibtex-actions-open-entry` there without the ability to chose alternate actions on it with `embark` is a bit of a usability issue.

I'm also not following the last part here. The embark menus work correctly, since embark relies on the keymaps for those bindings. 

So a limitation is we only have the one  `<leader> n b` binding in doom, but doing `embark-act` from there does bring up all of them.

![Screenshot from 2021-07-14 09-26-26](https://user-images.githubusercontent.com/1134/125629936-13109c47-d6d3-4cb7-9eb1-0ee19d205b20.png)
![Screenshot from 2021-06-28 07-59-02](https://user-images.githubusercontent.com/1134/125629939-f717690b-2612-4532-8811-09122e75d463.png)

2021-07-14 13:53 UTC, iyefrat commented
> > It does look like from the readme that in order to play well with embark you need to load the package after embark, but maybe that can change upstream.

>Am not following here. Can you please rephrase?

In the `bibtex-actions` readme the following is the suggested use-package:

```lisp
(use-package bibtex-actions
  :bind (("C-c b" . bibtex-actions-insert-citation)
         :map minibuffer-local-map
         ("M-b" . bibtex-actions-insert-preset))
  :after embark
  :config
  :custom
  ;; make sure to set this to ensure open commands work correctly
  (bibtex-completion-additional-search-fields '(doi url))
  (bibtex-completion-bibliography '("~/bib/references.bib")))
```
Which seems to mean that in order for the package to work with embark, it has to be loaded after it. This also was necessary for getting it to work in the Vertico PR, but adding `:after embark` if you aren't using `embark` will cause the `use-package` statement not to get evaluated. There are three ways to work around this:

1. Rework `bibtex-actions` so that it doesn't need to be loaded after embark

2021-07-14 14:14 UTC, bdarcus commented
> 1. Rework `bibtex-actions` so that it doesn't need to be loaded after embark (best option if possible)

I'm a bit fuzzy on `use-package` in general, but maybe the issue isn't the package per se, but the embark variables that need to be set there for it work with it? I mean lines like this in your PR:

``` elisp
(add-to-list 'embark-keymap-alist '(bibtex . bibtex-actions-map))
```

BTW, in `bibtex-actions-org-cite` I require Embark and set those variables there. So `bibtex-actions-embark` would be conceptually similar if that made sense.

2021-07-14 14:59 UTC, iyefrat commented
> I'm a bit fuzzy on `use-package` in general,

By the way, the secret to understanding `use-package` is using `SPC m m` to expand the macro, that makes what exactly it's doing clearer in ways the keyword documentation under `SPC h f` sometimes doesn't.

> but maybe the issue isn't the package per se, but the embark variables that need to be set there for it work with it? I mean lines like this in your PR:
> 
> ```emacs-lisp
> (add-to-list 'embark-keymap-alist '(bibtex . bibtex-actions-map))
> ```

Yeah. tag me in the PR that tries to implement this if you do that, I'll look it over. I also might try to do it myself in the near future, but I want to submit the Vertico PR first.
   
> In the [`bibtex-actions-org-cite`](https://github.com/bdarcus/bibtex-actions/blob/main/bibtex-actions-org-cite.el) I just added, I require Embark and set those variables there. Is that WYM?

No, although that does mean that you should add `embark` the :after` statement of the `use-package` statement. 

Having:

```lisp
(use-package! bibtex-actions-embark :after embark)
```
In your emacs config means that it'll load that file only after `embark` is loaded. It should actually be:

```lisp
(use-package! bibtex-actions-embark
 :after (bibtex-actions embark))
```
Because it should also be loaded after `bibtex-actions`.
Adding the `(require 'embark)` in the file itself does a different thing, the `use-package` statement in your emacs config tells emacs "after you finish loading `bibtex-actions` and `embark`, whenever that is, load `bibtex-actions-embark`". The `require` statement in your package tells emacs to load the `embark` file during the loading of `bibtex-actions-org-cite`, but that only happens if you load `bibtex-actions-org-cite` somewhere.

2021-07-24 10:37 UTC, bdarcus commented on modules/tools/biblio/config.el
> +
@tecosaur - when you get a chance, any suggestions on what the settings here should be for TeX?

Maybe just keep it simple and do this?

```suggestion
    (setq org-cite-export-processors
          '((latex natbib)
            (t csl)))

```

2021-07-25 09:25 UTC, closed without merging