Update ui/deft README to new format
hlissner/doom-emacs pull request #5257
Opened 2021-07-12 17:55 UTC by powerverwirrt

Re: #1166
I've updated the README for ui/deft to fit the new format (first time contributor).

2021-07-12 20:06 UTC, hlissner requested changes

2021-07-12 20:06 UTC, hlissner commented on modules/ui/deft/README.org
> +#+DATE:    July 11, 2021
Replace with `August 27, 2018` (when the module was added)

2021-07-12 20:06 UTC, hlissner commented on modules/ui/deft/README.org
> +** Note
Replace with `* Troubleshooting`

2021-07-16 13:23 UTC, mackizzer approved these changes

2021-07-16 16:31 UTC, hlissner approved these changes

2021-07-16 16:31 UTC, merged

2021-07-16 16:31 UTC, hlissner commented
Thanks for the help! And congrats on your first PR to doom!