lang/org: Add +`roam2` flag for org-roam v2
hlissner/doom-emacs pull request #5271
Opened 2021-07-18 22:39 UTC by Wetlize

This PR introduces support in Doom for `org-roam` v2, which just recently was released. It's still WIP (though most of the things are now done) and the following need to be addressed first, before this will be turn into a PR that can be merged:
- [ ] Better support for `evil-mode` in `org-roam-mode` based buffers
  + [ ] Add evil based bindings for `magit-section`/`org-roam-mode`
  + [ ] Figure out why Emacs override evil bindings and leader keys in `magit-section`s provided by `org-roam-mode` whenever the point is positioned right on them, and fix that.
- [ ] Confirm that deferred initialization of the database doesn't cause any problems. So far (from my tests) everything works as expected.

2021-07-19 03:51 UTC, hlissner requested changes
Good stuff! Just needs one minor change and this is good to go.

2021-07-19 03:51 UTC, hlissner commented on modules/lang/org/contrib/roam2.el
> +   '(ansi-color dash f rx seq magit-section))
Use `:defer-incrementally (ansi-color dash f rx seq magit-section)` instead

2021-07-19 05:49 UTC, nackjicholson commented
Thanks @Wetlize ! Really glad to see this is in the works!

2021-07-19 07:27 UTC, Wetlize commented on modules/lang/org/contrib/roam2.el
> +   '(ansi-color dash f rx seq magit-section))
But if I do it, then Doom will add `org-roam` itself to `doom-incremental-packages` before `org` and its dependencies will be added there. AFAIK, because of that, `org-roam` will be loaded before `org` and its dependencies (since `org-roam` `require`s `org`), which in turn cause eager (instead of incremental) loading of `org`. Should I still do it?

2021-07-19 08:51 UTC, Wetlize commented on modules/lang/org/doctor.el
>      (warn! "Couldn't find the sqlite3 executable. org-roam will not work."))
Sorry for bothering, but can you clarify a bit? Isn't `sqlite3` is a hard dependency of the package or I'm just missing something?

2021-07-19 09:19 UTC, hlissner commented on modules/lang/org/contrib/roam2.el
> +   '(ansi-color dash f rx seq magit-section))
Nevermind then. I'll have to fix load order for `:defer-incrementally` to address this. I'll fix this post-merge.

2021-07-19 09:32 UTC, jethrokuan commented on modules/lang/org/doctor.el
>      (warn! "Couldn't find the sqlite3 executable. org-roam will not work."))
in v2 we reverted to using `emacsql-sqlite`, which compiles the sqlite binary during installation and doesn't look for it using `executable-find`, so the check is redundant.

2021-07-20 18:05 UTC, Wetlize commented
Sorry folks. I've injured my hand today so this might not ship as fast as I was initially planning. Hope this will be completed by the end of this week.

2021-07-20 21:13 UTC, pgronkievitz commented
> Sorry folks. I've injured my hand today (nothing serious, but it will slow me down for some time) so this might not ship as fast as I was initially planning. Hope this will be completed by the end of this week or beginning of the next one.

I think it's not a problem to the most of people. Your health is way more important than writing this. Take care of yourself!

2021-07-23 02:40 UTC, e3bc54b2 commented
> v2 reverted to using `emacsql-sqlite` instead of `emacsql-sqlite3`. It will now try to build the needed `sqlite3` executable itself, using available C compiler, instead of searching for it with `executable-find` and in case of failure, leaving the package in a half corrupt state.

Does this mean I now need gcc/clang in my path instead of sqlite3?

2021-07-23 03:09 UTC, Wetlize commented
> Does this mean I now need gcc/clang in my path instead of sqlite3?

Pretty much it. [Here](https://github.com/skeeto/emacsql/blob/9dca5996168c4963eb67e61c7f17fdcb8228e314/emacsql-sqlite.el#L67) you can see the list of compilers that will be tried by `emacs-sqlite`. Org-roam has also [manual entry](https://github.com/org-roam/org-roam/blob/master/doc/org-roam.org#c-compiler) about this. Doom will try to build the binary either, when you run `doom build` or when `org-roam` will try to query to the database the first time, The latter doesn't work ATM, so right now it will try to build it when the package will be loaded.

2021-07-24 15:21 UTC, Wetlize commented
This should be good to go for the review. I'm only not sure about 82761c18475f807b0709843c7df78a0fe312075e, which I'm not aware of a better way to handle this problem.

2021-07-24 22:17 UTC, hlissner requested changes
Could you reword 94add08102a129f13ae9b4672e58996e50addfd6 to:

```
Bump org-roam

org-roam/org-roam@e997c01 -> org-roam/org-roam@028c95a
```

Bump commits should always follow this format.

Other than this, I think this is ready to merge.

2021-07-24 22:21 UTC, Wetlize commented
Sure, I though you'll squash it all (or ask me to do that).

2021-07-24 23:55 UTC, Wetlize commented
Should be good to go. I've also cleaned up the history a bit to make it a bit less noisy.

2021-07-25 03:15 UTC, hlissner approved these changes

2021-07-25 08:13 UTC, merged

2021-07-25 08:13 UTC, hlissner commented
Great work! Thanks again for your help!

2021-10-02 23:09 UTC, memeplex commented
Thanks! A reference to the new flag should be added to the list in modules.org.

2021-10-02 23:42 UTC, hlissner commented
I'm currently rewriting and redesigning our module documentation. `+roam2` will be added to it when it is done.