Add org-cite to :tools/biblio
hlissner/doom-emacs pull request #5290
Opened 2021-07-25 09:42 UTC by bdarcus

Sorry; for the massive merges, I had to redo #5212 to get the git correct. I'll leave the longer background there, and just summarize here.

## Summary

This adds support the native org-mode citations. Specifically it:

1. configures the native `org-cite` processors
2. add `oc-bibtex-actions` "follow" and "insert" processors for the vertico modlue, and the included "oc-basic" ones for helm and ivy
3. installs `citeproc-el`, which is required for the `oc-csl` export processors, and will be needed also for forthcoming preview functionality

## Issues and Questions

1. What to do with #2888? Certainly `org-ref` should be dropped, as there will be a version of that software targeting `org-cite` at some around the release of Org 9.5. But this PR should be reviewed together with that one.
2. How to configure `org-cite` processors? My suggestion is to include sensible default, as here, and document how to change them.
3. Keybindings: this is tricky. We need to bind `org-cite-insert` and `org-open-at-point`, as these are the two entry points for the module.

2021-07-25 09:58 UTC, bdarcus commented
FYI @iyefrat @tecosaur I closed the other PR and opened this one to get a clean history with the latest develop commits.

2021-07-28 07:56 UTC, bdarcus commented
While this is ready for input on the "issues/questions", I'm reverting to draft as, after talking to its author, I'm going to include at least one additional third-party processor: org-ref-cite.

2021-08-02 10:55 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  :after org
```suggestion
  :after org bibtex-completion
```

2021-08-18 12:40 UTC, roryk commented
So psyched for this, thanks for how much work you have put into it.

2021-08-29 12:39 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  (setq org-cite-export-processors
I'm getting this error, which points to a load order problem here.

```elisp
Debugger entered--Lisp error: (void-function org-export-derived-backend-p)
  org-export-derived-backend-p(nil latex)
```

This happens when opening an `org-roam` note the first time, but goes away on subsequent times.

2021-08-29 19:38 UTC, tecosaur commented on modules/tools/biblio/config.el
> +  :config
Why the empty `:init`?

2021-08-29 19:40 UTC, tecosaur commented on modules/tools/biblio/config.el
> +      :desc "Insert citation" "@" #'org-cite-insert)
(nit) This indentation doesn't look right, should it be?:
```
  (map! :map org-mode-map
        :localleader
        :desc "Insert citation" "@" #'org-cite-insert)
```

2021-08-29 19:47 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  :config
Oversight; fixed.

2021-08-29 19:47 UTC, bdarcus commented on modules/tools/biblio/config.el
> +      :desc "Insert citation" "@" #'org-cite-insert)
Yep; also fixed.

Thanks.

2021-08-30 13:11 UTC, yuuyins commented on modules/tools/biblio/README.org
> +You must set the path variable for either =bibtex-actions= (if using =vertico= completion) or =bibtex-completion= (if using =ivy= or =helm=); this module will in turn set the =org-cite-global-bibliog
I'm using vertico. If I

1. Set bibtex-actions-bibliography to bib.bib and bibtex-actions-notes-path to ~/org/ref, and set to nil both bibtex-completion-bibliography and bibtex-completion-notes-path.
2. Put cursor in org-cite citation
3. Try org-ref-cite-open-notes

I get `(wrong-type-argument stringp nil)` https://bin.disroot.org/?aaae5f2c5d0f318a#3E715k3UbbNHCWctZANRSge2diwir9u5WU1aLd8JYqhj


org-ref-cite-open-notes only works if I set bibtex-completion-bibliography to bib.bib and bibtex-completion-notes-path to ~/org/ref

2021-08-30 13:19 UTC, bdarcus commented on modules/tools/biblio/README.org
> +You must set the path variable for either =bibtex-actions= (if using =vertico= completion) or =bibtex-completion= (if using =ivy= or =helm=); this module will in turn set the =org-cite-global-bibliog
Oh, yeah, I guess I need to generalize those instructions.

Why are you using that command though; in what context?

2021-08-30 15:15 UTC, yuuyins commented on modules/tools/biblio/README.org
> +You must set the path variable for either =bibtex-actions= (if using =vertico= completion) or =bibtex-completion= (if using =ivy= or =helm=); this module will in turn set the =org-cite-global-bibliog
@bdarcus im just using the defaults processors from this module, i didn't change them.
![org-cite-processors](https://user-images.githubusercontent.com/86538850/131362125-d4a6c9ad-a5ba-4376-8bf5-17fc7682c3b9.png)

2021-08-30 15:21 UTC, bdarcus commented on modules/tools/biblio/README.org
> +You must set the path variable for either =bibtex-actions= (if using =vertico= completion) or =bibtex-completion= (if using =ivy= or =helm=); this module will in turn set the =org-cite-global-bibliog
Hmm ... I don't understand why you're seeing that hydra menu then.

You should be seeing the embark/which-key menu.

2021-08-31 18:41 UTC, bdarcus commented
With https://github.com/hlissner/doom-emacs/pull/5290/commits/ffdad5920571ab444b3fc07766fc2d1c9bc3403c I've reverted addition of `org-ref-cite` because of its unclear future.

The linter is complaining, so I will likely to need to rebase all this.

2021-08-31 20:07 UTC, bdarcus commented on modules/tools/biblio/README.org
> +You must set the path variable for either =bibtex-actions= (if using =vertico= completion) or =bibtex-completion= (if using =ivy= or =helm=); this module will in turn set the =org-cite-global-bibliog
Since I removed `org-ref-cite` (also, updated the README), can you give another try and see how it works now?

2021-09-01 18:34 UTC, yuuyins commented on modules/tools/biblio/README.org
> +You must set the path variable for either =bibtex-actions= (if using =vertico= completion) or =bibtex-completion= (if using =ivy= or =helm=); this module will in turn set the =org-cite-global-bibliog
just as a quick feedback i needed to manually set org-cite-global-bibliography because the module wasn't setting it from setting `bibtex-actions-bibliograph` alone. And setting `bibtex-actions-notes-path` doesn't work for `C-c C-o` or `bibtex-actions-dwim` in a org-cite citation, so I'm setting `bibtex-actions-notes-paths` directly https://gist.github.com/yuuyins/a7aeadc2e4ac524d5ad565c5e7e23d52 which makes it work to find bibliography notes. (either with or without `after bibtex-actions`). 

Also it seems `bibtex-actions-bibliography` varaible description is incorrect or some bug is happening: the variable says a list, so i initially tried setting it to a list, but then bibtex-actions-insert i get `(wrong-type-argument stringp ("/mnt/pro/org/org/bib/bib.bib")`. So i needed to insert a stringp for  bibtex-actions-insert.

There's an issue, but I'm not sure if it's by design. That menu on `bibtex-actions-dwim` only is available to org-ref citations (`bibtex-actions-insert-citations`), i.e. not available to org-cite citations (`org-cite-insert`). This is kinda an issue for me because now, since org-ref-cite was removed and that hydra menu isn't appearing, I can't create a new bibliographic note from org-cite citations.

https://user-images.githubusercontent.com/86538850/131725036-e2283922-ee14-4f21-93fb-5e1d0fead902.mp4

2021-09-01 18:48 UTC, bdarcus commented on modules/tools/biblio/README.org
> +You must set the path variable for either =bibtex-actions= (if using =vertico= completion) or =bibtex-completion= (if using =ivy= or =helm=); this module will in turn set the =org-cite-global-bibliog
> just as a quick feedback i needed to manually set org-cite-global-bibliography because the module wasn't setting it from setting `bibtex-actions-bibliograph` alone. And setting `bibtex-actions-notes-path` doesn't work for `C-c C-o` or `bibtex-actions-dwim` in a org-cite citation, so I'm setting `bibtex-actions-notes-paths` directly https://gist.github.com/yuuyins/a7aeadc2e4ac524d5ad565c5e7e23d52 which makes it work to find bibliography notes. (either with or without `after bibtex-actions`).
> 
> Also it seems `bibtex-actions-bibliography` varaible description is incorrect or some bug is happening: the variable says a list, so i initially tried setting it to a list, but then bibtex-actions-insert i get `(wrong-type-argument stringp ("/mnt/pro/org/org/bib/bib.bib")`. So i needed to insert a stringp for bibtex-actions-insert to work.

Hmm ... I've not seen this, but I'll take another look at the config.el file.
 
> There's an issue, but I'm not sure if it's by design. That menu on `bibtex-actions-dwim` only is available to org-ref citations (`bibtex-actions-insert-citations`), i.e. not available to org-cite citations (`org-cite-insert`). This is kinda an issue for me because now, since org-ref-cite was removed and that hydra menu isn't appearing, I can't create a new bibliographic note from org-cite citations.

What about `embark-act`? Is that what you mean?

If yes, this is what I see:

![image](https://user-images.githubusercontent.com/1134/131726616-d11138c9-b607-4f8b-9ed9-5c83486cb264.png)

2021-09-01 20:26 UTC, yuuyins commented on modules/tools/biblio/README.org
> +You must set the path variable for either =bibtex-actions= (if using =vertico= completion) or =bibtex-completion= (if using =ivy= or =helm=); this module will in turn set the =org-cite-global-bibliog
I wasn't aware about embark-act, it does what I need. Thank you! However, I couldn't find a way to customize a template for the note as I could with org-ref-cite by customizing `bibtex-completion-notes-template-multiple-files`. So, the only way is to override `bibtex-actions-file-open-notes-default`? I've looked into `bibtex-actions-template`, but it doesn't seem to do what I need.

2021-09-13 06:05 UTC, pgronkievitz commented
It's just my suggestion, but I think it's reasonable
Maybe store all of the keybindings in `SPC-m-R` space? it would stand for 'reference' - it's not ideal, but it's the best I can think of since `SPC-m-c`, `SPC-n-r` and `SPC-m-r` are taken
Another option is `SPC-m-z` as it has one less keystroke, but it has no mnemonic (`z` like Zotero maybe?)

2021-09-13 17:19 UTC, yuuyins commented
@pgronkievitz what is `SPC-m`?

I personally use the prefix `n b` (like note -> bibliobraphy) which is by default `bibtex-actions-open-entry`, so repurposing that might be an idea as well

```
(map! :leader
      (:prefix "n b"
       (:prefix "a"
        "a" #'bibtex-actions-add-pdf-attachment
        "l" #'bibtex-actions-add-pdf-to-library)
       ("c" #'org-cite-insert)
       ("d" #'bibtex-actions-dwim)
       (:prefix "i"
        "b" #'bibtex-actions-insert-bibtex
        "c" #'bibtex-actions-insert-citation
        "k" #'bibtex-actions-insert-key
        "p" #'bibtex-actions-insert-preset
        "r" #'bibtex-actions-insert-reference)
       ("I" #'org-cite-insert)
       (:prefix "o"
        "o" #'bibtex-actions-open
        "e" #'bibtex-actions-open-entry
        "l" #'bibtex-actions-open-link
        "n" #'bibtex-actions-open-notes
        "p" #'bibtex-actions-open-pdf)
       ("r" #'bibtex-actions-refresh)
       ("R" #'bibtex-actions-read)))
```

2021-09-14 13:34 UTC, pgronkievitz commented
> @pgronkievitz what is `SPC-m`?

yeah, I probably should use a bit better wording. What I meant is to use "localleader" instead of "notes" prefix, because "notes" are available globally and those commands are useful exclusively (or at least mostly) inside org file, so in my opinion it doesn't make any sense to have access to e.g. `#'bibtex-actions-insert-bibtex` in dashboard.

2021-09-14 13:41 UTC, bdarcus commented
> What I meant is to use "localleader" instead of "notes" prefix, because "notes" are available globally and those commands are useful exclusively (or at least mostly) inside org file, so in my opinion it doesn't make any sense to have access to e.g. `#'bibtex-actions-insert-bibtex` in dashboard.

It's actually more complicated than this though.

- some commands only make sense in org; namely `org-cite-insert`
- some commands (arguably) only make sense in latex or markdown (the bibtex-actions insert commands)
- but it can be useful to browse outside these modes, which is why the original binding for `ivy-bibtex` and `helm-bibtex` is what it is (global)

2021-09-16 19:11 UTC, mbosley commented
I've been playing around with this PR, since I'm very interested in moving away the fairly bloated org-ref package. While I've been able to insert citations and open PDFs with org-cite just fine, one issue I've been having is getting bibtex-actions to play nicely with the existing notes in my `roam` folder. I set `bibtex-actions-notes-path` to my roam folder, where I have an existing set of notes for citations of the form `bibtexkey.org`. When I try to access the citation notes through Embark Act, I get the error `find-file-noselect: Wrong type argument: stringp, nil`. Any advice on fixing this?

2021-09-16 19:18 UTC, bdarcus commented
> When I try to access the citation notes through Embark Act, I get the error `find-file-noselect: Wrong type argument: stringp, nil`. Any advice on fixing this?

It's likely a bug. Can you report it on the bibtex-actions tracker?

While you do, can you report if `bibtex-actions-open-notes` works correctly? My suspicion is not; that i'ts not an embark issue.

2021-09-16 19:23 UTC, bdarcus commented
Sigh ... something went wrong with git.

2021-11-02 13:15 UTC, ErnestDong commented
Could you please make another PR to fix the name change of your [package](https://github.com/bdarcus/citar/pull/349) if you have time? it breaks doom-cli since there is no bibtex-actions any more.

2021-11-05 14:07 UTC, cdlm commented on modules/tools/biblio/config.el
> +  (map! :map org-mode-map
Shouldn't wait until after `oc` is loaded to setup this binding; on the contrary, `org-cite-insert` should be available in org-mode buffers, and should autoload `oc` if needed.

2021-11-05 19:07 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  (map! :map org-mode-map
I'm not actually clear on what the suggest change is, not having a good handle on keybindings in doom.

2021-11-05 19:40 UTC, cdlm commented on modules/tools/biblio/config.el
> +  (map! :map org-mode-map
Remove that `(map! …)` from `(use-package! oc …)` and add it back out of it:
```emacs-lisp
(map! :after org
      :map org-mode-map
      :localleader
      :desc "Insert citation" "@" #'org-cite-insert)
```
n.b. the `:after org` clause, or wrap the binding in `(after! org …)`

2021-11-06 12:37 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  (map! :map org-mode-map
@tecosaur - any input on this binding question?

2021-11-06 18:41 UTC, tecosaur commented on modules/tools/biblio/config.el
> +  (map! :map org-mode-map
It looks sensible to me :+1:

2021-11-06 19:36 UTC, tecosaur requested changes

2021-11-06 19:36 UTC, tecosaur commented on modules/tools/biblio/config.el
> +                         bibtex-completion-bibliography)))
Shouldn't this be wrapped with `bound-and-true-p` ?

2021-11-06 19:44 UTC, bdarcus commented
I think we recent changes, can probably remove that entirely.

2021-11-06 19:45 UTC, tecosaur commented
Even better!

2021-11-06 19:46 UTC, bdarcus commented
Except, as I think about it, does it make any practical difference?

The command only makes sense in an org buffer. And if one opens an org
buffer, it should load the binding.

Right?

2021-11-06 19:47 UTC, tecosaur commented
@bdarcus I'm no longer sure which of my two messages your comments are referring to.

2021-11-06 20:05 UTC, bdarcus commented
> @bdarcus I'm no longer sure which of my two messages your comments are referring to.

Let me move it to the thread it belongs, now that i"m a computer.

2021-11-06 20:06 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  (map! :map org-mode-map
Except, as I think about it, does it make any practical difference?

The command only makes sense in an org buffer. And if one opens an org
buffer, it should load the binding.

Right?

2021-11-06 20:07 UTC, bdarcus commented on modules/tools/biblio/config.el
> +                         bibtex-completion-bibliography)))
On this, you're referring to line 34?

2021-11-07 04:11 UTC, tecosaur commented on modules/tools/biblio/config.el
> +  (map! :map org-mode-map
So you currently have the line `:after org bibtex-completion citar` after `(use-package! oc`. This seems equivalent if `citar` is loaded at/before `org`. It looks like you currently load `citar` eagerly?

2021-11-07 04:12 UTC, tecosaur commented on modules/tools/biblio/config.el
> +                         bibtex-completion-bibliography)))
It sounds like you may be able to get away with just `(let ((paths citar-bibliography))` then, or just using the body and replacing `paths` with `citar-bibliography`.

2021-11-07 13:48 UTC, bdarcus commented on modules/tools/biblio/config.el
> +  (map! :map org-mode-map
>  It looks like you currently load citar eagerly?

That's not my intention.

Perhaps I should just remove the `:after` line?

2021-11-07 15:29 UTC, cdlm commented on modules/tools/biblio/config.el
> +          (if (stringp paths) (list paths) paths)))
```suggestion
          (if (stringp paths) (list paths) paths))))
```

2021-11-21 19:00 UTC, hlissner requested changes

2021-11-21 19:19 UTC, bdarcus commented on modules/tools/biblio/config.el
> +    (citar-org-note-include '(org-id org-roam-ref))))
I think I resolve all your comments @hlissner.

2021-11-21 19:56 UTC, hlissner commented
> We need to bind org-cite-insert and org-open-at-point, as these are the two entry points for the org-cite module.
> 
> But how, and where?

How about adding a `citation` clause [to +org/dwim-at-point](https://github.com/hlissner/doom-emacs/blob/rewrite-docs/modules/lang/org/autoload/org.el#L125) (which is already on `RET` in normal mode and org already binds `C-c C-o` to `org-open-at-point`)?

```diff
       (while (and context (memq type '(verbatim code bold italic underline strike-through subscript superscript)))
         (setq context (org-element-property :parent context)
               type (org-element-type context)))
       (pcase type
+        (`citation
+         (org-cite-follow context arg))
+
         (`headline
          (cond ((memq (bound-and-true-p org-goto-map)
                       (current-active-maps))
                 (org-goto-ret))
```

As for inserting a citation, considering `org-cite-insert` is now built into org, I think we can add a localleader key to the `:lang org` module for it, perhaps under [the `i` prefix](https://github.com/hlissner/doom-emacs/blob/rewrite-docs/modules/lang/org/config.el#L822-L826) with the other insert commands.

That said, I'm to redesign our org module after the CLI rewrite. It's much overdue, so I'm fine with deciding on a temporary keybind for now.

2021-11-21 20:16 UTC, hlissner commented on modules/tools/biblio/config.el
> +    (citar-org-note-include '(org-id org-roam-ref))))
> I removed the require ox line, and I no longer see that problem. Perhaps it was fixed upstream?

It may depend on the entry point. `ox` explicitly loads `oc`, so if you load `oc` directly, you might still see this issue, though I'm not certain in what scenarios this  would happen naturally.

2021-11-21 20:21 UTC, bdarcus commented
> > We need to bind org-cite-insert and org-open-at-point, as these are the two entry points for the org-cite module.
> > But how, and where?
> 
> How about adding a `citation` clause [to +org/dwim-at-point](https://github.com/hlissner/doom-emacs/blob/rewrite-docs/modules/lang/org/autoload/org.el#L125) (which is already on `RET` in normal mode and org already binds `C-c C-o` to `org-open-at-point`)?

That seems sensible at first glance (I wasn't aware of that function), though you'd also want it available for `citation-reference`.

With `citar`, I have left-click on the mouse set to run `org-open-at-point`, and `right-click` to run `embark-act`. The `org-cite-activate-processor` attaches a map with those and other bindings to the citations.

> As for inserting a citation, considering `oc` is now built into org, I think we can add a localleader key to the `:lang org` module for `org-cite-insert`, perhaps under [the `i` prefix](https://github.com/hlissner/doom-emacs/blob/rewrite-docs/modules/lang/org/config.el#L822-L826) with the other insert commands.

Makes sense.

> That said, I'm to redesign our org module after the CLI rewrite. It's much overdue, so I'm fine with deciding on a temporary keybind for now.

I have no strong opinion, but lean towards deferring to the rewrite. I think it's fine as is for now.

2021-11-21 22:40 UTC, hlissner approved these changes

2021-11-21 23:36 UTC, bdarcus commented
Oh sorry @hlissner - I just bumped the module again to incorporate a minor typo.

2021-11-22 00:05 UTC, hlissner approved these changes

2021-11-22 01:23 UTC, merged

2021-11-22 01:23 UTC, hlissner commented
Sorry for the _incredibly_ long turnaround time, but I'm happy this is finally merged. Thanks again for all your help!