[DRAFT] Vertico theme and crm improvements
hlissner/doom-emacs pull request #5299
Opened 2021-07-26 13:04 UTC by iyefrat

Current work is being done to improve theming, both in upstream `:completion vertico` packages and in `doom-themes`. This PR tracks the what we want to do so we don't get too scattered.

- [X] better `marginalia` symbol annotations
- [X] better `marginalia` file annotations
- [ ] `doom-themes` support for the improved `marginalia` file annotation (to match `diredfl`)
- [ ] in `doom-themes`, use `font-lock-doc-face` for marginalia docstring annotations
- [ ] `doom-themes` support for orderless faces
- [-] better `consult-completing-read-multiple` keys (WIP, I want to have `TAB` keep the current selected candidate)

cc: @tecosaur @elken @minad

2021-07-26 15:15 UTC, hlissner requested changes

2021-07-26 15:15 UTC, hlissner commented on modules/ui/doom/packages.el
> +(package! doom-themes :pin "b7995ac041f8dadb021cd2445e85d29c9bf718ae")
Would you mind bumping this again? To include https://github.com/hlissner/emacs-doom-themes/pull/640 and https://github.com/hlissner/emacs-doom-themes/pull/639

2021-07-26 15:15 UTC, hlissner commented on modules/completion/vertico/autoload/vertico.el
> +  (funcall #'vertico-exit))
Why is it necessary to call this twice and in this manner?

2021-07-26 22:20 UTC, iyefrat commented on modules/ui/doom/packages.el
> +(package! doom-themes :pin "b7995ac041f8dadb021cd2445e85d29c9bf718ae")
Yeah the exact bump commits are placeholders for the moment, I'll bump both to the newest versions once everything is ready (baring any noticeable regressions)

2021-07-26 22:27 UTC, iyefrat commented on modules/completion/vertico/autoload/vertico.el
> +  (funcall #'vertico-exit))
Oh, this is a mistake, this is the crm exit function and `vertico-exit` is the selecting function. That's because the default `consult-crm` has you press `RET` once to select and twice to exit.

2021-07-27 10:21 UTC, elken commented on modules/completion/vertico/autoload/vertico.el
> +  (funcall #'vertico-exit))
Is one not to run when the minibuffer closes?

2021-07-27 18:13 UTC, iyefrat commented
I'm converting this back to draft because there are some cool upstream embark changes that would be a shame to wait until the next bump to get, but require a bit of manual work on my part to fix the which key intergration. Should be ready soonish.

2021-07-27 20:23 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (setq embark-indicator #'+vertico/embark-which-key-indicator)
Note that there is an interesting alternative to the which-key style indicator, the recently introduced verbose indicator (it's what's used by default). it looks like this:
![image](https://user-images.githubusercontent.com/19792685/127222253-402f43e9-884e-49ca-945c-47b435eeeda9.png)

2021-07-27 20:26 UTC, bdarcus commented on modules/completion/vertico/config.el
> +  (setq embark-indicator #'+vertico/embark-which-key-indicator)
Nice!

Hey, you should send that screenshot to Omar, who needs a nice screenshot!

2021-07-27 20:31 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (setq embark-indicator #'+vertico/embark-which-key-indicator)
Uh I think that screenshots on the embark readme should probably have things like a nonarbitrary aspect ratio and not cutting off lines of text at the bottom. Also they should probably be taken from a reasonably default config, e.g. not having the doom modeline, or icons.

Although this reminds me, I should probably add a screenshot to `all-the-icons-completion`

2021-07-27 21:41 UTC, bdarcus commented on modules/completion/vertico/config.el
> +  (setq embark-indicator #'+vertico/embark-which-key-indicator)
What's different about the new which-key one, other than that submenus work?

2021-07-27 21:49 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (setq embark-indicator #'+vertico/embark-which-key-indicator)
Nothing that I can notice to be honest

2021-07-28 13:50 UTC, iyefrat commented
@hlissner also note 9d2131b, the lazy loading of `recentf-mode` introduced in 97048e2 had the side effect having consult previews on when using `SPC f r`, due to the fact that `consult-customize` works on named commands. This fixes that using advice, hopefully that's fine.

2021-07-28 15:58 UTC, numkem commented
Is it possible to ad the icons to `projectile-find-file`?

Thanks!

2021-07-28 17:21 UTC, iyefrat commented
@numkem yeah I'll add this to `all-the-icons-completions` and bump it, good catch

2021-07-28 18:38 UTC, iyefrat commented on modules/completion/vertico/config.el
> +            '(projectile-switch-project . project-file)))
Some of the annotations in the `project-file` type commands where you first select a project and then a file are a bit shaky, due to marginalia not yet providing very good support for these types of project commands. For some commands (e.g. `doom/find-file-in-other-project`) both the project list and file list get file annotations, but for others such as `projectile-switch-project`, they don't really get annotations. This might be due to `marginalia` using `project.el` as the backend or something.

2021-07-28 18:43 UTC, oantolin commented on modules/completion/vertico/config.el
> +  (setq embark-indicator #'+vertico/embark-which-key-indicator)
The main point of having a new which-key indicator is that the indicator protocol changed so the old one won't work anymore! But also, the new one displays (in the which-key help message) whether you are using `embark-act` or `embark-become`, and also shows the current target and an ellipsis to indicate there are further targets you can cycle to.

2021-07-29 17:51 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (advice-add #'marginalia--project-root :override #'projectile-project-root)
should this be `#'doom-project-root`?

2021-07-29 19:52 UTC, minad commented on modules/config/default/+evil-bindings.el
> +       (cond ((featurep! :completion vertico)   (cmd!! #'consult-line-multi '(4)))
I've seen this (4) pattern a few times, which emulates the interactive prefix argument. I recommend to use this only for commands where (4) actually carries some meaning and if not use something else. For `consult-line-multi` this works:

~~~ elisp
(consult-line-multi 'all-buffer)
(consult-line-multi '(:include ".*\\.el\\'" :exclude "init\\.el\\'"))
~~~

2021-07-31 02:29 UTC, hlissner requested changes
Looks good! Just one correction and I think this is ready to merge.

2021-07-31 02:29 UTC, hlissner commented on modules/completion/vertico/config.el
> +  (advice-add #'marginalia--project-root :override #'projectile-project-root)
Yes, please do

2021-07-31 07:50 UTC, iyefrat commented on modules/config/default/+evil-bindings.el
> +       (cond ((featurep! :completion vertico)   (cmd!! #'consult-line-multi '(4)))
fixed

2021-07-31 07:53 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (advice-add #'marginalia--project-root :override #'projectile-project-root)
fixed

2021-07-31 08:34 UTC, hlissner approved these changes

2021-07-31 08:34 UTC, merged

2021-07-31 08:34 UTC, hlissner commented
Looks good to me. Great work! And thanks again!