Allow quickly closing the LSP signature buffer for evil users
hlissner/doom-emacs pull request #5309
Opened 2021-07-28 08:52 UTC by daanturo

In normal state by ESC

We should have a way to quickly escape this:
![image](https://user-images.githubusercontent.com/32123754/127293577-053f1b43-5c30-43dc-abd0-c5b149573c80.png)

2021-07-28 16:04 UTC, hlissner requested changes

2021-07-28 16:04 UTC, hlissner commented on modules/tools/lsp/+lsp.el
> +  (add-hook 'doom-escape-hook 'lsp-signature-stop)
Please sharp-quote the function as per our conventions:

```elisp
(add-hook 'doom-escape-hook #'lsp-signature-stop)
```

2021-07-28 16:05 UTC, hlissner commented on modules/tools/lsp/+lsp.el
> +  (add-hook 'doom-escape-hook 'lsp-signature-stop)
Also, this is adding a global hook; what happens when `lsp-signatures-stop` is called in a non-LSP buffer?

2021-07-28 16:37 UTC, daanturo commented on modules/tools/lsp/+lsp.el
> +  (add-hook 'doom-escape-hook 'lsp-signature-stop)
> Also, this is adding a global hook; what happens when `lsp-signatures-stop` is called in a non-LSP buffer?

As I tried, it didn't produce any messages or raise any errors/warnings.
But perhaps that's not guaranteed in the future, so let's make it lsp-mode only.

2021-07-28 17:01 UTC, daanturo commented
BTW do you think other hooks should be executed after closing the signature successfully while it's active? 
Currently the hook returns `t` (prevent other hooks) since in `lsp-signature-mode-map` (signature is shown), `C-g` is directly mapped to `lsp-signature-stop`, which doesn't do anything that is non-lsp.

2021-07-28 19:30 UTC, hlissner commented on modules/tools/lsp/+lsp.el
> +  (add-hook 'doom-escape-hook 'lsp-signature-stop)
> Another side note: another Emacs developer has noted that defun's return value is undefined, but I have seen that

I'm aware of this. `add-hook!` gets around this by reading the function name in the `defun` format.

2021-07-31 04:17 UTC, hlissner commented
> BTW do you think other hooks should be executed after closing the signature successfully while it's active?

Yes, that makes sense to me.

Quick question: is turning off `lsp-signature-mode` the right way to close the signature? Does LSP reactivate it every time the signature is shown?

2021-07-31 07:40 UTC, daanturo commented
> Quick question: is turning off `lsp-signature-mode` the right way to close the signature?

By inspecting LSP's source, I think it's not supposed to be activated directly but should be turn on/off by `lsp-signature-activate` & `lsp-signature-stop`, respectively as there are only bindings for the 2 command (but not the mode itself) and they also do many things before toggling `lsp-signature-more`.

>  Does LSP reactivate it every time the signature is shown?

Yes, `lsp-signature-mode` is temporary, it is deactivated automatically after we move the cursor out of the describe symbol.

2021-07-31 09:03 UTC, hlissner approved these changes

2021-07-31 09:03 UTC, merged

2021-07-31 09:03 UTC, hlissner commented
Understood, then this looks fine to merge. Thanks again for your help!