Mu4e hotfixes
hlissner/doom-emacs pull request #5333
Opened 2021-08-02 18:44 UTC by tecosaur

Let me know if you want something better, but the commits here should be pretty descriptive.
This fixes two issues that have been reported on Discord for mac and mu4e 1.6 users.

```
fix(mu4e): account for signature change in v1.6

Mu4e 1.6 changes the signature of `mu4e-draft-open'. Since we don't care
about the args replace funcall with apply to make sure it's happy no
matter how many args it expected.

fix(mu4e): improve mu-lock compatability with mac

On mac process args aren't defined, but comm is. Since comm also works
on Linux, we now check for that instead, accounting for a potential
capitalisation difference.

docs(mu4e): fix a typo (errors, plural)

Someone politely requested I add this to my PR on Discord ... why not.
```

2021-08-02 21:26 UTC, hlissner requested changes

2021-08-02 21:26 UTC, hlissner commented on modules/email/mu4e/README.org
> +# I reccomend rerouting all of the errors to /dev/null
`s/reccomend/recommend`

2021-08-02 21:26 UTC, hlissner commented on modules/email/mu4e/autoload/mu-lock.el
>             (process (process-attributes pid)))
Add `(case-fold-search nil)` to ensure case sensitivity in `string-match-p`.

2021-08-03 01:59 UTC, tecosaur commented on modules/email/mu4e/autoload/mu-lock.el
>             (process (process-attributes pid)))
But we don't want it to be case sensitive...

2021-08-03 02:03 UTC, tecosaur commented on modules/email/mu4e/README.org
> +# I reccomend rerouting all of the errors to /dev/null
Done.

2021-08-03 02:20 UTC, hlissner commented on modules/email/mu4e/autoload/mu-lock.el
>             (process (process-attributes pid)))
Don't you? Considering you changed the regexp to `"[Ee]macs"`.

2021-08-03 02:41 UTC, tecosaur commented on modules/email/mu4e/autoload/mu-lock.el
>             (process (process-attributes pid)))
I changed it to `[Ee]macs` because since `case-fold-search` isn't bound to anything, this way we're fine either way.

2021-08-03 03:34 UTC, merged