haskell module improvements
hlissner/doom-emacs pull request #5337
Opened 2021-08-03 20:21 UTC by iyefrat

As discussed on the discord, this PR removes `ghcide` and `dante` support from the haskell module, and rewrites the readme both to reflect this and to generally be up to date regardless.

I'll probably send more improvements down the line as well, but I think this is a good start.

cc: @fosskers

2021-08-03 21:53 UTC, fosskers reviewed
Generally looks good. Consider a `M-q` on longer lines to auto-format them.

2021-08-03 21:53 UTC, fosskers commented on modules/lang/haskell/README.org
> ++ Include links to packages & external things where possible
Leftover from the template?

2021-08-03 22:02 UTC, iyefrat commented on modules/lang/haskell/README.org
> ++ Include links to packages & external things where possible
Whoops, good catches. I always forget to `M-q` lines, I should figure out how to automate that.

2021-08-03 23:42 UTC, jeetelongname commented on modules/lang/haskell/README.org
> +(setq lsp-haskell-formatting-provider "brittany")
Should this not be wrapped in an `after! lsp-haskell` block?

2021-08-03 23:53 UTC, iyefrat commented on modules/lang/haskell/README.org
> +(setq lsp-haskell-formatting-provider "brittany")
It doesn't change anything, `lsp-haskell-formatting-provider` is defined with a `defcustom`, so it doesn't override a `setq`. Not really sure what level of best practices I'm supposed to get into in a readme snippet.

2021-08-04 10:00 UTC, daanturo commented on modules/lang/haskell/doctor.el
> +  (warn! "Couldn't find hlint. Flycheck may have issues in haskell-mode"))
Shouldn't we emit this warning only when `-lsp`?
```suggestion
(unless (or (featurep! +lsp)
            (executable-find "hlint"))
  (warn! "Couldn't find hlint. Flycheck may have issues in haskell-mode. Install it or enable +lsp"))
```

2021-08-04 10:10 UTC, iyefrat commented on modules/lang/haskell/doctor.el
> +  (warn! "Couldn't find hlint. Flycheck may have issues in haskell-mode"))
correct me if I'm wrong, but don't you need to install hlint separately in order to get it to work with the lsp? if not, is this also the case for the formatters?

2021-08-04 11:08 UTC, daanturo commented on modules/lang/haskell/doctor.el
> +  (warn! "Couldn't find hlint. Flycheck may have issues in haskell-mode"))
I don't know if nix package manager's haskell-language-server has been tweaked, but it can give diagnostics and formatting capabilities without `hlint` and `brittany`.
However there's `hls-hlint-plugin`, it must serve something so please ignore my suggested change above.

2021-08-04 14:37 UTC, iyefrat commented on modules/lang/haskell/doctor.el
> +  (warn! "Couldn't find hlint. Flycheck may have issues in haskell-mode"))
I went and checked the code of `hls`. The plugins have `hlint`, `brittany`, etc. as dependencies, so they don't need to be installed. I checked by enabling the ormolu formatter, and it worked despite me not having ormolu installed. I'll update the doctor checks, thank you for bringing this to my attention!

2021-08-04 23:18 UTC, iyefrat commented
I know the CI is failing here due to the commit linting, but I think it has an off-by-one error, the longest line is exactly 72 characters

2021-09-14 21:42 UTC, hlissner commented on modules/lang/haskell/README.org
> +(setq lsp-haskell-formatting-provider "brittany")
It should be wrapped in `(after! lsp-haskell ...)` as a rule of thumb, even if it isn't strictly necessary in this case.

2021-09-14 21:46 UTC, hlissner requested changes

2021-09-14 21:46 UTC, hlissner commented on modules/lang/haskell/config.el
> +(when (featurep! +lsp) (load! "+lsp"))
Now that this has been simplified could you move the contents of +lsp.el here?

2021-09-14 22:57 UTC, iyefrat commented on modules/lang/haskell/README.org
> +(setq lsp-haskell-formatting-provider "brittany")
Done.

2021-09-14 22:57 UTC, iyefrat commented on modules/lang/haskell/config.el
> +(when (featurep! +lsp) (load! "+lsp"))
Done.

2021-09-14 22:58 UTC, hlissner approved these changes

2021-09-14 22:58 UTC, merged

2021-09-14 22:59 UTC, hlissner commented
Looks good! Thanks again for your help!

2021-09-15 06:02 UTC, fosskers commented
Fantastic!