Make ibuffer-visit-buffer workspace-aware
hlissner/doom-emacs pull request #5351
Opened 2021-08-07 20:03 UTC by petr-tik

Fixes #5061 

check if the buffer that is being visited belongs to any
existing workspace and then switch to the workspace before opening the
buffer

** 2 review items marked in code comments

Please review and suggest the best ideas and I will address and/or delete comments accordingly. 

** Performance 

I tried it locally and it worked, but I usually run <6 workspace with 10 buffers each. I am not show what kind of performance 
degradation we should expect for power-users with 10 workspace with 100 buffers in each.

2021-11-21 13:50 UTC, hlissner requested changes
Sorry for the late response. There are some issues here that prevent me from accepting this PR. Besides the points I've outlined below, please reword your commit message to conform to [our git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854):

```
feat(ibuffer): add workspace-aware visit-buffer command

Check if the buffer that is being visited belongs to any existing
workspace and then switch to the workspace before opening the buffer

Fix: #5061
```

(The reworded commit reflects the changes I've requested)

> When I turned ibuffer on in my config, I experienced an unpleasant slowdown in ibuffer generation (i guess it's projectile running slowly on my tramp projects), so i would personally prefer to leave it where it is, but am happy to take guidance and move under ibuffer/config.el

I'd like to address this. A simple workaround may be to disable `ibuffer-projectile`. e.g.

```elisp
;; add to $DOOMDIR/packages.el
(package! ibuffer-projectile :disable t)
```

Then run `doom sync -u`, restart Emacs, and see if it resolves the issue.

2021-11-21 13:50 UTC, hlissner commented on modules/ui/workspaces/config.el
> +               (workspace-name (-first (lambda (worksp-name)
Doom does not use dash.el. Replace `-first` with `cl-find-if`.

2021-11-21 13:50 UTC, hlissner commented on modules/ui/workspaces/config.el
> +      (message "%s doesn't belong to any workspace" buf)))
This body should be wrapped in `(when (bound-and-true-p persp-mode) ...)` to guard against cases where it has been temporarily (or otherwise) disabled.

2021-11-21 13:50 UTC, hlissner commented on modules/ui/workspaces/config.el
> +  (advice-add #'ibuffer-visit-buffer :before #'+workspace-ibuffer-switch-to-buffers-workspace)
I do agree there needs to be a "switch-to-buffer's-workspace" command, but I don't think this is the correct approach (I.e. it shouldn't be the default behavior of ibuffer -- resorting to advice should be a last resort).

Instead, I suggest:

1. A separate command is written, e.g. `+ibuffer/visit-buffer-in-workspace` (defined in the `:emacs ibuffer` module). There is a need for a generalized `+workspaces/switch-to-buffer` command too, so I'd appreciate if you wrote one (in the `:ui workspaces` module) and used it in `+ibuffer/visit-buffer-in-workspace`.

2. Either remap `ibuffer-visit-buffer` in `ibuffer-mode-map` (I.e. `(define-key ibuffer-mode-map [remap ibuffer-visit-buffer] #'+ibuffer/visit-buffer-in-workspace)`) _or_ bind it to another key. E.g. `C-RET`. What do you think?

2021-11-29 21:34 UTC, petr-tik commented
thanks for the review. Appreciate you must have been busy, i will try to address it this week and ping you again

2021-11-29 21:47 UTC, petr-tik commented on modules/ui/workspaces/config.el
> +  (advice-add #'ibuffer-visit-buffer :before #'+workspace-ibuffer-switch-to-buffers-workspace)
> What do you think?

I would like to survey and follow the least surprising behaviour/UX for the users. I will implement the functions first and then we can discuss what the defaults should be.

2021-12-03 17:39 UTC, petr-tik commented on modules/ui/workspaces/config.el
> +      (message "%s doesn't belong to any workspace" buf)))
thanks for spotting. Addressed

2021-12-03 17:39 UTC, petr-tik commented on modules/ui/workspaces/config.el
> +               (workspace-name (-first (lambda (worksp-name)
thanks for helping me out with this. Replaced

2021-12-03 17:42 UTC, petr-tik commented on modules/ui/workspaces/config.el
> +  (advice-add #'ibuffer-visit-buffer :before #'+workspace-ibuffer-switch-to-buffers-workspace)
I decided to rename the function to `+ibuffer/visit-buffer-in-its-workspace`. What are your thoughts on that? 

Also, what about the case of a non-workspace buffer? Should we maybe create a new workspace or use `persp-temporarily-display-buffer` to pull the buffer into the current workspace? 

I decided to default to remaping `ibuffer-visit-buffer`, since I thought people who have opted into both workspaces and ibuffer would expect/accept a default action that leverages both simultaneously. Happy to change the default if you feel it's too intrusive

2021-12-03 19:40 UTC, iyefrat commented on modules/ui/workspaces/config.el
> +               (workspace-name (-first (lambda (worksp-name)
`-if-let*` is from dash too. Can you replace it with `if-let*`?

2021-12-03 19:43 UTC, iyefrat commented on modules/ui/workspaces/config.el
> +      (message "%s doesn't belong to any workspace" buf)))
Replace `-if-let*` with `if-let` here as well.

2022-04-01 18:52 UTC, iyefrat commented
boop

2022-04-01 22:26 UTC, petr-tik commented
are you booping me or Henrik?

2022-04-02 14:45 UTC, iyefrat commented
Oh I just wanted to make sure that the PR first get closed cause it got marked as stale. It's still relevant, Henrik has just been a bit busy

2022-04-03 18:52 UTC, closed without merging

2022-04-03 19:00 UTC, hlissner commented
Sorry for taking so long to get to this. After some deliberation, I've added this functionality in c309e61, with four differences to what's proposed here: 

1. If a buffer is present in more than one workspace, prompt the user to select which workspace they want to end up in.
2. If the buffer is present in no workspaces, add it to the current one.
3. Isolate the functionality to the ibuffer module. I'm working on generalizing this functionality in the workspaces module.
4. I've named the function `+ibuffer/visit-workspace-buffer` to match `+vertico/switch-workspace-buffer`, which does similar. I'm not 100% on this naming, but that's a yak I'll shave later (as part of a bigger effort to rename a bunch of poorly named functions/variables in Doom's code base).

In any case, this should resolve this and #5061. Let me know if I've missed anything!