Vertico Improvements
hlissner/doom-emacs pull request #5353
Opened 2021-08-07 22:57 UTC by iyefrat

- Fix a minor issue with the new prefix-help-command settings
- add more thorough explanations to the readme
- Bump the module, and adapt to upstream changes
- update `all-the-icons-completion`'s recipe as it got accepted to melpa

Note that in it's current state this PR removes the use of `fd` in `consult-find` commands. This is because my attempt in adapting the configuration to the upstream changes broke the command. For this reason the PR is still in draft, but I intend to solve this tomorrow (and make a few other additions).

2021-08-08 07:52 UTC, minad commented on modules/completion/vertico/config.el
> +  (setq embark-indicators '(+vertico/embark-which-key-indicator embark-high))
Typo? Here you may want to remove embark-verbose-indicator and add +vertico/embark-which-key-indicator instead. We may add more useful indicators in the future, see embark-highlight-indicator and embark-isearch-highlight-indicator.

2021-08-08 07:55 UTC, minad commented
> Note that in it's current state this PR removes the use of fd in consult-find commands. 

The best way to get a `consult-fd` command now is to write your own, since `consult-find` became too specialized/tied to POSIX/GNU find. See https://github.com/minad/consult/wiki#find-files-using-fd.

2021-08-08 18:19 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (setq embark-indicators '(+vertico/embark-which-key-indicator embark-high))
Oh whoops, that's supposed to be `embark-highlight-indicator`. Not sure what you mean about `+vertico/embark-which-key-indicator` though, this code does set it doesn't it? Just the highlight indicator as well.

2021-08-08 20:35 UTC, minad commented on modules/completion/vertico/config.el
> +  (setq embark-indicators '(+vertico/embark-which-key-indicator embark-high))
I meant that you may not want to overwrite the list, just replace mixed->whichkey.

2021-08-08 20:36 UTC, minad commented on modules/completion/vertico/config.el
> +  (setq embark-indicators '(+vertico/embark-which-key-indicator embark-high))
And maybe even add https://github.com/oantolin/embark/wiki/Additional-Configuration#colorize-the-current-vertico-candidate-differently-when-acting?

2021-08-08 20:41 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (setq embark-indicators '(+vertico/embark-which-key-indicator embark-high))
> I meant that you may not want to overwrite the list, just replace mixed->whichkey.

Ah, good point.

> And maybe even add https://github.com/oantolin/embark/wiki/Additional-Configuration#colorize-the-current-vertico-candidate-differently-when-acting?

Yeah I was planning on that, but wanted to get the basics sorted first

2021-08-09 19:56 UTC, minad commented
@iyefrat I went with a hybrid approach now for the orderless matching.

* For consult-grep with pcre and consult-git-grep you can use as many regular expressions as you want, and the regular expressions can match in any order.
* For consult-ripgrep without pcre I ony enable unordered matching for up to three regular expressions. For more regular expressions, the unordered matching disenganges. Overall this feels like a good compromise.

See https://github.com/minad/consult/commit/f96718419d2ab54b447c0cb0def2d951a8e9e72b.

2021-08-10 10:38 UTC, iyefrat commented
@minad Thanks for the update. I'll update the bump to include this after a bit of testing, worst case it'll get in in the next one. This means that now the main addition of using the orderless regexp compiler is the use of style dispatchers, yeah?

2021-08-18 11:31 UTC, minad commented
@iyefrat You probably saw this, but there have been quite a few critical bugs in the Consult 0.10 version due to my grep async refactorings. I just tagged Consult 0.11, so you may want to update the pinning.

2021-09-09 20:23 UTC, zauster commented
Hey, I tested your PR (based on Doom bf8495b) and i get an error: 
`
Failed to load magit package incrementally, because: (void-variable embark-indicators)
`
I see that a variable `embark-indicator` (without a trailing s) exists, maybe a typo?

2021-09-14 17:20 UTC, hlissner requested changes

2021-09-14 17:20 UTC, hlissner commented on modules/completion/vertico/doctor.el
> +(autoload #'consult--grep-lookahead-p "consult")
Load the package directly Instead of autoloading this call. e.g. `(require 'consult)`

2021-09-14 17:20 UTC, hlissner commented on modules/completion/vertico/packages.el
> +(package! marginalia :pin "c6ca58bea819c3b5e4b3295ad693c5cd0ae5db31")
Please bump these one more time; there are a couple more updates waiting for them.

2021-09-14 17:20 UTC, hlissner commented on modules/config/default/+evil-bindings.el
> +         :desc "LSP Find declaration"                "j"   #'eglot-find-declaration))
Instead of the `(:when TRUE ...) (:when FALSE ...)` approach, use:

```lisp
        :desc "LSP Find declaration"                "j"   #'eglot-find-declaration
        (:when (featurep! :completion vertico)
         :desc "Jump to symbol in current workspace" "j"   #'consult-eglot-symbols))
```

The latter will overwrite the former when applicable.

2021-09-14 17:20 UTC, hlissner commented on modules/config/default/autoload/default.el
> +  (cond ((and (featurep! :completion vertico) (featurep! :tools lsp))
Should this check for `lsp-mode` (or `eglot-managed-mode`)?

2021-09-14 17:20 UTC, hlissner commented on modules/config/default/autoload/default.el
> +        ((featurep! :checkers syntax)
This should check for `flycheck-mode`.

2021-09-14 17:20 UTC, hlissner commented on modules/config/default/autoload/default.el
> +        (t
And this should check for `flymake-mode`.

2021-09-14 17:20 UTC, hlissner commented on modules/tools/lsp/+eglot.el
> +
Two blank lines between top-level `use-package!` blocks, please.

2021-09-14 17:20 UTC, hlissner commented on modules/tools/lsp/packages.el
> +      (package! eglot :pin "c17bdf6c98d6bf0f1a85f1175556e1038654402f")
eglot was bumped in e03f1d19d. Could you rebase your PR onto `develop`?

2021-09-14 17:20 UTC, hlissner commented on modules/config/default/+emacs-bindings.el
> +         :desc "LSP Find declaration"                "j" #'eglot-find-declaration)))
See my review for +evil-bindings.el below.

2021-09-14 17:20 UTC, hlissner commented on modules/completion/vertico/config.el
> +  (setq +vertico-consult-fd-args
No `defvar` exists for `+vertico-consult-fd-args`, but should (at the top of config.el).

2021-09-14 17:45 UTC, iyefrat commented on modules/completion/vertico/doctor.el
> +(autoload #'consult--grep-lookahead-p "consult")
Done.

2021-09-14 17:45 UTC, iyefrat commented on modules/completion/vertico/packages.el
> +(package! marginalia :pin "c6ca58bea819c3b5e4b3295ad693c5cd0ae5db31")
Done (from looking over the git commits, there doesn't seem to be any manual intervention required, and no obvious bugs so far).

2021-09-14 17:51 UTC, iyefrat commented on modules/config/default/+evil-bindings.el
> +         :desc "LSP Find declaration"                "j"   #'eglot-find-declaration))
Done.

2021-09-14 18:02 UTC, iyefrat commented on modules/config/default/autoload/default.el
> +  (cond ((and (featurep! :completion vertico) (featurep! :tools lsp))
Yeah you're right, I'll add a `(bound-and-true-p lsp-mode)`.

2021-09-14 18:02 UTC, iyefrat commented on modules/config/default/autoload/default.el
> +        ((featurep! :checkers syntax)
Done.

2021-09-14 18:02 UTC, iyefrat commented on modules/config/default/autoload/default.el
> +        (t
Done. Should there be an error message or something in the base case of having nothing on?

2021-09-14 18:03 UTC, iyefrat commented on modules/tools/lsp/+eglot.el
> +
Done.

2021-09-14 18:04 UTC, iyefrat commented on modules/tools/lsp/packages.el
> +      (package! eglot :pin "c17bdf6c98d6bf0f1a85f1175556e1038654402f")
I already rebased, this pin is the updated one :D

2021-09-14 18:11 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (setq +vertico-consult-fd-args
Should I move the `setq` logic to the `defvar` or initialize it as just the string of`doom-projectile-fd-binary` or something?

2021-09-14 21:14 UTC, hlissner commented on modules/config/default/autoload/default.el
> +        (t
Ideally, yes. Perhaps a `(user-error "No diagnostics backend is enabled; e.g. flycheck or flymake")`

2021-09-14 21:16 UTC, hlissner commented on modules/completion/vertico/config.el
> +  (setq +vertico-consult-fd-args
Initialize it as `nil` at top-level, keep the `setq`, but wrap it in a check. `+vertico-consult-fd-args` shouldn't be changed if its value isn't `nil`.

2021-09-14 22:03 UTC, iyefrat commented on modules/config/default/autoload/default.el
> +        (t
Done.

2021-09-14 22:55 UTC, hlissner approved these changes

2021-09-14 23:00 UTC, merged

2021-09-14 23:00 UTC, hlissner commented
Fantastic work! Thanks again for your help!