fix(snippets): yas-expand error when yas-choose-value
hlissner/doom-emacs pull request #5429
Opened 2021-08-29 02:40 UTC by HyunggyuJang

`+snippets-prompt-private` is being overzealous that intercepts the candidates triggered by `yas-choose-value`.

For example, triggering `jupyter` in org mode, renders
#+begin_src jupyter-Wrong type argument: yas--template, "python" :session  :async yes

#+end_src

2021-09-14 11:13 UTC, hlissner requested changes
Please wrap the body of your commit message to 72 characters (to conform to our [git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854)). e.g.

```
fix(snippets): yas-expand error when yas-choose-value

`+snippets-prompt-private` is being overzealous that intercepts the candidates
triggered by `yas-choose-value`.

For example, triggering `jupyter` in org mode, renders
#+begin_src jupyter-Wrong type argument: yas--template, "python" :session :async yes

#+end_src
```

Don't have to worry about line length for the #+begin_src line however.

2021-09-14 11:13 UTC, hlissner commented on modules/editor/snippets/autoload/snippets.el
> +           (choices (condition-case nil
Replace `nil` with `_`. This is the convention for binding unused variables.

2021-09-15 01:05 UTC, HyunggyuJang commented on modules/editor/snippets/autoload/snippets.el
> +           (choices (condition-case nil
Thanks for review! I've amended.

2021-09-15 16:57 UTC, hlissner approved these changes

2021-09-15 16:59 UTC, merged

2021-09-15 16:59 UTC, hlissner commented
Thanks for your help!