Enable web-mode on heex files
hlissner/doom-emacs pull request #5443
Opened 2021-09-02 04:10 UTC by aswinmohanme

Fixes #5442 

Add `heex` extension to Elixir web-mode.

2021-09-13 19:19 UTC, sei40kr commented
@aswinmohanme cc: @hlissner 
How about creating project-mode for Phoenix and adding this to the mode-enter hooks

``` emacs-lisp
(web-mode-set-engine "phoenix")
```

It will provide better syntax highlight.

2021-09-14 10:35 UTC, hlissner requested changes

2021-09-14 10:35 UTC, hlissner commented on modules/lang/web/+html.el
> +  :mode "\\.(l|h)?eex\\'"
Regex is incorrect. Parens need to be escaped, but rather than that better to use character classes instead:

```
"\\.[lh]?eex\\'"
```

2021-09-14 10:38 UTC, hlissner commented
> @aswinmohanme cc: @hlissner
> How about creating project-mode for Phoenix and adding this to the mode-enter hooks
> 
> ```emacs-lisp
> (web-mode-set-engine "phoenix")
> ```
> 
> It will provide us better syntax highlight.

Does this work?

```elisp
(add-to-list 'web-mode-engines-alist '("pheonix" . "\\.[lh]eex\\'"))
```

2021-09-14 10:44 UTC, sei40kr commented
@hlissner cc: @aswinmohanme It works well!

But I also got this warning:

```
Warning (lsp-mode): Unable to calculate the languageId for buffer ‘example.leex’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is web-mode
```

2021-09-14 10:50 UTC, hlissner commented
LSP+web-mode integration is unrelated to this PR (likely relevant to https://github.com/hlissner/doom-emacs/issues/5464). Please open a separate issue for that.

2021-09-14 11:06 UTC, hlissner requested changes
Please change the commit message to `feat(web): add *.[lh]?eex support` to adhere to our [git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854).

2021-09-15 16:56 UTC, merged

2021-09-15 16:56 UTC, hlissner commented
Nice work. Thanks for your help!