Fix extra trailing brace after haskell comment
hlissner/doom-emacs pull request #5450
Opened 2021-09-04 16:16 UTC by celsobonutti

Fixes  #5448

I've added a condition to the smartparens braces expansion, not including "{" if we're in `haskell-mode`.
I'm not much of an elisp user, so it may be very wrong. I would be very happy to make it better if anyone has a suggestion :-)

2021-11-11 00:01 UTC, iyefrat commented
bump

2021-11-21 20:25 UTC, hlissner requested changes
Please squash your commits into one and reword the commit to conform this PR to [our git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854):

```
fix(default): smartparens rules for haskell

The default haskell-mode rules would result in an extra } appended to
the closing pair (#5448).

Fix: #5448
```

2021-11-21 20:25 UTC, hlissner commented on modules/config/default/config.el
> +
Remove superfluous blank line.

2021-11-21 20:25 UTC, hlissner commented on modules/config/default/config.el
> +    (after! haskell-mode
s/haskell-mode/smartparens-haskell

[smartparens-haskell.el](https://github.com/Fuco1/smartparens/blob/master/smartparens-haskell.el) is where the default sp config lives.

2022-01-05 03:05 UTC, closed without merging