fix(emacs-lisp): quiet doc lints in org src blocks
hlissner/doom-emacs pull request #5490
Opened 2021-09-17 04:01 UTC by fosskers

Previously, OrgMode src blocks that contained Emacs Lisp were not given special treatment by flycheck, and were thus were given obtrusive warnings that only usually apply to Lisp being written as part of an Emacs package.

This PR adds a detection mechanism for these Elisp src blocks that allows the flycheck warnings to be disabled, as in one's Doom config.

2021-09-17 07:12 UTC, hlissner approved these changes

2021-09-17 07:13 UTC, hlissner requested changes

2021-09-17 07:13 UTC, hlissner commented on modules/lang/emacs-lisp/autoload.el
> +                 (null buffer-file-name)
Please change this to `(null (buffer-file-name (buffer-base-buffer)))`, so that flycheck doesn't get gimped in narrowed/indirect clones of legitimate elisp files.

2021-09-17 15:17 UTC, fosskers commented on modules/lang/emacs-lisp/autoload.el
> +                 (null buffer-file-name)
Done.

2021-09-17 17:52 UTC, hlissner approved these changes

2021-09-23 09:37 UTC, merged

2021-09-23 09:37 UTC, hlissner commented
LGTM, thanks!