module: add :input bidi
hlissner/doom-emacs pull request #5526
Opened 2021-09-28 00:25 UTC by iyefrat

This pull requests adds better support for bidirectional text. The module isn't complete yet, but I'm opening this as a draft so to more easily get feedback from other RTL language users.

2021-12-05 00:06 UTC, iyefrat commented
In case you have gotten here through email, the top post has been edited with all the relevant info.

2021-12-15 14:39 UTC, iyefrat commented
I am not sure what changed, but there has been a regression with the whitespace/punctuation font stuff. I'll undraft this once that's solved.

2022-04-21 01:34 UTC, hlissner requested changes
Great work! Just have to fix one small typo and it'll be merge ready.

2022-04-21 01:34 UTC, hlissner commented on modules/input/bidi/config.el
> +  "Overrideing font for arabic and arabic-derived scripts.
s/Overrideing/Overriding/

2022-04-21 06:33 UTC, iyefrat commented on modules/input/bidi/config.el
> +  "Overrideing font for arabic and arabic-derived scripts.
whoops! fixed.

2022-04-21 22:21 UTC, hlissner approved these changes

2022-04-21 22:21 UTC, merged

2022-04-21 22:21 UTC, hlissner commented
LGTM! Thanks again for your help!