refactor(pass): make duplicate functions obsolete
hlissner/doom-emacs pull request #5548
Opened 2021-10-01 22:10 UTC by dschrempf

The following functions are affected: `+pass/edit-entry`,
`+pass/copy-field`, `+pass/copy-secret`, `+pass/browse-url`. All of
these functions have counterparts in `password-store`. Additionally, the
functions in password store add git commits when files are
changed.

The obsolete functions can be removed at some point.

Questions:
- Should we also deprecate the `ivy` and `consult` versions? The
`password-store` versions work perfectly well here with `vertico` (not
sure about `ivy` though).

  - [x] It targets the develop branch
  - [x] No other pull requests exist for this issue
  - [ ] The issue is NOT in Doom's do-not-PR list: https://doomemacs.org/d/do-not-pr (<- sorry, I could not check this list)
  - [x] Any relevant issues and PRs have been linked to
  - [ ] Commit messages conform to our conventions: https://doomemacs.org/d/how2commit (<- same here, let me know if the commit message should be changed)

2021-10-04 12:37 UTC, dschrempf commented
It turns out that the `password-store-xxx` functions actually fire up `pass` while the Doom specific functions use `find-file`. This means that if the `EDITOR` variable is not set to `emacslient` or some derivative, the functions will actually not be equivalent. In my opinion the Doom specific functions can still be made obsolete and removed, but I wanted to make you aware of this.

2021-10-04 18:14 UTC, hlissner requested changes
> It turns out that the `password-store-xxx` functions actually fire up `pass` while the Doom specific functions use `find-file`. This means that if the `EDITOR` variable is not set to `emacslient` or some derivative, the functions are not equivalent. In my opinion the Doom specific functions can still be made obsolete and removed, but I wanted to make you aware of this.

That should be fine. The `with-editor` sets EDITOR locally, so the user doesn't have to.

That said, would you mind changing these to aliases using autoloaded `define-obsolete-function-alias`. e.g.

```elisp
;;;###autoload
(define-obsolete-function-alias '+pass/edit-entry #'password-store-edit "21.12")
;; (And remove the definition for `+pass/edit-entry`)
```

And do so for each of them.

2021-10-04 18:40 UTC, dschrempf commented
This reduced the file quite a bit!

We could reduce more if we remove the `+pass-get-secret` function. The only difference to the `password-store-copy` function is that the first returns the secret while the second copies the secret to the kill ring (or clipboard). `+pass-get-secret` and `+pass-get-user` are mentioned in a README when settings up IRC. Also, there are tests for these two functions.

2021-10-04 18:47 UTC, dschrempf commented
I should also say that `+pass/ivy` is now using the obsolete functions. I will change this now.

2021-10-04 18:52 UTC, dschrempf commented
I changed the ivy actions. However, I did not test the code because I am not using `ivy`.

2021-10-04 23:48 UTC, hlissner approved these changes

2021-10-05 00:27 UTC, merged

2021-10-05 00:29 UTC, hlissner commented
Great work. Thanks for your help (and congrats on your first contribution to Doom)!

> Should we also deprecate the ivy and consult versions?

I may no longer be necessary for consult, but ivy I think still needs it. I'll investigate this soon.