Add `:lang fortran` module
hlissner/doom-emacs pull request #5676
Opened 2021-10-22 22:22 UTC by fosskers

This PR adds support for the [Fortran Language](https://fortran-lang.org/), since an off-the-shelf solution mostly doesn't exist if you aren't using Visual Studio on Windows. Critically, this PR brings together all the treats of modernity recently added to the Fortran world; namely a package manager and LSP. It also bridges the gap between `gfortran` and Intel Fortran, since the latter is much loved but hard to integrate into development environments.

#### TODO

- [x] Basic config skeleton
- [x] `+lsp`
- [x] Common Keybindings
- [x] Compilation / Running support
- ~Optional modeline buttons for building/running (`+buttons`?)~
- ~`+intel`~
- [x] `doom doctor` checks
- [x] README clean up

**Note to Self:** Look into `ob-fortran`.

2021-12-14 00:29 UTC, hlissner requested changes

2021-12-14 00:29 UTC, hlissner commented on modules/lang/fortran/config.el
> +  :config
Add `:defer t` to lazy load the package.

2021-12-14 00:29 UTC, hlissner commented on modules/lang/fortran/README.org
> +#+SINCE:   v3.0.0
```diff
-#+SINCE:   v3.0.0
+#+SINCE:   v3.0.0 (#5676)
```

2021-12-15 00:20 UTC, fosskers commented on modules/lang/fortran/config.el
> +  :config
Done.

2021-12-15 00:20 UTC, fosskers commented on modules/lang/fortran/README.org
> +#+SINCE:   v3.0.0
Done.

2021-12-15 14:16 UTC, merged

2021-12-15 14:16 UTC, hlissner commented
LGTM! Thanks for your help!

2021-12-15 17:59 UTC, fosskers commented
The crossed-off features in the original post will be addressed in follow-up PRs.