`:completion vertico` improvements
hlissner/doom-emacs pull request #5710
Opened 2021-10-30 18:18 UTC by iyefrat

- minor code reorganization
- which-key embark indicator improvements
- `+vertico/search-symbol-at-point` preview fix
- bump packages

2021-11-01 07:35 UTC, minad commented
@iyefrat There has been a change in vertico-repeat. The package does not activate itself anymore automatically:

https://github.com/minad/vertico/commit/ff63d353bef62a7c66834200a564a00d1a92c833#diff-42d2775dfb0ba97a32545981ad1df8d637721deb57d035f65bd5e56ed20b7725

2021-11-01 11:22 UTC, iyefrat commented
@minad thanks. What was the reason for this change? Also, is `vertico-repeat` purposely not autoloaded now or is that a mistake?

2021-11-01 11:29 UTC, minad commented
It is better style this way, since the package does not autoactivate itself by only installing it. 

I could also add an autoload to vertico-repeat, however the first time you run vertico-repeat without having started a vertico session before you will only get an error message.

2021-11-01 11:30 UTC, minad commented
See https://github.com/minad/vertico/commit/665660f91004e4c6aad1e18b9cdc256607228c42

2021-11-18 22:23 UTC, hlissner requested changes

2021-11-18 22:31 UTC, iyefrat commented on modules/completion/vertico/config.el
> +      (let ((embark-indicators (delq #'+vertico-embark-which-key-indicator embark-indicators)))
Done, there has also been a simplification of this function in the wiki, so I added that as well.

2021-11-18 22:31 UTC, iyefrat commented on modules/completion/vertico/config.el
> +         ("C-x C-j" . consult-dir-jump-file)))
Done.

2021-11-18 22:39 UTC, iyefrat commented
Also I pushed a formatting commit, a function was changed a while back but the formatting slipped by.

2021-11-19 22:42 UTC, hlissner approved these changes

2021-11-19 22:43 UTC, merged

2021-11-19 22:43 UTC, hlissner commented
LGTM. Thanks again for your help!