Use persp-set-keymap-prefix instead of setq
hlissner/doom-emacs pull request #5718
Opened 2021-11-02 07:13 UTC by shackra

this is to change the default keymap of persp-mode correctly and avoid
weird bugs

- https://github.com/Bad-ptr/persp-mode.el/blob/298df111f081b5925f0aa0126a1b8d334117e0a2/persp-mode.el#L1002-L1017
- https://www.reddit.com/r/DoomEmacs/comments/qgn814/adding_a_specific_package_as_a_module/?utm_source=share&utm_medium=web2x&context=3
- https://github.com/merrickluo/lsp-tailwindcss/issues/22

Under [some circumstances](https://www.reddit.com/r/DoomEmacs/comments/qgn814/adding_a_specific_package_as_a_module/?utm_source=share&utm_medium=web2x&context=3) `:config (default +bindings)` will fail to rebind the keymap of persp-mode which in turn breaks some bindings for projectile, to prevent this bug from happening, using a function [provided by persp-mode](https://github.com/Bad-ptr/persp-mode.el/blob/298df111f081b5925f0aa0126a1b8d334117e0a2/persp-mode.el#L1002-L1017) to change the keymap is required.

Using [`setq` to change a `defcustom`](https://emacs.stackexchange.com/questions/44220/how-to-overwrite-a-defcustom-of-a-package-within-the-initfile#comment68327_44223) shouldn't be done anyway.

2021-11-09 15:55 UTC, shackra commented
I know this is a small change, but I wonder if something is missing that could get this approved and merge

2021-11-18 00:58 UTC, hlissner requested changes

2021-11-18 00:58 UTC, hlissner commented on modules/config/default/+emacs-bindings.el
> +(persp-set-keymap-prefix (kbd "C-c w"))
Can you try `(setq! persp-keymap-prefix (kbd "C-c w"))` instead?

I'd rather avoid having to eagerly load the package just for this.

2021-11-18 01:01 UTC, hlissner requested changes
Assuming `s/setq/setq!` works, please squash your two commits and reword it to conform to [our git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854):

```
fix(default): use persp-keymap-prefix's setter
```

2021-11-23 05:02 UTC, shackra commented
> Assuming `s/setq/setq!` works, please squash your two commits and reword it to conform to [our git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854):
> 
> ```
> fix(default): use persp-keymap-prefix's setter
> ```
> 
> > I know this is a small change, but I wonder if something is missing that could get this approved and merge
> 
> Sorry for the late response. I've been ill the past two months, so my activity's been spotty. I am only returning to Doom now.

yeah, `setq!` works fine.

2021-11-23 11:49 UTC, hlissner approved these changes

2021-11-24 12:11 UTC, merged

2021-11-24 12:11 UTC, hlissner commented
Thanks for your help!