fix: ol-notmuch moved from org-contrib to new repo
hlissner/doom-emacs pull request #5746
Opened 2021-11-08 03:09 UTC by leezu

[org-contrib](https://git.sr.ht/~bzg/org-contrib) is moving a number of files to separate repositories, including ol-notmuch.el. ol-notmuch.el is set up by default in the notmuch module, but was no longer installed by default, resulting in a `Problems while trying to load feature ‘ol-notmuch’` message when opening the org-agenda.

The new repo location is referenced in the file at org-contrib: https://git.sr.ht/~bzg/org-contrib/tree/e14dfea5/item/lisp/ol-notmuch.el#L8

2021-11-17 22:52 UTC, hlissner requested changes
Please reword the commit message to conform to [our git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854):

```
fix(notmuch): ol-notmuch missing

ol-notmuch.el was moved out of org-contrib into its own repo. 

Ref: https://git.sr.ht/~bzg/org-contrib/tree/e14dfea5/item/lisp/ol-notmuch.el#L8
```

2021-11-17 22:52 UTC, hlissner commented on modules/email/notmuch/packages.el
> +  (package! ol-notmuch :pin "126fb446d8fa9e54cf21103afaf506fd81273c02" :recipe (:host nil :repo "https://git.sr.ht/~tarsius/ol-notmuch")))
Please remove the `:recipe`, since [ol-notmuch is now on MELPA](https://melpa.org/#/ol-notmuch).

2021-11-22 22:25 UTC, leezu commented
Great that ol-notmuch is now on MELPA. I've updated the PR. Thank you @hlissner.

2021-11-24 10:49 UTC, hlissner approved these changes

2021-11-24 12:10 UTC, merged

2021-11-24 12:10 UTC, hlissner commented
LGTM. Thanks for your help!