Show outline path on refile to current file
hlissner/doom-emacs pull request #5750
Opened 2021-11-08 21:43 UTC by jinder1s

Before this change, the refile to current file command would result in a list of headings in current file. In case of duplicate names, it was hard to tell which heading referred to which.  With org-refile-use-outline-path set to t, now you should see a baths to each heading in a file.

Fixes #0000 

{{{ Summarize what you've changed HERE and why }}}

2021-11-17 22:37 UTC, hlissner requested changes
Please reword the commit message to conform to [our git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854):

```
fix(org): show outline path on refile to current file

Before this change, the +org/refile-to-current-file command would
display a flat list of tail headings in the current file, without
context, which can result in duplicates and can make it difficult to
tell where you're refiling a heading to.

This changes each heading to be a full path.
```

- `nit` is not the correct type for this kind of commit.
- BODY contained some grammar issues and was a little vague.

2021-11-17 22:37 UTC, hlissner commented on modules/lang/org/autoload/org-refile.el
> +        (org-refile-use-outline-path 't)
Please remove unnecessary quoting:

```diff
-       (org-refile-use-outline-path 't)
+       (org-refile-use-outline-path t)
```

2021-11-19 15:30 UTC, jinder1s commented
Hi, thanks for the code review.

I reworded the commit message and  modified code as suggested. Let me know if there is anything else you'd like me to change.

2021-11-19 15:37 UTC, hlissner approved these changes

2021-11-19 22:44 UTC, merged

2021-11-19 22:44 UTC, hlissner commented
Great work. Thanks for your help!