fix(latex): run AUCTeX folding after font locking
hlissner/doom-emacs pull request #5754
Opened 2021-11-10 02:42 UTC by vqhuy

This guarantees that `TeX-fold-buffer` is run after the style hooks and not before. Otherwise, it looks like they may reset/erase font-lock stuff you have set up.

Currently, `TeX-fold-buffer` sometimes is applied before font locking hooks, causing incomplete folding (usually wrong colorization).

2021-11-17 22:21 UTC, hlissner requested changes

2021-11-17 22:21 UTC, hlissner commented on modules/lang/latex/config.el
> +  (defun +delayed-TeX-fold-buffer ()
Rename to `+latex-Tex-fold-buffer-h` to conform to [Doom's naming conventions](https://github.com/hlissner/doom-emacs/blob/develop/docs/contributing.org#naming-conventions).

2021-11-17 23:09 UTC, vqhuy commented on modules/lang/latex/config.el
> +  (defun +delayed-TeX-fold-buffer ()
Done.

2021-11-17 23:49 UTC, hlissner approved these changes

2021-11-18 18:05 UTC, merged

2021-11-18 18:05 UTC, hlissner commented
Thanks again for your help!