fix(popup,reftex): show reftex-citation in popup
hlissner/doom-emacs pull request #5787
Opened 2021-11-17 14:05 UTC by vqhuy

2021-11-17 16:35 UTC, hlissner requested changes
Please reword commit to:

```
fix(popup): show reftex-citation in popup
```

There is no "reftex" module, so it is not a valid scope.

2021-11-17 16:51 UTC, vqhuy commented
Done.

2021-11-17 17:00 UTC, hlissner approved these changes

2021-11-18 18:09 UTC, merged

2021-11-18 18:09 UTC, hlissner commented
Thanks!