fix(evil): handle edge cases of embrace
hlissner/doom-emacs pull request #5792
Opened 2021-11-18 01:59 UTC by vqhuy

If the surround key is `\(`, the text should be surrounded as
`\( text \)`. The same for `\[` and `\{`.

Currently, when the surround key is `\(`, `+evil--embrace-escaped` returns `"\( " . "\ )"`, which changes the text to `\( text\ )` (notice the space before `\` and `)`).

2021-11-18 17:16 UTC, hlissner requested changes

2021-11-18 17:16 UTC, hlissner commented on modules/editor/evil/autoload/embrace.el
> +          ((eq char 123) (cons "\\{ " " \\}"))
Could you generalize this into the else clause of the `cond`?

We'd just need to detect if `(cdr pair)` starts with a space, and if so, then prepend a space to `text` (the format string).

2021-11-19 13:36 UTC, vqhuy commented on modules/editor/evil/autoload/embrace.el
> +          ((eq char 123) (cons "\\{ " " \\}"))
but we also need to remove the space between `\` and the `)` returned by `+evil--embrace-escaped`. Is that an elegant solution? Not sure if the user has some weird pairs that include whitespace, so trying to generalize this might break users' setting?

2021-11-19 13:37 UTC, vqhuy commented on modules/editor/evil/autoload/embrace.el
> +          ((eq char 123) (cons "\\{ " " \\}"))
I mean this fix is specified for the default setting, if the user has extra setting then she needs to be careful with her own implementation.

2021-11-19 16:48 UTC, vqhuy commented on modules/editor/evil/autoload/embrace.el
> +          ((eq char 123) (cons "\\{ " " \\}"))
actually we also need to remove that space too. I gave it a try in https://github.com/hlissner/doom-emacs/pull/5792/commits/3bec6ae972272714b5c7275114e7d5cd3d630c12 but not sure how `sp-point-in-string` works here, so I just ignored it.

2021-11-19 16:49 UTC, vqhuy commented on modules/editor/evil/autoload/embrace.el
> +          ((eq char 123) (cons "\\{ " " \\}"))
FYI, putting `(end (if (sp-point-in-string) "%s\\\\" "%s\\"))` causes an error `Invalid use of \\ in replacement text` by `replace-match` inside `replace-regexp-in-string`.

2021-11-22 10:01 UTC, vqhuy commented
@hlissner Is there anything I can do to get this done?

2021-11-24 11:22 UTC, hlissner approved these changes

2021-11-24 11:51 UTC, hlissner requested changes

2021-11-24 11:51 UTC, hlissner commented on modules/editor/evil/autoload/embrace.el
> +                                        (cdr pair)))))))
To fix the issue with in-string escaping, try this:

```diff
-      (let ((pair (+evil--embrace-get-pair (string char)))
-            (start (if (sp-point-in-string) "\\\\%s" "\\%s"))
-            (end "%s\\\\"))
-        (cons (format start (car pair))
-              (replace-regexp-in-string "^[[:space:]]*"
-                                        (lambda(s) (format end s))
-                                        (cdr pair)))))))
+      (let* ((pair (+evil--embrace-get-pair (string char)))
+             (escape (if (sp-point-in-string) "\\\\" "\\"))
+             (escape (format "\\1%s" (regexp-quote escape))))
+        (cons (replace-regexp-in-string "^\\( *\\)" escape (car pair))
+              (replace-regexp-in-string "^\\( *\\)" escape (cdr pair)))))))
```

2021-11-24 11:52 UTC, hlissner commented on modules/editor/evil/autoload/embrace.el
> +          ((eq char 123) (cons "\\{ " " \\}"))
Backslashes need another step of escaping to be used in a regular expression (e.g. filter it through `regexp-quote`). See my recent review for a solution that takes care of this.

2021-11-24 21:46 UTC, vqhuy commented
Thanks, I think the PR is good now.

2021-11-24 23:57 UTC, hlissner approved these changes

2021-11-25 00:45 UTC, merged

2021-11-25 00:45 UTC, hlissner commented
LGTM. Thanks again for your help! (And for putting up with my nitpicks)