feat(magit): replace github-review for code-review
hlissner/doom-emacs pull request #5846
Opened 2021-11-28 10:14 UTC by elken

code-review is considered to be a superset of github-review, and as well
as supporting more forges (gitlab support is WIP) also better fits in
with magit.

2021-11-29 10:24 UTC, elken commented
Discussion [here](https://github.com/wandersoncferreira/code-review/issues/28#issuecomment-981194557) on handling bindings, so the snippet might end up being removed.

2021-12-04 16:05 UTC, elken commented
Will fix the commit linter and delete this comment after

2021-12-14 00:18 UTC, hlissner requested changes
Sorry for the late response! Could you:

1. bump `:tools magit` once more (and squash it into the latest bump commit)?
2. Move the changes to README.org to the rewrite-docs branch?

2021-12-14 00:18 UTC, hlissner commented on modules/tools/magit/config.el
> +  (after! evil-collection
Shouldn't this be `(after! evil-collection-magit ...)` ?

2021-12-14 06:28 UTC, elken commented on modules/tools/magit/config.el
> +  (after! evil-collection
Yes it should, thanks

2021-12-14 06:28 UTC, elken commented
> Sorry for the late response! Could you:
> 
>     1. bump `:tools magit` once more (and squash it into the latest bump commit)?

No worries

>     2. Move the changes to README.org to the rewrite-docs branch?

Under another PR? Sure

2021-12-15 13:12 UTC, hlissner approved these changes

2021-12-15 14:17 UTC, merged

2021-12-15 14:17 UTC, hlissner commented
Thanks again for your help!