fix(default): only use `woman` on macOS
hlissner/doom-emacs pull request #5888
Opened 2021-12-11 19:03 UTC by ethan-leba

`man -k "^"` is very slow on macOS.

```
sh-3.2$ time man -k "^" > /dev/null

real	0m1.599s
user	0m0.391s
sys	0m1.209s
```

It's possible that this could just be a me issue, so if anyone else with a mac can fact-check this that would be great!

2021-12-14 15:15 UTC, elken commented
![image](https://user-images.githubusercontent.com/2872862/146025681-14e1d0c2-aa3b-4915-919f-6afe88104fc4.png)
First 2 are under zsh, second 2 under sh

2021-12-14 15:41 UTC, ethan-leba commented
should i add a note explaining the perf. issue to the docstring, or is it fine as is?

2021-12-14 18:15 UTC, hlissner requested changes
> should i add a note explaining the perf. issue to the docstring, or is it fine as is?

Yes, please do.

2021-12-15 13:12 UTC, hlissner approved these changes

2021-12-15 13:31 UTC, ethan-leba commented
Sorry for proposing more last-minute changes, but I've realized that the `woman-manpath` isn't necessarily correct (not sure how this variable is set, really) -- it's missing some more man exotic locations which contain things like `git`.

```
Value
("/usr/local/share/man" "/usr/share/man" "/opt/X11/share/man" "/Library/Apple/usr/share/man" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man" "/Library/Developer/CommandLineTools/usr/share/man")

Original Value
("/usr/share/man" "/usr/local/share/man" "/usr/X11/man" "/Library/Apple/usr/share/man"
 ("/bin" . "/usr/share/man")
 ("/sbin" . "/usr/share/man")
 ("/usr/bin" . "/usr/share/man")
 ("/usr/sbin" . "/usr/share/man")
 ("/usr/local/bin" . "/usr/local/share/man")
 ("/usr/local/sbin" . "/usr/local/share/man")
 ("/usr/X11/bin" . "/usr/X11/man")
 ("/usr/bin/X11" . "/usr/X11/man")
 ("/usr/bin/mh" . "/usr/share/man"))
```

Adding this snippet to my config was able to resolve this issue:
```emacs-lisp
(after! woman
  (setq woman-manpath (split-string (cdr (doom-call-process "man" "--path")) path-separator t)))
```

and it seems performant enough to run at load time, though it would probably be ideal to store this value:
```emacs-lisp
(defun test-manpath ()
  (split-string (cdr (doom-call-process "man" "--path")) path-separator t))

(benchmark 1000 '(test-manpath))
"elapsed time: 6.061939s"
```

I'm not sure where this would fit in the default config module (if it does at all), do you have any thoughts?

2021-12-15 14:07 UTC, hlissner commented
I'm working on a cleaner way for modules to cache data to file during `doom sync`. In the meantime, I suggest caching the manpath on first use (or when given the prefix arg):

```diff
+(defun +default/man-or-woman (&optional nocache)
   "Invoke `man' if man is installed and the platform is not MacOS, otherwise use `woman'.

 `man -k \"^\"` is very slow on MacOS, which is what `Man-completion-table' uses to
 generate `completing-read' candidates."
+  (interactive "P")
+  (when (or nocache (null (get '+default/man-or-woman 'cached)))
+    (setq woman-manpath
+          (split-string (cdr (doom-call-process "man" "--path"))
+                        path-separator t))
+    (put '+default/man-or-woman 'cached t))
   (call-interactively
    (if (and (not IS-MAC) (executable-find "man"))
        #'man
      #'woman)))
```

2021-12-15 14:29 UTC, hlissner commented
Actually, scratch that, your `(after! woman ...)` snippet is good enough. I'll accept putting it in `:config default` for now. It's not the ideal placement, but I'll revisit that once my todo list looks less intimidating.

2021-12-15 14:47 UTC, hlissner requested changes

2021-12-15 14:47 UTC, hlissner commented on modules/config/default/autoload/default.el
> +
Can you move this in `config/default/config.el` in the "reasonable defaults" section?

2021-12-15 17:03 UTC, hlissner approved these changes

2021-12-15 17:04 UTC, merged

2021-12-15 17:04 UTC, hlissner commented
LGTM. Thanks for your help! (And for putting up with all my nitpicks!)