fix(erlang): fix broken erlang-mode
hlissner/doom-emacs pull request #5893
Opened 2021-12-14 02:29 UTC by gilbertwong96

- [x] It targets the develop branch
  - [x] No other pull requests exist for this issue
  - [ ] The issue is NOT in Doom's do-not-PR list: https://gist.github.com/hlissner/bb6365626d825aeaf5e857b1c03c9837
  - [x] Any relevant issues and PRs have been linked to erlang/otp#5314
  - [x] Commit messages conform to our conventions: https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854

Fixes #0000 

1. Upgrade OTP version to fix broken erlang mode. See Github issue erlang/otp#5314
2. Remove `company-erlang` and `ivy-erlang-complete`. The lsp mode provides
much better function than these two packages. `ivy-erlang-complete`
would slow down the buffer enabled erlang mode when the buffer is huge
enough. It is not a good choice to integrate `ivy-erlang-complete` nowadays.

2021-12-14 02:40 UTC, gilbertwong96 commented
I changed the `modules/lang/erlang/README.org`. I suppose that the `README.org` has to follow the source code change I committed. @hlissner

2021-12-14 03:06 UTC, hlissner requested changes
Thanks for your help! This PR needs some work, however:

1. Please move the README.org changes to a new PR targeting our `rewrite-docs` branch. Doom's Module documentation is undergoing a redesign in that branch.
2. Either remove `company-erlang` entirely, or restore its `package!` declaration. As it is now, the package won't be available when `company-erlang-init` is called, which doesn't seem intentional. If possible, I want users to have a non-LSP option available to them, but I don't know Erlang, so I entrust the decision to you.
3. This PR doesn't conform to [our git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854). Please:
   - Split the erlang@118cb37b->erlang@f7blc003 change into its own [bump](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854#types) commit.
     ```
     bump: :lang erlang

     erlang/otp@118cb37bd5b9 -> erlang/otp@9b07aedd669c

     Ref: erlang/otp#5314
     ```
   - Whether or not you decide to keep company-erlang, please remove it in a commit separate from the bump commit above, as a [refactor](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854#types) commit with indication that it is [a breaking change](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854#breaking-changes). e.g.
     ```
     refactor!(erlang): remove company-erlang

     BREAKING CHANGE: <explain what was changed, why it was changed, and how the user should adapt to the change>
     ```
   - Split the removal of `ivy-erlang-complete-reparse` into a [refactor](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854#types) commit with indication that it is [a breaking change](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854#breaking-changes).
     ```
     refactor!(erlang): remove ivy-erlang-complete-reparse

     BREAKING CHANGE: <explain what was changed, why it was changed, and how the user should adapt to the change>
     ```

2021-12-16 18:56 UTC, gilbertwong96 commented on modules/lang/erlang/doctor.el
> +;;; lang/rust/doctor.el
Done

2021-12-16 18:57 UTC, gilbertwong96 commented on modules/lang/erlang/packages.el
> -    (package! company-erlang :pin "bc0524a16f17b66c7397690e4ca0e004f09ea6c5")))
`company-erlang` is really not a good choice even as a non-LSP option.

2021-12-16 18:57 UTC, gilbertwong96 commented on modules/lang/erlang/config.el
> +  :config (add-hook 'erlang-mode-local-vars-hook #'lsp!)
Done

2021-12-16 18:57 UTC, gilbertwong96 commented
I will update docs later.

2021-12-18 00:18 UTC, hlissner requested changes
It seems erlang/otp has seen quite a few updates since the bumped commit. Could you bumpt the module again?

2021-12-18 00:18 UTC, hlissner commented on modules/lang/erlang/config.el
> +  (when (featurep! :tools lsp)
Please revert this. The `+lsp` flag is required for toggling LSP behavior in any `:lang` module that provides it.

2021-12-18 00:18 UTC, hlissner commented on modules/lang/erlang/packages.el
> +(package! erlang :pin "f7blbc003489b22c946c180d48c19175 ")
The SHA is too short, has unnecessary whitespace, and does not match the SHA in the commit message (erlang/otp@9b07aed)

2021-12-18 05:52 UTC, gilbertwong96 commented on modules/lang/erlang/packages.el
> +(package! erlang :pin "f7blbc003489b22c946c180d48c19175 ")
Sorry for my carelessness.

2021-12-18 06:08 UTC, gilbertwong96 commented on modules/lang/erlang/packages.el
> +(package! erlang :pin "f7blbc003489b22c946c180d48c19175 ")
I have pinned to the latest OTP tagged version erlang/otp@5d0fa9d31812947479eb29f797990da6655d4fa2

2021-12-18 10:12 UTC, gilbertwong96 commented on modules/lang/erlang/config.el
> +  (when (featurep! :tools lsp)
It seems that the `feature! +lsp` could not toggling LSP behavior.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/20479699/146633133-8573e13b-0238-4ac5-ac2e-1320623de44a.png">

I changed it to  `featurep! :tools lsp`. It works.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/20479699/146637313-b4519e81-45da-4662-b512-afc1fc7ec0c8.png">

2022-01-03 16:48 UTC, hlissner commented on modules/lang/erlang/config.el
> +  (when (featurep! :tools lsp)
This means you haven't enabled `+lsp` on the module. It should remain tied to this flag, whether or not `:tools lsp` is enabled.

2022-01-03 16:49 UTC, hlissner requested changes

2022-01-03 16:49 UTC, hlissner commented on modules/lang/erlang/packages.el
> +(package! erlang :pin "5d0fa9d31812947479eb29f797990da6655d4fa2")
Sorry for the delay (due to the holidays). Would you mind bumping `erlang` once more? There were a few updates since the last one.

2022-01-04 02:54 UTC, gilbertwong96 commented on modules/lang/erlang/packages.el
> +(package! erlang :pin "5d0fa9d31812947479eb29f797990da6655d4fa2")
Updated

2022-01-04 02:54 UTC, gilbertwong96 commented on modules/lang/erlang/config.el
> +  (when (featurep! :tools lsp)
Done

2022-01-04 20:02 UTC, hlissner approved these changes

2022-01-05 03:06 UTC, merged

2022-01-05 03:06 UTC, hlissner commented
This looks good to me. Thanks for your help (and for putting up with my nits)!

2022-01-05 03:15 UTC, gilbertwong96 commented
You’re welcome.

> On Jan 5, 2022, at 11:07 AM, Henrik Lissner ***@***.***> wrote:
> 
> 
> This looks good to me. Thanks for your help (and for putting up with my nits)!
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/hlissner/doom-emacs/pull/5893#issuecomment-1005343263>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AE4H5U5FUXUJFKFWTPEVJV3UUOYVZANCNFSM5J7WWODQ>.
> You are receiving this because you authored the thread.
>