`:completion vertico` improvements
hlissner/doom-emacs pull request #5953
Opened 2022-01-03 23:55 UTC by iyefrat

- a rework of how the `completing-read-multiple` keybindings work (see commit message for details)
- module bump 

I went over the commit bump and nothing should be out of the ordinary, but i'd like to give it a few days to make sure nothing obvious broke, hence the draft

2022-01-03 23:56 UTC, iyefrat commented
Oh also I forgot, for some reason in the crm commit, the last line (starting with `S-TAB:`) got recognized as a trailer by the CI. this didn't happen with the previous likes even though they have the xxx: format as well. not sure what's up with that, I had to add an extra line to get the ci to pass

2022-01-04 02:38 UTC, hlissner requested changes
> I had to add an extra line to get the ci to pass

Better to use list notation to avoid it:

```
refactor!(vertico): crm keybindings behaviour

BREAKING CHANGE: This commit changes the behaviour of the TAB and RET
keys in a consult-completing read multiple session, in order to make
them more intuitive. The behaviour is now:

- TAB: (unchanged) always select or deselect the current candidate, and if
  the candidate is selected, move the index to the next one (this allows
  for pressing TAB repeatedly to select multiple subsequent candidates).
- RET: If no candidates have been selected, select the current candidate
  and exit the completion session. If some have been selected, disregard
  the current candidate and exit.
- S-TAB: (new) like TAB, but the keeps the input.
```

That, or I can force-merge, despite any CI warnings.

Anyhow, I'll look into fixing the linter soon.

2022-01-04 10:46 UTC, iyefrat commented
good idea, I switched to list notation.

2022-01-11 21:03 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (set-popup-rule! "^\\*Embark" :size 0.35 :ttl nil :quit nil)
@hlissner just to make sure this change doesn't slip by. I think it makes sense to handle all embark buffers similarly, and usually you export stuff when you want to keep it around for a while. However doing `SPC b k` on these buffers when they are displayed in a popup window doesn't seem to actually kill them, but killing them after switching to them with `SPC <` does. Any idea why that might be the case?

2022-01-13 21:17 UTC, iyefrat commented on modules/completion/vertico/config.el
> +  (set-popup-rule! "^\\*Embark" :size 0.35 :ttl nil :quit nil)
i'm delaying this change to the next vertico pr

2022-01-14 00:10 UTC, hlissner approved these changes

2022-01-14 00:11 UTC, merged

2022-01-14 00:11 UTC, hlissner commented
Great work as always! Thanks again!