docs(haskell): fix docs for alternative formatter
hlissner/doom-emacs pull request #5955
Opened 2022-01-04 04:45 UTC by carlosdagos

Small fixup to use the proper form when setting an alternative formatter using the `!after` macro.

_Small note:_ This PR targets the `rewrite-docs` branch as per [the Discord message here](https://discord.com/channels/406534637242810369/406624667496087572/927300806250754048)

2022-01-04 16:35 UTC, iyefrat commented
Hey, can you edit your commit message so that `!after` is `after!`?

2022-01-04 18:17 UTC, hlissner requested changes

2022-01-04 18:17 UTC, hlissner commented on modules/lang/haskell/README.org
> +(after! haskell
The package is named `haskell-mode`, so this must be `(after! haskell-mode`

2022-01-05 10:56 UTC, michaelpj commented on modules/lang/haskell/README.org
> +(after! haskell
Probably it should actually be after `lsp-haskell`? (`lsp-haskell` is the `lsp-mode` Haskell client, `haskell-mode` is the old Haskell major mode).

2022-01-05 11:04 UTC, carlosdagos commented on modules/lang/haskell/README.org
> +(after! haskell
I had it as `(after! haskell ...)` and that worked fine. But I tried as @michaelpj mentioned and works fine as well, actually. And I think it's actually the better approach, as we're `setq`ing the `lsp-haskell-formatting-provider` var after all. I'll change it to that 😄

2022-01-05 14:08 UTC, merged

2022-01-05 14:08 UTC, hlissner commented
Good catch! Thanks for the help!