docs(org): fix type in org README capture example
hlissner/doom-emacs pull request #5986
Opened 2022-01-11 20:24 UTC by Bounga

Fix a small type in org module capture example

2022-01-12 00:08 UTC, hlissner requested changes
1. Use lower-case `#+BEGIN_SRC` and `#+END_SRC`.
2. Remove added whitespace after paragraph.
3. `s/type/typo` in the git commit message.
4. Remove redundancies ("org" and "README") in git commit message: `docs(org): fix typo in capture example`. These are both implied by the commit type (docs) and scope (org).

2022-01-12 20:21 UTC, hlissner approved these changes

2022-01-12 20:22 UTC, Bounga commented
@hlissner Sorry for the mess. It should be good now.

2022-01-13 20:49 UTC, merged

2022-01-13 20:49 UTC, hlissner commented
No worries! Thanks again for your help!