tweak(julia): update lsp environment to recent LTS
hlissner/doom-emacs pull request #6010
Opened 2022-01-16 20:24 UTC by kiranshila

As of 1 Dec, Julia v1.6 is the [new LTS release](https://discourse.julialang.org/t/julia-v1-7-0-has-been-released-and-v1-6-is-now-lts/72336). This bumps the docs to reflect this as well as the configuration for the default environment in the lsp backends.

2022-01-16 20:29 UTC, hlissner requested changes
Our docs on in our [do-not-pr list](https://gist.github.com/hlissner/bb6365626d825aeaf5e857b1c03c9837). Please make this change to the `rewrite-docs` branch instead.

2022-01-16 20:55 UTC, kiranshila commented
Is this docs? Primarily it bumps the version of the default environment for the lsp backends - the documentation update is just to reflect that change.

2022-01-19 15:03 UTC, l2dy commented
It touches `README.org`, so it contains a docs change. Changing these files on the `master` branch may cause merge conflicts when the `rewrite-docs` branch is finished and need to be merged to `master`.

2022-01-19 15:05 UTC, l2dy commented
You should split this into 2 PRs, one for code targeting `master` and the other for docs targeting `rewrite-docs`.

2022-01-19 19:54 UTC, kiranshila commented
@l2dy Makes sense I suppose w.r.t the merge conflicts. It just seems strange that the docs would be out of sync from the implementation

2022-01-20 18:26 UTC, kiranshila commented
Ok I updated this PR to be just the change to the elisp

2022-01-27 02:35 UTC, hlissner approved these changes

2022-01-27 02:36 UTC, merged

2022-01-27 02:42 UTC, hlissner commented
Thanks for the help, and sorry for the trouble!