fix(vertico): completion category of +default/find-file-under-here
hlissner/doom-emacs pull request #6025
Opened 2022-01-22 19:56 UTC by PaulPorfiroff

`(car. cdr)` -> `(car . cdr)`

Fix dotted pair syntax in `marginalia-command-categories` for `+default/find-file-under-here`, so all the completion-category-driven machinery works as intended.

2022-01-22 20:37 UTC, iyefrat submitted a review, later dismissed

2022-01-27 02:58 UTC, hlissner submitted a review, later dismissed

2022-01-27 02:59 UTC, hlissner requested changes
Could you rebase this onto `master`? `develop` is now EOL.

2022-01-28 14:45 UTC, PaulPorfiroff commented
@hlissner, done.

2022-01-28 14:59 UTC, PaulPorfiroff commented
Btw, I've been branching off of the `develop`, because [docs/contributing.org](https://github.com/hlissner/doom-emacs/blob/master/docs/contributing.org#commits--prs) still says so.

2022-01-28 16:45 UTC, hlissner approved these changes

2022-01-28 20:01 UTC, merged

2022-01-28 20:01 UTC, hlissner commented
Thanks for your help!

> Btw, I used the develop branch, because docs/contributing.org still says so.

Aye, this will be corrected soon. Thanks!