fix(rss): unbalanced parens in map!
hlissner/doom-emacs pull request #6066
Opened 2022-01-30 19:53 UTC by danilevy1212

I introduced an umbalanced parens expression in https://github.com/hlissner/doom-emacs/pull/6065, this PR fixes it.

2022-01-30 20:31 UTC, hlissner requested changes

2022-01-30 20:31 UTC, hlissner commented on modules/app/rss/config.el
> +    (map! (:map elfeed-show-mode-map
Could you remove the inner parens and align each line with the `:map`? This would be consistent with other uses of this macro. I.e.

```elisp
    (map! :map elfeed-show-mode-map
          :n "gc" nil
          :n "gc" #'+rss/copy-link)))
```

2022-01-30 20:38 UTC, danilevy1212 commented on modules/app/rss/config.el
> +    (map! (:map elfeed-show-mode-map
Done :)

2022-01-31 00:17 UTC, hlissner approved these changes
Looks good to me!

2022-01-31 00:19 UTC, merged