bump: update squashed hash in emacs-undo-fu-session
hlissner/doom-emacs pull request #6092
Opened 2022-02-07 23:26 UTC by yamanq

ideasman42/emacs-undo-fu-session@edf050d61334 -> ideasman42/emacs-undo-fu-session@3e810c7c9ab7

I changed the commit hash for undo-fu-session, as upstream seems to have squashed the commit:
[edf050d6](https://gitlab.com/ideasman42/emacs-undo-fu-session/-/commit/edf050d6133478d04fc06cc65914517b18d6bcc6) -> [3e810c7c](https://gitlab.com/ideasman42/emacs-undo-fu-session/-/commit/3e810c7c9ab75d2b6f92c7c876290abbc164e750)

Only 3e810c7c is attached to [master](https://gitlab.com/ideasman42/emacs-undo-fu-session/-/commits/master).

There are no changes between these two commits with the exception of a log line, but I was getting some warnings that the edf050d6 object could not be found when running doom upgrade a few times:

First run of doom upgrade
```
      > (80/291) Re-cloning emacs-undo-fu-session...
        > Cloning emacs-undo-fu-session...
          Warning (straight): Could not reset to commit "edf050d6133478d04fc06cc65914517b18d6bcc6" in repository "emacs-undo-fu-session"
      ✓ (80/291) emacs-undo-fu-session: 1810251 -> edf050d [1 commit(s)]
          ERROR: Couldn't collect commit list because: fatal: bad object edf050d6133478d04fc06cc65914517b18d6bcc6

```

Second run and subsequent runs:
```
      > (80/291) Re-cloning emacs-undo-fu-session...
        > Cloning emacs-undo-fu-session...
          Warning (straight): Could not reset to commit "edf050d6133478d04fc06cc65914517b18d6bcc6" in repository "emacs-undo-fu-session"
      ✓ (80/291) emacs-undo-fu-session: 3e810c7 -> edf050d [1 commit(s)]
          ERROR: Couldn't collect commit list because: fatal: bad object edf050d6133478d04fc06cc65914517b18d6bcc6
```

Deleting emacs-undo-fu-session and rerunning doom upgrade is a workaround for getting rid of the warning. This should probably be merged as it seems to be using the latest commit from master instead of pinning.

2022-02-08 00:56 UTC, hlissner requested changes
To conform with [our git conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854) please reword the commit to:

```
bump: :emacs undo

ideasman42/emacs-undo-fu-session@edf050d61334 -> ideasman42/emacs-undo-fu-session@3e810c7c9ab7

Upstream, ideasman42/emacs-undo-fu-session@edf050d61334 was squashed into master. This bump pins to an attached commit.

Ref: https://gitlab.com/ideasman42/emacs-undo-fu-session/-/commit/3e810c7c9ab75d2b6f92c7c876290abbc164e750
```

2022-02-08 01:02 UTC, yamanq commented
Reworded, thanks.

2022-02-08 15:55 UTC, hlissner approved these changes

2022-02-09 03:55 UTC, merged

2022-02-09 03:55 UTC, hlissner commented
LGTM. Thanks for the help!