bump: :lang csharp
hlissner/doom-emacs pull request #6111
Opened 2022-02-13 21:46 UTC by DrPandemic

emacs-csharp/csharp-mode@fe8a68e9849fc7617e0c870cacd6599b8a797638 -> emacs-csharp/csharp-mode@9917e1b97d6a374c8043124817142ea3419a649b

Bump csharp-mode to its latest tag.

2022-02-13 22:24 UTC, hlissner requested changes
The `develop` branch is EOL. Please rebase this onto `master`.

2022-02-13 23:31 UTC, DrPandemic commented
I read the the we shouldn't push PRs on documentation files, however it might be nice to update https://github.com/hlissner/doom-emacs/blob/master/docs/contributing.org#commits--prs to mention `master` rather than `develop`.

2022-02-14 17:24 UTC, hlissner approved these changes

2022-02-14 20:23 UTC, merged

2022-02-14 20:23 UTC, hlissner commented
Understood, will update it soon. Thanks for the help!