remove obsolete rust config
hlissner/doom-emacs pull request #6154
Opened 2022-02-25 17:46 UTC by brotzeit

Fixes #6070

and

rustic depends on rust-mode since version 2.0 so the rust-mode hack shouldn't be needed anymore

depends on #6153

2022-03-19 01:48 UTC, hlissner approved these changes

2022-03-19 15:57 UTC, hlissner requested changes

2022-03-19 15:57 UTC, hlissner commented on modules/lang/rust/config.el
> -    (add-to-list 'org-src-lang-modes '("rust" . rustic)))
This still seems necessary. Neither of these lines are autoloaded in rustic-babel.el and the package isn't eagerly loaded, so org won't use `rustic-mode` on `rust` babel blocks until a rustic-mode buffer is opened elsewhere.

2022-03-19 16:08 UTC, brotzeit commented on modules/lang/rust/config.el
> -    (add-to-list 'org-src-lang-modes '("rust" . rustic)))
Oh, thanks for the hint. I'll fix it and give you an update.

2022-03-31 19:10 UTC, closed without merging

2022-03-31 19:13 UTC, hlissner commented
I've implemented your other changes and then some, to reflect changes upstream, along with a minor refactor of our `:lang rust`. For the time being I've kept the `(after! org-src ...)` block, but I'll keep an eye out for any changes upstream that make them redundant. Anyhow, thanks for bringing it to my attention (and for your great work on rustic)!