Expanded Fortran UI
hlissner/doom-emacs pull request #6178
Opened 2022-03-06 00:38 UTC by fosskers

This PR expands the Fortran module to allow build tool control through modeline menus.

2022-03-19 01:44 UTC, hlissner requested changes
Can you incorporate these two new commands into the module's localleader keybinds? I may eventually remove the menus, as Doom endorses no particular menu bar workflow (at least, for now), so the functionality should be available by other means.

2022-03-19 01:45 UTC, hlissner requested changes

2022-03-19 01:45 UTC, hlissner commented on modules/lang/fortran/config.el
> +        ["Run" +fortran/gfortran-run :active t :help "Run the Executable"])))
Correct indentation (should be indented +2 spaces, not +4).

2022-03-19 01:45 UTC, hlissner commented on modules/lang/fortran/autoload.el
> -
Please restore this whitespace.

2022-03-19 15:15 UTC, fosskers commented
Should be good to go. I hear you about the menus - the form I have of them is strictly a first pass and was pretty educational in figuring out how `easy-menu-define` works.

2022-03-21 02:59 UTC, hlissner approved these changes

2022-03-21 03:00 UTC, merged

2022-03-21 03:00 UTC, hlissner commented
LGTM. Thanks for your help!

2022-03-21 03:17 UTC, fosskers commented
Support for Intel Fortran coming soon! That'll basically establish Doom as the only real non-Eclipse option for using Intel Fortran on Linux.